<?php

namespace Database\Seeders;

use App\Models\BloodBank;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class BloodBankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bloodBanks = [
            [
                'name_en' => 'SMS Hospital Blood Bank',
                'name_hi' => 'एसएमएस अस्पताल ब्लड बैंक',
                'address_en' => 'Sawai Man Singh Hospital, JLN Marg',
                'address_hi' => 'सवाई मान सिंह अस्पताल, जेएलएन मार्ग',
                'pincode' => '302004',
                'latitude' => 26.8929,
                'longitude' => 75.8153,
                'country_code' => '+91',
                'phone' => '1412560291',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412560291',
                'email' => 'smsbloodbank@rajasthan.gov.in',
                'website' => 'https://education.rajasthan.gov.in/smsmedicalcollege',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'last_updated_stock_at' => Carbon::now()->subMinutes(15),
            ],
            [
                'name_en' => 'Santokba Durlabhji Memorial Hospital (SDMH) Blood Bank',
                'name_hi' => 'संतोकबा दुर्लभजी मेमोरियल अस्पताल (एसडीएमएच) ब्लड बैंक',
                'address_en' => 'Bhawani Singh Marg, Rambagh',
                'address_hi' => 'भवानी सिंह मार्ग, रामबाग',
                'pincode' => '302015',
                'latitude' => 26.8985,
                'longitude' => 75.8078,
                'country_code' => '+91',
                'phone' => '1412566251',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412566258',
                'email' => 'bloodbank@sdmh.in',
                'website' => 'https://sdmh.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+', 'A-', 'B-'],
                'last_updated_stock_at' => Carbon::now()->subMinutes(30),
            ],
            [
                'name_en' => 'Bhagwan Mahaveer Cancer Hospital Blood Bank',
                'name_hi' => 'भगवान महावीर कैंसर अस्पताल ब्लड बैंक',
                'address_en' => 'JLN Marg, Bajaj Nagar',
                'address_hi' => 'जेएलएन मार्ग, बजाज नगर',
                'pincode' => '302017',
                'latitude' => 26.8532,
                'longitude' => 75.8048,
                'country_code' => '+91',
                'phone' => '1412700107',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412700108',
                'email' => 'bloodbank@bmchrc.org',
                'website' => 'https://bmchrc.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+'],
                'last_updated_stock_at' => Carbon::now()->subHour(),
            ],
            [
                'name_en' => 'Red Cross Society Blood Bank',
                'name_hi' => 'रेड क्रॉस सोसाइटी ब्लड बैंक',
                'address_en' => 'Near Sanganeri Gate, M.I. Road',
                'address_hi' => 'सांगानेरी गेट के पास, एम.आई. रोड',
                'pincode' => '302003',
                'latitude' => 26.9154,
                'longitude' => 75.8267,
                'country_code' => '+91',
                'phone' => '1412615124',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412615124',
                'email' => 'redcrossjaipur@gmail.com',
                'website' => 'https://indianredcross.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => false,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+', 'O-'],
                'last_updated_stock_at' => Carbon::now()->subHours(2),
            ],
            [
                'name_en' => 'Rotary Club Jaipur Blood Bank',
                'name_hi' => 'रोटरी क्लब जयपुर ब्लड बैंक',
                'address_en' => 'JLN Marg, Near Police Memorial',
                'address_hi' => 'जेएलएन मार्ग, पुलिस मेमोरियल के पास',
                'pincode' => '302004',
                'latitude' => 26.8856,
                'longitude' => 75.8124,
                'country_code' => '+91',
                'phone' => '1412561111',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412561112',
                'email' => 'rotarybloodbankjaipur@gmail.com',
                'website' => 'https://rotarybloodbank.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+', 'A-', 'B-', 'O-', 'AB-'],
                'last_updated_stock_at' => Carbon::now()->subMinutes(5),
            ],
            [
                'name_en' => 'Fortis Escorts Hospital Blood Bank',
                'name_hi' => 'फोर्टिस एस्कॉर्ट्स अस्पताल ब्लड बैंक',
                'address_en' => 'JLN Marg, Malviya Nagar',
                'address_hi' => 'जेएलएन मार्ग, मालवीय नगर',
                'pincode' => '302017',
                'latitude' => 26.8521,
                'longitude' => 75.8055,
                'country_code' => '+91',
                'phone' => '1412547000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412547000',
                'email' => 'bloodbank.jaipur@fortishealthcare.com',
                'website' => 'https://fortishealthcare.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+'],
                'last_updated_stock_at' => Carbon::now()->subMinutes(45),
            ],
            [
                'name_en' => 'Mahatma Gandhi Hospital Blood Bank',
                'name_hi' => 'महात्मा गांधी अस्पताल ब्लड बैंक',
                'address_en' => 'RIICO Institutional Area, Sitapura',
                'address_hi' => 'रीको इंस्टीट्यूशनल एरिया, सीतापुरा',
                'pincode' => '302022',
                'latitude' => 26.7634,
                'longitude' => 75.8504,
                'country_code' => '+91',
                'phone' => '1412771777',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1412771777',
                'email' => 'bloodbank@mgumst.org',
                'website' => 'https://mgumst.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+', 'B-', 'O-'],
                'last_updated_stock_at' => Carbon::now()->subMinutes(20),
            ],
            [
                'name_en' => 'Rukmani Birla Hospital (RBH) Blood Bank',
                'name_hi' => 'रुक्मणी बिड़ला अस्पताल (आरबीएच) ब्लड बैंक',
                'address_en' => 'Gopalpura Bypass, Near Triveni Nagar',
                'address_hi' => 'गोपालपुरा बाईपास, त्रिवेणी नगर के पास',
                'pincode' => '302018',
                'latitude' => 26.8745,
                'longitude' => 75.7821,
                'country_code' => '+91',
                'phone' => '1413006000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '1413006000',
                'email' => 'bloodbank@rbh.in',
                'website' => 'https://rbh.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'B+', 'O+', 'AB+'],
                'last_updated_stock_at' => Carbon::now()->subHours(3),
            ]
        ];

        foreach ($bloodBanks as $bank) {
            BloodBank::updateOrCreate(
                ['name_en' => $bank['name_en']],
                $bank
            );
        }
    }
}
