<?php

namespace Database\Seeders;

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::departments() as $department) {
            Department::updateOrCreate(
                ['name_en' => $department['name']],
                [
                    'name_en' => $department['name'],
                    'name_hi' => $department['name_hi'] ?? self::hindiNameFor($department['name']),
                    'description_en' => $department['description'],
                    'description_hi' => $department['description_hi'] ?? self::hindiDescriptionFor($department['name']),
                    'is_active' => true,
                ]
            );
        }

        // Ensure any existing doctors have their primary department_id populated from the pivot table
        \App\Models\Doctor::whereNull('department_id')
            ->chunkById(100, function ($doctors) {
                foreach ($doctors as $doctor) {
                    $firstDept = $doctor->departments()->first();
                    if ($firstDept) {
                        $doctor->update(['department_id' => $firstDept->id]);
                    }
                }
            });
    }

    public static function departments(): array
    {
        return [
            ['name' => 'Addiction Medicine', 'description' => 'Prevention, diagnosis, treatment, and recovery support for substance use disorders.'],
            ['name' => 'Adolescent Medicine', 'description' => 'Health care for teenagers and young adults.'],
            ['name' => 'Allergy and Immunology', 'description' => 'Care for allergies, asthma, immune deficiencies, and hypersensitivity disorders.'],
            ['name' => 'Anesthesiology', 'description' => 'Anesthesia, perioperative medicine, pain control, and critical care support.'],
            ['name' => 'Audiology', 'description' => 'Evaluation and management of hearing and balance disorders.'],
            ['name' => 'Bariatric Medicine', 'description' => 'Medical and surgical care for obesity and weight-related conditions.'],
            ['name' => 'Breast Surgery', 'description' => 'Diagnosis and surgical management of benign and malignant breast disease.'],
            ['name' => 'Cardiac Surgery', 'description' => 'Surgical treatment of heart and great vessel disease.'],
            ['name' => 'Cardiology', 'description' => 'Diagnosis and treatment of heart and vascular system disorders.'],
            ['name' => 'Clinical Genetics', 'description' => 'Evaluation and counseling for inherited and genetic disorders.'],
            ['name' => 'Colorectal Surgery', 'description' => 'Surgical care for colon, rectal, and anal disorders.'],
            ['name' => 'Critical Care Medicine', 'description' => 'Specialized care for life-threatening illness and organ support.'],
            ['name' => 'Dentistry', 'description' => 'Care for teeth, gums, oral health, and dental disease.'],
            ['name' => 'Dermatology', 'description' => 'Diagnosis and treatment of skin, hair, and nail conditions.'],
            ['name' => 'Developmental and Behavioral Pediatrics', 'description' => 'Care for developmental, learning, and behavioral concerns in children.'],
            ['name' => 'Emergency Medicine', 'description' => 'Immediate care for acute illness, injury, and medical emergencies.'],
            ['name' => 'Endocrinology', 'description' => 'Hormonal and metabolic disorders, including diabetes and thyroid disease.'],
            ['name' => 'ENT (Otolaryngology)', 'description' => 'Care for ear, nose, throat, head, and neck disorders.'],
            ['name' => 'Family Medicine', 'description' => 'Comprehensive primary care for people of all ages.'],
            ['name' => 'Gastroenterology', 'description' => 'Digestive system disorders involving the stomach, intestines, liver, and pancreas.'],
            ['name' => 'General Medicine', 'description' => 'Primary care and management of acute and chronic adult illnesses.'],
            ['name' => 'General Surgery', 'description' => 'Surgical care for common abdominal, soft tissue, endocrine, and emergency conditions.'],
            ['name' => 'Geriatrics', 'description' => 'Health care focused on older adults and age-related conditions.'],
            ['name' => 'Gynecology', 'description' => 'Care for women and reproductive system disorders.'],
            ['name' => 'Hematology', 'description' => 'Diagnosis and treatment of blood and bone marrow disorders.'],
            ['name' => 'Hepatology', 'description' => 'Care for liver, gallbladder, biliary tract, and pancreas-related liver disorders.'],
            ['name' => 'Infectious Diseases', 'description' => 'Diagnosis, treatment, and prevention of infections.'],
            ['name' => 'Internal Medicine', 'description' => 'Adult medical care for complex acute and chronic diseases.'],
            ['name' => 'Interventional Cardiology', 'description' => 'Catheter-based diagnosis and treatment of heart and vascular disease.'],
            ['name' => 'Interventional Radiology', 'description' => 'Image-guided minimally invasive procedures.'],
            ['name' => 'Neonatology', 'description' => 'Specialized medical care for newborns, especially premature or critically ill infants.'],
            ['name' => 'Nephrology', 'description' => 'Care for kidney disease, dialysis, and electrolyte disorders.'],
            ['name' => 'Neurology', 'description' => 'Treatment of disorders of the brain, spinal cord, nerves, and muscles.'],
            ['name' => 'Neurosurgery', 'description' => 'Surgical care for brain, spine, nerve, and skull disorders.'],
            ['name' => 'Nuclear Medicine', 'description' => 'Diagnostic imaging and therapy using radioactive tracers.'],
            ['name' => 'Nutrition and Dietetics', 'description' => 'Medical nutrition therapy, diet planning, and nutritional rehabilitation.'],
            ['name' => 'Obstetrics', 'description' => 'Care during pregnancy, childbirth, and the postpartum period.'],
            ['name' => 'Obstetrics and Gynecology', 'description' => 'Women\'s reproductive health, pregnancy care, and childbirth.'],
            ['name' => 'Occupational Medicine', 'description' => 'Health care related to work, workplace hazards, and fitness for duty.'],
            ['name' => 'Oncology', 'description' => 'Diagnosis, staging, and treatment of cancer.'],
            ['name' => 'Ophthalmology', 'description' => 'Medical and surgical eye care and vision evaluation.'],
            ['name' => 'Oral and Maxillofacial Surgery', 'description' => 'Surgery of the mouth, jaws, face, and related structures.'],
            ['name' => 'Orthodontics', 'description' => 'Correction of teeth and jaw alignment.'],
            ['name' => 'Orthopedics', 'description' => 'Care of bones, joints, ligaments, tendons, and the musculoskeletal system.'],
            ['name' => 'Pain Medicine', 'description' => 'Diagnosis and treatment of acute and chronic pain conditions.'],
            ['name' => 'Palliative Medicine', 'description' => 'Symptom relief and supportive care for serious illness.'],
            ['name' => 'Pathology', 'description' => 'Laboratory diagnosis of disease using tissues, cells, and body fluids.'],
            ['name' => 'Pediatric Cardiology', 'description' => 'Heart care for infants, children, and adolescents.'],
            ['name' => 'Pediatric Endocrinology', 'description' => 'Hormonal and growth disorders in children.'],
            ['name' => 'Pediatric Gastroenterology', 'description' => 'Digestive, liver, and nutrition disorders in children.'],
            ['name' => 'Pediatric Neurology', 'description' => 'Brain, nerve, and muscle disorders in children.'],
            ['name' => 'Pediatric Surgery', 'description' => 'Surgical care for infants, children, and adolescents.'],
            ['name' => 'Pediatrics', 'description' => 'Medical care of infants, children, and adolescents.'],
            ['name' => 'Physical Medicine and Rehabilitation', 'description' => 'Restoring function after injury, illness, surgery, or disability.'],
            ['name' => 'Physiotherapy', 'description' => 'Movement, exercise, and rehabilitation therapies.'],
            ['name' => 'Plastic and Reconstructive Surgery', 'description' => 'Reconstructive, restorative, and cosmetic surgical care.'],
            ['name' => 'Podiatry', 'description' => 'Care for foot, ankle, and lower limb disorders.'],
            ['name' => 'Preventive Medicine', 'description' => 'Disease prevention, screening, public health, and risk reduction.'],
            ['name' => 'Psychiatry', 'description' => 'Diagnosis and treatment of mental, emotional, and behavioral disorders.'],
            ['name' => 'Psychology', 'description' => 'Assessment and therapy for emotional, behavioral, and cognitive concerns.'],
            ['name' => 'Pulmonology', 'description' => 'Diseases involving the lungs and respiratory tract.'],
            ['name' => 'Radiation Oncology', 'description' => 'Cancer treatment using radiation therapy.'],
            ['name' => 'Radiology', 'description' => 'Medical imaging for diagnosis and treatment planning.'],
            ['name' => 'Reproductive Endocrinology and Infertility', 'description' => 'Fertility care and reproductive hormone disorders.'],
            ['name' => 'Rheumatology', 'description' => 'Autoimmune, inflammatory, joint, and connective tissue disorders.'],
            ['name' => 'Sleep Medicine', 'description' => 'Diagnosis and treatment of sleep disorders.'],
            ['name' => 'Sports Medicine', 'description' => 'Care for exercise-related injuries, performance, and musculoskeletal health.'],
            ['name' => 'Thoracic Surgery', 'description' => 'Surgery of the lungs, chest wall, esophagus, and mediastinum.'],
            ['name' => 'Transplant Medicine', 'description' => 'Care before and after organ or tissue transplantation.'],
            ['name' => 'Trauma Surgery', 'description' => 'Surgical care for traumatic injuries and emergencies.'],
            ['name' => 'Urology', 'description' => 'Diseases of the urinary tract and male reproductive system.'],
            ['name' => 'Vascular Surgery', 'description' => 'Surgical and endovascular care for artery, vein, and lymphatic disorders.'],
        ];
    }

    public static function hindiNameFor(string $name): string
    {
        return [
            'Addiction Medicine' => 'नशा मुक्ति चिकित्सा',
            'Adolescent Medicine' => 'किशोर चिकित्सा',
            'Allergy and Immunology' => 'एलर्जी और प्रतिरक्षा विज्ञान',
            'Anesthesiology' => 'एनेस्थीसियोलॉजी',
            'Audiology' => 'श्रवण विज्ञान',
            'Bariatric Medicine' => 'बैरिएट्रिक चिकित्सा',
            'Breast Surgery' => 'स्तन शल्य चिकित्सा',
            'Cardiac Surgery' => 'हृदय शल्य चिकित्सा',
            'Cardiology' => 'हृदय रोग विभाग',
            'Clinical Genetics' => 'क्लिनिकल आनुवंशिकी',
            'Colorectal Surgery' => 'कोलोरेक्टल शल्य चिकित्सा',
            'Critical Care Medicine' => 'गहन चिकित्सा',
            'Dentistry' => 'दंत चिकित्सा',
            'Dermatology' => 'त्वचा रोग विभाग',
            'Developmental and Behavioral Pediatrics' => 'विकासात्मक और व्यवहारिक बाल चिकित्सा',
            'Emergency Medicine' => 'आपातकालीन चिकित्सा',
            'Endocrinology' => 'अंतःस्राविकी',
            'ENT (Otolaryngology)' => 'कान, नाक और गला रोग विभाग',
            'Family Medicine' => 'पारिवारिक चिकित्सा',
            'Gastroenterology' => 'पाचन तंत्र रोग विभाग',
            'General Medicine' => 'सामान्य चिकित्सा',
            'General Surgery' => 'सामान्य शल्य चिकित्सा',
            'Geriatrics' => 'वृद्धावस्था चिकित्सा',
            'Gynecology' => 'स्त्री रोग विभाग',
            'Hematology' => 'रक्त रोग विभाग',
            'Hepatology' => 'यकृत रोग विभाग',
            'Infectious Diseases' => 'संक्रामक रोग विभाग',
            'Internal Medicine' => 'आंतरिक चिकित्सा',
            'Interventional Cardiology' => 'इंटरवेंशनल कार्डियोलॉजी',
            'Interventional Radiology' => 'इंटरवेंशनल रेडियोलॉजी',
            'Neonatology' => 'नवजात शिशु चिकित्सा',
            'Nephrology' => 'गुर्दा रोग विभाग',
            'Neurology' => 'तंत्रिका रोग विभाग',
            'Neurosurgery' => 'तंत्रिका शल्य चिकित्सा',
            'Nuclear Medicine' => 'न्यूक्लियर मेडिसिन',
            'Nutrition and Dietetics' => 'पोषण और आहार विज्ञान',
            'Obstetrics' => 'प्रसूति विभाग',
            'Obstetrics and Gynecology' => 'प्रसूति एवं स्त्री रोग विभाग',
            'Occupational Medicine' => 'व्यावसायिक चिकित्सा',
            'Oncology' => 'कैंसर रोग विभाग',
            'Ophthalmology' => 'नेत्र रोग विभाग',
            'Oral and Maxillofacial Surgery' => 'मुख एवं जबड़ा शल्य चिकित्सा',
            'Orthodontics' => 'ऑर्थोडॉन्टिक्स',
            'Orthopedics' => 'हड्डी रोग विभाग',
            'Pain Medicine' => 'दर्द चिकित्सा',
            'Palliative Medicine' => 'प्रशामक चिकित्सा',
            'Pathology' => 'पैथोलॉजी',
            'Pediatric Cardiology' => 'बाल हृदय रोग विभाग',
            'Pediatric Endocrinology' => 'बाल अंतःस्राविकी',
            'Pediatric Gastroenterology' => 'बाल पाचन तंत्र रोग विभाग',
            'Pediatric Neurology' => 'बाल तंत्रिका रोग विभाग',
            'Pediatric Surgery' => 'बाल शल्य चिकित्सा',
            'Pediatrics' => 'बाल रोग विभाग',
            'Physical Medicine and Rehabilitation' => 'भौतिक चिकित्सा एवं पुनर्वास',
            'Physiotherapy' => 'फिजियोथेरेपी',
            'Plastic and Reconstructive Surgery' => 'प्लास्टिक एवं पुनर्निर्माण शल्य चिकित्सा',
            'Podiatry' => 'पैर रोग चिकित्सा',
            'Preventive Medicine' => 'निवारक चिकित्सा',
            'Psychiatry' => 'मनोचिकित्सा',
            'Psychology' => 'मनोविज्ञान',
            'Pulmonology' => 'श्वसन रोग विभाग',
            'Radiation Oncology' => 'रेडिएशन ऑन्कोलॉजी',
            'Radiology' => 'रेडियोलॉजी',
            'Reproductive Endocrinology and Infertility' => 'प्रजनन अंतःस्राविकी और बांझपन',
            'Rheumatology' => 'रूमेटोलॉजी',
            'Sleep Medicine' => 'नींद चिकित्सा',
            'Sports Medicine' => 'खेल चिकित्सा',
            'Thoracic Surgery' => 'वक्ष शल्य चिकित्सा',
            'Transplant Medicine' => 'प्रत्यारोपण चिकित्सा',
            'Trauma Surgery' => 'ट्रॉमा शल्य चिकित्सा',
            'Urology' => 'मूत्र रोग विभाग',
            'Vascular Surgery' => 'रक्तवाहिनी शल्य चिकित्सा',
        ][$name];
    }

    public static function hindiDescriptionFor(string $name): string
    {
        return [
            'Addiction Medicine' => 'मादक द्रव्यों के सेवन से संबंधित विकारों की रोकथाम, निदान, उपचार और पुनर्वास सहायता।',
            'Adolescent Medicine' => 'किशोरों और युवाओं के लिए विशेष स्वास्थ्य देखभाल।',
            'Allergy and Immunology' => 'एलर्जी, अस्थमा, प्रतिरक्षा संबंधी कमियों और अतिसंवेदनशीलता विकारों का उपचार।',
            'Anesthesiology' => 'एनेस्थीसिया, पेरिऑपरेटिव मेडिसिन, दर्द नियंत्रण और गहन चिकित्सा सहायता।',
            'Audiology' => 'श्रवण और संतुलन संबंधी विकारों का मूल्यांकन और प्रबंधन।',
            'Bariatric Medicine' => 'मोटापे और वजन से संबंधित स्थितियों के लिए चिकित्सा और शल्य चिकित्सा देखभाल।',
            'Breast Surgery' => 'स्तन रोगों का निदान और शल्य चिकित्सा प्रबंधन।',
            'Cardiac Surgery' => 'हृदय और रक्त वाहिकाओं के रोगों का शल्य चिकित्सा उपचार।',
            'Cardiology' => 'हृदय और संवहनी प्रणाली के विकारों का निदान और उपचार।',
            'Clinical Genetics' => 'आनुवंशिक और आनुवंशिक विकारों के लिए मूल्यांकन और परामर्श।',
            'Colorectal Surgery' => 'कोलन, मलाशय और गुदा संबंधी विकारों के लिए शल्य चिकित्सा देखभाल।',
            'Critical Care Medicine' => 'गंभीर बीमारियों और अंग सहायता के लिए विशेष देखभाल।',
            'Dentistry' => 'दांतों, मसूड़ों, मौखिक स्वास्थ्य और दंत रोगों की देखभाल।',
            'Dermatology' => 'त्वचा, बाल और नाखूनों की स्थितियों का निदान और उपचार।',
            'Developmental and Behavioral Pediatrics' => 'बच्चों में विकासात्मक, सीखने और व्यवहार संबंधी चिंताओं की देखभाल।',
            'Emergency Medicine' => 'तीव्र बीमारी, चोट और चिकित्सा आपात स्थिति के लिए तत्काल देखभाल।',
            'Endocrinology' => 'हार्मोनल और चयापचय संबंधी विकार, जिसमें मधुमेह और थायरॉयड रोग शामिल हैं।',
            'ENT (Otolaryngology)' => 'कान, नाक, गले, सिर और गर्दन के विकारों की देखभाल।',
            'Family Medicine' => 'सभी उम्र के लोगों के लिए व्यापक प्राथमिक स्वास्थ्य देखभाल।',
            'Gastroenterology' => 'पेट, आंतों, यकृत और अग्न्याशय से जुड़े पाचन तंत्र के विकार।',
            'General Medicine' => 'तीव्र और पुरानी वयस्क बीमारियों की प्राथमिक देखभाल और प्रबंधन।',
            'General Surgery' => 'सामान्य पेट, कोमल ऊतक, अंतःस्रावी और आपातकालीन स्थितियों के लिए शल्य चिकित्सा देखभाल।',
            'Geriatrics' => 'वृद्ध वयस्कों और उम्र से संबंधित स्थितियों पर केंद्रित स्वास्थ्य देखभाल।',
            'Gynecology' => 'महिलाओं और प्रजनन प्रणाली के विकारों की देखभाल।',
            'Hematology' => 'रक्त और अस्थि मज्जा विकारों का निदान और उपचार।',
            'Hepatology' => 'यकृत, पित्ताशय, पित्त पथ और अग्न्याशय से संबंधित यकृत विकारों की देखभाल।',
            'Infectious Diseases' => 'संक्रमण का निदान, उपचार और रोकथाम।',
            'Internal Medicine' => 'जटिल तीव्र और पुरानी बीमारियों के लिए वयस्क चिकित्सा देखभाल।',
            'Interventional Cardiology' => 'कैथेटर आधारित हृदय और संवहनी रोग का निदान और उपचार।',
            'Interventional Radiology' => 'इमेज-गाइडेड न्यूनतम इनवेसिव प्रक्रियाएं।',
            'Neonatology' => 'नवजात शिशुओं, विशेष रूप से समय से पहले या गंभीर रूप से बीमार शिशुओं के लिए विशेष चिकित्सा देखभाल।',
            'Nephrology' => 'गुर्दे की बीमारी, डायलिसिस और इलेक्ट्रोलाइट विकारों की देखभाल।',
            'Neurology' => 'मस्तिष्क, रीढ़ की हड्डी, नसों और मांसपेशियों के विकारों का उपचार।',
            'Neurosurgery' => 'मस्तिष्क, रीढ़, तंत्रिका और खोपड़ी के विकारों के लिए शल्य चिकित्सा देखभाल।',
            'Nuclear Medicine' => 'रेडियोधर्मी ट्रेसर का उपयोग करके नैदानिक इमेजिंग और थेरेपी।',
            'Nutrition and Dietetics' => 'चिकित्सा पोषण चिकित्सा, आहार योजना और पोषण पुनर्वास।',
            'Obstetrics' => 'गर्भावस्था, प्रसव और प्रसवोत्तर अवधि के दौरान देखभाल।',
            'Obstetrics and Gynecology' => 'महिलाओं का प्रजनन स्वास्थ्य, गर्भावस्था की देखभाल और प्रसव।',
            'Occupational Medicine' => 'काम, कार्यस्थल के खतरों और कर्तव्य के लिए फिटनेस से संबंधित स्वास्थ्य देखभाल।',
            'Oncology' => 'कैंसर का निदान, स्टेजिंग और उपचार।',
            'Ophthalmology' => 'चिकित्सा और शल्य चिकित्सा नेत्र देखभाल और दृष्टि मूल्यांकन।',
            'Oral and Maxillofacial Surgery' => 'मुंह, जबड़े, चेहरे और संबंधित संरचनाओं की सर्जरी।',
            'Orthodontics' => 'दांतों और जबड़े के संरेखण का सुधार।',
            'Orthopedics' => 'हड्डियों, जोड़ों, स्नायुबंधन, टेंडन और मस्कुलोस्केलेटल सिस्टम की देखभाल।',
            'Pain Medicine' => 'तीव्र और पुराने दर्द की स्थितियों का निदान और उपचार।',
            'Palliative Medicine' => 'गंभीर बीमारी के लिए लक्षण राहत और सहायक देखभाल।',
            'Pathology' => 'ऊतकों, कोशिकाओं और शरीर के तरल पदार्थों का उपयोग करके बीमारी का प्रयोगशाला निदान।',
            'Pediatric Cardiology' => 'शिशुओं, बच्चों और किशोरों के लिए हृदय की देखभाल।',
            'Pediatric Endocrinology' => 'बच्चों में हार्मोनल और विकास संबंधी विकार।',
            'Pediatric Gastroenterology' => 'बच्चों में पाचन, यकृत और पोषण संबंधी विकार।',
            'Pediatric Neurology' => 'बच्चों में मस्तिष्क, तंत्रिका और मांसपेशियों के विकार।',
            'Pediatric Surgery' => 'शिशुओं, बच्चों और किशोरों के लिए शल्य चिकित्सा देखभाल।',
            'Pediatrics' => 'शिशुओं, बच्चों और किशोरों की चिकित्सा देखभाल।',
            'Physical Medicine and Rehabilitation' => 'चोट, बीमारी, सर्जरी या विकलांगता के बाद कार्यक्षमता बहाल करना।',
            'Physiotherapy' => 'आंदोलन, व्यायाम और पुनर्वास उपचार।',
            'Plastic and Reconstructive Surgery' => 'पुनर्निर्माण, पुनर्स्थापनात्मक और कॉस्मेटिक शल्य चिकित्सा देखभाल।',
            'Podiatry' => 'पैर, टखने और निचले अंगों के विकारों की देखभाल।',
            'Preventive Medicine' => 'रोग निवारण, स्क्रीनिंग, सार्वजनिक स्वास्थ्य और जोखिम में कमी।',
            'Psychiatry' => 'मानसिक, भावनात्मक और व्यवहार संबंधी विकारों का निदान और उपचार।',
            'Psychology' => 'भावनात्मक, व्यवहारिक और संज्ञानात्मक चिंताओं के लिए मूल्यांकन और चिकित्सा।',
            'Pulmonology' => 'फेफड़ों और श्वसन पथ से जुड़े रोग।',
            'Radiation Oncology' => 'विकिरण चिकित्सा का उपयोग करके कैंसर का उपचार।',
            'Radiology' => 'निदान और उपचार योजना के लिए मेडिकल इमेजिंग।',
            'Reproductive Endocrinology and Infertility' => 'प्रजनन क्षमता की देखभाल और प्रजनन हार्मोन विकार।',
            'Rheumatology' => 'ऑटोइम्यून, सूजन, जोड़ और संयोजी ऊतक विकार।',
            'Sleep Medicine' => 'नींद संबंधी विकारों का निदान और उपचार।',
            'Sports Medicine' => 'व्यायाम से संबंधित चोटों, प्रदर्शन और मस्कुलोस्केलेटल स्वास्थ्य की देखभाल।',
            'Thoracic Surgery' => 'फेफड़ों, छाती की दीवार, अन्नप्रणाली और मीडियास्टिनम की सर्जरी।',
            'Transplant Medicine' => 'अंग या ऊतक प्रत्यारोपण से पहले और बाद की देखभाल।',
            'Trauma Surgery' => 'दर्दनाक चोटों और आपात स्थिति के लिए शल्य चिकित्सा देखभाल।',
            'Urology' => 'मूत्र पथ और पुरुष प्रजनन प्रणाली के रोग।',
            'Vascular Surgery' => 'धमनी, शिरा और लसीका विकारों के लिए शल्य चिकित्सा और एंडोवास्कुलर देखभाल।',
        ][$name] ?? 'विशेष स्वास्थ्य सेवा विभाग।';
    }
}
