<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Disease;
use App\Models\Symptom;
use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Department::query()->doesntExist()) {
            $this->call(DepartmentSeeder::class);
        }

        $departments = Department::query()->get()->keyBy('name_en');

        foreach (self::diseasesByDepartment() as $departmentName => $diseases) {
            $department = $departments->get($departmentName);

            if (! $department) {
                $department = Department::create([
                    'name_en' => $departmentName,
                    'name_hi' => DepartmentSeeder::hindiNameFor($departmentName),
                    'description_en' => null,
                    'description_hi' => null,
                    'is_active' => true,
                ]);

                $departments->put($departmentName, $department);
            }

            foreach ($diseases as $diseaseName) {
                $disease = Disease::updateOrCreate(
                    [
                        'name_en' => $diseaseName,
                        'department_id' => $department->id,
                    ],
                    [
                        'name_en' => $diseaseName,
                        'name_hi' => self::hindiNameFor($diseaseName),
                        'department_id' => $department->id,
                    ]
                );

                $symptomIds = [];
                foreach (self::symptomsForDisease($diseaseName) as $symptomNameEn) {
                    $symptom = Symptom::firstOrCreate(
                        ['name_en' => $symptomNameEn],
                        ['name_hi' => self::hindiNameFor($symptomNameEn)]
                    );

                    // Ensure fallback if the translation was previously missing
                    if (empty($symptom->name_hi) || $symptom->name_hi === $symptomNameEn) {
                        $symptom->name_hi = self::hindiNameFor($symptomNameEn);
                        $symptom->save();
                    }

                    $symptomIds[] = $symptom->id;
                }

                $disease->symptoms()->syncWithoutDetaching($symptomIds);
            }
        }
    }

    public static function symptomsForDisease(string $diseaseName): array
    {
        $map = [
            // Addiction Medicine
            'Alcohol Use Disorder' => ['Craving', 'Withdrawal Symptoms', 'Tolerance', 'Tremor', 'Sweating'],
            'Opioid Use Disorder' => ['Craving', 'Withdrawal Symptoms', 'Tolerance', 'Muscle Ache', 'Drowsiness'],
            'Nicotine Dependence' => ['Craving', 'Irritability', 'Anxiety', 'Difficulty Concentrating'],
            'Cannabis Use Disorder' => ['Craving', 'Memory Loss', 'Mood Swings', 'Lethargy'],
            'Stimulant Use Disorder' => ['Craving', 'Agitation', 'Weight Loss', 'Insomnia'],
            'Sedative Use Disorder' => ['Drowsiness', 'Confusion', 'Memory Loss', 'Weakness'],
            'Gambling Disorder' => ['Craving', 'Anxiety', 'Irritability', 'Mood Swings'],

            // Allergy and Immunology
            'Allergic Rhinitis' => ['Sneezing', 'Runny Nose', 'Itchy Eyes', 'Nasal Congestion'],
            'Food Allergy' => ['Itching', 'Swelling', 'Rash', 'Nausea', 'Abdominal Pain'],
            'Drug Allergy' => ['Rash', 'Itching', 'Fever', 'Swelling', 'Shortness of Breath'],
            'Urticaria' => ['Rash', 'Itching', 'Redness', 'Swelling'],
            'Angioedema' => ['Swelling', 'Itching', 'Shortness of Breath', 'Pain'],
            'Anaphylaxis' => ['Shortness of Breath', 'Swelling', 'Dizziness', 'Rash', 'Nausea'],
            'Atopic Dermatitis' => ['Dry Skin', 'Itching', 'Redness', 'Rash'],
            'Primary Immunodeficiency' => ['Frequent Infections', 'Fatigue', 'Weakness', 'Weight Loss'],
            'Common Variable Immunodeficiency' => ['Frequent Infections', 'Fatigue', 'Chronic Cough', 'Diarrhea'],

            // Cardiology
            'Hypertension' => ['Headache', 'Dizziness', 'Fatigue', 'Blurred Vision'],
            'Coronary Artery Disease' => ['Chest Pain', 'Shortness of Breath', 'Nausea', 'Fatigue'],
            'Angina' => ['Chest Pain', 'Shortness of Breath', 'Fatigue', 'Sweating'],
            'Myocardial Infarction' => ['Chest Pain', 'Shortness of Breath', 'Sweating', 'Pain Radiating to Arm'],
            'Heart Failure' => ['Shortness of Breath', 'Fatigue', 'Swollen Legs', 'Rapid Heartbeat'],
            'Atrial Fibrillation' => ['Palpitations', 'Shortness of Breath', 'Fatigue', 'Dizziness'],
            'Arrhythmia' => ['Palpitations', 'Dizziness', 'Fainting', 'Shortness of Breath'],
            'Valvular Heart Disease' => ['Shortness of Breath', 'Fatigue', 'Swollen Legs', 'Palpitations'],
            'Cardiomyopathy' => ['Shortness of Breath', 'Swollen Legs', 'Fatigue', 'Palpitations'],
            'Pericarditis' => ['Chest Pain', 'Fever', 'Weakness', 'Shortness of Breath'],
            'Peripheral Artery Disease' => ['Leg Pain', 'Cramping', 'Numbness', 'Cold Extremities'],
            'Deep Vein Thrombosis' => ['Leg Pain', 'Swelling', 'Redness', 'Warmth in Leg'],
            'Hyperlipidemia' => ['No Specific Symptoms', 'Chest Pain', 'Fatigue'],
            'Myocarditis' => ['Chest Pain', 'Fatigue', 'Shortness of Breath', 'Rapid Heartbeat', 'Fever'],
            'Endocarditis' => ['Fever', 'Chills', 'Heart Murmur', 'Fatigue', 'Aching Joints'],
            'Rheumatic Heart Disease' => ['Shortness of Breath', 'Fatigue', 'Heart Murmur', 'Chest Pain'],

            // Dermatology
            'Acne Vulgaris' => ['Pimples', 'Blackheads', 'Redness', 'Oily Skin'],
            'Eczema' => ['Dry Skin', 'Itching', 'Red Patches', 'Skin Cracking'],
            'Psoriasis' => ['Scaly Patches', 'Itching', 'Redness', 'Joint Pain'],
            'Vitiligo' => ['Loss of Skin Color', 'White Patches', 'Premature Graying'],
            'Fungal Skin Infection' => ['Itching', 'Redness', 'Skin Peeling', 'Ring-shaped Rash'],
            'Scabies' => ['Severe Itching', 'Rash', 'Blisters', 'Skin Sores'],
            'Rosacea' => ['Facial Redness', 'Visible Blood Vessels', 'Pimples', 'Eye Irritation'],
            'Alopecia Areata' => ['Hair Loss', 'Patchy Baldness', 'Nail Dents'],
            'Melasma' => ['Brown Patches on Face', 'Skin Discoloration'],
            'Cellulitis' => ['Redness', 'Swelling', 'Pain', 'Fever', 'Warm Skin'],
            'Impetigo' => ['Red Sores', 'Blisters', 'Itching', 'Yellow Crusts'],
            'Herpes Zoster' => ['Painful Rash', 'Blisters', 'Itching', 'Fever', 'Nerve Pain'],
            'Skin Cancer' => ['Skin Changes', 'New Mole', 'Sore That Won\'t Heal', 'Skin Ulcer'],
            'Contact Dermatitis' => ['Red Rash', 'Itching', 'Dry Skin', 'Blisters', 'Swelling'],
            'Seborrheic Dermatitis' => ['Dandruff', 'Scaly Patches', 'Red Skin', 'Itching'],
            'Warts' => ['Fleshy Bump', 'Rough Skin', 'Black Pinpoints on Skin'],

            // Emergency Medicine
            'Chest Pain' => ['Chest Tightness', 'Shortness of Breath', 'Sweating', 'Pain Radiating to Arm'],
            'Severe Abdominal Pain' => ['Nausea', 'Vomiting', 'Fever', 'Bloating', 'Pain'],
            'Stroke Symptoms' => ['Facial Drooping', 'Weakness', 'Speech Difficulty', 'Confusion'],
            'Sepsis' => ['Fever', 'Chills', 'Rapid Heartbeat', 'Confusion', 'Shortness of Breath'],
            'Acute Asthma Attack' => ['Severe Wheezing', 'Shortness of Breath', 'Chest Tightness', 'Panic'],
            'Severe Dehydration' => ['Extreme Thirst', 'Dry Mouth', 'Dark Urine', 'Dizziness', 'Confusion'],
            'Poisoning' => ['Nausea', 'Vomiting', 'Confusion', 'Difficulty Breathing', 'Seizure'],
            'Burn Injury' => ['Pain', 'Redness', 'Blisters', 'Skin Peeling', 'Swelling'],
            'Head Injury' => ['Headache', 'Confusion', 'Dizziness', 'Nausea', 'Memory Loss'],
            'Fracture' => ['Severe Pain', 'Swelling', 'Deformity', 'Inability to Move'],
            'Syncope' => ['Fainting', 'Dizziness', 'Lightheadedness', 'Sweating'],
            'Seizure' => ['Convulsions', 'Loss of Consciousness', 'Confusion', 'Staring Spell'],

            // Endocrinology
            'Type 1 Diabetes' => ['Frequent Urination', 'Excessive Thirst', 'Weight Loss', 'Fatigue'],
            'Type 2 Diabetes' => ['Frequent Urination', 'Excessive Thirst', 'Fatigue', 'Blurred Vision'],
            'Gestational Diabetes' => ['Frequent Urination', 'Excessive Thirst', 'Fatigue', 'Nausea'],
            'Hypothyroidism' => ['Fatigue', 'Weight Gain', 'Cold Intolerance', 'Dry Skin', 'Constipation'],
            'Hyperthyroidism' => ['Weight Loss', 'Rapid Heartbeat', 'Sweating', 'Anxiety', 'Heat Intolerance'],
            'Graves Disease' => ['Weight Loss', 'Anxiety', 'Bulging Eyes', 'Rapid Heartbeat'],
            'Hashimoto Thyroiditis' => ['Fatigue', 'Weight Gain', 'Neck Swelling', 'Cold Intolerance'],
            'Thyroid Nodule' => ['Neck Swelling', 'Difficulty Swallowing', 'Voice Changes', 'Pain'],
            'Cushing Syndrome' => ['Weight Gain', 'Stretch Marks', 'Fatigue', 'Muscle Weakness'],
            'Addison Disease' => ['Fatigue', 'Weight Loss', 'Low Blood Pressure', 'Skin Darkening'],
            'Polycystic Ovary Syndrome' => ['Irregular Menstrual Cycle', 'Acne', 'Weight Gain', 'Excess Hair Growth'],
            'Osteoporosis' => ['Back Pain', 'Loss of Height', 'Bone Fracture', 'Stooped Posture'],
            'Obesity' => ['Excessive Body Fat', 'Shortness of Breath', 'Fatigue', 'Joint Pain'],
            'Pituitary Adenoma' => ['Headache', 'Vision Changes', 'Fatigue', 'Hormonal Imbalance'],
            'Hyperparathyroidism' => ['Bone Pain', 'Kidney Stones', 'Fatigue', 'Weakness', 'Depression'],

            // ENT (Otolaryngology)
            'Sinusitis' => ['Nasal Congestion', 'Facial Pain', 'Headache', 'Runny Nose'],
            'Tonsillitis' => ['Sore Throat', 'Difficulty Swallowing', 'Fever', 'Swollen Tonsils'],
            'Otitis Media' => ['Ear Pain', 'Fever', 'Hearing Loss', 'Ear Discharge'],
            'Otitis Externa' => ['Ear Pain', 'Itching in Ear', 'Redness', 'Ear Discharge'],
            'Hearing Loss' => ['Muffled Hearing', 'Difficulty Understanding Speech', 'Ringing in Ears'],
            'Tinnitus' => ['Ringing in Ears', 'Buzzing Sound', 'Hearing Loss', 'Dizziness'],
            'Vertigo' => ['Dizziness', 'Spinning Sensation', 'Nausea', 'Loss of Balance'],
            'Nasal Polyps' => ['Nasal Congestion', 'Runny Nose', 'Decreased Sense of Smell', 'Facial Pressure'],
            'Deviated Nasal Septum' => ['Nasal Congestion', 'Nosebleeds', 'Facial Pain', 'Loud Breathing'],
            'Laryngitis' => ['Hoarseness', 'Voice Loss', 'Sore Throat', 'Dry Cough'],
            'Voice Disorder' => ['Hoarseness', 'Voice Break', 'Throat Pain', 'Vocal Fatigue'],
            'Sleep Apnea' => ['Snoring', 'Daytime Sleepiness', 'Morning Headache', 'Dry Mouth'],
            'Epistaxis' => ['Bleeding from Nose', 'Dizziness', 'Swallowing Blood', 'Weakness'],
            'Meniere\'s Disease' => ['Vertigo', 'Hearing Loss', 'Tinnitus', 'Feeling of Fullness in Ear'],

            // Gastroenterology
            'Gastroesophageal Reflux Disease' => ['Heartburn', 'Chest Pain', 'Difficulty Swallowing', 'Regurgitation'],
            'Peptic Ulcer Disease' => ['Abdominal Pain', 'Nausea', 'Vomiting', 'Bloating', 'Heartburn'],
            'Gastritis' => ['Abdominal Pain', 'Nausea', 'Vomiting', 'Loss of Appetite'],
            'Irritable Bowel Syndrome' => ['Abdominal Pain', 'Bloating', 'Diarrhea', 'Constipation'],
            'Inflammatory Bowel Disease' => ['Diarrhea', 'Abdominal Pain', 'Weight Loss', 'Fatigue', 'Blood in Stool'],
            'Ulcerative Colitis' => ['Diarrhea', 'Blood in Stool', 'Abdominal Pain', 'Weight Loss'],
            'Crohn Disease' => ['Abdominal Pain', 'Diarrhea', 'Weight Loss', 'Fatigue', 'Fever'],
            'Celiac Disease' => ['Diarrhea', 'Bloating', 'Gas', 'Fatigue', 'Weight Loss'],
            'Gallstones' => ['Severe Abdominal Pain', 'Back Pain', 'Nausea', 'Vomiting'],
            'Pancreatitis' => ['Severe Abdominal Pain', 'Nausea', 'Vomiting', 'Fever', 'Rapid Heartbeat'],
            'Hepatitis' => ['Fatigue', 'Jaundice', 'Nausea', 'Dark Urine', 'Abdominal Pain'],
            'Cirrhosis' => ['Fatigue', 'Jaundice', 'Swollen Legs', 'Weight Loss', 'Easy Bruising'],
            'Fatty Liver Disease' => ['Fatigue', 'Abdominal Pain', 'Weakness', 'Weight Loss'],
            'Constipation' => ['Infrequent Bowel Movements', 'Hard Stools', 'Straining', 'Abdominal Pain'],
            'Diarrhea' => ['Loose Stools', 'Frequent Bowel Movements', 'Abdominal Cramps', 'Nausea'],
            'Hemorrhoids' => ['Anal Itching', 'Pain During Bowel Movements', 'Bleeding', 'Swelling'],
            'Diverticulitis' => ['Lower Left Abdominal Pain', 'Fever', 'Nausea', 'Constipation', 'Diarrhea'],

            // General Medicine
            'Fever' => ['High Body Temperature', 'Chills', 'Sweating', 'Headache', 'Muscle Ache'],
            'Common Cold' => ['Runny Nose', 'Sore Throat', 'Cough', 'Congestion', 'Sneezing'],
            'Influenza' => ['Fever', 'Muscle Ache', 'Chills', 'Fatigue', 'Dry Cough'],
            'Fatigue' => ['Tiredness', 'Weakness', 'Lack of Energy', 'Difficulty Concentrating'],
            'Anemia' => ['Fatigue', 'Weakness', 'Pale Skin', 'Shortness of Breath', 'Dizziness'],
            'Vitamin D Deficiency' => ['Bone Pain', 'Muscle Weakness', 'Fatigue', 'Mood Changes'],
            'Vitamin B12 Deficiency' => ['Fatigue', 'Weakness', 'Numbness', 'Tingling', 'Memory Loss'],
            'Migraine' => ['Headache', 'Nausea', 'Sensitivity to Light', 'Sensitivity to Sound'],
            'Dengue Fever' => ['Fever', 'Headache', 'Body Pain', 'Joint Pain', 'Rash'],
            'Malaria' => ['Fever', 'Chills', 'Sweating', 'Headache', 'Nausea'],
            'Typhoid Fever' => ['Fever', 'Headache', 'Weakness', 'Abdominal Pain', 'Loss of Appetite'],
            'Urinary Tract Infection' => ['Burning Urination', 'Frequent Urination', 'Lower Abdominal Pain', 'Cloudy Urine'],
            'Dehydration' => ['Extreme Thirst', 'Dry Mouth', 'Dark Urine', 'Dizziness', 'Fatigue'],
            'Electrolyte Imbalance' => ['Muscle Cramps', 'Weakness', 'Irregular Heartbeat', 'Confusion'],

            // General Surgery
            'Appendicitis' => ['Lower Right Abdominal Pain', 'Nausea', 'Vomiting', 'Fever', 'Loss of Appetite'],
            'Hernia' => ['Bulge in Groin or Abdomen', 'Pain', 'Weakness', 'Feeling of Pressure'],
            'Gallbladder Disease' => ['Upper Right Abdominal Pain', 'Nausea', 'Vomiting', 'Fever'],
            'Abscess' => ['Painful Swelling', 'Redness', 'Warmth', 'Pus Discharge', 'Fever'],
            'Pilonidal Sinus' => ['Pain at Tailbone', 'Swelling', 'Redness', 'Pus Discharge'],
            'Thyroid Swelling' => ['Lump in Neck', 'Difficulty Swallowing', 'Voice Changes', 'Cough'],
            'Breast Lump' => ['Painless Lump', 'Breast Pain', 'Skin Changes', 'Nipple Discharge'],
            'Bowel Obstruction' => ['Severe Abdominal Pain', 'Vomiting', 'Bloating', 'Inability to Pass Gas'],
            'Varicose Veins' => ['Bulging Veins', 'Leg Pain', 'Swelling', 'Heavy Feeling in Legs'],
            'Soft Tissue Tumor' => ['Painless Lump', 'Swelling', 'Pain', 'Restricted Movement'],

            // Geriatrics
            'Dementia' => ['Memory Loss', 'Confusion', 'Difficulty Thinking', 'Behavioral Changes'],
            'Delirium' => ['Sudden Confusion', 'Disorientation', 'Hallucinations', 'Agitation'],
            'Falls in Elderly' => ['Loss of Balance', 'Dizziness', 'Weakness', 'Vision Problems'],
            'Frailty' => ['Weight Loss', 'Weakness', 'Exhaustion', 'Slow Walking Speed'],
            'Polypharmacy' => ['Confusion', 'Dizziness', 'Fatigue', 'Nausea', 'Drug Interactions'],
            'Urinary Incontinence' => ['Leakage of Urine', 'Frequent Urination', 'Sudden Urge to Urinate'],
            'Pressure Ulcer' => ['Skin Redness', 'Skin Ulcer', 'Pain', 'Infection'],
            'Parkinsonism' => ['Tremor', 'Stiffness', 'Slow Movement', 'Loss of Balance'],

            // Gynecology
            'Irregular Menstrual Cycle' => ['Missed Periods', 'Heavy Bleeding', 'Spotting', 'Cramping'],
            'Dysmenorrhea' => ['Severe Menstrual Cramps', 'Pelvic Pain', 'Back Pain', 'Nausea'],
            'Endometriosis' => ['Pelvic Pain', 'Painful Menstruation', 'Painful Intercourse', 'Infertility'],
            'Uterine Fibroid' => ['Heavy Menstrual Bleeding', 'Pelvic Pain', 'Frequent Urination', 'Back Pain'],
            'Ovarian Cyst' => ['Pelvic Pain', 'Bloating', 'Irregular Menstrual Cycle', 'Painful Intercourse'],
            'Pelvic Inflammatory Disease' => ['Pelvic Pain', 'Fever', 'Abnormal Vaginal Discharge', 'Painful Urination'],
            'Vaginitis' => ['Vaginal Itching', 'Vaginal Discharge', 'Odor', 'Painful Urination'],
            'Menopause Symptoms' => ['Hot Flashes', 'Night Sweats', 'Mood Swings', 'Vaginal Dryness'],
            'Abnormal Uterine Bleeding' => ['Heavy Bleeding', 'Bleeding Between Periods', 'Prolonged Periods'],
            'Cervical Dysplasia' => ['Abnormal Vaginal Bleeding', 'Spotting After Intercourse', 'Pelvic Pain'],
            'Adenomyosis' => ['Heavy Menstrual Bleeding', 'Severe Menstrual Cramps', 'Pelvic Pain', 'Painful Intercourse'],

            // Hematology
            'Iron Deficiency Anemia' => ['Fatigue', 'Weakness', 'Pale Skin', 'Cold Hands and Feet', 'Brittle Nails'],
            'Aplastic Anemia' => ['Fatigue', 'Frequent Infections', 'Easy Bruising', 'Bleeding Gums'],
            'Thalassemia' => ['Fatigue', 'Weakness', 'Pale Skin', 'Facial Bone Deformities', 'Dark Urine'],
            'Sickle Cell Disease' => ['Episodes of Pain', 'Fatigue', 'Swelling of Hands and Feet', 'Frequent Infections'],
            'Hemophilia' => ['Unexplained Bleeding', 'Large Bruises', 'Joint Pain', 'Prolonged Bleeding'],
            'Thrombocytopenia' => ['Easy Bruising', 'Prolonged Bleeding', 'Bleeding Gums', 'Blood in Urine'],
            'Leukemia' => ['Fever', 'Fatigue', 'Frequent Infections', 'Weight Loss', 'Bleeding'],
            'Lymphoma' => ['Swollen Lymph Nodes', 'Fatigue', 'Weight Loss', 'Night Sweats', 'Fever'],
            'Multiple Myeloma' => ['Bone Pain', 'Fatigue', 'Frequent Infections', 'Kidney Problems', 'Weight Loss'],
            'Polycythemia Vera' => ['Headache', 'Dizziness', 'Itching', 'Redness of Face', 'Fatigue'],

            // Infectious Diseases
            'Tuberculosis' => ['Chronic Cough', 'Weight Loss', 'Fever', 'Night Sweats', 'Chest Pain'],
            'HIV Infection' => ['Fever', 'Fatigue', 'Swollen Lymph Nodes', 'Weight Loss', 'Sore Throat'],
            'COVID-19' => ['Fever', 'Dry Cough', 'Fatigue', 'Loss of Taste or Smell', 'Shortness of Breath'],
            'Chikungunya' => ['Fever', 'Severe Joint Pain', 'Muscle Ache', 'Headache', 'Rash'],
            'Hepatitis B' => ['Fatigue', 'Jaundice', 'Dark Urine', 'Abdominal Pain', 'Nausea'],
            'Hepatitis C' => ['Fatigue', 'Jaundice', 'Dark Urine', 'Abdominal Pain', 'Loss of Appetite'],
            'Rabies Exposure' => ['Fever', 'Headache', 'Nausea', 'Vomiting', 'Agitation'],
            'Meningitis' => ['Sudden High Fever', 'Stiff Neck', 'Severe Headache', 'Nausea', 'Confusion'],
            'Syphilis' => ['Painless Sore', 'Skin Rash', 'Fever', 'Swollen Lymph Nodes', 'Fatigue'],
            'Gonorrhea' => ['Painful Urination', 'Abnormal Discharge', 'Pelvic Pain', 'Testicular Pain'],
            'Chlamydia' => ['Painful Urination', 'Abnormal Vaginal Discharge', 'Penile Discharge', 'Pelvic Pain'],

            // Nephrology
            'Chronic Kidney Disease' => ['Fatigue', 'Swollen Legs', 'Frequent Urination', 'Nausea', 'Shortness of Breath'],
            'Acute Kidney Injury' => ['Decreased Urine Output', 'Swelling', 'Fatigue', 'Confusion', 'Nausea'],
            'Nephrotic Syndrome' => ['Severe Swelling', 'Foamy Urine', 'Weight Gain', 'Fatigue'],
            'Glomerulonephritis' => ['Pink or Cola-colored Urine', 'Foamy Urine', 'High Blood Pressure', 'Swelling'],
            'Kidney Stones' => ['Severe Abdominal Pain', 'Back Pain', 'Burning Urination', 'Nausea', 'Blood in Urine'],
            'Polycystic Kidney Disease' => ['High Blood Pressure', 'Back Pain', 'Blood in Urine', 'Frequent Urination'],
            'Diabetic Nephropathy' => ['Swelling', 'Protein in Urine', 'Fatigue', 'Frequent Urination'],
            'Hypertensive Nephropathy' => ['High Blood Pressure', 'Swelling', 'Frequent Urination', 'Fatigue'],
            'Electrolyte Disorder' => ['Muscle Cramps', 'Weakness', 'Irregular Heartbeat', 'Confusion', 'Nausea'],

            // Neurology
            'Epilepsy' => ['Seizure', 'Confusion', 'Loss of Consciousness', 'Staring Spell'],
            'Stroke' => ['Weakness', 'Speech Difficulty', 'Dizziness', 'Facial Drooping', 'Numbness'],
            'Transient Ischemic Attack' => ['Temporary Weakness', 'Speech Difficulty', 'Dizziness', 'Facial Drooping'],
            'Parkinson Disease' => ['Tremor', 'Slow Movement', 'Stiffness', 'Loss of Balance'],
            'Multiple Sclerosis' => ['Numbness', 'Weakness', 'Vision Loss', 'Tingling', 'Fatigue'],
            'Neuropathy' => ['Numbness', 'Tingling', 'Burning Pain', 'Muscle Weakness'],
            'Alzheimer Disease' => ['Memory Loss', 'Confusion', 'Difficulty Thinking', 'Behavioral Changes'],
            'Bell Palsy' => ['Facial Drooping', 'Inability to Close Eye', 'Drooling', 'Pain Around Jaw'],
            'Tremor' => ['Involuntary Shaking', 'Trembling Voice', 'Difficulty Writing'],
            'Myasthenia Gravis' => ['Muscle Weakness', 'Drooping Eyelids', 'Difficulty Swallowing', 'Shortness of Breath'],
            'Huntington Disease' => ['Involuntary Movements', 'Cognitive Decline', 'Depression', 'Mood Swings'],
            'Amyotrophic Lateral Sclerosis' => ['Muscle Weakness', 'Muscle Twitches', 'Slurred Speech', 'Difficulty Swallowing'],
            'Guillain-Barre Syndrome' => ['Weakness in Legs', 'Tingling', 'Unsteady Walking', 'Difficulty Breathing'],
            'Trigeminal Neuralgia' => ['Severe Facial Pain', 'Electric Shock-like Pain', 'Pain Triggered by Chewing'],
            'Restless Legs Syndrome' => ['Urge to Move Legs', 'Crawling Sensation in Legs', 'Worse at Night'],

            // Obstetrics
            'Normal Pregnancy' => ['Missed Periods', 'Nausea', 'Breast Tenderness', 'Fatigue', 'Frequent Urination'],
            'High Risk Pregnancy' => ['Vaginal Bleeding', 'Severe Abdominal Pain', 'High Blood Pressure', 'Severe Headache'],
            'Ectopic Pregnancy' => ['Severe Abdominal Pain', 'Vaginal Bleeding', 'Shoulder Pain', 'Dizziness'],
            'Miscarriage' => ['Vaginal Bleeding', 'Severe Cramping', 'Abdominal Pain', 'Passing Tissue'],
            'Preeclampsia' => ['High Blood Pressure', 'Protein in Urine', 'Severe Headache', 'Vision Changes', 'Swelling'],
            'Placenta Previa' => ['Painless Vaginal Bleeding', 'Premature Contractions', 'Abdominal Pain'],
            'Preterm Labor' => ['Regular Contractions', 'Pelvic Pressure', 'Lower Back Pain', 'Vaginal Discharge'],
            'Postpartum Hemorrhage' => ['Excessive Vaginal Bleeding', 'Drop in Blood Pressure', 'Pale Skin', 'Dizziness'],
            'Postpartum Depression' => ['Severe Mood Swings', 'Excessive Crying', 'Difficulty Bonding with Baby', 'Fatigue'],

            // Oncology
            'Breast Cancer' => ['Breast Lump', 'Changes in Breast Shape', 'Skin Dimpling', 'Nipple Discharge'],
            'Lung Cancer' => ['Chronic Cough', 'Chest Pain', 'Shortness of Breath', 'Coughing up Blood', 'Weight Loss'],
            'Colorectal Cancer' => ['Change in Bowel Habits', 'Blood in Stool', 'Abdominal Pain', 'Weight Loss', 'Fatigue'],
            'Prostate Cancer' => ['Difficulty Urinating', 'Weak Urine Stream', 'Blood in Urine', 'Pelvic Pain', 'Bone Pain'],
            'Cervical Cancer' => ['Abnormal Vaginal Bleeding', 'Pelvic Pain', 'Painful Intercourse', 'Vaginal Discharge'],
            'Ovarian Cancer' => ['Bloating', 'Pelvic Pain', 'Difficulty Eating', 'Frequent Urination', 'Weight Loss'],
            'Liver Cancer' => ['Weight Loss', 'Loss of Appetite', 'Upper Abdominal Pain', 'Nausea', 'Jaundice'],
            'Stomach Cancer' => ['Difficulty Swallowing', 'Feeling Full after Eating Little', 'Nausea', 'Weight Loss', 'Stomach Pain'],
            'Pancreatic Cancer' => ['Upper Abdominal Pain', 'Jaundice', 'Weight Loss', 'Loss of Appetite', 'Fatigue'],
            'Brain Tumor' => ['New Onset Headaches', 'Seizure', 'Vision Changes', 'Loss of Balance', 'Confusion'],
            'Melanoma' => ['Changes in an Existing Mole', 'New Pigmented Growth', 'Irregular Skin Lesion', 'Itching'],

            // Ophthalmology
            'Refractive Error' => ['Blurred Vision', 'Squinting', 'Eye Strain', 'Headache'],
            'Cataract' => ['Blurred Vision', 'Sensitivity to Light', 'Poor Night Vision', 'Fading Colors'],
            'Glaucoma' => ['Loss of Peripheral Vision', 'Eye Pain', 'Red Eyes', 'Blurred Vision', 'Halos Around Lights'],
            'Conjunctivitis' => ['Red Eyes', 'Itchy Eyes', 'Tearing', 'Eye Discharge', 'Crusting of Eyelids'],
            'Dry Eye Syndrome' => ['Stinging in Eyes', 'Red Eyes', 'Sensitivity to Light', 'Blurred Vision', 'Feeling of Sand in Eye'],
            'Diabetic Retinopathy' => ['Spots in Vision', 'Blurred Vision', 'Fluctuating Vision', 'Vision Loss'],
            'Age Related Macular Degeneration' => ['Blurred Central Vision', 'Distorted Vision', 'Difficulty Adapting to Low Light'],
            'Retinal Detachment' => ['Sudden Flashes of Light', 'Floaters', 'Shadow over Vision', 'Sudden Vision Loss'],
            'Uveitis' => ['Eye Redness', 'Eye Pain', 'Sensitivity to Light', 'Blurred Vision', 'Floaters'],
            'Keratitis' => ['Eye Redness', 'Eye Pain', 'Tearing', 'Difficulty Opening Eyes', 'Blurred Vision'],
            'Strabismus' => ['Crossed Eyes', 'Double Vision', 'Uncoordinated Eye Movements', 'Loss of Depth Perception'],
            'Amblyopia' => ['Poor Vision in One Eye', 'Squinting', 'Head Tilting', 'Poor Depth Perception'],
            'Color Blindness' => ['Difficulty Distinguishing Colors', 'Inability to See Shades'],
            'Stye' => ['Red Bump on Eyelid', 'Eyelid Pain', 'Swelling of Eyelid', 'Tearing'],
            'Chalazion' => ['Painless Bump on Eyelid', 'Blurred Vision', 'Eyelid Heaviness'],

            // Orthopedics
            'Osteoarthritis' => ['Joint Pain', 'Stiffness', 'Swelling', 'Decreased Range of Motion', 'Bone Spurs'],
            'Rheumatoid Arthritis' => ['Joint Pain', 'Joint Swelling', 'Morning Stiffness', 'Fatigue', 'Fever'],
            'Back Pain' => ['Lower Back Pain', 'Muscle Ache', 'Shooting Pain', 'Stiffness', 'Limited Mobility'],
            'Neck Pain' => ['Stiff Neck', 'Pain Worse with Movement', 'Muscle Spasm', 'Headache'],
            'Dislocation' => ['Visible Deformity', 'Severe Pain', 'Swelling', 'Inability to Move Joint'],
            'Ligament Tear' => ['Sudden Severe Pain', 'Popping Sound', 'Swelling', 'Inability to Bear Weight'],
            'Meniscus Tear' => ['Knee Pain', 'Swelling', 'Stiffness', 'Popping Sensation in Knee'],
            'Rotator Cuff Tear' => ['Shoulder Pain', 'Weakness in Arm', 'Difficulty Lifting Arm', 'Crackling Sensation'],
            'Carpal Tunnel Syndrome' => ['Tingling in Hand', 'Numbness in Fingers', 'Weakness in Hand', 'Pain in Wrist'],
            'Sciatica' => ['Lower Back Pain', 'Leg Pain', 'Numbness in Leg', 'Tingling', 'Weakness'],
            'Scoliosis' => ['Uneven Shoulders', 'Uneven Waist', 'One Hip Higher', 'Back Pain'],
            'Gout' => ['Severe Joint Pain', 'Joint Swelling', 'Redness', 'Heat in Joint', 'Lingering Discomfort'],
            'Plantar Fasciitis' => ['Heel Pain', 'Pain with First Steps', 'Foot Stiffness'],
            'Achilles Tendinitis' => ['Pain in Heel', 'Stiffness in Calf', 'Swelling in Heel'],
            'Tennis Elbow' => ['Pain on Outside of Elbow', 'Weak Grip', 'Pain Lifting Objects'],

            // Pediatrics
            'Pediatric Fever' => ['High Body Temperature', 'Irritability', 'Lethargy', 'Poor Appetite', 'Crying'],
            'Pediatric Asthma' => ['Wheezing', 'Coughing', 'Shortness of Breath', 'Chest Tightness', 'Rapid Breathing'],
            'Bronchiolitis' => ['Runny Nose', 'Congestion', 'Cough', 'Wheezing', 'Fever'],
            'Pneumonia in Children' => ['Fever', 'Cough', 'Rapid Breathing', 'Wheezing', 'Lethargy'],
            'Chickenpox' => ['Itchy Rash', 'Blisters', 'Fever', 'Fatigue', 'Loss of Appetite'],
            'Measles' => ['Fever', 'Dry Cough', 'Runny Nose', 'Sore Throat', 'Skin Rash'],
            'Mumps' => ['Swollen Salivary Glands', 'Fever', 'Headache', 'Muscle Ache', 'Pain While Chewing'],
            'Hand Foot and Mouth Disease' => ['Fever', 'Sore Throat', 'Painful Blisters in Mouth', 'Rash on Hands and Feet'],
            'Growth Delay' => ['Short Stature', 'Slow Weight Gain', 'Delayed Development', 'Lack of Appetite'],
            'Failure to Thrive' => ['Slow Weight Gain', 'Irritability', 'Fatigue', 'Delayed Motor Skills'],
            'Neonatal Jaundice' => ['Yellowing of Skin', 'Yellowing of Eyes', 'Sleepiness', 'Poor Feeding'],
            'Pediatric Diarrhea' => ['Frequent Watery Stools', 'Abdominal Cramps', 'Fever', 'Dehydration', 'Nausea'],
            'Worm Infestation' => ['Abdominal Pain', 'Diarrhea', 'Weight Loss', 'Itching Around Anus', 'Fatigue'],
            'Croup' => ['Barking Cough', 'Stridor', 'Hoarseness', 'Difficulty Breathing'],
            'Rubella' => ['Skin Rash', 'Fever', 'Swollen Lymph Nodes', 'Joint Pain'],

            // Psychiatry
            'Major Depressive Disorder' => ['Sadness', 'Fatigue', 'Loss of Interest', 'Sleep Disturbances', 'Weight Changes'],
            'Generalized Anxiety Disorder' => ['Excessive Worry', 'Restlessness', 'Fatigue', 'Difficulty Concentrating', 'Muscle Tension'],
            'Panic Disorder' => ['Sudden Terror', 'Rapid Heartbeat', 'Sweating', 'Shortness of Breath', 'Trembling'],
            'Bipolar Disorder' => ['Mood Swings', 'High Energy', 'Sadness', 'Impulsivity', 'Decreased Need for Sleep'],
            'Schizophrenia' => ['Delusions', 'Hallucinations', 'Disorganized Speech', 'Lack of Motivation', 'Social Withdrawal'],
            'Obsessive Compulsive Disorder' => ['Intrusive Thoughts', 'Compulsive Behavior', 'Fear of Contamination', 'Need for Symmetry'],
            'Post Traumatic Stress Disorder' => ['Flashbacks', 'Nightmares', 'Severe Anxiety', 'Avoidance', 'Easily Startled'],
            'Attention Deficit Hyperactivity Disorder' => ['Inattention', 'Hyperactivity', 'Impulsivity', 'Difficulty Focusing', 'Restlessness'],
            'Autism Spectrum Disorder' => ['Social Interaction Difficulties', 'Repetitive Behaviors', 'Delayed Speech', 'Lack of Eye Contact'],
            'Insomnia' => ['Difficulty Falling Asleep', 'Waking Up Frequently', 'Fatigue', 'Irritability', 'Daytime Sleepiness'],
            'Eating Disorder' => ['Extreme Weight Loss', 'Binge Eating', 'Induced Vomiting', 'Body Image Distortion', 'Fatigue'],
            'Borderline Personality Disorder' => ['Fear of Abandonment', 'Unstable Relationships', 'Mood Swings', 'Impulsive Behavior'],

            // Pulmonology
            'Asthma' => ['Chronic Cough', 'Shortness of Breath', 'Wheezing', 'Chest Tightness'],
            'Chronic Obstructive Pulmonary Disease' => ['Shortness of Breath', 'Chronic Cough', 'Wheezing', 'Fatigue', 'Excessive Mucus'],
            'Pneumonia' => ['Fever', 'Chronic Cough', 'Shortness of Breath', 'Chest Pain', 'Chills'],
            'Bronchitis' => ['Cough', 'Mucus Production', 'Fatigue', 'Shortness of Breath', 'Chest Discomfort'],
            'Pulmonary Fibrosis' => ['Shortness of Breath', 'Dry Cough', 'Fatigue', 'Unexplained Weight Loss', 'Aching Muscles'],
            'Pleural Effusion' => ['Chest Pain', 'Dry Cough', 'Shortness of Breath', 'Fever', 'Difficulty Breathing Lying Down'],
            'Pulmonary Embolism' => ['Sudden Shortness of Breath', 'Chest Pain', 'Coughing up Blood', 'Rapid Heartbeat', 'Sweating'],
            'Chronic Cough' => ['Persistent Cough', 'Runny Nose', 'Heartburn', 'Hoarseness', 'Wheezing'],
            'Cystic Fibrosis' => ['Salty Tasting Skin', 'Persistent Cough', 'Frequent Lung Infections', 'Poor Growth'],
            'Bronchiectasis' => ['Chronic Cough', 'Coughing up Mucus', 'Shortness of Breath', 'Chest Pain'],

            // Rheumatology
            'Systemic Lupus Erythematosus' => ['Fatigue', 'Joint Pain', 'Butterfly Rash', 'Fever', 'Sensitivity to Light'],
            'Ankylosing Spondylitis' => ['Lower Back Pain', 'Stiffness', 'Fatigue', 'Joint Pain', 'Reduced Flexibility'],
            'Psoriatic Arthritis' => ['Joint Pain', 'Stiffness', 'Swelling', 'Red Patches on Skin', 'Nail Changes'],
            'Vasculitis' => ['Fever', 'Headache', 'Fatigue', 'Weight Loss', 'Night Sweats', 'Numbness'],
            'Scleroderma' => ['Skin Thickening', 'Joint Pain', 'Cold Extremities', 'Heartburn', 'Shortness of Breath'],
            'Sjogren Syndrome' => ['Dry Eyes', 'Dry Mouth', 'Joint Pain', 'Fatigue', 'Swollen Salivary Glands'],
            'Fibromyalgia' => ['Widespread Muscle Pain', 'Fatigue', 'Sleep Disturbances', 'Memory Problems', 'Headache'],
            'Polymyalgia Rheumatica' => ['Shoulder Pain', 'Neck Pain', 'Hip Pain', 'Morning Stiffness', 'Fatigue'],

            // Urology
            'Benign Prostatic Hyperplasia' => ['Frequent Urination', 'Weak Urine Stream', 'Difficulty Urinating', 'Nocturia', 'Incomplete Bladder Emptying'],
            'Prostatitis' => ['Painful Urination', 'Pelvic Pain', 'Frequent Urination', 'Fever', 'Cloudy Urine'],
            'Erectile Dysfunction' => ['Difficulty Achieving Erection', 'Difficulty Maintaining Erection', 'Reduced Sexual Desire'],
            'Male Infertility' => ['Inability to Conceive', 'Sexual Dysfunction', 'Pain in Testicle', 'Swelling in Testicle'],
            'Bladder Cancer' => ['Blood in Urine', 'Frequent Urination', 'Painful Urination', 'Back Pain', 'Pelvic Pain'],
            'Testicular Torsion' => ['Sudden Severe Testicular Pain', 'Swelling in Scrotum', 'Nausea', 'Vomiting', 'Abdominal Pain'],
            'Hydrocele' => ['Painless Swelling in Scrotum', 'Feeling of Heaviness in Scrotum', 'Discomfort'],
            'Interstitial Cystitis' => ['Pelvic Pain', 'Frequent Urination', 'Urge to Urinate', 'Painful Urination'],
            'Overactive Bladder' => ['Sudden Urge to Urinate', 'Frequent Urination', 'Leakage of Urine', 'Nocturia'],

            // Vascular Surgery
            'Aortic Aneurysm' => ['Deep Pain in Back or Side', 'Pulsating Feeling near Navel', 'Shortness of Breath'],
            'Carotid Artery Disease' => ['Sudden Weakness', 'Speech Difficulty', 'Sudden Vision Loss', 'Dizziness', 'Severe Headache'],
            'Chronic Venous Insufficiency' => ['Swelling in Legs', 'Leg Pain', 'Varicose Veins', 'Skin Color Changes in Legs', 'Leg Ulcers'],
            'Diabetic Foot Ulcer' => ['Sore on Foot', 'Redness', 'Swelling', 'Odor from Foot', 'Numbness'],
            'Lymphedema' => ['Swelling in Arm or Leg', 'Feeling of Heaviness', 'Restricted Range of Motion', 'Aching', 'Hardening of Skin'],
        ];

        $symptoms = $map[$diseaseName] ?? [$diseaseName];

        return array_values(array_unique(array_filter(array_map('trim', $symptoms))));
    }

    public static function hindiNameFor(string $name): string
    {
        return [
            // Departments 
            'Addiction Medicine' => 'व्यसन चिकित्सा',
            'Allergy and Immunology' => 'एलर्जी और इम्यूनोलॉजी',
            'Cardiology' => 'हृदय रोग विभाग (कार्डियोलॉजी)',
            'Dermatology' => 'त्वचा विज्ञान (डर्मेटोलॉजी)',
            'Emergency Medicine' => 'आपातकालीन चिकित्सा',
            'Endocrinology' => 'अंतःस्रावी विज्ञान (एंडोक्रिनोलॉजी)',
            'ENT (Otolaryngology)' => 'ईएनटी (कान, नाक, गला)',
            'Gastroenterology' => 'गैस्ट्रोएंटरोलॉजी',
            'General Medicine' => 'सामान्य चिकित्सा',
            'General Surgery' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
            'Geriatrics' => 'वृद्धावस्था चिकित्सा',
            'Gynecology' => 'स्त्री रोग विज्ञान',
            'Hematology' => 'हेमेटोलॉजी (रक्त विज्ञान)',
            'Infectious Diseases' => 'संक्रामक रोग',
            'Nephrology' => 'नेफ्रोलॉजी (गुर्दा रोग)',
            'Neurology' => 'न्यूरोलॉजी (तंत्रिका विज्ञान)',
            'Obstetrics' => 'प्रसूति विज्ञान',
            'Oncology' => 'ऑन्कोलॉजी (कैंसर विज्ञान)',
            'Ophthalmology' => 'नेत्र विज्ञान',
            'Orthopedics' => 'ऑर्थोपेडिक्स (हड्डी रोग)',
            'Pediatrics' => 'बाल चिकित्सा',
            'Psychiatry' => 'मनोरोग विज्ञान',
            'Pulmonology' => 'पल्मोनोलॉजी (फेफड़े के रोग)',
            'Rheumatology' => 'रुमेटोलॉजी (गठिया रोग)',
            'Urology' => 'यूरोलॉजी (मूत्र विज्ञान)',
            'Vascular Surgery' => 'संवहनी शल्य चिकित्सा',

            // Diseases
            'Acne Vulgaris' => 'मुंहासे',
            'Abnormal Uterine Bleeding' => 'असामान्य गर्भाशयी रक्तस्राव',
            'Abscess' => 'फोड़ा',
            'Acute Asthma Attack' => 'तीव्र अस्थमा अटैक',
            'Acute Kidney Injury' => 'तीव्र गुर्दा क्षति',
            'Addison Disease' => 'एडिसन रोग',
            'Age Related Macular Degeneration' => 'उम्र से संबंधित मैक्युलर डिजनरेशन',
            'Alcohol Use Disorder' => 'शराब उपयोग विकार',
            'Allergic Rhinitis' => 'एलर्जिक राइनाइटिस',
            'Alopecia Areata' => 'एलोपेसिया एरीटा',
            'Alzheimer Disease' => 'अल्जाइमर रोग',
            'Amblyopia' => 'आलसी आंख',
            'Anaphylaxis' => 'एनाफिलैक्सिस',
            'Anemia' => 'एनीमिया',
            'Angina' => 'एनजाइना',
            'Angioedema' => 'एंजियोएडेमा',
            'Ankylosing Spondylitis' => 'एंकिलोजिंग स्पॉन्डिलाइटिस',
            'Aortic Aneurysm' => 'महाधमनी एन्यूरिज्म',
            'Aplastic Anemia' => 'अप्लास्टिक एनीमिया',
            'Appendicitis' => 'अपेंडिसाइटिस',
            'Arrhythmia' => 'हृदय गति अनियमितता',
            'Asthma' => 'अस्थमा',
            'Atopic Dermatitis' => 'एटोपिक डर्मेटाइटिस',
            'Atrial Fibrillation' => 'एट्रियल फिब्रिलेशन',
            'Attention Deficit Hyperactivity Disorder' => 'ध्यान-अभाव अति सक्रियता विकार',
            'Autism Spectrum Disorder' => 'ऑटिज्म स्पेक्ट्रम विकार',
            'Back Pain' => 'पीठ दर्द',
            'Bell Palsy' => 'बेल्स पाल्सी',
            'Benign Prostatic Hyperplasia' => 'प्रोस्टेट ग्रंथि का सौम्य बढ़ना',
            'Bipolar Disorder' => 'द्विध्रुवी विकार',
            'Bladder Cancer' => 'मूत्राशय कैंसर',
            'Brain Tumor' => 'मस्तिष्क ट्यूमर',
            'Breast Cancer' => 'स्तन कैंसर',
            'Breast Lump' => 'स्तन में गांठ',
            'Bronchiolitis' => 'ब्रोंकियोलाइटिस',
            'Bronchitis' => 'ब्रोंकाइटिस',
            'Bowel Obstruction' => 'आंत्र अवरोध',
            'Burn Injury' => 'जलने की चोट',
            'Cannabis Use Disorder' => 'भांग उपयोग विकार',
            'Cardiomyopathy' => 'कार्डियोमायोपैथी',
            'Carotid Artery Disease' => 'कैरोटिड धमनी रोग',
            'Carpal Tunnel Syndrome' => 'कार्पल टनल सिंड्रोम',
            'Cataract' => 'मोतियाबिंद',
            'Celiac Disease' => 'सीलिएक रोग',
            'Cellulitis' => 'सेल्युलाइटिस',
            'Cervical Cancer' => 'गर्भाशय ग्रीवा कैंसर',
            'Cervical Dysplasia' => 'गर्भाशय ग्रीवा डिस्प्लेसिया',
            'Chest Pain' => 'छाती में दर्द',
            'Chickenpox' => 'चेचक',
            'Chikungunya' => 'चिकनगुनिया',
            'Chronic Cough' => 'पुरानी खांसी',
            'Chronic Kidney Disease' => 'दीर्घकालिक गुर्दा रोग',
            'Chronic Obstructive Pulmonary Disease' => 'क्रॉनिक ऑब्सट्रक्टिव पल्मोनरी डिजीज',
            'Chronic Venous Insufficiency' => 'दीर्घकालिक शिरापरक अपर्याप्तता',
            'Cirrhosis' => 'सिरोसिस',
            'Colorectal Cancer' => 'कोलोरेक्टल कैंसर',
            'Common Cold' => 'सामान्य जुकाम',
            'Common Variable Immunodeficiency' => 'कॉमन वेरिएबल इम्यूनोडेफिशिएंसी',
            'Conjunctivitis' => 'कंजंक्टिवाइटिस',
            'Constipation' => 'कब्ज',
            'Coronary Artery Disease' => 'कोरोनरी धमनी रोग',
            'Crohn Disease' => 'क्रोहन रोग',
            'Cushing Syndrome' => 'कुशिंग सिंड्रोम',
            'COVID-19' => 'कोविड-19',
            'Deep Vein Thrombosis' => 'गहरी शिरा घनास्त्रता',
            'Dehydration' => 'निर्जलीकरण',
            'Delirium' => 'डिलीरियम',
            'Dementia' => 'डिमेंशिया',
            'Dengue Fever' => 'डेंगू बुखार',
            'Deviated Nasal Septum' => 'नाक की टेढ़ी सेप्टम',
            'Diabetic Foot Ulcer' => 'मधुमेहजनित पैर का अल्सर',
            'Diabetic Nephropathy' => 'मधुमेहजनित गुर्दा रोग',
            'Diabetic Retinopathy' => 'मधुमेहजनित रेटिनोपैथी',
            'Diarrhea' => 'दस्त',
            'Dislocation' => 'जोड़ खिसकना',
            'Drug Allergy' => 'दवा से एलर्जी',
            'Dry Eye Syndrome' => 'सूखी आंख सिंड्रोम',
            'Dysmenorrhea' => 'कष्टार्तव',
            'Eating Disorder' => 'भोजन विकार',
            'Ectopic Pregnancy' => 'अस्थानिक गर्भावस्था',
            'Eczema' => 'एक्जिमा',
            'Electrolyte Disorder' => 'इलेक्ट्रोलाइट विकार',
            'Electrolyte Imbalance' => 'इलेक्ट्रोलाइट असंतुलन',
            'Endometriosis' => 'एंडोमेट्रियोसिस',
            'Epilepsy' => 'मिर्गी',
            'Epistaxis' => 'नाक से खून आना',
            'Erectile Dysfunction' => 'स्तंभन दोष',
            'Failure to Thrive' => 'विकास में कमी',
            'Falls in Elderly' => 'बुजुर्गों में गिरना',
            'Fatigue' => 'थकान',
            'Fatty Liver Disease' => 'फैटी लिवर रोग',
            'Fever' => 'बुखार',
            'Fibromyalgia' => 'फाइब्रोमायल्जिया',
            'Food Allergy' => 'खाद्य एलर्जी',
            'Fracture' => 'हड्डी टूटना',
            'Frailty' => 'दुर्बलता',
            'Fungal Skin Infection' => 'त्वचा का फंगल संक्रमण',
            'Gallbladder Disease' => 'पित्ताशय रोग',
            'Gallstones' => 'पित्त की पथरी',
            'Gambling Disorder' => 'जुआ विकार',
            'Gastritis' => 'गैस्ट्राइटिस',
            'Gastroesophageal Reflux Disease' => 'गैस्ट्रोइसोफेजियल रिफ्लक्स रोग',
            'Generalized Anxiety Disorder' => 'सामान्यीकृत चिंता विकार',
            'Gestational Diabetes' => 'गर्भावधि मधुमेह',
            'Glaucoma' => 'ग्लूकोमा',
            'Glomerulonephritis' => 'ग्लोमेरुलोनेफ्राइटिस',
            'Gout' => 'गठिया',
            'Graves Disease' => 'ग्रेव्स रोग',
            'Growth Delay' => 'विकास में देरी',
            'Hand Foot and Mouth Disease' => 'हाथ, पैर और मुंह रोग',
            'Hashimoto Thyroiditis' => 'हाशिमोटो थायरॉयडाइटिस',
            'Head Injury' => 'सिर की चोट',
            'Hearing Loss' => 'सुनने में कमी',
            'Heart Failure' => 'हृदय विफलता',
            'Hemophilia' => 'हीमोफीलिया',
            'Hemorrhoids' => 'बवासीर',
            'Hepatitis' => 'हेपेटाइटिस',
            'Hepatitis B' => 'हेपेटाइटिस बी',
            'Hepatitis C' => 'हेपेटाइटिस सी',
            'Hernia' => 'हर्निया',
            'Herpes Zoster' => 'हरपीज जोस्टर',
            'High Risk Pregnancy' => 'उच्च जोखिम गर्भावस्था',
            'HIV Infection' => 'एचआईवी संक्रमण',
            'Hydrocele' => 'हाइड्रोसील',
            'Hyperlipidemia' => 'उच्च लिपिड स्तर',
            'Hypertension' => 'उच्च रक्तचाप',
            'Hypertensive Nephropathy' => 'उच्च रक्तचापजनित गुर्दा रोग',
            'Hyperthyroidism' => 'हाइपरथायरॉयडिज्म',
            'Hypothyroidism' => 'हाइपोथायरॉयडिज्म',
            'Impetigo' => 'इम्पेटाइगो',
            'Inflammatory Bowel Disease' => 'आंत्र सूजन रोग',
            'Influenza' => 'इन्फ्लुएंजा',
            'Insomnia' => 'अनिद्रा',
            'Irregular Menstrual Cycle' => 'अनियमित मासिक धर्म',
            'Irritable Bowel Syndrome' => 'इरिटेबल बाउल सिंड्रोम',
            'Iron Deficiency Anemia' => 'लौह-अल्पता एनीमिया',
            'Keratitis' => 'केराटाइटिस',
            'Kidney Stones' => 'गुर्दे की पथरी',
            'Laryngitis' => 'स्वरयंत्र शोथ',
            'Leukemia' => 'ल्यूकेमिया',
            'Ligament Tear' => 'लिगामेंट फटना',
            'Liver Cancer' => 'यकृत कैंसर',
            'Lung Cancer' => 'फेफड़ों का कैंसर',
            'Lymphoma' => 'लिम्फोमा',
            'Lymphedema' => 'लिम्फेडेमा',
            'Major Depressive Disorder' => 'गंभीर अवसाद विकार',
            'Malaria' => 'मलेरिया',
            'Male Infertility' => 'पुरुष बांझपन',
            'Melanoma' => 'मेलानोमा',
            'Melasma' => 'मेलास्मा',
            'Measles' => 'खसरा',
            'Meningitis' => 'मेनिन्जाइटिस',
            'Meniscus Tear' => 'मेनिस्कस फटना',
            'Menopause Symptoms' => 'रजोनिवृत्ति के लक्षण',
            'Migraine' => 'माइग्रेन',
            'Miscarriage' => 'गर्भपात',
            'Multiple Myeloma' => 'मल्टीपल मायलोमा',
            'Multiple Sclerosis' => 'मल्टीपल स्क्लेरोसिस',
            'Mumps' => 'कण्ठमाला',
            'Myasthenia Gravis' => 'मायस्थीनिया ग्रेविस',
            'Myocardial Infarction' => 'हृदयाघात',
            'Nasal Polyps' => 'नाक के पॉलीप्स',
            'Neck Pain' => 'गर्दन दर्द',
            'Neonatal Jaundice' => 'नवजात पीलिया',
            'Nephrotic Syndrome' => 'नेफ्रोटिक सिंड्रोम',
            'Neuropathy' => 'न्यूरोपैथी',
            'Nicotine Dependence' => 'निकोटीन निर्भरता',
            'Normal Pregnancy' => 'सामान्य गर्भावस्था',
            'Obsessive Compulsive Disorder' => 'ऑब्सेसिव कम्पल्सिव डिसऑर्डर',
            'Obesity' => 'मोटापा',
            'Opioid Use Disorder' => 'ओपिओइड उपयोग विकार',
            'Osteoarthritis' => 'ऑस्टियोआर्थराइटिस',
            'Osteoporosis' => 'ऑस्टियोपोरोसिस',
            'Otitis Externa' => 'बाहरी कान का संक्रमण',
            'Otitis Media' => 'मध्य कान का संक्रमण',
            'Ovarian Cancer' => 'अंडाशय कैंसर',
            'Ovarian Cyst' => 'अंडाशय की सिस्ट',
            'Pancreatic Cancer' => 'अग्न्याशय कैंसर',
            'Pancreatitis' => 'अग्न्याशयशोथ',
            'Panic Disorder' => 'पैनिक विकार',
            'Parkinson Disease' => 'पार्किंसन रोग',
            'Parkinsonism' => 'पार्किंसनिज्म',
            'Pediatric Asthma' => 'बच्चों में अस्थमा',
            'Pediatric Diarrhea' => 'बच्चों में दस्त',
            'Pediatric Fever' => 'बच्चों में बुखार',
            'Pelvic Inflammatory Disease' => 'श्रोणि सूजन रोग',
            'Peptic Ulcer Disease' => 'पेप्टिक अल्सर रोग',
            'Peripheral Artery Disease' => 'परिधीय धमनी रोग',
            'Pericarditis' => 'पेरीकार्डाइटिस',
            'Pituitary Adenoma' => 'पिट्यूटरी एडेनोमा',
            'Placenta Previa' => 'प्लेसेंटा प्रीविया',
            'Pleural Effusion' => 'फुफ्फुस द्रव संचय',
            'Pilonidal Sinus' => 'पायलोनाइडल साइनस',
            'Pneumonia' => 'निमोनिया',
            'Pneumonia in Children' => 'बच्चों में निमोनिया',
            'Poisoning' => 'विषाक्तता',
            'Polycystic Kidney Disease' => 'पॉलीसिस्टिक किडनी रोग',
            'Polycystic Ovary Syndrome' => 'पॉलीसिस्टिक ओवरी सिंड्रोम',
            'Polycythemia Vera' => 'पॉलीसाइथीमिया वेरा',
            'Polypharmacy' => 'बहु-औषधि उपयोग',
            'Polymyalgia Rheumatica' => 'पॉलीमायल्जिया रूमेटिका',
            'Post Traumatic Stress Disorder' => 'आघातोत्तर तनाव विकार',
            'Postpartum Depression' => 'प्रसवोत्तर अवसाद',
            'Postpartum Hemorrhage' => 'प्रसवोत्तर रक्तस्राव',
            'Preeclampsia' => 'प्रीएक्लेम्पसिया',
            'Pressure Ulcer' => 'दबाव घाव',
            'Preterm Labor' => 'समय से पहले प्रसव पीड़ा',
            'Primary Immunodeficiency' => 'प्राथमिक प्रतिरक्षा कमी',
            'Prostate Cancer' => 'प्रोस्टेट कैंसर',
            'Prostatitis' => 'प्रोस्टेटाइटिस',
            'Psoriasis' => 'सोरायसिस',
            'Psoriatic Arthritis' => 'सोरायटिक गठिया',
            'Pulmonary Embolism' => 'फुफ्फुसीय एम्बोलिज्म',
            'Pulmonary Fibrosis' => 'फेफड़ों का फाइब्रोसिस',
            'Rabies Exposure' => 'रेबीज संपर्क',
            'Refractive Error' => 'दृष्टि दोष',
            'Retinal Detachment' => 'रेटिना अलग होना',
            'Rheumatoid Arthritis' => 'रूमेटाइड आर्थराइटिस',
            'Rosacea' => 'रोसैसिया',
            'Rotator Cuff Tear' => 'रोटेटर कफ फटना',
            'Scabies' => 'खुजली',
            'Schizophrenia' => 'सिजोफ्रेनिया',
            'Sciatica' => 'सायटिका',
            'Scleroderma' => 'स्क्लेरोडर्मा',
            'Scoliosis' => 'रीढ़ की वक्रता',
            'Sedative Use Disorder' => 'सेडेटिव उपयोग विकार',
            'Seizure' => 'दौरा',
            'Sepsis' => 'सेप्सिस',
            'Severe Abdominal Pain' => 'तेज पेट दर्द',
            'Severe Dehydration' => 'गंभीर निर्जलीकरण',
            'Sickle Cell Disease' => 'सिकल सेल रोग',
            'Sinusitis' => 'साइनसाइटिस',
            'Sjogren Syndrome' => 'शोग्रेन सिंड्रोम',
            'Skin Cancer' => 'त्वचा कैंसर',
            'Sleep Apnea' => 'स्लीप एपनिया',
            'Soft Tissue Tumor' => 'मृदु ऊतक ट्यूमर',
            'Stimulant Use Disorder' => 'उत्तेजक पदार्थ उपयोग विकार',
            'Stomach Cancer' => 'पेट का कैंसर',
            'Strabismus' => 'भेंगापन',
            'Stroke' => 'स्ट्रोक',
            'Stroke Symptoms' => 'स्ट्रोक के लक्षण',
            'Syncope' => 'बेहोशी',
            'Systemic Lupus Erythematosus' => 'सिस्टमिक ल्यूपस एरिथेमेटोसस',
            'Testicular Torsion' => 'वृषण मरोड़',
            'Thalassemia' => 'थैलेसीमिया',
            'Thrombocytopenia' => 'थ्रोम्बोसाइटोपीनिया',
            'Thyroid Nodule' => 'थायरॉयड गांठ',
            'Thyroid Swelling' => 'थायरॉयड सूजन',
            'Tinnitus' => 'कान में आवाज आना',
            'Tonsillitis' => 'टॉन्सिलाइटिस',
            'Transient Ischemic Attack' => 'क्षणिक इस्केमिक अटैक',
            'Tremor' => 'कंपकंपी',
            'Tuberculosis' => 'क्षय रोग',
            'Typhoid Fever' => 'टाइफाइड बुखार',
            'Type 1 Diabetes' => 'टाइप 1 मधुमेह',
            'Type 2 Diabetes' => 'टाइप 2 मधुमेह',
            'Ulcerative Colitis' => 'अल्सरेटिव कोलाइटिस',
            'Urticaria' => 'पित्ती',
            'Urinary Incontinence' => 'मूत्र असंयम',
            'Urinary Tract Infection' => 'मूत्र मार्ग संक्रमण',
            'Uterine Fibroid' => 'गर्भाशय फाइब्रॉइड',
            'Uveitis' => 'यूवाइटिस',
            'Vaginitis' => 'योनि शोथ',
            'Valvular Heart Disease' => 'हृदय वाल्व रोग',
            'Varicose Veins' => 'वैरिकोज नसें',
            'Vasculitis' => 'रक्तवाहिनी शोथ',
            'Vertigo' => 'चक्कर आना',
            'Vitamin B12 Deficiency' => 'विटामिन बी12 की कमी',
            'Vitamin D Deficiency' => 'विटामिन डी की कमी',
            'Vitiligo' => 'सफेद दाग',
            'Voice Disorder' => 'आवाज संबंधी विकार',
            'Worm Infestation' => 'कृमि संक्रमण',
            // Added Diseases
            'Myocarditis' => 'मायोकार्डिटिस',
            'Endocarditis' => 'एंडोकार्डिटिस',
            'Rheumatic Heart Disease' => 'आमवाती हृदय रोग',
            'Contact Dermatitis' => 'संपर्क डर्मेटाइटिस',
            'Seborrheic Dermatitis' => 'सेबोरहाइक डर्मेटाइटिस',
            'Warts' => 'मस्से',
            'Hyperparathyroidism' => 'हाइपरपैराथायरायडिज्म',
            'Diverticulitis' => 'डायवर्टीकुलाइटिस',
            'Huntington Disease' => 'हंटिंगटन रोग',
            'Amyotrophic Lateral Sclerosis' => 'एमियोट्रोफिक लेटरल स्क्लेरोसिस (ALS)',
            'Guillain-Barre Syndrome' => 'गुइलेन-बैरे सिंड्रोम',
            'Trigeminal Neuralgia' => 'ट्राइजेमिनल न्यूराल्जिया',
            'Restless Legs Syndrome' => 'रेस्टलेस लेग्स सिंड्रोम',
            'Cystic Fibrosis' => 'सिस्टिक फाइब्रोसिस',
            'Bronchiectasis' => 'ब्रोंकाइक्टेसिस',
            'Borderline Personality Disorder' => 'बॉर्डरलाइन पर्सनैलिटी डिसऑर्डर',
            'Plantar Fasciitis' => 'प्लांटर फैसीसाइटिस',
            'Achilles Tendinitis' => 'अकिलीज़ टेंडिनाइटिस',
            'Tennis Elbow' => 'टेनिस एल्बो',
            'Color Blindness' => 'वर्णांधता (कलर ब्लाइंडनेस)',
            'Stye' => 'गुहेरी',
            'Chalazion' => 'चेलेज़ियन',
            'Meniere\'s Disease' => 'मेनियर रोग',
            'Interstitial Cystitis' => 'इंटरस्टीशियल सिस्टिटिस',
            'Overactive Bladder' => 'अतिसक्रिय मूत्राशय',
            'Adenomyosis' => 'एडेनोमायोसिस',
            'Syphilis' => 'सिफलिस',
            'Gonorrhea' => 'गोनोरिया',
            'Chlamydia' => 'क्लैमाइडिया',
            'Croup' => 'क्रुप',
            'Rubella' => 'रूबेला',

            // ALL Symptoms
            'Abdominal Cramps' => 'पेट में ऐंठन',
            'Abdominal Pain' => 'पेट दर्द',
            'Abnormal Discharge' => 'असामान्य स्राव',
            'Abnormal Vaginal Bleeding' => 'असामान्य योनि रक्तस्राव',
            'Abnormal Vaginal Discharge' => 'असामान्य योनि स्राव',
            'Aching' => 'दर्द',
            'Aching Joints' => 'जोड़ों में दर्द',
            'Aching Muscles' => 'मांसपेशियों में दर्द',
            'Agitation' => 'व्याकुलता',
            'Anal Itching' => 'गुदा में खुजली',
            'Anxiety' => 'चिंता',
            'Avoidance' => 'बचाव',
            'Back Pain' => 'पीठ दर्द',
            'Barking Cough' => 'भौंकने जैसी खांसी',
            'Behavioral Changes' => 'व्यवहार में बदलाव',
            'Binge Eating' => 'अत्यधिक खाना',
            'Black Pinpoints on Skin' => 'त्वचा पर काले बिंदु',
            'Blackheads' => 'ब्लैकहेड्स',
            'Bleeding' => 'रक्तस्राव',
            'Bleeding Between Periods' => 'मासिक धर्म के बीच रक्तस्राव',
            'Bleeding Gums' => 'मसूड़ों से खून आना',
            'Bleeding from Nose' => 'नाक से खून आना',
            'Blisters' => 'छाले',
            'Bloating' => 'पेट फूलना',
            'Blood in Stool' => 'मल में खून',
            'Blood in Urine' => 'पेशाब में खून',
            'Blurred Central Vision' => 'धुंधली केंद्रीय दृष्टि',
            'Blurred Vision' => 'धुंधली दृष्टि',
            'Body Image Distortion' => 'शारीरिक छवि में विकृति',
            'Body Pain' => 'बदन दर्द',
            'Bone Fracture' => 'हड्डी का टूटना',
            'Bone Pain' => 'हड्डियों में दर्द',
            'Bone Spurs' => 'हड्डी का बढ़ना',
            'Breast Lump' => 'स्तन में गांठ',
            'Breast Pain' => 'स्तन में दर्द',
            'Breast Tenderness' => 'स्तनों में कोमलता',
            'Brittle Nails' => 'कमजोर नाखून',
            'Brown Patches on Face' => 'चेहरे पर भूरे धब्बे',
            'Bulge in Groin or Abdomen' => 'कमर या पेट में उभार',
            'Bulging Eyes' => 'उभरी हुई आंखें',
            'Bulging Veins' => 'उभरी हुई नसें',
            'Burning Pain' => 'जलन वाला दर्द',
            'Burning Urination' => 'पेशाब में जलन',
            'Butterfly Rash' => 'तितली के आकार के दाने',
            'Buzzing Sound' => 'भिनभिनाने की आवाज',
            'Change in Bowel Habits' => 'मल त्याग की आदतों में बदलाव',
            'Changes in Breast Shape' => 'स्तन के आकार में परिवर्तन',
            'Changes in an Existing Mole' => 'मौजूदा तिल में बदलाव',
            'Chest Discomfort' => 'छाती में बेचैनी',
            'Chest Pain' => 'छाती में दर्द',
            'Chest Tightness' => 'छाती में जकड़न',
            'Chills' => 'ठंड लगना',
            'Chronic Cough' => 'पुरानी खांसी',
            'Cloudy Urine' => 'धुंधला मूत्र',
            'Cognitive Decline' => 'संज्ञानात्मक गिरावट',
            'Cold Extremities' => 'ठंडे हाथ-पैर',
            'Cold Hands and Feet' => 'ठंडे हाथ-पैर',
            'Cold Intolerance' => 'ठंड बर्दाश्त न होना',
            'Compulsive Behavior' => 'मजबूरी भरा व्यवहार',
            'Confusion' => 'उलझन',
            'Congestion' => 'जमाव',
            'Constipation' => 'कब्ज',
            'Convulsions' => 'ऐंठन / दौरे',
            'Cough' => 'खांसी',
            'Coughing' => 'खांसी',
            'Coughing up Blood' => 'खांसी में खून आना',
            'Coughing up Mucus' => 'बलगम वाली खांसी',
            'Crackling Sensation' => 'चटकने का अहसास',
            'Cramping' => 'ऐंठन',
            'Craving' => 'तीव्र इच्छा',
            'Crawling Sensation in Legs' => 'पैरों में रेंगने का अहसास',
            'Crossed Eyes' => 'भेंगापन',
            'Crusting of Eyelids' => 'पलकों पर पपड़ी',
            'Crying' => 'रोना',
            'Dandruff' => 'डैंड्रफ (रूसी)',
            'Dark Urine' => 'गहरे रंग का पेशाब',
            'Daytime Sleepiness' => 'दिन में नींद आना',
            'Decreased Need for Sleep' => 'नींद की कम आवश्यकता',
            'Decreased Range of Motion' => 'गति की सीमा में कमी',
            'Decreased Sense of Smell' => 'सूंघने की क्षमता में कमी',
            'Decreased Urine Output' => 'मूत्र उत्पादन में कमी',
            'Deep Pain in Back or Side' => 'पीठ या बाजू में गहरा दर्द',
            'Deformity' => 'विकृति',
            'Delayed Development' => 'विकास में देरी',
            'Delayed Motor Skills' => 'देरी से मोटर कौशल',
            'Delayed Speech' => 'बोलने में देरी',
            'Delusions' => 'भ्रम',
            'Depression' => 'अवसाद',
            'Diarrhea' => 'दस्त',
            'Difficulty Achieving Erection' => 'स्तंभन प्राप्त करने में कठिनाई',
            'Difficulty Adapting to Low Light' => 'कम रोशनी में देखने में कठिनाई',
            'Difficulty Bonding with Baby' => 'बच्चे के साथ जुड़ाव में कठिनाई',
            'Difficulty Breathing' => 'सांस लेने में कठिनाई',
            'Difficulty Breathing Lying Down' => 'लेटने पर सांस लेने में कठिनाई',
            'Difficulty Concentrating' => 'ध्यान केंद्रित करने में कठिनाई',
            'Difficulty Distinguishing Colors' => 'रंगों को पहचानने में कठिनाई',
            'Difficulty Eating' => 'खाने में कठिनाई',
            'Difficulty Falling Asleep' => 'नींद आने में कठिनाई',
            'Difficulty Focusing' => 'ध्यान केंद्रित करने में कठिनाई',
            'Difficulty Lifting Arm' => 'हाथ उठाने में कठिनाई',
            'Difficulty Maintaining Erection' => 'स्तंभन बनाए रखने में कठिनाई',
            'Difficulty Opening Eyes' => 'आंखें खोलने में कठिनाई',
            'Difficulty Swallowing' => 'निगलने में कठिनाई',
            'Difficulty Thinking' => 'सोचने में कठिनाई',
            'Difficulty Understanding Speech' => 'बातचीत समझने में कठिनाई',
            'Difficulty Urinating' => 'पेशाब करने में कठिनाई',
            'Difficulty Writing' => 'लिखने में कठिनाई',
            'Discomfort' => 'बेचैनी',
            'Disorganized Speech' => 'अव्यवस्थित बातचीत',
            'Disorientation' => 'भटकाव',
            'Distorted Vision' => 'विकृत दृष्टि',
            'Dizziness' => 'चक्कर आना',
            'Double Vision' => 'दोहरी दृष्टि',
            'Drop in Blood Pressure' => 'रक्तचाप में गिरावट',
            'Drooling' => 'लार टपकना',
            'Drooping Eyelids' => 'लटकी हुई पलकें',
            'Drowsiness' => 'सुस्ती',
            'Drug Interactions' => 'दवाओं की परस्पर क्रिया',
            'Dry Cough' => 'सूखी खांसी',
            'Dry Eyes' => 'सूखी आंखें',
            'Dry Mouth' => 'सूखा मुंह',
            'Dry Skin' => 'सूखी त्वचा',
            'Ear Discharge' => 'कान से स्राव (कान बहना)',
            'Ear Pain' => 'कान में दर्द',
            'Easily Startled' => 'आसानी से चौंक जाना',
            'Easy Bruising' => 'आसानी से चोट लगना',
            'Electric Shock-like Pain' => 'बिजली के झटके जैसा दर्द',
            'Episodes of Pain' => 'दर्द के दौरे',
            'Excess Hair Growth' => 'अत्यधिक बालों का विकास',
            'Excessive Body Fat' => 'अत्यधिक शरीर की चर्बी',
            'Excessive Crying' => 'अत्यधिक रोना',
            'Excessive Mucus' => 'अत्यधिक बलगम',
            'Excessive Sweating' => 'अत्यधिक पसीना आना',
            'Excessive Thirst' => 'अत्यधिक प्यास',
            'Excessive Vaginal Bleeding' => 'अत्यधिक योनि रक्तस्राव',
            'Excessive Worry' => 'अत्यधिक चिंता',
            'Exhaustion' => 'अत्यधिक थकान',
            'Extreme Thirst' => 'अत्यधिक प्यास',
            'Extreme Weight Loss' => 'अत्यधिक वजन कम होना',
            'Eye Discharge' => 'आंखों से स्राव (कीचड़ आना)',
            'Eye Irritation' => 'आंखों में जलन',
            'Eye Pain' => 'आंखों में दर्द',
            'Eye Redness' => 'आंखों में लालिमा',
            'Eye Strain' => 'आंखों पर जोर',
            'Eyelid Heaviness' => 'पलक का भारीपन',
            'Eyelid Pain' => 'पलक में दर्द',
            'Facial Bone Deformities' => 'चेहरे की हड्डी की विकृति',
            'Facial Drooping' => 'चेहरे का लटकना',
            'Facial Pain' => 'चेहरे में दर्द',
            'Facial Pressure' => 'चेहरे पर दबाव',
            'Facial Redness' => 'चेहरे पर लालिमा',
            'Fading Colors' => 'रंग फीके पड़ना',
            'Fainting' => 'बेहोशी',
            'Fatigue' => 'थकान',
            'Fear of Abandonment' => 'परित्याग का डर',
            'Fear of Contamination' => 'संदूषण का डर',
            'Feeling Full after Eating Little' => 'थोड़ा खाने के बाद पेट भरा महसूस होना',
            'Feeling of Fullness in Ear' => 'कान में भारीपन महसूस होना',
            'Feeling of Heaviness' => 'भारीपन का एहसास',
            'Feeling of Heaviness in Scrotum' => 'अंडकोश में भारीपन का अहसास',
            'Feeling of Pressure' => 'दबाव का एहसास',
            'Feeling of Sand in Eye' => 'आंख में रेत जैसा महसूस होना',
            'Fever' => 'बुखार',
            'Flashbacks' => 'पुरानी यादें आना (फ्लैशबैक)',
            'Fleshy Bump' => 'मांसल उभार',
            'Floaters' => 'आंखों के सामने तैरते धब्बे',
            'Fluctuating Vision' => 'दृष्टि में उतार-चढ़ाव',
            'Foamy Urine' => 'झागदार पेशाब',
            'Foot Stiffness' => 'पैर में अकड़न',
            'Frequent Bowel Movements' => 'बार-बार मल त्याग',
            'Frequent Infections' => 'बार-बार संक्रमण',
            'Frequent Lung Infections' => 'बार-बार फेफड़ों का संक्रमण',
            'Frequent Urination' => 'बार-बार पेशाब आना',
            'Frequent Watery Stools' => 'बार-बार पानी जैसा दस्त',
            'Gas' => 'गैस',
            'Hallucinations' => 'मतिभ्रम',
            'Halos Around Lights' => 'रोशनी के चारों ओर घेरे',
            'Hard Stools' => 'कठोर मल',
            'Hardening of Skin' => 'त्वचा का सख्त होना',
            'Head Tilting' => 'सिर झुकाना',
            'Headache' => 'सिरदर्द',
            'Hearing Loss' => 'सुनने में कमी',
            'Heart Murmur' => 'हृदय में असामान्य ध्वनि',
            'Heartburn' => 'सीने में जलन',
            'Heat Intolerance' => 'गर्मी बर्दाश्त न होना',
            'Heat in Joint' => 'जोड़ों में गर्मी',
            'Heavy Bleeding' => 'भारी रक्तस्राव',
            'Heavy Feeling in Legs' => 'पैरों में भारीपन',
            'Heavy Menstrual Bleeding' => 'भारी मासिक धर्म रक्तस्राव',
            'Heel Pain' => 'एड़ी में दर्द',
            'High Blood Pressure' => 'उच्च रक्तचाप',
            'High Body Temperature' => 'शरीर का उच्च तापमान',
            'High Energy' => 'उच्च ऊर्जा',
            'Hip Pain' => 'कूल्हे का दर्द',
            'Hoarseness' => 'आवाज बैठना',
            'Hormonal Imbalance' => 'हार्मोनल असंतुलन',
            'Hot Flashes' => 'हॉट फ्लैशेस',
            'Impulsive Behavior' => 'आवेगी व्यवहार',
            'Impulsivity' => 'आवेग',
            'Inability to Bear Weight' => 'वजन न सह पाना',
            'Inability to Close Eye' => 'आंख बंद करने में असमर्थता',
            'Inability to Conceive' => 'गर्भधारण करने में असमर्थता',
            'Inability to Move' => 'हिलने-डुलने में असमर्थता',
            'Inability to Move Joint' => 'जोड़ को हिलाने में असमर्थता',
            'Inability to Pass Gas' => 'गैस पास करने में असमर्थता',
            'Inability to See Shades' => 'शेड्स (रंग के प्रकार) न देख पाना',
            'Inattention' => 'ध्यान न देना',
            'Incomplete Bladder Emptying' => 'मूत्राशय का पूरी तरह खाली न होना',
            'Induced Vomiting' => 'जबरन उल्टी करना',
            'Infection' => 'संक्रमण',
            'Infertility' => 'बांझपन',
            'Infrequent Bowel Movements' => 'अनियमित मल त्याग',
            'Intrusive Thoughts' => 'अवांछित विचार',
            'Involuntary Movements' => 'अनैच्छिक गति',
            'Involuntary Shaking' => 'अनैच्छिक झटके',
            'Irregular Blood Pressure' => 'अनियमित रक्तचाप',
            'Irregular Heartbeat' => 'अनियमित धड़कन',
            'Irregular Menstrual Cycle' => 'अनियमित मासिक धर्म',
            'Irregular Skin Lesion' => 'अनियमित त्वचा का घाव',
            'Irritability' => 'चिड़चिड़ापन',
            'Itching' => 'खुजली',
            'Itching Around Anus' => 'गुदा के आसपास खुजली',
            'Itching in Ear' => 'कान में खुजली',
            'Itchy Eyes' => 'आंखों में खुजली',
            'Itchy Rash' => 'खुजली वाले दाने',
            'Jaundice' => 'पीलिया',
            'Joint Pain' => 'जोड़ों का दर्द',
            'Joint Stiffness' => 'जोड़ों की अकड़न',
            'Joint Swelling' => 'जोड़ों में सूजन',
            'Kidney Problems' => 'गुर्दे की समस्याएं',
            'Knee Pain' => 'घुटने में दर्द',
            'Lack of Appetite' => 'भूख की कमी',
            'Lack of Energy' => 'ऊर्जा की कमी',
            'Lack of Eye Contact' => 'आंख न मिलाना',
            'Lack of Motivation' => 'प्रेरणा की कमी',
            'Large Bruises' => 'बड़े-बड़े नील पड़ना',
            'Leakage of Urine' => 'मूत्र का रिसाव',
            'Leg Pain' => 'पैर में दर्द',
            'Leg Ulcers' => 'पैर के अल्सर',
            'Lethargy' => 'सुस्ती',
            'Lightheadedness' => 'चक्कर आना (हल्का महसूस होना)',
            'Limited Mobility' => 'सीमित गतिशीलता',
            'Lingering Discomfort' => 'लंबे समय तक रहने वाली बेचैनी',
            'Loose Stools' => 'पतला मल',
            'Loss of Appetite' => 'भूख न लगना',
            'Loss of Balance' => 'संतुलन खोना',
            'Loss of Consciousness' => 'बेहोशी',
            'Loss of Depth Perception' => 'गहराई की धारणा का खोना',
            'Loss of Height' => 'लंबाई कम होना',
            'Loss of Interest' => 'रुचि कम होना',
            'Loss of Peripheral Vision' => 'परिधीय दृष्टि का कम होना',
            'Loss of Skin Color' => 'त्वचा का रंग उड़ना',
            'Loss of Taste or Smell' => 'स्वाद या गंध न आना',
            'Loud Breathing' => 'जोर से सांस लेना',
            'Low Blood Pressure' => 'निम्न रक्तचाप',
            'Lower Back Pain' => 'पीठ के निचले हिस्से में दर्द',
            'Lower Left Abdominal Pain' => 'पेट के निचले बाएं हिस्से में दर्द',
            'Lower Right Abdominal Pain' => 'पेट के निचले दाहिने हिस्से में दर्द',
            'Lump in Neck' => 'गर्दन में गांठ',
            'Lump or Mass' => 'गांठ या द्रव्यमान',
            'Memory Loss' => 'याददाश्त जाना',
            'Memory Problems' => 'याददाश्त की समस्या',
            'Missed Periods' => 'मासिक धर्म न आना',
            'Mood Changes' => 'मूड में बदलाव',
            'Mood Swings' => 'मूड स्विंग',
            'Morning Headache' => 'सुबह सिरदर्द',
            'Morning Stiffness' => 'सुबह की अकड़न',
            'Mucus Production' => 'बलगम बनना',
            'Muffled Hearing' => 'दबी हुई आवाज सुनाई देना',
            'Muscle Ache' => 'मांसपेशियों में दर्द',
            'Muscle Cramps' => 'मांसपेशियों में ऐंठन',
            'Muscle Spasm' => 'मांसपेशियों में खिंचाव',
            'Muscle Tension' => 'मांसपेशियों में तनाव',
            'Muscle Twitches' => 'मांसपेशियों में फड़कन',
            'Muscle Weakness' => 'मांसपेशियों में कमजोरी',
            'Nail Changes' => 'नाखूनों में बदलाव',
            'Nail Dents' => 'नाखूनों में गड्ढे',
            'Nasal Congestion' => 'बंद नाक',
            'Nausea' => 'जी मिचलाना',
            'Neck Pain' => 'गर्दन दर्द',
            'Neck Swelling' => 'गर्दन में सूजन',
            'Need for Symmetry' => 'समरूपता की आवश्यकता',
            'Nerve Pain' => 'नसों का दर्द',
            'New Mole' => 'नया तिल',
            'New Onset Headaches' => 'नए शुरू हुए सिरदर्द',
            'New Pigmented Growth' => 'नया रंजित विकास',
            'Night Sweats' => 'रात को पसीना आना',
            'Nightmares' => 'बुरे सपने',
            'Nipple Discharge' => 'निप्पल से स्राव',
            'No Specific Symptoms' => 'कोई विशिष्ट लक्षण नहीं',
            'Nocturia' => 'रात में बार-बार पेशाब आना',
            'Nosebleeds' => 'नकसीर',
            'Numbness' => 'सुन्न होना',
            'Numbness in Fingers' => 'उंगलियों में सुन्नपन',
            'Numbness in Leg' => 'पैर में सुन्नपन',
            'Odor' => 'दुर्गंध',
            'Odor from Foot' => 'पैरों से दुर्गंध',
            'Oily Skin' => 'तैलीय त्वचा',
            'One Hip Higher' => 'एक कूल्हा ऊंचा होना',
            'Pain' => 'दर्द',
            'Pain Around Jaw' => 'जबड़े के आसपास दर्द',
            'Pain During Bowel Movements' => 'मल त्याग के दौरान दर्द',
            'Pain Lifting Objects' => 'सामान उठाने में दर्द',
            'Pain Radiating to Arm' => 'हाथ तक फैलने वाला दर्द',
            'Pain Triggered by Chewing' => 'चबाने पर दर्द',
            'Pain While Chewing' => 'चबाते समय दर्द',
            'Pain at Tailbone' => 'रीढ़ की हड्डी के अंत में दर्द',
            'Pain in Heel' => 'एड़ी में दर्द',
            'Pain in Testicle' => 'अंडकोश में दर्द',
            'Pain in Wrist' => 'कलाई में दर्द',
            'Pain on Outside of Elbow' => 'कोहनी के बाहरी हिस्से में दर्द',
            'Pain Worse with Movement' => 'हिलने पर दर्द बढ़ना',
            'Pain with First Steps' => 'पहले कदम के साथ दर्द',
            'Painful Blisters in Mouth' => 'मुंह में दर्दनाक छाले',
            'Painful Intercourse' => 'दर्दनाक संभोग',
            'Painful Menstruation' => 'दर्दनाक मासिक धर्म',
            'Painful Rash' => 'दर्दनाक दाने',
            'Painful Swelling' => 'दर्दनाक सूजन',
            'Painful Urination' => 'पेशाब में दर्द',
            'Painless Bump on Eyelid' => 'पलक पर दर्द रहित उभार',
            'Painless Lump' => 'बिना दर्द की गांठ',
            'Painless Sore' => 'दर्द रहित घाव',
            'Painless Swelling in Scrotum' => 'अंडकोश में दर्द रहित सूजन',
            'Painless Vaginal Bleeding' => 'दर्द रहित योनि रक्तस्राव',
            'Pale Skin' => 'पीली त्वचा',
            'Palpitations' => 'धड़कन तेज होना',
            'Panic' => 'घबराहट',
            'Passing Tissue' => 'ऊतक का निकलना',
            'Patchy Baldness' => 'जगह-जगह से गंजापन',
            'Pelvic Pain' => 'पेल्विक दर्द',
            'Pelvic Pressure' => 'पेल्विक दबाव',
            'Penile Discharge' => 'लिंग से स्राव',
            'Persistent Cough' => 'लगातार खांसी',
            'Pimples' => 'मुंहासे',
            'Pink or Cola-colored Urine' => 'गुलाबी या कोला रंग का पेशाब',
            'Poor Appetite' => 'भूख न लगना',
            'Poor Depth Perception' => 'गहराई का खराब अनुमान',
            'Poor Feeding' => 'ठीक से न खाना',
            'Poor Growth' => 'खराब विकास',
            'Poor Night Vision' => 'रात में कम दिखना',
            'Poor Vision in One Eye' => 'एक आंख में कम दृष्टि',
            'Popping Sensation in Knee' => 'घुटने में चटकने का अहसास',
            'Popping Sound' => 'चटकने की आवाज',
            'Premature Contractions' => 'समय से पहले संकुचन',
            'Premature Graying' => 'समय से पहले बाल सफेद होना',
            'Prolonged Bleeding' => 'लंबे समय तक रक्तस्राव',
            'Prolonged Periods' => 'लंबे समय तक चलने वाले पीरियड्स',
            'Protein in Urine' => 'पेशाब में प्रोटीन',
            'Pulsating Feeling near Navel' => 'नाभि के पास धड़कन जैसा महसूस होना',
            'Pus Discharge' => 'मवाद निकलना',
            'Rapid Breathing' => 'तेज सांस लेना',
            'Rapid Heartbeat' => 'तेज धड़कन',
            'Rash' => 'दाने',
            'Rash on Hands and Feet' => 'हाथों और पैरों पर दाने',
            'Red Bump on Eyelid' => 'पलक पर लाल उभार',
            'Red Eyes' => 'लाल आंखें',
            'Red Patches' => 'लाल धब्बे',
            'Red Patches on Skin' => 'त्वचा पर लाल धब्बे',
            'Red Rash' => 'लाल चकत्ते',
            'Red Skin' => 'लाल त्वचा',
            'Red Sores' => 'लाल घाव',
            'Redness' => 'लालिमा',
            'Redness of Face' => 'चेहरे का लाल होना',
            'Reduced Flexibility' => 'लचीलेपन में कमी',
            'Reduced Sexual Desire' => 'यौन इच्छा में कमी',
            'Regular Contractions' => 'नियमित संकुचन',
            'Regurgitation' => 'खाना वापस आना',
            'Repetitive Behaviors' => 'बार-बार दोहराया जाने वाला व्यवहार',
            'Restless Legs' => 'पैरों में बेचैनी',
            'Restlessness' => 'बेचैनी',
            'Restricted Movement' => 'सीमित गतिविधि',
            'Restricted Range of Motion' => 'गति की सीमित सीमा',
            'Ringing in Ears' => 'कानों में बजना',
            'Ring-shaped Rash' => 'अंगूठी के आकार के दाने',
            'Rough Skin' => 'खुरदरी त्वचा',
            'Runny Nose' => 'बहती नाक',
            'Sadness' => 'उदासी',
            'Salty Tasting Skin' => 'नमकीन स्वाद वाली त्वचा',
            'Scaly Patches' => 'पपड़ीदार धब्बे',
            'Seizure' => 'दौरा',
            'Sensitivity to Light' => 'प्रकाश के प्रति संवेदनशीलता',
            'Sensitivity to Sound' => 'ध्वनि के प्रति संवेदनशीलता',
            'Severe Abdominal Pain' => 'तेज पेट दर्द',
            'Severe Anxiety' => 'गंभीर चिंता',
            'Severe Cramping' => 'गंभीर ऐंठन',
            'Severe Facial Pain' => 'चेहरे में तेज दर्द',
            'Severe Headache' => 'गंभीर सिरदर्द',
            'Severe Itching' => 'तेज खुजली',
            'Severe Joint Pain' => 'जोड़ों में गंभीर दर्द',
            'Severe Menstrual Cramps' => 'गंभीर मासिक धर्म ऐंठन',
            'Severe Mood Swings' => 'गंभीर मूड स्विंग',
            'Severe Pain' => 'गंभीर दर्द',
            'Severe Swelling' => 'गंभीर सूजन',
            'Severe Wheezing' => 'गंभीर घरघराहट',
            'Sexual Dysfunction' => 'यौन अक्षमता',
            'Shadow over Vision' => 'दृष्टि पर छाया',
            'Short Stature' => 'छोटा कद',
            'Shortness of Breath' => 'सांस लेने में तकलीफ',
            'Shoulder Pain' => 'कंधे में दर्द',
            'Skin Changes' => 'त्वचा में बदलाव',
            'Skin Color Changes in Legs' => 'पैरों की त्वचा के रंग में बदलाव',
            'Skin Cracking' => 'त्वचा का फटना',
            'Skin Darkening' => 'त्वचा का काला पड़ना',
            'Skin Dimpling' => 'त्वचा में गड्ढे पड़ना',
            'Skin Discoloration' => 'त्वचा का रंग बदलना',
            'Skin Peeling' => 'त्वचा छीलना',
            'Skin Rash' => 'त्वचा पर दाने',
            'Skin Redness' => 'त्वचा का लाल होना',
            'Skin Sores' => 'त्वचा के घाव',
            'Skin Thickening' => 'त्वचा का मोटा होना',
            'Skin Ulcer' => 'त्वचा का अल्सर',
            'Sleep Disturbances' => 'नींद में खलल',
            'Sleepiness' => 'नींद आना',
            'Slow Movement' => 'धीमी गति',
            'Slow Walking Speed' => 'धीमी चलने की गति',
            'Slow Weight Gain' => 'वजन धीरे-धीरे बढ़ना',
            'Slurred Speech' => 'अस्पष्ट बोली',
            'Sneezing' => 'छींक आना',
            'Snoring' => 'खर्राटे लेना',
            'Social Interaction Difficulties' => 'सामाजिक बातचीत में कठिनाई',
            'Social Withdrawal' => 'सामाजिक अलगाव',
            'Sore That Won\'t Heal' => 'घाव जो ठीक नहीं हो रहा',
            'Sore Throat' => 'गले में खराश',
            'Sore on Foot' => 'पैर पर घाव',
            'Speech Difficulty' => 'बोलने में कठिनाई',
            'Spinning Sensation' => 'घूमने का अहसास (चक्कर)',
            'Spots in Vision' => 'दृष्टि में धब्बे',
            'Spotting' => 'स्पॉटिंग (हल्का रक्तस्राव)',
            'Spotting After Intercourse' => 'संभोग के बाद स्पॉटिंग',
            'Squinting' => 'आंखें सिकोड़ना',
            'Staring Spell' => 'घूरने का दौरा',
            'Stiff Neck' => 'गर्दन में अकड़न',
            'Stiffness' => 'अकड़न',
            'Stiffness in Calf' => 'पिंडली में अकड़न',
            'Stinging in Eyes' => 'आंखों में चुभन',
            'Stomach Pain' => 'पेट दर्द',
            'Stooped Posture' => 'झुकी हुई मुद्रा',
            'Straining' => 'जोर लगाना',
            'Stretch Marks' => 'खिंचाव के निशान (स्ट्रेच मार्क्स)',
            'Stridor' => 'सांस लेते समय तेज आवाज',
            'Sudden Confusion' => 'अचानक उलझन',
            'Sudden Flashes of Light' => 'अचानक प्रकाश की चमक',
            'Sudden High Fever' => 'अचानक तेज बुखार',
            'Sudden Severe Pain' => 'अचानक तेज दर्द',
            'Sudden Severe Testicular Pain' => 'अचानक तेज अंडकोश का दर्द',
            'Sudden Shortness of Breath' => 'अचानक सांस लेने में तकलीफ',
            'Sudden Terror' => 'अचानक आतंक/डर',
            'Sudden Urge to Urinate' => 'अचानक पेशाब करने की तीव्र इच्छा',
            'Sudden Vision Loss' => 'अचानक दृष्टि का जाना',
            'Sudden Weakness' => 'अचानक कमजोरी',
            'Swallowing Blood' => 'खून निगलना',
            'Sweating' => 'पसीना आना',
            'Swelling' => 'सूजन',
            'Swelling in Arm or Leg' => 'हाथ या पैर में सूजन',
            'Swelling in Heel' => 'एड़ी में सूजन',
            'Swelling in Legs' => 'पैरों में सूजन',
            'Swelling in Scrotum' => 'अंडकोश में सूजन',
            'Swelling in Testicle' => 'अंडकोश में सूजन',
            'Swelling of Eyelid' => 'पलक की सूजन',
            'Swelling of Hands and Feet' => 'हाथों और पैरों में सूजन',
            'Swollen Legs' => 'सूजे हुए पैर',
            'Swollen Lymph Nodes' => 'सूजी हुई लिम्फ नोड्स',
            'Swollen Salivary Glands' => 'सूजी हुई लार ग्रंथियां',
            'Swollen Tonsils' => 'सूजे हुए टॉन्सिल',
            'Tearing' => 'आंखों से पानी आना',
            'Temporary Weakness' => 'अस्थायी कमजोरी',
            'Testicular Pain' => 'अंडकोश का दर्द',
            'Throat Pain' => 'गले में दर्द',
            'Tingling' => 'झुनझुनी',
            'Tingling in Hand' => 'हाथ में झुनझुनी',
            'Tiredness' => 'थकान',
            'Tolerance' => 'सहनशीलता',
            'Trembling' => 'कांपना',
            'Trembling Voice' => 'कांपती आवाज',
            'Tremor' => 'कंपकंपी',
            'Uncoordinated Eye Movements' => 'असमन्वित आंखों की गति',
            'Uneven Shoulders' => 'असमान कंधे',
            'Uneven Waist' => 'असमान कमर',
            'Unexplained Bleeding' => 'अकारण रक्तस्राव',
            'Unexplained Weight Loss' => 'अकारण वजन कम होना',
            'Unstable Relationships' => 'अस्थिर रिश्ते',
            'Unsteady Walking' => 'अस्थिर चाल',
            'Upper Abdominal Pain' => 'ऊपरी पेट में दर्द',
            'Upper Right Abdominal Pain' => 'ऊपरी दाहिने पेट में दर्द',
            'Urge to Move Legs' => 'पैरों को हिलाने की तीव्र इच्छा',
            'Urge to Urinate' => 'पेशाब करने की इच्छा',
            'Vaginal Bleeding' => 'योनि रक्तस्राव',
            'Vaginal Discharge' => 'योनि स्राव',
            'Vaginal Dryness' => 'योनि का सूखापन',
            'Vaginal Itching' => 'योनि में खुजली',
            'Varicose Veins' => 'वैरिकोज नसें',
            'Visible Blood Vessels' => 'दिखने वाली रक्त वाहिकाएं',
            'Visible Deformity' => 'दिखने वाली विकृति',
            'Vision Changes' => 'दृष्टि में बदलाव',
            'Vision Loss' => 'दृष्टि का जाना',
            'Vision Problems' => 'दृष्टि संबंधी समस्याएं',
            'Vocal Fatigue' => 'आवाज की थकान',
            'Voice Break' => 'आवाज टूटना',
            'Voice Changes' => 'आवाज में बदलाव',
            'Voice Loss' => 'आवाज जाना',
            'Vomiting' => 'उल्टी',
            'Waking Up Frequently' => 'बार-बार जागना',
            'Warm Skin' => 'गर्म त्वचा',
            'Warmth' => 'गर्मी का अहसास',
            'Warmth in Leg' => 'पैर में गर्मी',
            'Weak Grip' => 'कमजोर पकड़',
            'Weak Urine Stream' => 'कमजोर मूत्र प्रवाह',
            'Weakness' => 'कमजोरी',
            'Weakness in Arm' => 'हाथ में कमजोरी',
            'Weakness in Hand' => 'हाथ में कमजोरी',
            'Weakness in Legs' => 'पैरों में कमजोरी',
            'Weight Changes' => 'वजन में बदलाव',
            'Weight Gain' => 'वजन बढ़ना',
            'Weight Loss' => 'वजन कम होना',
            'Wheezing' => 'घरघराहट',
            'White Patches' => 'सफेद धब्बे',
            'Widespread Muscle Pain' => 'व्यापक मांसपेशियों में दर्द',
            'Withdrawal Symptoms' => 'वापसी के लक्षण',
            'Worse at Night' => 'रात में बिगड़ना',
            'Yellow Crusts' => 'पीली पपड़ी',
            'Yellowing of Eyes' => 'आंखों का पीला होना',
            'Yellowing of Skin' => 'त्वचा का पीला होना',

        ][$name] ?? $name;
    }

    public static function diseasesByDepartment(): array
    {
        return [
            'Addiction Medicine' => [
                'Alcohol Use Disorder',
                'Opioid Use Disorder',
                'Nicotine Dependence',
                'Cannabis Use Disorder',
                'Stimulant Use Disorder',
                'Sedative Use Disorder',
                'Gambling Disorder',
            ],
            'Allergy and Immunology' => [
                'Allergic Rhinitis',
                'Food Allergy',
                'Drug Allergy',
                'Urticaria',
                'Angioedema',
                'Anaphylaxis',
                'Atopic Dermatitis',
                'Primary Immunodeficiency',
                'Common Variable Immunodeficiency',
            ],
            'Cardiology' => [
                'Hypertension',
                'Coronary Artery Disease',
                'Angina',
                'Myocardial Infarction',
                'Heart Failure',
                'Atrial Fibrillation',
                'Arrhythmia',
                'Valvular Heart Disease',
                'Cardiomyopathy',
                'Pericarditis',
                'Peripheral Artery Disease',
                'Deep Vein Thrombosis',
                'Hyperlipidemia',
                'Myocarditis',
                'Endocarditis',
                'Rheumatic Heart Disease',
            ],
            'Dermatology' => [
                'Acne Vulgaris',
                'Eczema',
                'Psoriasis',
                'Vitiligo',
                'Fungal Skin Infection',
                'Scabies',
                'Urticaria',
                'Rosacea',
                'Alopecia Areata',
                'Melasma',
                'Cellulitis',
                'Impetigo',
                'Herpes Zoster',
                'Skin Cancer',
                'Contact Dermatitis',
                'Seborrheic Dermatitis',
                'Warts',
            ],
            'Emergency Medicine' => [
                'Chest Pain',
                'Severe Abdominal Pain',
                'Stroke Symptoms',
                'Sepsis',
                'Anaphylaxis',
                'Acute Asthma Attack',
                'Severe Dehydration',
                'Poisoning',
                'Burn Injury',
                'Head Injury',
                'Fracture',
                'Syncope',
                'Seizure',
            ],
            'Endocrinology' => [
                'Type 1 Diabetes',
                'Type 2 Diabetes',
                'Gestational Diabetes',
                'Hypothyroidism',
                'Hyperthyroidism',
                'Graves Disease',
                'Hashimoto Thyroiditis',
                'Thyroid Nodule',
                'Cushing Syndrome',
                'Addison Disease',
                'Polycystic Ovary Syndrome',
                'Osteoporosis',
                'Obesity',
                'Pituitary Adenoma',
                'Hyperparathyroidism',
            ],
            'ENT (Otolaryngology)' => [
                'Sinusitis',
                'Tonsillitis',
                'Otitis Media',
                'Otitis Externa',
                'Hearing Loss',
                'Tinnitus',
                'Vertigo',
                'Nasal Polyps',
                'Deviated Nasal Septum',
                'Laryngitis',
                'Voice Disorder',
                'Sleep Apnea',
                'Epistaxis',
                'Meniere\'s Disease',
            ],
            'Gastroenterology' => [
                'Gastroesophageal Reflux Disease',
                'Peptic Ulcer Disease',
                'Gastritis',
                'Irritable Bowel Syndrome',
                'Inflammatory Bowel Disease',
                'Ulcerative Colitis',
                'Crohn Disease',
                'Celiac Disease',
                'Gallstones',
                'Pancreatitis',
                'Hepatitis',
                'Cirrhosis',
                'Fatty Liver Disease',
                'Constipation',
                'Diarrhea',
                'Hemorrhoids',
                'Diverticulitis',
            ],
            'General Medicine' => [
                'Fever',
                'Common Cold',
                'Influenza',
                'Fatigue',
                'Anemia',
                'Vitamin D Deficiency',
                'Vitamin B12 Deficiency',
                'Migraine',
                'Dengue Fever',
                'Malaria',
                'Typhoid Fever',
                'Urinary Tract Infection',
                'Dehydration',
                'Electrolyte Imbalance',
            ],
            'General Surgery' => [
                'Appendicitis',
                'Hernia',
                'Gallbladder Disease',
                'Abscess',
                'Pilonidal Sinus',
                'Thyroid Swelling',
                'Breast Lump',
                'Bowel Obstruction',
                'Varicose Veins',
                'Soft Tissue Tumor',
            ],
            'Geriatrics' => [
                'Dementia',
                'Delirium',
                'Falls in Elderly',
                'Frailty',
                'Polypharmacy',
                'Urinary Incontinence',
                'Pressure Ulcer',
                'Parkinsonism',
            ],
            'Gynecology' => [
                'Irregular Menstrual Cycle',
                'Dysmenorrhea',
                'Endometriosis',
                'Uterine Fibroid',
                'Ovarian Cyst',
                'Pelvic Inflammatory Disease',
                'Vaginitis',
                'Menopause Symptoms',
                'Abnormal Uterine Bleeding',
                'Cervical Dysplasia',
                'Adenomyosis',
            ],
            'Hematology' => [
                'Iron Deficiency Anemia',
                'Aplastic Anemia',
                'Thalassemia',
                'Sickle Cell Disease',
                'Hemophilia',
                'Thrombocytopenia',
                'Leukemia',
                'Lymphoma',
                'Multiple Myeloma',
                'Polycythemia Vera',
            ],
            'Infectious Diseases' => [
                'Tuberculosis',
                'HIV Infection',
                'COVID-19',
                'Dengue Fever',
                'Malaria',
                'Typhoid Fever',
                'Chikungunya',
                'Hepatitis B',
                'Hepatitis C',
                'Rabies Exposure',
                'Sepsis',
                'Cellulitis',
                'Meningitis',
                'Syphilis',
                'Gonorrhea',
                'Chlamydia',
            ],
            'Nephrology' => [
                'Chronic Kidney Disease',
                'Acute Kidney Injury',
                'Nephrotic Syndrome',
                'Glomerulonephritis',
                'Kidney Stones',
                'Polycystic Kidney Disease',
                'Diabetic Nephropathy',
                'Hypertensive Nephropathy',
                'Electrolyte Disorder',
            ],
            'Neurology' => [
                'Migraine',
                'Epilepsy',
                'Stroke',
                'Transient Ischemic Attack',
                'Parkinson Disease',
                'Multiple Sclerosis',
                'Neuropathy',
                'Dementia',
                'Alzheimer Disease',
                'Bell Palsy',
                'Vertigo',
                'Tremor',
                'Myasthenia Gravis',
                'Huntington Disease',
                'Amyotrophic Lateral Sclerosis',
                'Guillain-Barre Syndrome',
                'Trigeminal Neuralgia',
                'Restless Legs Syndrome',
            ],
            'Obstetrics' => [
                'Normal Pregnancy',
                'High Risk Pregnancy',
                'Ectopic Pregnancy',
                'Miscarriage',
                'Preeclampsia',
                'Gestational Diabetes',
                'Placenta Previa',
                'Preterm Labor',
                'Postpartum Hemorrhage',
                'Postpartum Depression',
            ],
            'Oncology' => [
                'Breast Cancer',
                'Lung Cancer',
                'Colorectal Cancer',
                'Prostate Cancer',
                'Cervical Cancer',
                'Ovarian Cancer',
                'Liver Cancer',
                'Stomach Cancer',
                'Pancreatic Cancer',
                'Brain Tumor',
                'Leukemia',
                'Lymphoma',
                'Melanoma',
            ],
            'Ophthalmology' => [
                'Refractive Error',
                'Cataract',
                'Glaucoma',
                'Conjunctivitis',
                'Dry Eye Syndrome',
                'Diabetic Retinopathy',
                'Age Related Macular Degeneration',
                'Retinal Detachment',
                'Uveitis',
                'Keratitis',
                'Strabismus',
                'Amblyopia',
                'Color Blindness',
                'Stye',
                'Chalazion',
            ],
            'Orthopedics' => [
                'Osteoarthritis',
                'Rheumatoid Arthritis',
                'Back Pain',
                'Neck Pain',
                'Fracture',
                'Dislocation',
                'Ligament Tear',
                'Meniscus Tear',
                'Rotator Cuff Tear',
                'Carpal Tunnel Syndrome',
                'Sciatica',
                'Osteoporosis',
                'Scoliosis',
                'Gout',
                'Plantar Fasciitis',
                'Achilles Tendinitis',
                'Tennis Elbow',
            ],
            'Pediatrics' => [
                'Pediatric Fever',
                'Pediatric Asthma',
                'Bronchiolitis',
                'Pneumonia in Children',
                'Chickenpox',
                'Measles',
                'Mumps',
                'Hand Foot and Mouth Disease',
                'Growth Delay',
                'Failure to Thrive',
                'Neonatal Jaundice',
                'Pediatric Diarrhea',
                'Worm Infestation',
                'Croup',
                'Rubella',
            ],
            'Psychiatry' => [
                'Major Depressive Disorder',
                'Generalized Anxiety Disorder',
                'Panic Disorder',
                'Bipolar Disorder',
                'Schizophrenia',
                'Obsessive Compulsive Disorder',
                'Post Traumatic Stress Disorder',
                'Attention Deficit Hyperactivity Disorder',
                'Autism Spectrum Disorder',
                'Insomnia',
                'Eating Disorder',
                'Borderline Personality Disorder',
            ],
            'Pulmonology' => [
                'Asthma',
                'Chronic Obstructive Pulmonary Disease',
                'Pneumonia',
                'Bronchitis',
                'Tuberculosis',
                'Pulmonary Fibrosis',
                'Pleural Effusion',
                'Pulmonary Embolism',
                'Sleep Apnea',
                'Lung Cancer',
                'Chronic Cough',
                'Cystic Fibrosis',
                'Bronchiectasis',
            ],
            'Rheumatology' => [
                'Rheumatoid Arthritis',
                'Systemic Lupus Erythematosus',
                'Ankylosing Spondylitis',
                'Psoriatic Arthritis',
                'Gout',
                'Vasculitis',
                'Scleroderma',
                'Sjogren Syndrome',
                'Fibromyalgia',
                'Polymyalgia Rheumatica',
            ],
            'Urology' => [
                'Kidney Stones',
                'Urinary Tract Infection',
                'Benign Prostatic Hyperplasia',
                'Prostatitis',
                'Erectile Dysfunction',
                'Male Infertility',
                'Urinary Incontinence',
                'Bladder Cancer',
                'Prostate Cancer',
                'Testicular Torsion',
                'Hydrocele',
                'Interstitial Cystitis',
                'Overactive Bladder',
            ],
            'Vascular Surgery' => [
                'Varicose Veins',
                'Peripheral Artery Disease',
                'Aortic Aneurysm',
                'Carotid Artery Disease',
                'Deep Vein Thrombosis',
                'Chronic Venous Insufficiency',
                'Diabetic Foot Ulcer',
                'Lymphedema',
            ],
        ];
    }
}
