<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Disease;
use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Department::query()->doesntExist()) {
            $this->call(DepartmentSeeder::class);
        }

        $departments = Department::query()->get()->keyBy('name_en');

        foreach (self::diseasesByDepartment() as $departmentName => $diseases) {
            $department = $departments->get($departmentName);

            if (! $department) {
                $department = Department::create([
                    'name_en' => $departmentName,
                    'name_hi' => DepartmentSeeder::hindiNameFor($departmentName),
                    'description_en' => null,
                    'description_hi' => null,
                    'is_active' => true,
                ]);

                $departments->put($departmentName, $department);
            }

            foreach ($diseases as $diseaseName) {
                Disease::updateOrCreate(
                    [
                        'name_en' => $diseaseName,
                        'department_id' => $department->id,
                    ],
                    [
                        'name_en' => $diseaseName,
                        'name_hi' => self::hindiNameFor($diseaseName),
                        'department_id' => $department->id,
                    ]
                );
            }
        }
    }

    public static function hindiNameFor(string $name): string
    {
        return [
            'Acne Vulgaris' => 'मुंहासे',
            'Abnormal Uterine Bleeding' => 'असामान्य गर्भाशयी रक्तस्राव',
            'Abscess' => 'फोड़ा',
            'Acute Asthma Attack' => 'तीव्र अस्थमा अटैक',
            'Acute Kidney Injury' => 'तीव्र गुर्दा क्षति',
            'Addison Disease' => 'एडिसन रोग',
            'Age Related Macular Degeneration' => 'उम्र से संबंधित मैक्युलर डिजनरेशन',
            'Alcohol Use Disorder' => 'शराब उपयोग विकार',
            'Allergic Rhinitis' => 'एलर्जिक राइनाइटिस',
            'Alopecia Areata' => 'एलोपेसिया एरीटा',
            'Alzheimer Disease' => 'अल्जाइमर रोग',
            'Amblyopia' => 'आलसी आंख',
            'Anaphylaxis' => 'एनाफिलैक्सिस',
            'Anemia' => 'एनीमिया',
            'Angina' => 'एनजाइना',
            'Angioedema' => 'एंजियोएडेमा',
            'Ankylosing Spondylitis' => 'एंकिलोजिंग स्पॉन्डिलाइटिस',
            'Aortic Aneurysm' => 'महाधमनी एन्यूरिज्म',
            'Aplastic Anemia' => 'अप्लास्टिक एनीमिया',
            'Appendicitis' => 'अपेंडिसाइटिस',
            'Arrhythmia' => 'हृदय गति अनियमितता',
            'Asthma' => 'अस्थमा',
            'Atopic Dermatitis' => 'एटोपिक डर्मेटाइटिस',
            'Atrial Fibrillation' => 'एट्रियल फिब्रिलेशन',
            'Attention Deficit Hyperactivity Disorder' => 'ध्यान-अभाव अति सक्रियता विकार',
            'Autism Spectrum Disorder' => 'ऑटिज्म स्पेक्ट्रम विकार',
            'Back Pain' => 'पीठ दर्द',
            'Bell Palsy' => 'बेल्स पाल्सी',
            'Benign Prostatic Hyperplasia' => 'प्रोस्टेट ग्रंथि का सौम्य बढ़ना',
            'Bipolar Disorder' => 'द्विध्रुवी विकार',
            'Bladder Cancer' => 'मूत्राशय कैंसर',
            'Brain Tumor' => 'मस्तिष्क ट्यूमर',
            'Breast Cancer' => 'स्तन कैंसर',
            'Breast Lump' => 'स्तन में गांठ',
            'Bronchiolitis' => 'ब्रोंकियोलाइटिस',
            'Bronchitis' => 'ब्रोंकाइटिस',
            'Bowel Obstruction' => 'आंत्र अवरोध',
            'Burn Injury' => 'जलने की चोट',
            'Cannabis Use Disorder' => 'भांग उपयोग विकार',
            'Cardiomyopathy' => 'कार्डियोमायोपैथी',
            'Carotid Artery Disease' => 'कैरोटिड धमनी रोग',
            'Carpal Tunnel Syndrome' => 'कार्पल टनल सिंड्रोम',
            'Cataract' => 'मोतियाबिंद',
            'Celiac Disease' => 'सीलिएक रोग',
            'Cellulitis' => 'सेल्युलाइटिस',
            'Cervical Cancer' => 'गर्भाशय ग्रीवा कैंसर',
            'Cervical Dysplasia' => 'गर्भाशय ग्रीवा डिस्प्लेसिया',
            'Chest Pain' => 'छाती में दर्द',
            'Chickenpox' => 'चेचक',
            'Chikungunya' => 'चिकनगुनिया',
            'Chronic Cough' => 'पुरानी खांसी',
            'Chronic Kidney Disease' => 'दीर्घकालिक गुर्दा रोग',
            'Chronic Obstructive Pulmonary Disease' => 'क्रॉनिक ऑब्सट्रक्टिव पल्मोनरी डिजीज',
            'Chronic Venous Insufficiency' => 'दीर्घकालिक शिरापरक अपर्याप्तता',
            'Cirrhosis' => 'सिरोसिस',
            'Colorectal Cancer' => 'कोलोरेक्टल कैंसर',
            'Common Cold' => 'सामान्य जुकाम',
            'Common Variable Immunodeficiency' => 'कॉमन वेरिएबल इम्यूनोडेफिशिएंसी',
            'Conjunctivitis' => 'कंजंक्टिवाइटिस',
            'Constipation' => 'कब्ज',
            'Coronary Artery Disease' => 'कोरोनरी धमनी रोग',
            'Crohn Disease' => 'क्रोहन रोग',
            'Cushing Syndrome' => 'कुशिंग सिंड्रोम',
            'COVID-19' => 'कोविड-19',
            'Deep Vein Thrombosis' => 'गहरी शिरा घनास्त्रता',
            'Dehydration' => 'निर्जलीकरण',
            'Delirium' => 'डिलीरियम',
            'Dementia' => 'डिमेंशिया',
            'Dengue Fever' => 'डेंगू बुखार',
            'Deviated Nasal Septum' => 'नाक की टेढ़ी सेप्टम',
            'Diabetic Foot Ulcer' => 'मधुमेहजनित पैर का अल्सर',
            'Diabetic Nephropathy' => 'मधुमेहजनित गुर्दा रोग',
            'Diabetic Retinopathy' => 'मधुमेहजनित रेटिनोपैथी',
            'Diarrhea' => 'दस्त',
            'Dislocation' => 'जोड़ खिसकना',
            'Drug Allergy' => 'दवा से एलर्जी',
            'Dry Eye Syndrome' => 'सूखी आंख सिंड्रोम',
            'Dysmenorrhea' => 'कष्टार्तव',
            'Eating Disorder' => 'भोजन विकार',
            'Ectopic Pregnancy' => 'अस्थानिक गर्भावस्था',
            'Eczema' => 'एक्जिमा',
            'Electrolyte Disorder' => 'इलेक्ट्रोलाइट विकार',
            'Electrolyte Imbalance' => 'इलेक्ट्रोलाइट असंतुलन',
            'Endometriosis' => 'एंडोमेट्रियोसिस',
            'Epilepsy' => 'मिर्गी',
            'Epistaxis' => 'नाक से खून आना',
            'Erectile Dysfunction' => 'स्तंभन दोष',
            'Failure to Thrive' => 'विकास में कमी',
            'Falls in Elderly' => 'बुजुर्गों में गिरना',
            'Fatigue' => 'थकान',
            'Fatty Liver Disease' => 'फैटी लिवर रोग',
            'Fever' => 'बुखार',
            'Fibromyalgia' => 'फाइब्रोमायल्जिया',
            'Food Allergy' => 'खाद्य एलर्जी',
            'Fracture' => 'हड्डी टूटना',
            'Frailty' => 'दुर्बलता',
            'Fungal Skin Infection' => 'त्वचा का फंगल संक्रमण',
            'Gallbladder Disease' => 'पित्ताशय रोग',
            'Gallstones' => 'पित्त की पथरी',
            'Gambling Disorder' => 'जुआ विकार',
            'Gastritis' => 'गैस्ट्राइटिस',
            'Gastroesophageal Reflux Disease' => 'गैस्ट्रोइसोफेजियल रिफ्लक्स रोग',
            'Generalized Anxiety Disorder' => 'सामान्यीकृत चिंता विकार',
            'Gestational Diabetes' => 'गर्भावधि मधुमेह',
            'Glaucoma' => 'ग्लूकोमा',
            'Glomerulonephritis' => 'ग्लोमेरुलोनेफ्राइटिस',
            'Gout' => 'गठिया',
            'Graves Disease' => 'ग्रेव्स रोग',
            'Growth Delay' => 'विकास में देरी',
            'Hand Foot and Mouth Disease' => 'हाथ, पैर और मुंह रोग',
            'Hashimoto Thyroiditis' => 'हाशिमोटो थायरॉयडाइटिस',
            'Head Injury' => 'सिर की चोट',
            'Hearing Loss' => 'सुनने में कमी',
            'Heart Failure' => 'हृदय विफलता',
            'Hemophilia' => 'हीमोफीलिया',
            'Hemorrhoids' => 'बवासीर',
            'Hepatitis' => 'हेपेटाइटिस',
            'Hepatitis B' => 'हेपेटाइटिस बी',
            'Hepatitis C' => 'हेपेटाइटिस सी',
            'Hernia' => 'हर्निया',
            'Herpes Zoster' => 'हरपीज जोस्टर',
            'High Risk Pregnancy' => 'उच्च जोखिम गर्भावस्था',
            'HIV Infection' => 'एचआईवी संक्रमण',
            'Hydrocele' => 'हाइड्रोसील',
            'Hyperlipidemia' => 'उच्च लिपिड स्तर',
            'Hypertension' => 'उच्च रक्तचाप',
            'Hypertensive Nephropathy' => 'उच्च रक्तचापजनित गुर्दा रोग',
            'Hyperthyroidism' => 'हाइपरथायरॉयडिज्म',
            'Hypothyroidism' => 'हाइपोथायरॉयडिज्म',
            'Impetigo' => 'इम्पेटाइगो',
            'Inflammatory Bowel Disease' => 'आंत्र सूजन रोग',
            'Influenza' => 'इन्फ्लुएंजा',
            'Insomnia' => 'अनिद्रा',
            'Irregular Menstrual Cycle' => 'अनियमित मासिक धर्म',
            'Irritable Bowel Syndrome' => 'इरिटेबल बाउल सिंड्रोम',
            'Iron Deficiency Anemia' => 'लौह-अल्पता एनीमिया',
            'Keratitis' => 'केराटाइटिस',
            'Kidney Stones' => 'गुर्दे की पथरी',
            'Laryngitis' => 'स्वरयंत्र शोथ',
            'Leukemia' => 'ल्यूकेमिया',
            'Ligament Tear' => 'लिगामेंट फटना',
            'Liver Cancer' => 'यकृत कैंसर',
            'Lung Cancer' => 'फेफड़ों का कैंसर',
            'Lymphoma' => 'लिम्फोमा',
            'Lymphedema' => 'लिम्फेडेमा',
            'Major Depressive Disorder' => 'गंभीर अवसाद विकार',
            'Malaria' => 'मलेरिया',
            'Male Infertility' => 'पुरुष बांझपन',
            'Melanoma' => 'मेलानोमा',
            'Melasma' => 'मेलास्मा',
            'Measles' => 'खसरा',
            'Meningitis' => 'मेनिन्जाइटिस',
            'Meniscus Tear' => 'मेनिस्कस फटना',
            'Menopause Symptoms' => 'रजोनिवृत्ति के लक्षण',
            'Migraine' => 'माइग्रेन',
            'Miscarriage' => 'गर्भपात',
            'Multiple Myeloma' => 'मल्टीपल मायलोमा',
            'Multiple Sclerosis' => 'मल्टीपल स्क्लेरोसिस',
            'Mumps' => 'कण्ठमाला',
            'Myasthenia Gravis' => 'मायस्थीनिया ग्रेविस',
            'Myocardial Infarction' => 'हृदयाघात',
            'Nasal Polyps' => 'नाक के पॉलीप्स',
            'Neck Pain' => 'गर्दन दर्द',
            'Neonatal Jaundice' => 'नवजात पीलिया',
            'Nephrotic Syndrome' => 'नेफ्रोटिक सिंड्रोम',
            'Neuropathy' => 'न्यूरोपैथी',
            'Nicotine Dependence' => 'निकोटीन निर्भरता',
            'Normal Pregnancy' => 'सामान्य गर्भावस्था',
            'Obsessive Compulsive Disorder' => 'ऑब्सेसिव कम्पल्सिव डिसऑर्डर',
            'Obesity' => 'मोटापा',
            'Opioid Use Disorder' => 'ओपिओइड उपयोग विकार',
            'Osteoarthritis' => 'ऑस्टियोआर्थराइटिस',
            'Osteoporosis' => 'ऑस्टियोपोरोसिस',
            'Otitis Externa' => 'बाहरी कान का संक्रमण',
            'Otitis Media' => 'मध्य कान का संक्रमण',
            'Ovarian Cancer' => 'अंडाशय कैंसर',
            'Ovarian Cyst' => 'अंडाशय की सिस्ट',
            'Pancreatic Cancer' => 'अग्न्याशय कैंसर',
            'Pancreatitis' => 'अग्न्याशयशोथ',
            'Panic Disorder' => 'पैनिक विकार',
            'Parkinson Disease' => 'पार्किंसन रोग',
            'Parkinsonism' => 'पार्किंसनिज्म',
            'Pediatric Asthma' => 'बच्चों में अस्थमा',
            'Pediatric Diarrhea' => 'बच्चों में दस्त',
            'Pediatric Fever' => 'बच्चों में बुखार',
            'Pelvic Inflammatory Disease' => 'श्रोणि सूजन रोग',
            'Peptic Ulcer Disease' => 'पेप्टिक अल्सर रोग',
            'Peripheral Artery Disease' => 'परिधीय धमनी रोग',
            'Pericarditis' => 'पेरीकार्डाइटिस',
            'Pituitary Adenoma' => 'पिट्यूटरी एडेनोमा',
            'Placenta Previa' => 'प्लेसेंटा प्रीविया',
            'Pleural Effusion' => 'फुफ्फुस द्रव संचय',
            'Pilonidal Sinus' => 'पायलोनाइडल साइनस',
            'Pneumonia' => 'निमोनिया',
            'Pneumonia in Children' => 'बच्चों में निमोनिया',
            'Poisoning' => 'विषाक्तता',
            'Polycystic Kidney Disease' => 'पॉलीसिस्टिक किडनी रोग',
            'Polycystic Ovary Syndrome' => 'पॉलीसिस्टिक ओवरी सिंड्रोम',
            'Polycythemia Vera' => 'पॉलीसाइथीमिया वेरा',
            'Polypharmacy' => 'बहु-औषधि उपयोग',
            'Polymyalgia Rheumatica' => 'पॉलीमायल्जिया रूमेटिका',
            'Post Traumatic Stress Disorder' => 'आघातोत्तर तनाव विकार',
            'Postpartum Depression' => 'प्रसवोत्तर अवसाद',
            'Postpartum Hemorrhage' => 'प्रसवोत्तर रक्तस्राव',
            'Preeclampsia' => 'प्रीएक्लेम्पसिया',
            'Pressure Ulcer' => 'दबाव घाव',
            'Preterm Labor' => 'समय से पहले प्रसव पीड़ा',
            'Primary Immunodeficiency' => 'प्राथमिक प्रतिरक्षा कमी',
            'Prostate Cancer' => 'प्रोस्टेट कैंसर',
            'Prostatitis' => 'प्रोस्टेटाइटिस',
            'Psoriasis' => 'सोरायसिस',
            'Psoriatic Arthritis' => 'सोरायटिक गठिया',
            'Pulmonary Embolism' => 'फुफ्फुसीय एम्बोलिज्म',
            'Pulmonary Fibrosis' => 'फेफड़ों का फाइब्रोसिस',
            'Rabies Exposure' => 'रेबीज संपर्क',
            'Refractive Error' => 'दृष्टि दोष',
            'Retinal Detachment' => 'रेटिना अलग होना',
            'Rheumatoid Arthritis' => 'रूमेटाइड आर्थराइटिस',
            'Rosacea' => 'रोसैसिया',
            'Rotator Cuff Tear' => 'रोटेटर कफ फटना',
            'Scabies' => 'खुजली',
            'Schizophrenia' => 'सिजोफ्रेनिया',
            'Sciatica' => 'सायटिका',
            'Scleroderma' => 'स्क्लेरोडर्मा',
            'Scoliosis' => 'रीढ़ की वक्रता',
            'Sedative Use Disorder' => 'सेडेटिव उपयोग विकार',
            'Seizure' => 'दौरा',
            'Sepsis' => 'सेप्सिस',
            'Severe Abdominal Pain' => 'तेज पेट दर्द',
            'Severe Dehydration' => 'गंभीर निर्जलीकरण',
            'Sickle Cell Disease' => 'सिकल सेल रोग',
            'Sinusitis' => 'साइनसाइटिस',
            'Sjogren Syndrome' => 'शोग्रेन सिंड्रोम',
            'Skin Cancer' => 'त्वचा कैंसर',
            'Sleep Apnea' => 'स्लीप एपनिया',
            'Soft Tissue Tumor' => 'मृदु ऊतक ट्यूमर',
            'Stimulant Use Disorder' => 'उत्तेजक पदार्थ उपयोग विकार',
            'Stomach Cancer' => 'पेट का कैंसर',
            'Strabismus' => 'भेंगापन',
            'Stroke' => 'स्ट्रोक',
            'Stroke Symptoms' => 'स्ट्रोक के लक्षण',
            'Syncope' => 'बेहोशी',
            'Systemic Lupus Erythematosus' => 'सिस्टमिक ल्यूपस एरिथेमेटोसस',
            'Testicular Torsion' => 'वृषण मरोड़',
            'Thalassemia' => 'थैलेसीमिया',
            'Thrombocytopenia' => 'थ्रोम्बोसाइटोपीनिया',
            'Thyroid Nodule' => 'थायरॉयड गांठ',
            'Thyroid Swelling' => 'थायरॉयड सूजन',
            'Tinnitus' => 'कान में आवाज आना',
            'Tonsillitis' => 'टॉन्सिलाइटिस',
            'Transient Ischemic Attack' => 'क्षणिक इस्केमिक अटैक',
            'Tremor' => 'कंपकंपी',
            'Tuberculosis' => 'क्षय रोग',
            'Typhoid Fever' => 'टाइफाइड बुखार',
            'Type 1 Diabetes' => 'टाइप 1 मधुमेह',
            'Type 2 Diabetes' => 'टाइप 2 मधुमेह',
            'Ulcerative Colitis' => 'अल्सरेटिव कोलाइटिस',
            'Urticaria' => 'पित्ती',
            'Urinary Incontinence' => 'मूत्र असंयम',
            'Urinary Tract Infection' => 'मूत्र मार्ग संक्रमण',
            'Uterine Fibroid' => 'गर्भाशय फाइब्रॉइड',
            'Uveitis' => 'यूवाइटिस',
            'Vaginitis' => 'योनि शोथ',
            'Valvular Heart Disease' => 'हृदय वाल्व रोग',
            'Varicose Veins' => 'वैरिकोज नसें',
            'Vasculitis' => 'रक्तवाहिनी शोथ',
            'Vertigo' => 'चक्कर आना',
            'Vitamin B12 Deficiency' => 'विटामिन बी12 की कमी',
            'Vitamin D Deficiency' => 'विटामिन डी की कमी',
            'Vitiligo' => 'सफेद दाग',
            'Voice Disorder' => 'आवाज संबंधी विकार',
            'Worm Infestation' => 'कृमि संक्रमण',
        ][$name];
    }

    public static function diseasesByDepartment(): array
    {
        return [
            'Addiction Medicine' => [
                'Alcohol Use Disorder',
                'Opioid Use Disorder',
                'Nicotine Dependence',
                'Cannabis Use Disorder',
                'Stimulant Use Disorder',
                'Sedative Use Disorder',
                'Gambling Disorder',
            ],
            'Allergy and Immunology' => [
                'Allergic Rhinitis',
                'Food Allergy',
                'Drug Allergy',
                'Urticaria',
                'Angioedema',
                'Anaphylaxis',
                'Atopic Dermatitis',
                'Primary Immunodeficiency',
                'Common Variable Immunodeficiency',
            ],
            'Cardiology' => [
                'Hypertension',
                'Coronary Artery Disease',
                'Angina',
                'Myocardial Infarction',
                'Heart Failure',
                'Atrial Fibrillation',
                'Arrhythmia',
                'Valvular Heart Disease',
                'Cardiomyopathy',
                'Pericarditis',
                'Peripheral Artery Disease',
                'Deep Vein Thrombosis',
                'Hyperlipidemia',
            ],
            'Dermatology' => [
                'Acne Vulgaris',
                'Eczema',
                'Psoriasis',
                'Vitiligo',
                'Fungal Skin Infection',
                'Scabies',
                'Urticaria',
                'Rosacea',
                'Alopecia Areata',
                'Melasma',
                'Cellulitis',
                'Impetigo',
                'Herpes Zoster',
                'Skin Cancer',
            ],
            'Emergency Medicine' => [
                'Chest Pain',
                'Severe Abdominal Pain',
                'Stroke Symptoms',
                'Sepsis',
                'Anaphylaxis',
                'Acute Asthma Attack',
                'Severe Dehydration',
                'Poisoning',
                'Burn Injury',
                'Head Injury',
                'Fracture',
                'Syncope',
                'Seizure',
            ],
            'Endocrinology' => [
                'Type 1 Diabetes',
                'Type 2 Diabetes',
                'Gestational Diabetes',
                'Hypothyroidism',
                'Hyperthyroidism',
                'Graves Disease',
                'Hashimoto Thyroiditis',
                'Thyroid Nodule',
                'Cushing Syndrome',
                'Addison Disease',
                'Polycystic Ovary Syndrome',
                'Osteoporosis',
                'Obesity',
                'Pituitary Adenoma',
            ],
            'ENT (Otolaryngology)' => [
                'Sinusitis',
                'Tonsillitis',
                'Otitis Media',
                'Otitis Externa',
                'Hearing Loss',
                'Tinnitus',
                'Vertigo',
                'Nasal Polyps',
                'Deviated Nasal Septum',
                'Laryngitis',
                'Voice Disorder',
                'Sleep Apnea',
                'Epistaxis',
            ],
            'Gastroenterology' => [
                'Gastroesophageal Reflux Disease',
                'Peptic Ulcer Disease',
                'Gastritis',
                'Irritable Bowel Syndrome',
                'Inflammatory Bowel Disease',
                'Ulcerative Colitis',
                'Crohn Disease',
                'Celiac Disease',
                'Gallstones',
                'Pancreatitis',
                'Hepatitis',
                'Cirrhosis',
                'Fatty Liver Disease',
                'Constipation',
                'Diarrhea',
                'Hemorrhoids',
            ],
            'General Medicine' => [
                'Fever',
                'Common Cold',
                'Influenza',
                'Fatigue',
                'Anemia',
                'Vitamin D Deficiency',
                'Vitamin B12 Deficiency',
                'Migraine',
                'Dengue Fever',
                'Malaria',
                'Typhoid Fever',
                'Urinary Tract Infection',
                'Dehydration',
                'Electrolyte Imbalance',
            ],
            'General Surgery' => [
                'Appendicitis',
                'Hernia',
                'Gallbladder Disease',
                'Abscess',
                'Pilonidal Sinus',
                'Thyroid Swelling',
                'Breast Lump',
                'Bowel Obstruction',
                'Varicose Veins',
                'Soft Tissue Tumor',
            ],
            'Geriatrics' => [
                'Dementia',
                'Delirium',
                'Falls in Elderly',
                'Frailty',
                'Polypharmacy',
                'Urinary Incontinence',
                'Pressure Ulcer',
                'Osteoporosis',
                'Parkinsonism',
            ],
            'Gynecology' => [
                'Irregular Menstrual Cycle',
                'Dysmenorrhea',
                'Endometriosis',
                'Uterine Fibroid',
                'Ovarian Cyst',
                'Pelvic Inflammatory Disease',
                'Vaginitis',
                'Menopause Symptoms',
                'Abnormal Uterine Bleeding',
                'Cervical Dysplasia',
            ],
            'Hematology' => [
                'Iron Deficiency Anemia',
                'Aplastic Anemia',
                'Thalassemia',
                'Sickle Cell Disease',
                'Hemophilia',
                'Thrombocytopenia',
                'Leukemia',
                'Lymphoma',
                'Multiple Myeloma',
                'Polycythemia Vera',
            ],
            'Infectious Diseases' => [
                'Tuberculosis',
                'HIV Infection',
                'COVID-19',
                'Dengue Fever',
                'Malaria',
                'Typhoid Fever',
                'Chikungunya',
                'Hepatitis B',
                'Hepatitis C',
                'Rabies Exposure',
                'Sepsis',
                'Cellulitis',
                'Meningitis',
            ],
            'Nephrology' => [
                'Chronic Kidney Disease',
                'Acute Kidney Injury',
                'Nephrotic Syndrome',
                'Glomerulonephritis',
                'Kidney Stones',
                'Polycystic Kidney Disease',
                'Diabetic Nephropathy',
                'Hypertensive Nephropathy',
                'Electrolyte Disorder',
            ],
            'Neurology' => [
                'Migraine',
                'Epilepsy',
                'Stroke',
                'Transient Ischemic Attack',
                'Parkinson Disease',
                'Multiple Sclerosis',
                'Neuropathy',
                'Dementia',
                'Alzheimer Disease',
                'Bell Palsy',
                'Vertigo',
                'Tremor',
                'Myasthenia Gravis',
            ],
            'Obstetrics' => [
                'Normal Pregnancy',
                'High Risk Pregnancy',
                'Ectopic Pregnancy',
                'Miscarriage',
                'Preeclampsia',
                'Gestational Diabetes',
                'Placenta Previa',
                'Preterm Labor',
                'Postpartum Hemorrhage',
                'Postpartum Depression',
            ],
            'Oncology' => [
                'Breast Cancer',
                'Lung Cancer',
                'Colorectal Cancer',
                'Prostate Cancer',
                'Cervical Cancer',
                'Ovarian Cancer',
                'Liver Cancer',
                'Stomach Cancer',
                'Pancreatic Cancer',
                'Brain Tumor',
                'Leukemia',
                'Lymphoma',
                'Melanoma',
            ],
            'Ophthalmology' => [
                'Refractive Error',
                'Cataract',
                'Glaucoma',
                'Conjunctivitis',
                'Dry Eye Syndrome',
                'Diabetic Retinopathy',
                'Age Related Macular Degeneration',
                'Retinal Detachment',
                'Uveitis',
                'Keratitis',
                'Strabismus',
                'Amblyopia',
            ],
            'Orthopedics' => [
                'Osteoarthritis',
                'Rheumatoid Arthritis',
                'Back Pain',
                'Neck Pain',
                'Fracture',
                'Dislocation',
                'Ligament Tear',
                'Meniscus Tear',
                'Rotator Cuff Tear',
                'Carpal Tunnel Syndrome',
                'Sciatica',
                'Osteoporosis',
                'Scoliosis',
                'Gout',
            ],
            'Pediatrics' => [
                'Pediatric Fever',
                'Pediatric Asthma',
                'Bronchiolitis',
                'Pneumonia in Children',
                'Chickenpox',
                'Measles',
                'Mumps',
                'Hand Foot and Mouth Disease',
                'Growth Delay',
                'Failure to Thrive',
                'Neonatal Jaundice',
                'Pediatric Diarrhea',
                'Worm Infestation',
            ],
            'Psychiatry' => [
                'Major Depressive Disorder',
                'Generalized Anxiety Disorder',
                'Panic Disorder',
                'Bipolar Disorder',
                'Schizophrenia',
                'Obsessive Compulsive Disorder',
                'Post Traumatic Stress Disorder',
                'Attention Deficit Hyperactivity Disorder',
                'Autism Spectrum Disorder',
                'Insomnia',
                'Eating Disorder',
            ],
            'Pulmonology' => [
                'Asthma',
                'Chronic Obstructive Pulmonary Disease',
                'Pneumonia',
                'Bronchitis',
                'Tuberculosis',
                'Pulmonary Fibrosis',
                'Pleural Effusion',
                'Pulmonary Embolism',
                'Sleep Apnea',
                'Lung Cancer',
                'Chronic Cough',
            ],
            'Rheumatology' => [
                'Rheumatoid Arthritis',
                'Systemic Lupus Erythematosus',
                'Ankylosing Spondylitis',
                'Psoriatic Arthritis',
                'Gout',
                'Vasculitis',
                'Scleroderma',
                'Sjogren Syndrome',
                'Fibromyalgia',
                'Polymyalgia Rheumatica',
            ],
            'Urology' => [
                'Kidney Stones',
                'Urinary Tract Infection',
                'Benign Prostatic Hyperplasia',
                'Prostatitis',
                'Erectile Dysfunction',
                'Male Infertility',
                'Urinary Incontinence',
                'Bladder Cancer',
                'Prostate Cancer',
                'Testicular Torsion',
                'Hydrocele',
            ],
            'Vascular Surgery' => [
                'Varicose Veins',
                'Peripheral Artery Disease',
                'Aortic Aneurysm',
                'Carotid Artery Disease',
                'Deep Vein Thrombosis',
                'Chronic Venous Insufficiency',
                'Diabetic Foot Ulcer',
                'Lymphedema',
            ],
        ];
    }
}
