<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        foreach ($this->medicines() as $medicine) {
            DB::table('medicines')->upsert(
                [$this->prepareMedicineRow($medicine, $now)],
                ['slug'],
                $this->updatableColumns()
            );
        }
    }

    private function prepareMedicineRow(array $medicine, $now): array
    {
        foreach (['brand_names_json', 'faqs_json', 'source_references_json'] as $jsonColumn) {
            if (array_key_exists($jsonColumn, $medicine) && is_array($medicine[$jsonColumn])) {
                $medicine[$jsonColumn] = json_encode($medicine[$jsonColumn], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            }
        }

        $medicine['created_at'] = $now;
        $medicine['updated_at'] = $now;

        return $medicine;
    }

    private function updatableColumns(): array
    {
        return [
            'name',
            'generic_name',
            'brand_names_json',
            'composition',
            'strength',
            'medicine_type',
            'category',
            'prescription_required',
            'purpose_en',
            'purpose_hi',
            'overview_en',
            'overview_hi',
            'uses_en',
            'uses_hi',
            'benefits_en',
            'benefits_hi',
            'dosage_information_en',
            'dosage_information_hi',
            'mechanism_en',
            'mechanism_hi',
            'common_side_effects_en',
            'common_side_effects_hi',
            'serious_side_effects_en',
            'serious_side_effects_hi',
            'drug_interactions_en',
            'drug_interactions_hi',
            'food_interactions_en',
            'food_interactions_hi',
            'alcohol_warning_en',
            'alcohol_warning_hi',
            'pregnancy_warning_en',
            'pregnancy_warning_hi',
            'breastfeeding_warning_en',
            'breastfeeding_warning_hi',
            'kidney_warning_en',
            'kidney_warning_hi',
            'liver_warning_en',
            'liver_warning_hi',
            'driving_warning_en',
            'driving_warning_hi',
            'allergy_warning_en',
            'allergy_warning_hi',
            'precautions_en',
            'precautions_hi',
            'contraindications_en',
            'contraindications_hi',
            'avoid_if_en',
            'avoid_if_hi',
            'missed_dose_en',
            'missed_dose_hi',
            'overdose_en',
            'overdose_hi',
            'storage_en',
            'storage_hi',
            'expert_advice_en',
            'expert_advice_hi',
            'when_to_contact_doctor_en',
            'when_to_contact_doctor_hi',
            'faqs_json',
            'source_references_json',
            'meta_title_en',
            'meta_title_hi',
            'meta_description_en',
            'meta_description_hi',
            'reviewed_by',
            'last_reviewed_at',
            'ai_generated',
            'medically_reviewed',
            'review_status',
            'is_published',
            'created_by',
            'updated_by',
            'updated_at',
        ];
    }

    private function medicines(): iterable
    {
        yield from [
            [
                'name' => 'Paracetamol',
                'slug' => 'paracetamol',
                'generic_name' => 'Acetaminophen',
                'brand_names_json' => ['Dolo 650', 'Crocin', 'Calpol'],
                'composition' => 'Paracetamol',
                'strength' => '500 mg / 650 mg',
                'medicine_type' => 'Tablet / Syrup',
                'category' => 'Pain relief and fever',
                'prescription_required' => false,
                'purpose_en' => 'General educational information for fever reduction and mild to moderate pain relief.',
                'purpose_hi' => 'बुखार कम करने और हल्के से मध्यम दर्द में सामान्य शैक्षणिक जानकारी।',
                'overview_en' => 'Paracetamol is commonly used for fever and pain relief. It may be considered for short-term symptomatic relief, but the right use depends on age, dose, liver health, and other medicines.',
                'overview_hi' => 'पैरासिटामोल बुखार और दर्द में आमतौर पर उपयोग की जाने वाली दवा है। इसका सही उपयोग उम्र, मात्रा, लिवर की स्थिति और अन्य दवाओं पर निर्भर करता है।',
                'uses_en' => 'May be used for fever, body ache, headache, or mild pain when advised appropriately.',
                'uses_hi' => 'उचित सलाह मिलने पर बुखार, बदन दर्द, सिरदर्द या हल्के दर्द में उपयोग किया जा सकता है।',
                'benefits_en' => 'Can help reduce fever and improve comfort while the underlying cause is being assessed.',
                'benefits_hi' => 'मूल कारण की जांच के दौरान बुखार कम करने और आराम देने में मदद कर सकती है।',
                'dosage_information_en' => 'Dosage depends on age, weight, liver health, total daily intake, and professional advice. Do not combine multiple paracetamol-containing products without checking the labels carefully.',
                'dosage_information_hi' => 'खुराक उम्र, वजन, लिवर की स्थिति, कुल दैनिक मात्रा और डॉक्टर की सलाह पर निर्भर करती है। एक से अधिक पैरासिटामोल वाली दवाएं बिना लेबल जांचे साथ में न लें।',
                'mechanism_en' => 'It works by helping reduce pain signals and fever response in the body.',
                'mechanism_hi' => 'यह शरीर में दर्द के संकेत और बुखार की प्रतिक्रिया को कम करने में मदद करती है।',
                'common_side_effects_en' => 'Side effects are uncommon at usual doses but may include nausea or stomach discomfort in some people.',
                'common_side_effects_hi' => 'सामान्य मात्रा में दुष्प्रभाव कम होते हैं, लेकिन कुछ लोगों में मतली या पेट में असहजता हो सकती है।',
                'serious_side_effects_en' => 'Too much paracetamol can seriously harm the liver. Seek urgent help for overdose, confusion, vomiting, or unusual sleepiness.',
                'serious_side_effects_hi' => 'अधिक मात्रा में पैरासिटामोल लिवर को गंभीर नुकसान पहुंचा सकती है। ओवरडोज, उल्टी, भ्रम या बहुत ज्यादा नींद आने पर तुरंत मदद लें।',
                'alcohol_warning_en' => 'Alcohol can increase liver risk. Ask a doctor or pharmacist before use if you drink regularly.',
                'alcohol_warning_hi' => 'शराब लिवर के जोखिम को बढ़ा सकती है। यदि आप नियमित रूप से शराब लेते हैं, तो उपयोग से पहले डॉक्टर या फार्मासिस्ट से पूछें।',
                'pregnancy_warning_en' => 'Pregnancy safety depends on the situation and doctor advice.',
                'pregnancy_warning_hi' => 'गर्भावस्था में सुरक्षा स्थिति और डॉक्टर की सलाह पर निर्भर करती है।',
                'breastfeeding_warning_en' => 'Breastfeeding use should still be discussed if the medicine is needed often or in higher doses.',
                'breastfeeding_warning_hi' => 'स्तनपान के दौरान भी यदि दवा बार-बार या अधिक मात्रा में चाहिए, तो डॉक्टर से चर्चा करें।',
                'liver_warning_en' => 'Use extra caution in liver disease or if other liver-impacting medicines are being taken.',
                'liver_warning_hi' => 'लिवर की बीमारी होने पर या लिवर पर असर डालने वाली अन्य दवाएं चल रही हों तो अतिरिक्त सावधानी रखें।',
                'allergy_warning_en' => 'Avoid if you have had an allergic reaction to paracetamol before.',
                'allergy_warning_hi' => 'यदि पहले पैरासिटामोल से एलर्जी हुई हो तो इसका उपयोग न करें।',
                'precautions_en' => 'Read combination cold-and-flu labels carefully to avoid accidental duplicate intake.',
                'precautions_hi' => 'गलती से दोहरी मात्रा लेने से बचने के लिए कॉम्बिनेशन सर्दी-जुकाम वाली दवाओं के लेबल ध्यान से पढ़ें।',
                'missed_dose_en' => 'If it was advised on a schedule, ask how to restart safely. Do not double the next dose.',
                'missed_dose_hi' => 'यदि इसे तय समय पर लेने की सलाह दी गई थी, तो सुरक्षित तरीके से दोबारा शुरू करने के लिए पूछें। अगली मात्रा दोगुनी न लें।',
                'overdose_en' => 'Overdose can be dangerous even if you feel well at first. Seek emergency medical help immediately.',
                'overdose_hi' => 'ओवरडोज शुरू में सामान्य लगने पर भी खतरनाक हो सकती है। तुरंत आपातकालीन चिकित्सा सहायता लें।',
                'storage_en' => 'Store as per pack instructions and keep away from children.',
                'storage_hi' => 'पैक पर दिए निर्देशों के अनुसार रखें और बच्चों की पहुंच से दूर रखें।',
                'expert_advice_en' => 'Repeated fever or pain needs medical review instead of repeated self-medication.',
                'expert_advice_hi' => 'बार-बार बुखार या दर्द होने पर बार-बार स्वयं दवा लेने के बजाय डॉक्टर से जांच कराएं।',
                'when_to_contact_doctor_en' => 'Contact a doctor if fever persists, pain becomes severe, or overdose is suspected.',
                'when_to_contact_doctor_hi' => 'यदि बुखार बना रहे, दर्द बढ़े, या ओवरडोज का संदेह हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Is it an antibiotic?', 'answer' => 'No. Paracetamol is not an antibiotic.'],
                    ['question' => 'Can I use more than one fever medicine together?', 'answer' => 'Do not combine medicines without checking with a doctor or pharmacist.'],
                ],
                'meta_title_en' => 'Paracetamol: Uses, Side Effects, Dosage Info & Precautions',
                'meta_title_hi' => 'पैरासिटामोल: उपयोग, दुष्प्रभाव और सावधानियां',
                'meta_description_en' => 'General medicine information for paracetamol including uses, side effects, warnings, and when to contact a doctor.',
                'meta_description_hi' => 'पैरासिटामोल के उपयोग, दुष्प्रभाव, चेतावनी और डॉक्टर से कब संपर्क करें, इसकी सामान्य जानकारी।',
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Azithromycin',
                'slug' => 'azithromycin',
                'generic_name' => 'Azithromycin',
                'brand_names_json' => ['Azithral', 'Azee'],
                'composition' => 'Azithromycin',
                'strength' => '250 mg / 500 mg',
                'medicine_type' => 'Tablet / Suspension',
                'category' => 'Antibiotic',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for a prescription antibiotic used only when a qualified clinician advises it.',
                'purpose_hi' => 'यह एक प्रिस्क्रिप्शन एंटीबायोटिक है, जिसका उपयोग केवल योग्य डॉक्टर की सलाह पर किया जाना चाहिए।',
                'overview_en' => 'Azithromycin is an antibiotic. It does not help against every infection and should not be started without medical advice.',
                'overview_hi' => 'एज़िथ्रोमाइसिन एक एंटीबायोटिक है। यह हर संक्रमण में काम नहीं करती और बिना डॉक्टर की सलाह के शुरू नहीं करनी चाहिए।',
                'uses_en' => 'May be prescribed for certain bacterial infections when a doctor decides it is appropriate.',
                'uses_hi' => 'कुछ बैक्टीरियल संक्रमणों में डॉक्टर उचित समझें तो इसे लिखा जा सकता है।',
                'dosage_information_en' => 'Antibiotic dose and duration vary by infection, age, weight, and kidney or liver status. Incomplete or incorrect use can be harmful.',
                'dosage_information_hi' => 'एंटीबायोटिक की खुराक और अवधि संक्रमण, उम्र, वजन और किडनी/लिवर की स्थिति पर निर्भर करती है। गलत या अधूरा उपयोग हानिकारक हो सकता है।',
                'common_side_effects_en' => 'Possible side effects include nausea, loose motions, stomach upset, or altered taste.',
                'common_side_effects_hi' => 'मतली, दस्त, पेट खराब होना या स्वाद बदलना जैसे दुष्प्रभाव हो सकते हैं।',
                'serious_side_effects_en' => 'Severe allergy, persistent diarrhoea, palpitations, or yellowing of eyes/skin need urgent medical attention.',
                'serious_side_effects_hi' => 'गंभीर एलर्जी, लगातार दस्त, दिल की धड़कन का असामान्य लगना या आंख/त्वचा पीली पड़ना तुरंत जांच की जरूरत है।',
                'drug_interactions_en' => 'Interactions can happen with heart-rhythm medicines and some other prescription drugs. Always share your full medicine list.',
                'drug_interactions_hi' => 'दिल की धड़कन से जुड़ी दवाओं और कुछ अन्य दवाओं के साथ इंटरैक्शन हो सकता है। अपनी सभी दवाओं की सूची डॉक्टर को बताएं।',
                'pregnancy_warning_en' => 'Use in pregnancy should be clinician-guided.',
                'pregnancy_warning_hi' => 'गर्भावस्था में उपयोग डॉक्टर की सलाह पर होना चाहिए।',
                'breastfeeding_warning_en' => 'Breastfeeding questions should be discussed individually.',
                'breastfeeding_warning_hi' => 'स्तनपान के दौरान उपयोग पर व्यक्तिगत सलाह जरूरी है।',
                'precautions_en' => 'Do not self-start leftover antibiotics or use them for viral colds.',
                'precautions_hi' => 'बची हुई एंटीबायोटिक खुद से शुरू न करें और वायरल सर्दी-जुकाम में उपयोग न करें।',
                'overdose_en' => 'Seek urgent medical help if too much has been taken.',
                'overdose_hi' => 'अधिक मात्रा लेने पर तुरंत चिकित्सा सहायता लें।',
                'storage_en' => 'Store as instructed on the label.',
                'storage_hi' => 'लेबल पर दिए निर्देशों के अनुसार रखें।',
                'when_to_contact_doctor_en' => 'Contact your doctor if symptoms worsen, severe diarrhoea develops, or you suspect an allergic reaction.',
                'when_to_contact_doctor_hi' => 'यदि लक्षण बढ़ें, गंभीर दस्त हो, या एलर्जी का संदेह हो तो डॉक्टर से संपर्क करें।',
                'meta_title_en' => 'Azithromycin: Uses, Side Effects & Precautions',
                'meta_title_hi' => 'एज़िथ्रोमाइसिन: उपयोग, दुष्प्रभाव और सावधानियां',
                'meta_description_en' => 'General educational information for azithromycin including uses, side effects, and antibiotic safety warnings.',
                'meta_description_hi' => 'एज़िथ्रोमाइसिन की सामान्य शैक्षणिक जानकारी, उपयोग, दुष्प्रभाव और एंटीबायोटिक सुरक्षा चेतावनियां।',
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Cetirizine',
                'slug' => 'cetirizine',
                'generic_name' => 'Cetirizine',
                'brand_names_json' => ['Cetzine', 'Okacet'],
                'composition' => 'Cetirizine',
                'strength' => '10 mg',
                'medicine_type' => 'Tablet / Syrup',
                'category' => 'Allergy relief',
                'prescription_required' => false,
                'purpose_en' => 'General educational information for allergy symptom relief.',
                'purpose_hi' => 'एलर्जी के लक्षणों में राहत के लिए सामान्य शैक्षणिक जानकारी।',
                'overview_en' => 'Cetirizine may be used for allergy-related symptoms such as sneezing, itching, or runny nose when appropriate.',
                'overview_hi' => 'उचित स्थिति में सिट्रीजिन छींक, खुजली या नाक बहने जैसे एलर्जी लक्षणों में उपयोग की जा सकती है।',
                'common_side_effects_en' => 'Some people may feel sleepy or notice dry mouth.',
                'common_side_effects_hi' => 'कुछ लोगों को नींद आ सकती है या मुंह सूख सकता है।',
                'driving_warning_en' => 'If it makes you sleepy, avoid driving or using machinery.',
                'driving_warning_hi' => 'यदि इससे नींद आए तो ड्राइविंग या मशीन चलाने से बचें।',
                'precautions_en' => 'If allergy symptoms are severe, recurrent, or associated with breathing trouble, seek medical advice.',
                'precautions_hi' => 'यदि एलर्जी के लक्षण गंभीर हों, बार-बार हों, या सांस की तकलीफ हो, तो डॉक्टर से सलाह लें।',
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Pantoprazole',
                'slug' => 'pantoprazole',
                'generic_name' => 'Pantoprazole',
                'brand_names_json' => ['Pantocid', 'Pan 40'],
                'composition' => 'Pantoprazole',
                'strength' => '20 mg / 40 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Acidity and reflux',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for acid reduction medicines used in reflux and related conditions.',
                'purpose_hi' => 'एसिड कम करने वाली दवाओं की सामान्य जानकारी, जो रिफ्लक्स और संबंधित स्थितियों में उपयोग की जाती हैं।',
                'overview_en' => 'Pantoprazole reduces stomach acid. Long-term or repeated use should be reviewed by a doctor.',
                'overview_hi' => 'पैंटोप्राज़ोल पेट का एसिड कम करती है। लंबे समय तक या बार-बार उपयोग की डॉक्टर से समीक्षा होनी चाहिए।',
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Metformin',
                'slug' => 'metformin',
                'generic_name' => 'Metformin',
                'brand_names_json' => ['Glycomet', 'Glyciphage'],
                'composition' => 'Metformin',
                'strength' => '500 mg / 850 mg / 1000 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Diabetes',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for a prescription medicine used in diabetes care plans.',
                'purpose_hi' => 'मधुमेह देखभाल योजना में उपयोग होने वाली प्रिस्क्रिप्शन दवा की सामान्य जानकारी।',
                'overview_en' => 'Metformin is commonly used in diabetes care but should be taken only under medical supervision.',
                'overview_hi' => 'मेटफॉर्मिन मधुमेह में आमतौर पर उपयोग की जाती है, लेकिन इसका उपयोग डॉक्टर की निगरानी में होना चाहिए।',
                'kidney_warning_en' => 'Kidney function is important for safe use. Discuss current kidney health before taking it.',
                'kidney_warning_hi' => 'सुरक्षित उपयोग के लिए किडनी की स्थिति महत्वपूर्ण है। उपयोग से पहले किडनी की स्थिति पर चर्चा करें।',
                'review_status' => 'published',
                'is_published' => true,
            ],
        ];
    }
}
