<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        foreach ($this->medicines() as $medicine) {
            DB::table('medicines')->upsert(
                [$this->prepareMedicineRow($medicine, $now)],
                ['slug'],
                $this->updatableColumns()
            );
        }
    }

    private function prepareMedicineRow(array $medicine, $now): array
    {
        foreach (['brand_names_json', 'faqs_json', 'source_references_json'] as $jsonColumn) {
            if (array_key_exists($jsonColumn, $medicine) && is_array($medicine[$jsonColumn])) {
                $medicine[$jsonColumn] = json_encode($medicine[$jsonColumn], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            }
        }

        $medicine['created_at'] = $now;
        $medicine['updated_at'] = $now;

        return $medicine;
    }

    private function updatableColumns(): array
    {
        return [
            'name',
            'generic_name',
            'brand_names_json',
            'composition',
            'strength',
            'medicine_type',
            'category',
            'prescription_required',
            'purpose_en',
            'purpose_hi',
            'overview_en',
            'overview_hi',
            'uses_en',
            'uses_hi',
            'benefits_en',
            'benefits_hi',
            'dosage_information_en',
            'dosage_information_hi',
            'mechanism_en',
            'mechanism_hi',
            'common_side_effects_en',
            'common_side_effects_hi',
            'serious_side_effects_en',
            'serious_side_effects_hi',
            'drug_interactions_en',
            'drug_interactions_hi',
            'food_interactions_en',
            'food_interactions_hi',
            'alcohol_warning_en',
            'alcohol_warning_hi',
            'pregnancy_warning_en',
            'pregnancy_warning_hi',
            'breastfeeding_warning_en',
            'breastfeeding_warning_hi',
            'kidney_warning_en',
            'kidney_warning_hi',
            'liver_warning_en',
            'liver_warning_hi',
            'driving_warning_en',
            'driving_warning_hi',
            'allergy_warning_en',
            'allergy_warning_hi',
            'precautions_en',
            'precautions_hi',
            'contraindications_en',
            'contraindications_hi',
            'avoid_if_en',
            'avoid_if_hi',
            'missed_dose_en',
            'missed_dose_hi',
            'overdose_en',
            'overdose_hi',
            'storage_en',
            'storage_hi',
            'expert_advice_en',
            'expert_advice_hi',
            'when_to_contact_doctor_en',
            'when_to_contact_doctor_hi',
            'faqs_json',
            'source_references_json',
            'meta_title_en',
            'meta_title_hi',
            'meta_description_en',
            'meta_description_hi',
            'reviewed_by',
            'last_reviewed_at',
            'ai_generated',
            'medically_reviewed',
            'review_status',
            'is_published',
            'created_by',
            'updated_by',
            'updated_at',
        ];
    }

    private function medicines(): iterable
    {
        yield from [
            [
                'name' => 'Paracetamol',
                'slug' => 'paracetamol',
                'generic_name' => 'Acetaminophen',
                'brand_names_json' => ['Dolo 650', 'Crocin', 'Calpol', 'Pacimol'],
                'composition' => 'Paracetamol IP',
                'strength' => '500 mg / 650 mg',
                'medicine_type' => 'Tablet / Syrup',
                'category' => 'Pain relief and fever',
                'prescription_required' => false,
                'purpose_en' => 'General educational information for fever reduction and mild to moderate pain relief.',
                'purpose_hi' => 'बुखार कम करने और हल्के से मध्यम दर्द में सामान्य शैक्षणिक जानकारी।',
                'overview_en' => 'Paracetamol is commonly used for fever and pain relief. It may be considered for short-term symptomatic relief, but the right use depends on age, dose, liver health, and other medicines.',
                'overview_hi' => 'पैरासिटामोल बुखार और दर्द में आमतौर पर उपयोग की जाने वाली दवा है। इसका सही उपयोग उम्र, मात्रा, लिवर की स्थिति और अन्य दवाओं पर निर्भर करता है।',
                'uses_en' => 'May be used for fever, body ache, headache, toothache, joint pain, or mild pain when advised appropriately.',
                'uses_hi' => 'उचित सलाह मिलने पर बुखार, बदन दर्द, सिरदर्द, दांत दर्द, जोड़ों के दर्द या हल्के दर्द में उपयोग किया जा सकता है।',
                'benefits_en' => 'Can help reduce fever and improve comfort while the underlying cause is being assessed.',
                'benefits_hi' => 'मूल कारण की जांच के दौरान बुखार कम करने और आराम देने में मदद कर सकती है।',
                'dosage_information_en' => 'Dosage depends on age, weight, liver health, total daily intake, and professional advice. Standard adult dose is 500mg to 650mg every 4-6 hours, not exceeding 4g daily.',
                'dosage_information_hi' => 'खुराक उम्र, वजन, लिवर की स्थिति, कुल दैनिक मात्रा और डॉक्टर की सलाह पर निर्भर करती है। सामान्य वयस्कों के लिए खुराक 500mg से 650mg हर 4-6 घंटे में है, दैनिक 4g से अधिक न लें।',
                'mechanism_en' => 'It works by helping reduce pain signals and fever response in the body by inhibiting prostaglandin synthesis in the brain.',
                'mechanism_hi' => 'यह मस्तिष्क में प्रोस्टाग्लैंडीन संश्लेषण को रोककर शरीर में दर्द के संकेत और बुखार की प्रतिक्रिया को कम करने में मदद करती है।',
                'common_side_effects_en' => 'Side effects are uncommon at usual doses but may include nausea, skin rash, or stomach discomfort in some people.',
                'common_side_effects_hi' => 'सामान्य मात्रा में दुष्प्रभाव कम होते हैं, लेकिन कुछ लोगों में मतली, त्वचा पर लाल चकत्ते या पेट में असहजता हो सकती है।',
                'serious_side_effects_en' => 'Too much paracetamol can seriously harm the liver. Seek urgent help for overdose, confusion, vomiting, or unusual sleepiness.',
                'serious_side_effects_hi' => 'अधिक मात्रा में पैरासिटामोल लिवर को गंभीर नुकसान पहुंचा सकती है। ओवरडोज, उल्टी, भ्रम या बहुत ज्यादा नींद आने पर तुरंत मदद लें।',
                'drug_interactions_en' => 'Can interact with blood thinners like warfarin, other pain relievers, and liver-affecting drugs.',
                'drug_interactions_hi' => 'वारफेरिन जैसे रक्त को पतला करने वाले पदार्थों, अन्य दर्द निवारकों और लिवर को प्रभावित करने वाली दवाओं के साथ परस्पर क्रिया कर सकती है।',
                'food_interactions_en' => 'Taking with high carbohydrate foods may slightly delay its absorption.',
                'food_interactions_hi' => 'उच्च कार्बोहाइड्रेट वाले खाद्य पदार्थों के साथ लेने पर इसके अवशोषण में थोड़ी देरी हो सकती है।',
                'alcohol_warning_en' => 'Alcohol can increase liver risk. Ask a doctor or pharmacist before use if you drink regularly.',
                'alcohol_warning_hi' => 'शराब लिवर के जोखिम को बढ़ा सकती है। यदि आप नियमित रूप से शराब लेते हैं, तो उपयोग से पहले डॉक्टर या फार्मासिस्ट से पूछें।',
                'pregnancy_warning_en' => 'Pregnancy safety depends on the situation and doctor advice. Generally considered safe at low doses for short durations under guidance.',
                'pregnancy_warning_hi' => 'गर्भावस्था में सुरक्षा स्थिति और डॉक्टर की सलाह पर निर्भर करती है। आमतौर पर मार्गदर्शन में कम अवधि के लिए कम खुराक पर सुरक्षित माना जाता है।',
                'breastfeeding_warning_en' => 'Excreted in breast milk in small amounts. Breastfeeding use should still be discussed if the medicine is needed often.',
                'breastfeeding_warning_hi' => 'स्तनपान के दौरान कम मात्रा में दूध में उत्सर्जित होती है। यदि दवा अक्सर चाहिए, तो डॉक्टर से चर्चा करें।',
                'kidney_warning_en' => 'Caution needed in severe kidney impairment. Dose adjustment may be advised.',
                'kidney_warning_hi' => 'गंभीर किडनी रोग में सावधानी की आवश्यकता है। खुराक समायोजन की सलाह दी जा सकती है।',
                'liver_warning_en' => 'Use extra caution in liver disease or if other liver-impacting medicines are being taken.',
                'liver_warning_hi' => 'लिवर की बीमारी होने पर या लिवर पर असर डालने वाली अन्य दवाएं चल रही हों तो अतिरिक्त सावधानी रखें।',
                'driving_warning_en' => 'Generally does not affect your ability to drive or operate machinery.',
                'driving_warning_hi' => 'आमतौर पर ड्राइव करने या मशीनरी चलाने की आपकी क्षमता को प्रभावित नहीं करता है।',
                'allergy_warning_en' => 'Avoid if you have had an allergic reaction to paracetamol before, which may present as swelling or breathing trouble.',
                'allergy_warning_hi' => 'यदि पहले पैरासिटामोल से एलर्जी हुई हो तो इसका उपयोग न करें, जिससे सूजन या सांस लेने में तकलीफ हो सकती है।',
                'precautions_en' => 'Read combination cold-and-flu labels carefully to avoid accidental duplicate intake.',
                'precautions_hi' => 'गलती से दोहरी मात्रा लेने से बचने के लिए कॉम्बिनेशन सर्दी-जुकाम वाली दवाओं के लेबल ध्यान से पढ़ें।',
                'contraindications_en' => 'Contraindicated in patients with severe active liver disease or hypersensitivity to the drug.',
                'contraindications_hi' => 'गंभीर सक्रिय लिवर रोग या दवा के प्रति अतिसंवेदनशीलता वाले रोगियों में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have severe liver failure, or are allergic to paracetamol.',
                'avoid_if_hi' => 'यदि आपको गंभीर लिवर विफलता है, या पैरासिटामोल से एलर्जी है तो बचें।',
                'missed_dose_en' => 'If it was advised on a schedule, take it as soon as you remember. Skip if it is close to the next dose. Do not double the dose.',
                'missed_dose_hi' => 'यदि इसे तय समय पर लेने की सलाह दी गई थी, तो याद आते ही लें। यदि अगली खुराक का समय हो गया हो तो छोड़ दें। खुराक दोगुनी न लें।',
                'overdose_en' => 'Overdose can be dangerous even if you feel well at first. Seek emergency medical help immediately.',
                'overdose_hi' => 'ओवरडोज शुरू में सामान्य लगने पर भी खतरनाक हो सकती है। तुरंत आपातकालीन चिकित्सा सहायता लें।',
                'storage_en' => 'Store at room temperature below 30°C, away from direct sunlight and moisture. Keep away from children.',
                'storage_hi' => 'सीधे धूप और नमी से दूर, 30°C से नीचे कमरे के तापमान पर स्टोर करें। बच्चों से दूर रखें।',
                'expert_advice_en' => 'Repeated fever or pain needs medical review instead of repeated self-medication.',
                'expert_advice_hi' => 'बार-बार बुखार या दर्द होने पर बार-बार स्वयं दवा लेने के बजाय डॉक्टर से जांच कराएं।',
                'when_to_contact_doctor_en' => 'Contact a doctor if fever persists for more than 3 days, pain lasts more than 5 days, or overdose is suspected.',
                'when_to_contact_doctor_hi' => 'यदि बुखार 3 दिनों से अधिक बना रहे, दर्द 5 दिनों से अधिक रहे, या ओवरडोज का संदेह हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Is it an antibiotic?', 'answer' => 'No. Paracetamol is not an antibiotic.'],
                    ['question' => 'Can I use more than one fever medicine together?', 'answer' => 'Do not combine medicines without checking with a doctor or pharmacist.'],
                ],
                'source_references_json' => ['WHO Guidelines', 'IAP Pediatric Drug Directory'],
                'meta_title_en' => 'Paracetamol: Uses, Side Effects, Dosage Info & Precautions',
                'meta_title_hi' => 'पैरासिटामोल: उपयोग, दुष्प्रभाव और सावधानियां',
                'meta_description_en' => 'General medicine information for paracetamol including uses, side effects, warnings, and when to contact a doctor.',
                'meta_description_hi' => 'पैरासिटामोल के उपयोग, दुष्प्रभाव, चेतावनी और डॉक्टर से कब संपर्क करें, इसकी सामान्य जानकारी।',
                'reviewed_by' => 'Dr. Ramesh Kumar',
                'last_reviewed_at' => '2026-05-10 10:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Azithromycin',
                'slug' => 'azithromycin',
                'generic_name' => 'Azithromycin',
                'brand_names_json' => ['Azithral', 'Azee', 'Aziwok', 'Zithrox'],
                'composition' => 'Azithromycin Dihydrate',
                'strength' => '250 mg / 500 mg',
                'medicine_type' => 'Tablet / Suspension',
                'category' => 'Antibiotic',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for a prescription antibiotic used only when a qualified clinician advises it.',
                'purpose_hi' => 'यह एक प्रिस्क्रिप्शन एंटीबायोटिक है, जिसका उपयोग केवल योग्य डॉक्टर की सलाह पर किया जाना चाहिए।',
                'overview_en' => 'Azithromycin is a macrolide antibiotic. It does not help against every infection (like viral colds) and should not be started without medical advice.',
                'overview_hi' => 'एज़िथ्रोमाइसिन एक मैक्रोलाइड एंटीबायोटिक है। यह हर संक्रमण (जैसे वायरल सर्दी) में काम नहीं करती और बिना डॉक्टर की सलाह के शुरू नहीं करनी चाहिए।',
                'uses_en' => 'May be prescribed for certain bacterial infections of the respiratory tract, skin, ears, and sexually transmitted infections.',
                'uses_hi' => 'श्वसन तंत्र, त्वचा, कान के कुछ बैक्टीरियल संक्रमणों और यौन संचारित संक्रमणों में डॉक्टर इसे लिख सकते हैं।',
                'benefits_en' => 'Helps clear bacterial infections by stopping the growth and multiplication of bacteria.',
                'benefits_hi' => 'बैक्टीरिया के विकास और गुणन को रोककर बैक्टीरियल संक्रमण को समाप्त करने में मदद करती है।',
                'dosage_information_en' => 'Antibiotic dose and duration vary by infection, age, weight, and kidney or liver status. Usually taken once daily for 3 to 5 days.',
                'dosage_information_hi' => 'एंटीबायोटिक की खुराक और अवधि संक्रमण, उम्र, वजन और किडनी/लिवर की स्थिति पर निर्भर करती है। आमतौर पर 3 से 5 दिनों के लिए दिन में एक बार ली जाती है।',
                'mechanism_en' => 'Prevents bacterial protein synthesis by binding to the 50S ribosomal subunit of susceptible microorganisms.',
                'mechanism_hi' => 'यह संवेदनशील सूक्ष्मजीवों के 50S राइबोसोमल सबयूनिट से जुड़कर बैक्टीरिया के प्रोटीन संश्लेषण को रोकती है।',
                'common_side_effects_en' => 'Possible side effects include nausea, loose motions, stomach upset, vomiting, or altered taste.',
                'common_side_effects_hi' => 'मतली, दस्त, पेट खराब होना, उल्टी या स्वाद बदलना जैसे दुष्प्रभाव हो सकते हैं।',
                'serious_side_effects_en' => 'Severe allergy, persistent watery diarrhoea, palpitations, prolonged QT interval, or yellowing of eyes/skin need urgent medical attention.',
                'serious_side_effects_hi' => 'गंभीर एलर्जी, लगातार पतले दस्त, दिल की धड़कन का असामान्य लगना, क्यूटी अंतराल बढ़ना या आंख/त्वचा पीली पड़ना तुरंत चिकित्सा सहायता की जरूरत है।',
                'drug_interactions_en' => 'Interactions can happen with antacids, heart-rhythm medicines (like amiodarone), digoxin, and warfarin.',
                'drug_interactions_hi' => 'एंटासिड, दिल की धड़कन की दवाओं (जैसे एमियोडैरोन), डिगॉक्सिन और वारफेरिन के साथ इंटरैक्शन हो सकता है।',
                'food_interactions_en' => 'Can be taken with or without food, but taking with food may reduce stomach upset.',
                'food_interactions_hi' => 'इसे भोजन के साथ या बिना लिया जा सकता है, लेकिन भोजन के साथ लेने से पेट की खराबी कम हो सकती है।',
                'alcohol_warning_en' => 'Avoid alcohol as it may worsen stomach side effects and cause dehydration or liver strain.',
                'alcohol_warning_hi' => 'शराब से बचें क्योंकि यह पेट के दुष्प्रभावों को बढ़ा सकती है और निर्जलीकरण या लिवर पर दबाव डाल सकती है।',
                'pregnancy_warning_en' => 'Use in pregnancy should be clinician-guided. Only used if clearly needed.',
                'pregnancy_warning_hi' => 'गर्भावस्था में उपयोग डॉक्टर की सलाह पर होना चाहिए। केवल स्पष्ट आवश्यकता होने पर उपयोग किया जाता है।',
                'breastfeeding_warning_en' => 'Passes into breast milk. May cause diarrhea or rash in infants. Discuss with your pediatrician.',
                'breastfeeding_warning_hi' => 'स्तनपान के दौरान दूध में मिल सकती है। शिशुओं में दस्त या लाल चकत्ते हो सकते हैं। बाल रोग विशेषज्ञ से चर्चा करें।',
                'kidney_warning_en' => 'Use with caution in patients with severe renal impairment.',
                'kidney_warning_hi' => 'गंभीर किडनी रोग से पीड़ित रोगियों में सावधानी के साथ प्रयोग करें।',
                'liver_warning_en' => 'Mainly metabolized by the liver; avoid or use with caution in patients with liver impairment.',
                'liver_warning_hi' => 'मुख्य रूप से लिवर द्वारा मेटाबोलाइज्ड होता है; लिवर की खराबी वाले रोगियों में इससे बचें या सावधानी से उपयोग करें।',
                'driving_warning_en' => 'May cause dizziness or tiredness. Avoid driving if affected.',
                'driving_warning_hi' => 'इससे चक्कर या थकान हो सकती है। प्रभावित होने पर गाड़ी चलाने से बचें।',
                'allergy_warning_en' => 'Do not take if you are allergic to azithromycin, erythromycin, or other macrolide antibiotics.',
                'allergy_warning_hi' => 'यदि आपको एज़िथ्रोमाइसिन, एरीथ्रोमाइसिन, या अन्य मैक्रोलाइड एंटीबायोटिक दवाओं से एलर्जी है तो न लें।',
                'precautions_en' => 'Finish the full prescribed course even if symptoms disappear. Do not self-start leftover pills.',
                'precautions_hi' => 'लक्षण गायब होने पर भी पूरा निर्धारित कोर्स समाप्त करें। बची हुई गोलियां खुद से शुरू न करें।',
                'contraindications_en' => 'Contraindicated in history of cholestatic jaundice/hepatic dysfunction associated with prior use of azithromycin.',
                'contraindications_hi' => 'एज़िथ्रोमाइसिन के पिछले उपयोग से जुड़े कोलेस्टेटिक पीलिया/हेपेटिक डिसफंक्शन के इतिहास में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have cardiac issues like arrhythmia or QT prolongation.',
                'avoid_if_hi' => 'यदि आपको अतालता या क्यूटी प्रोलोगेशन जैसी हृदय संबंधी समस्याएं हैं तो बचें।',
                'missed_dose_en' => 'Take the missed dose as soon as you remember. If it is almost time for the next dose, skip the missed one.',
                'missed_dose_hi' => 'याद आते ही छूटी हुई खुराक लें। यदि अगली खुराक का समय हो गया हो, तो छूटी हुई खुराक छोड़ दें।',
                'overdose_en' => 'Seek urgent medical help if too much has been taken. Symptoms may include severe nausea, vomiting, or diarrhea.',
                'overdose_hi' => 'अधिक मात्रा लेने पर तुरंत चिकित्सा सहायता लें। लक्षणों में गंभीर मतली, उल्टी या दस्त शामिल हो सकते हैं।',
                'storage_en' => 'Store below 30°C in a dry place. Keep container tightly closed and out of reach of children.',
                'storage_hi' => 'सूखी जगह में 30 डिग्री सेल्सियस से नीचे स्टोर करें। कंटेनर को कसकर बंद रखें और बच्चों की पहुंच से दूर रखें।',
                'expert_advice_en' => 'Antibiotics treat bacterial infections, not viral infections like flu or cold. Overuse leads to resistance.',
                'expert_advice_hi' => 'एंटीबायोटिक्स बैक्टीरियल संक्रमणों का इलाज करते हैं, फ्लू या सर्दी जैसे वायरल संक्रमणों का नहीं। अत्यधिक उपयोग से प्रतिरोधकता बढ़ती है।',
                'when_to_contact_doctor_en' => 'Contact your doctor if symptoms worsen, severe watery or bloody diarrhoea develops, or you notice shortness of breath.',
                'when_to_contact_doctor_hi' => 'यदि लक्षण बिगड़ें, गंभीर पानी जैसे या खूनी दस्त विकसित हों, या सांस फूलने लगे तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Should I take it on an empty stomach?', 'answer' => 'It can be taken with or without food. Taking with food helps reduce stomach upset.'],
                    ['question' => 'Can I stop it when I feel better?', 'answer' => 'No. Always complete the entire course prescribed by your doctor.'],
                ],
                'source_references_json' => ['FDA Approved Labels', 'CDSCO Guidelines'],
                'meta_title_en' => 'Azithromycin: Uses, Side Effects & Precautions',
                'meta_title_hi' => 'एज़िथ्रोमाइसिन: उपयोग, दुष्प्रभाव और सावधानियां',
                'meta_description_en' => 'General educational information for azithromycin including uses, side effects, and antibiotic safety warnings.',
                'meta_description_hi' => 'एज़िथ्रोमाइसिन की सामान्य शैक्षणिक जानकारी, उपयोग, दुष्प्रभाव और एंटीबायोटिक सुरक्षा चेतावनियां।',
                'reviewed_by' => 'Dr. Sarah Smith',
                'last_reviewed_at' => '2026-04-12 12:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Cetirizine',
                'slug' => 'cetirizine',
                'generic_name' => 'Cetirizine Hydrochloride',
                'brand_names_json' => ['Cetzine', 'Okacet', 'Alerid', 'Zyrtec'],
                'composition' => 'Cetirizine Hydrochloride IP',
                'strength' => '10 mg',
                'medicine_type' => 'Tablet / Syrup',
                'category' => 'Allergy relief',
                'prescription_required' => false,
                'purpose_en' => 'General educational information for allergy symptom relief.',
                'purpose_hi' => 'एलर्जी के लक्षणों में राहत के लिए सामान्य शैक्षणिक जानकारी।',
                'overview_en' => 'Cetirizine is a second-generation antihistamine used for allergy-related symptoms such as sneezing, itching, watery eyes, or runny nose.',
                'overview_hi' => 'सिट्रीजिन एक दूसरी पीढ़ी की एंटीहिस्टामाइन दवा है जिसका उपयोग छींकने, खुजली, आंखों में पानी आने या नाक बहने जैसे एलर्जी के लक्षणों के लिए किया जाता है।',
                'uses_en' => 'Used to relieve symptoms of hay fever, seasonal allergies, hives, and allergic skin reactions.',
                'uses_hi' => 'हे फीवर, मौसमी एलर्जी, पित्ती और त्वचा पर एलर्जी की प्रतिक्रिया के लक्षणों को दूर करने के लिए उपयोग किया जाता है।',
                'benefits_en' => 'Provides quick, 24-hour relief from allergy symptoms with lower drowsiness than first-generation antihistamines.',
                'benefits_hi' => 'पहली पीढ़ी की एंटीहिस्टामाइन दवाओं की तुलना में कम उनींदेपन के साथ एलर्जी के लक्षणों से त्वरित, 24 घंटे की राहत प्रदान करती है।',
                'dosage_information_en' => 'Typically 5mg to 10mg once daily for adults and children over 6 years. Do not exceed recommended dosage.',
                'dosage_information_hi' => 'आमतौर पर वयस्कों और 6 वर्ष से अधिक उम्र के बच्चों के लिए दिन में एक बार 5mg से 10mg। अनुशंसित खुराक से अधिक न लें।',
                'mechanism_en' => 'Blocks histamine, a natural substance in the body that triggers allergic responses.',
                'mechanism_hi' => 'यह हिस्टामाइन को रोकता है, जो शरीर में एलर्जी की प्रतिक्रिया को ट्रिगर करने वाला एक प्राकृतिक पदार्थ है।',
                'common_side_effects_en' => 'Some people may experience drowsiness, dry mouth, tiredness, headache, or sore throat.',
                'common_side_effects_hi' => 'कुछ लोगों को उनींदापन, मुंह सूखना, थकान, सिरदर्द या गले में खराश महसूस हो सकती है।',
                'serious_side_effects_en' => 'Serious side effects are rare but can include difficulty urinating, vision changes, or severe allergic swelling.',
                'serious_side_effects_hi' => 'गंभीर दुष्प्रभाव दुर्लभ हैं लेकिन इसमें पेशाब करने में कठिनाई, दृष्टि में परिवर्तन या गंभीर एलर्जी सूजन शामिल हो सकती है।',
                'drug_interactions_en' => 'Caution with central nervous system depressants, sedatives, and sleep medicines.',
                'drug_interactions_hi' => 'केंद्रीय तंत्रिका तंत्र को दबाने वाली दवाओं, शामक और नींद की दवाओं के साथ सावधानी बरतें।',
                'food_interactions_en' => 'Can be taken with or without food. Avoid grapefruit juice.',
                'food_interactions_hi' => 'इसे भोजन के साथ या बिना लिया जा सकता है। अंगूर के रस से बचें।',
                'alcohol_warning_en' => 'Avoid alcohol as it may significantly increase drowsiness and impair concentration.',
                'alcohol_warning_hi' => 'शराब से बचें क्योंकि यह उनींदापन बढ़ा सकती है और ध्यान केंद्रित करने में बाधा उत्पन्न कर सकती है।',
                'pregnancy_warning_en' => 'Consult a doctor before use during pregnancy; generally considered safe but used only when necessary.',
                'pregnancy_warning_hi' => 'गर्भावस्था के दौरान उपयोग करने से पहले डॉक्टर से सलाह लें; आमतौर पर सुरक्षित माना जाता है लेकिन आवश्यक होने पर ही उपयोग किया जाता है।',
                'breastfeeding_warning_en' => 'Excreted in breast milk. Consult your doctor before using while breastfeeding.',
                'breastfeeding_warning_hi' => 'यह स्तन के दूध में उत्सर्जित होती है। स्तनपान के दौरान उपयोग करने से पहले अपने डॉक्टर से सलाह लें।',
                'kidney_warning_en' => 'Dose reduction or avoidance may be necessary in patients with moderate to severe renal impairment.',
                'kidney_warning_hi' => 'मध्यम से गंभीर किडनी रोग से पीड़ित रोगियों में खुराक में कमी या बचाव आवश्यक हो सकता है।',
                'liver_warning_en' => 'No major adjustments usually needed, but consult your doctor if you have severe liver disease.',
                'liver_warning_hi' => 'आमतौर पर किसी बड़े समायोजन की आवश्यकता नहीं होती है, लेकिन गंभीर लिवर रोग होने पर डॉक्टर से सलाह लें।',
                'driving_warning_en' => 'If it makes you sleepy or dizzy, avoid driving or operating machinery.',
                'driving_warning_hi' => 'यदि इससे नींद या चक्कर आए तो ड्राइविंग या मशीनरी चलाने से बचें।',
                'allergy_warning_en' => 'Do not use if allergic to cetirizine, hydroxyzine, or levocetirizine.',
                'allergy_warning_hi' => 'यदि सिट्रीजिन, हाइड्रोक्सीजाइन या लेवोसिट्रीजिन से एलर्जी है तो उपयोग न करें।',
                'precautions_en' => 'Use caution if you have urinary retention issues, enlarged prostate, or epilepsy.',
                'precautions_hi' => 'यदि आपको पेशाब रुकने की समस्या, बढ़ी हुई प्रोस्टेट ग्रंथि, या मिर्गी है तो सावधानी बरतें।',
                'contraindications_en' => 'Contraindicated in end-stage renal disease patients on hemodialysis.',
                'contraindications_hi' => 'हेमोडायलिसिस वाले अंतिम चरण के किडनी रोग के रोगियों में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have severe kidney failure (CrCl < 10 ml/min).',
                'avoid_if_hi' => 'यदि आपको गंभीर किडनी विफलता (CrCl < 10 ml/min) है तो बचें।',
                'missed_dose_en' => 'Take the missed dose as soon as you remember, or skip it if it is almost time for the next dose.',
                'missed_dose_hi' => 'याद आते ही छूटी हुई खुराक लें, या अगली खुराक का समय होने वाला हो तो छोड़ दें।',
                'overdose_en' => 'Overdose can cause extreme drowsiness in adults and agitation followed by drowsiness in children. Contact a doctor.',
                'overdose_hi' => 'ओवरडोज से वयस्कों में अत्यधिक उनींदापन और बच्चों में बेचैनी के बाद उनींदापन हो सकता है। डॉक्टर से संपर्क करें।',
                'storage_en' => 'Store below 25°C in a dry place. Do not freeze liquid forms.',
                'storage_hi' => 'सूखी जगह में 25 डिग्री सेल्सियस से नीचे स्टोर करें। तरल रूपों को फ्रीज न करें।',
                'expert_advice_en' => 'Taking it at bedtime may help manage daytime drowsiness.',
                'expert_advice_hi' => 'इसे सोते समय लेने से दिन के उनींदेपन को प्रबंधित करने में मदद मिल सकती है।',
                'when_to_contact_doctor_en' => 'Contact a doctor if allergy symptoms persist, breathing problems develop, or severe skin allergy occurs.',
                'when_to_contact_doctor_hi' => 'यदि एलर्जी के लक्षण बने रहें, सांस की समस्या विकसित हो, या गंभीर त्वचा एलर्जी हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Does it cause drowsiness?', 'answer' => 'Yes, although it is a second-generation antihistamine and causes less drowsiness than older ones, it can still affect some users.'],
                    ['question' => 'Can children take cetirizine?', 'answer' => 'Yes, in appropriate liquid dosages recommended by a pediatrician.'],
                ],
                'source_references_json' => ['NIH Drug Information', 'EMA Drug Safety Reports'],
                'meta_title_en' => 'Cetirizine: Allergy Relief, Uses, Side Effects',
                'meta_title_hi' => 'सिट्रीजिन: एलर्जी राहत, उपयोग, दुष्प्रभाव',
                'meta_description_en' => 'General educational information for cetirizine including uses, side effects, and allergy symptom relief tips.',
                'meta_description_hi' => 'सिट्रीजिन की सामान्य शैक्षणिक जानकारी जिसमें उपयोग, दुष्प्रभाव और एलर्जी के लक्षणों में राहत के टिप्स शामिल हैं।',
                'reviewed_by' => 'Dr. Anil Sharma',
                'last_reviewed_at' => '2026-03-15 09:30:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Pantoprazole',
                'slug' => 'pantoprazole',
                'generic_name' => 'Pantoprazole Sodium',
                'brand_names_json' => ['Pantocid', 'Pan 40', 'Pantodac', 'Pan-D'],
                'composition' => 'Pantoprazole Sodium Sesquihydrate',
                'strength' => '20 mg / 40 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Acidity and reflux',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for acid reduction medicines used in reflux and related conditions.',
                'purpose_hi' => 'एसिड कम करने वाली दवाओं की सामान्य जानकारी, जो रिफ्लक्स और संबंधित स्थितियों में उपयोग की जाती हैं।',
                'overview_en' => 'Pantoprazole is a proton pump inhibitor (PPI) that reduces stomach acid production. Long-term or repeated use should be medically supervised.',
                'overview_hi' => 'पैंटोप्राज़ोल एक प्रोटॉन पंप अवरोधक (PPI) है जो पेट के एसिड उत्पादन को कम करता है। लंबे समय तक या बार-बार उपयोग की डॉक्टर से समीक्षा होनी चाहिए।',
                'uses_en' => 'Used to treat gastroesophageal reflux disease (GERD), stomach ulcers, and conditions with excess stomach acid like Zollinger-Ellison syndrome.',
                'uses_hi' => 'गैस्ट्रोएसोफेगल रिफ्लक्स रोग (GERD), पेट के अल्सर और ज़ोलिंगर-एलिसन सिंड्रोम जैसी अतिरिक्त पेट के एसिड वाली स्थितियों के इलाज के लिए उपयोग किया जाता है।',
                'benefits_en' => 'Allows esophageal healing and prevents damage caused by acid reflux, relieving heartburn symptoms.',
                'benefits_hi' => 'यह एसोफैगल को ठीक होने देता है और एसिड रिफ्लक्स से होने वाले नुकसान को रोकता है, जिससे सीने में जलन के लक्षणों में राहत मिलती है।',
                'dosage_information_en' => 'Usually taken once daily in the morning, 1 hour before breakfast. Swallow whole; do not crush or chew.',
                'dosage_information_hi' => 'आमतौर पर सुबह नाश्ते से 1 घंटा पहले दिन में एक बार ली जाती है। पूरी निगलें; कुचलें या चबाएं नहीं।',
                'mechanism_en' => 'Inhibits the H+/K+-ATPase enzyme system (proton pump) in gastric parietal cells, blocking the final step of acid secretion.',
                'mechanism_hi' => 'यह गैस्ट्रिक पार्श्विका कोशिकाओं में H+/K+-ATPase एंजाइम प्रणाली (प्रोटॉन पंप) को रोकता है, जिससे एसिड स्राव के अंतिम चरण को अवरुद्ध किया जाता है।',
                'common_side_effects_en' => 'Common side effects include headache, diarrhea, stomach pain, flatulence, dizziness, or joint pain.',
                'common_side_effects_hi' => 'सामान्य दुष्प्रभावों में सिरदर्द, दस्त, पेट दर्द, गैस बनना, चक्कर आना या जोड़ों का दर्द शामिल हैं।',
                'serious_side_effects_en' => 'Severe side effects include kidney inflammation, severe diarrhea (C. diff), vitamin B12 deficiency (long-term), or low magnesium levels.',
                'serious_side_effects_hi' => 'गंभीर दुष्प्रभावों में किडनी की सूजन, गंभीर दस्त, विटामिन बी12 की कमी (लंबे समय तक उपयोग पर), या कम मैग्नीशियम स्तर शामिल हैं।',
                'drug_interactions_en' => 'Can interfere with ketoconazole, iron salts, atazanavir, and blood thinners like warfarin.',
                'drug_interactions_hi' => 'यह कीटोकोनाज़ोल, आयरन लवण, अताज़ानावीर और वारफेरिन जैसे रक्त को पतला करने वाले पदार्थों के साथ हस्तक्षेप कर सकता है।',
                'food_interactions_en' => 'Best taken 1 hour before a meal, usually breakfast, to ensure maximum efficacy.',
                'food_interactions_hi' => 'अधिकतम प्रभावकारिता सुनिश्चित करने के लिए भोजन, आमतौर पर नाश्ते से 1 घंटा पहले लेना सबसे अच्छा है।',
                'alcohol_warning_en' => 'Avoid alcohol as it increases stomach acid production and can worsen your reflux symptoms.',
                'alcohol_warning_hi' => 'शराब से बचें क्योंकि यह पेट में एसिड का उत्पादन बढ़ाती है और रिफ्लक्स के लक्षणों को बदतर बना सकती है।',
                'pregnancy_warning_en' => 'Use during pregnancy only if clearly needed and recommended by a doctor.',
                'pregnancy_warning_hi' => 'गर्भावस्था के दौरान केवल तभी उपयोग करें जब स्पष्ट रूप से आवश्यक हो और डॉक्टर द्वारा अनुशंसित हो।',
                'breastfeeding_warning_en' => 'Passes into breast milk. Benefits and risks should be discussed with a healthcare provider.',
                'breastfeeding_warning_hi' => 'यह स्तन के दूध में मिल सकती है। इसके लाभों और जोखिमों पर स्वास्थ्य सेवा प्रदाता के साथ चर्चा की जानी चाहिए।',
                'kidney_warning_en' => 'Generally safe, but acute interstitial nephritis (kidney inflammation) has been reported.',
                'kidney_warning_hi' => 'आमतौर पर सुरक्षित है, लेकिन तीव्र इंटरस्टिशियल नेफ्रैटिस (किडनी की सूजन) की सूचना मिली है।',
                'liver_warning_en' => 'Dose adjustments or monitoring may be needed in patients with severe liver impairment.',
                'liver_warning_hi' => 'गंभीर लिवर रोग वाले रोगियों में खुराक समायोजन या निगरानी की आवश्यकता हो सकती है।',
                'driving_warning_en' => 'Generally safe to drive unless you experience side effects like dizziness or blurred vision.',
                'driving_warning_hi' => 'जब तक आपको चक्कर या धुंधली दृष्टि जैसे दुष्प्रभाव महसूस न हों, ड्राइव करना आमतौर पर सुरक्षित है।',
                'allergy_warning_en' => 'Do not take if allergic to pantoprazole or other proton pump inhibitors.',
                'allergy_warning_hi' => 'यदि पैंटोप्राज़ोल या अन्य प्रोटॉन पंप अवरोधकों से एलर्जी है तो न लें।',
                'precautions_en' => 'Long term use may increase risk of bone fractures and magnesium deficiency. Take calcium/magnesium supplements if advised.',
                'precautions_hi' => 'लंबे समय तक उपयोग से हड्डियों के टूटने और मैग्नीशियम की कमी का खतरा बढ़ सकता है। सलाह दिए जाने पर कैल्शियम/मैग्नीशियम सप्लीमेंट लें।',
                'contraindications_en' => 'Hypersensitivity to active substances or any excipient.',
                'contraindications_hi' => 'सक्रिय पदार्थों या किसी भी उत्तेजक पदार्थ के प्रति अतिसंवेदनशीलता।',
                'avoid_if_en' => 'Avoid if you have osteoporosis risk without proper calcium management, or hypomagnesemia.',
                'avoid_if_hi' => 'यदि आपको उचित कैल्शियम प्रबंधन के बिना ऑस्टियोपोरोसिस का खतरा है, या हाइपोमैग्नेसीमिया है तो बचें।',
                'missed_dose_en' => 'Take it as soon as you remember. Skip it if it is almost time for the next dose. Do not double the dose.',
                'missed_dose_hi' => 'जैसे ही आपको याद आए, इसे लें। यदि अगली खुराक का समय हो गया हो तो छोड़ दें। खुराक दोगुनी न लें।',
                'overdose_en' => 'Overdoses are rare. Seek medical help if severe symptoms develop after accidental high dose.',
                'overdose_hi' => 'ओवरडोज़ दुर्लभ हैं। गलती से अधिक मात्रा लेने के बाद गंभीर लक्षण विकसित होने पर चिकित्सा सहायता लें।',
                'storage_en' => 'Store at room temperature below 30°C. Protect from moisture.',
                'storage_hi' => '30 डिग्री सेल्सियस से नीचे कमरे के तापमान पर स्टोर करें। नमी से बचाएं।',
                'expert_advice_en' => 'Lifestyle changes like avoiding late-night meals and spicy foods can help manage acid reflux.',
                'expert_advice_hi' => 'देर रात के भोजन और मसालेदार भोजन से बचने जैसे जीवनशैली में बदलाव एसिड रिफ्लक्स को प्रबंधित करने में मदद कर सकते हैं।',
                'when_to_contact_doctor_en' => 'Contact doctor if you experience difficulty swallowing, unexplained weight loss, or persistent vomiting.',
                'when_to_contact_doctor_hi' => 'यदि आपको निगलने में कठिनाई, बिना कारण वजन घटने या लगातार उल्टी होने का अनुभव हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Can I take it after meals?', 'answer' => 'For best results, take it 1 hour before a meal, preferably in the morning.'],
                    ['question' => 'Is it safe for long term use?', 'answer' => 'Long term use (more than a year) should be monitored by a doctor due to potential side effects like bone thinning.'],
                ],
                'source_references_json' => ['Mayo Clinic', 'British National Formulary (BNF)'],
                'meta_title_en' => 'Pantoprazole: GERD Treatment, Uses & Side Effects',
                'meta_title_hi' => 'पैंटोप्राज़ोल: जीईआरडी उपचार, उपयोग और दुष्प्रभाव',
                'meta_description_en' => 'Learn about Pantoprazole, its uses in treating acidity, acid reflux, dosage guidelines, and precautions.',
                'meta_description_hi' => 'पैंटोप्राज़ोल के बारे में जानें, एसिडिटी, एसिड रिफ्लक्स के इलाज में इसके उपयोग, खुराक के निर्देश और सावधानियां।',
                'reviewed_by' => 'Dr. K. K. Aggarwal',
                'last_reviewed_at' => '2026-02-28 14:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Metformin',
                'slug' => 'metformin',
                'generic_name' => 'Metformin Hydrochloride',
                'brand_names_json' => ['Glycomet', 'Glyciphage', 'Metformin SR', 'Obimet'],
                'composition' => 'Metformin Hydrochloride IP',
                'strength' => '500 mg / 850 mg / 1000 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Diabetes',
                'prescription_required' => true,
                'purpose_en' => 'Educational information for a prescription medicine used in diabetes care plans.',
                'purpose_hi' => 'मधुमेह देखभाल योजना में उपयोग होने वाली प्रिस्क्रिप्शन दवा की सामान्य जानकारी।',
                'overview_en' => 'Metformin is a first-line oral medication for type 2 diabetes. It helps control blood sugar levels under medical supervision.',
                'overview_hi' => 'मेटफॉर्मिन टाइप 2 मधुमेह के लिए एक अग्रिम पंक्ति की मौखिक दवा है। यह डॉक्टर की निगरानी में रक्त शर्करा के स्तर को नियंत्रित करने में मदद करती है।',
                'uses_en' => 'Prescribed for managing type 2 diabetes mellitus, and sometimes used off-label for polycystic ovary syndrome (PCOS).',
                'uses_hi' => 'टाइप 2 मधुमेह मेलिटस के प्रबंधन के लिए निर्धारित, और कभी-कभी पॉलीसिस्टिक ओवरी सिंड्रोम (PCOS) के लिए ऑफ-लेबल उपयोग किया जाता है।',
                'benefits_en' => 'Lowers blood glucose levels, improves insulin sensitivity, and does not cause hypoglycemia (low blood sugar) when used alone.',
                'benefits_hi' => 'रक्त शर्करा के स्तर को कम करता है, इंसुलिन संवेदनशीलता में सुधार करता है, और अकेले उपयोग किए जाने पर हाइपोग्लाइसीमिया (निम्न रक्त शर्करा) का कारण नहीं बनता है।',
                'dosage_information_en' => 'Taken with meals to reduce stomach side effects. Dosage is individualized based on blood glucose response.',
                'dosage_information_hi' => 'पेट के दुष्प्रभावों को कम करने के लिए भोजन के साथ लिया जाता है। रक्त शर्करा की प्रतिक्रिया के आधार पर खुराक व्यक्तिगत होती है।',
                'mechanism_en' => 'Decreases hepatic glucose production, decreases intestinal absorption of glucose, and improves insulin sensitivity by increasing peripheral glucose uptake.',
                'mechanism_hi' => 'यह लिवर में ग्लूकोज उत्पादन को कम करता है, ग्लूकोज के आंतों के अवशोषण को कम करता है, और इंसुलिन संवेदनशीलता में सुधार करता है।',
                'common_side_effects_en' => 'Common issues include nausea, diarrhea, abdominal pain, bloating, or metallic taste in the mouth.',
                'common_side_effects_hi' => 'सामान्य समस्याओं में मतली, दस्त, पेट दर्द, सूजन या मुंह में धातु का स्वाद शामिल हैं।',
                'serious_side_effects_en' => 'Lactic acidosis is a rare but life-threatening side effect. Watch for deep/rapid breathing, muscle pain, or severe tiredness.',
                'serious_side_effects_hi' => 'लैक्टिक एसिडोसिस एक दुर्लभ लेकिन जीवन के लिए खतरा पैदा करने वाला दुष्प्रभाव है। गहरी/तेज सांस, मांसपेशियों में दर्द या गंभीर थकान पर ध्यान दें।',
                'drug_interactions_en' => 'Interacts with contrast dyes used in imaging, cimetidine, and certain heart medications.',
                'drug_interactions_hi' => 'इमेजिंग में उपयोग किए जाने वाले कंट्रास्ट डाई, सिमेटिडाइन और दिल की कुछ दवाओं के साथ इंटरैक्शन करता है।',
                'food_interactions_en' => 'Take with meals. Avoid high-fiber diets directly around dosing times if stomach upset occurs.',
                'food_interactions_hi' => 'भोजन के साथ लें। यदि पेट खराब हो तो खुराक के समय उच्च फाइबर वाले आहार से बचें।',
                'alcohol_warning_en' => 'Avoid excessive alcohol intake as it increases the risk of lactic acidosis and hypoglycemia.',
                'alcohol_warning_hi' => 'अत्यधिक शराब के सेवन से बचें क्योंकि यह लैक्टिक एसिडोसिस और हाइपोग्लाइसीमिया के खतरे को बढ़ाता है।',
                'pregnancy_warning_en' => 'Insulin is preferred during pregnancy, but metformin may be used under close specialist supervision.',
                'pregnancy_warning_hi' => 'गर्भावस्था के दौरान इंसुलिन को प्राथमिकता दी जाती है, लेकिन मेटफॉर्मिन का उपयोग विशेषज्ञ की देखरेख में किया जा सकता है।',
                'breastfeeding_warning_en' => 'Excreted in small amounts. Consult your doctor to weigh benefits against infant risks.',
                'breastfeeding_warning_hi' => 'यह कम मात्रा में उत्सर्जित होती है। शिशु के जोखिमों के खिलाफ लाभों को तोलने के लिए अपने डॉक्टर से सलाह लें।',
                'kidney_warning_en' => 'Kidney function is critical. Contraindicated in patients with severe renal impairment (eGFR < 30 ml/min).',
                'kidney_warning_hi' => 'किडनी का कार्य महत्वपूर्ण है। गंभीर किडनी रोग (eGFR < 30 ml/min) वाले रोगियों में वर्जित है।',
                'liver_warning_en' => 'Avoid in patients with active liver disease due to increased risk of lactic acidosis.',
                'liver_warning_hi' => 'लैक्टिक एसिडोसिस के बढ़ते खतरे के कारण सक्रिय लिवर रोग वाले रोगियों में इससे बचें।',
                'driving_warning_en' => 'Does not cause drowsiness. However, when used with other diabetes medications, monitor for low blood sugar.',
                'driving_warning_hi' => 'यह उनींदापन का कारण नहीं बनता है। हालाँकि, अन्य मधुमेह दवाओं के साथ उपयोग किए जाने पर, निम्न रक्त शर्करा की निगरानी करें।',
                'allergy_warning_en' => 'Do not take if you have known hypersensitivity to metformin hydrochloride.',
                'allergy_warning_hi' => 'यदि आपको मेटफॉर्मिन हाइड्रोक्लोराइड के प्रति अतिसंवेदनशीलता है तो न लें।',
                'precautions_en' => 'Regular kidney function monitoring (at least once a year) is recommended while on metformin.',
                'precautions_hi' => 'मेटफॉर्मिन पर रहने के दौरान नियमित किडनी समारोह की निगरानी (साल में कम से कम एक बार) की सिफारिश की जाती है।',
                'contraindications_en' => 'Contraindicated in severe renal failure, metabolic acidosis, and acute conditions like dehydration.',
                'contraindications_hi' => 'गंभीर किडनी विफलता, मेटाबॉलिक एसिडोसिस और निर्जलीकरण जैसी तीव्र स्थितियों में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have diabetic ketoacidosis, or severe kidney/liver disease.',
                'avoid_if_hi' => 'यदि आपको मधुमेह केटोएसिडोसिस, या गंभीर किडनी/लिवर की बीमारी है तो बचें।',
                'missed_dose_en' => 'Take it with your next meal if missed. Do not take double dose to make up for the missed one.',
                'missed_dose_hi' => 'छूट जाने पर इसे अपने अगले भोजन के साथ लें। छूटी हुई खुराक की भरपाई के लिए दोगुनी खुराक न लें।',
                'overdose_en' => 'Overdose can trigger lactic acidosis. Seek immediate emergency medical care.',
                'overdose_hi' => 'ओवरडोज से लैक्टिक एसिडोसिस हो सकता है। तुरंत आपातकालीन चिकित्सा सहायता लें।',
                'storage_en' => 'Store below 25°C in a dry place, away from light.',
                'storage_hi' => 'प्रकाश से दूर, सूखी जगह में 25 डिग्री सेल्सियस से नीचे स्टोर करें।',
                'expert_advice_en' => 'Combine medication with a healthy diet and regular exercise for optimal blood sugar control.',
                'expert_advice_hi' => 'इष्टतम रक्त शर्करा नियंत्रण के लिए स्वस्थ आहार और नियमित व्यायाम के साथ दवा का संयोजन करें।',
                'when_to_contact_doctor_en' => 'Contact doctor if you experience fast or shallow breathing, severe stomach upset, or extreme fatigue.',
                'when_to_contact_doctor_hi' => 'यदि आपको तेज या उथली सांस, गंभीर पेट खराब होना, या अत्यधिक थकान का अनुभव हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Does Metformin cause weight loss?', 'answer' => 'It may help some patients lose weight by reducing appetite and improving insulin usage.'],
                    ['question' => 'Can Metformin cure diabetes?', 'answer' => 'No, it controls diabetes but does not cure it. Lifestyle and medication must be continued.'],
                ],
                'source_references_json' => ['ADA Clinical Practice Recommendations', 'Lexicomp Online'],
                'meta_title_en' => 'Metformin: Type 2 Diabetes Management, Side Effects & Info',
                'meta_title_hi' => 'मेटफॉर्मिन: टाइप 2 मधुमेह प्रबंधन, दुष्प्रभाव और जानकारी',
                'meta_description_en' => 'Understand how Metformin helps manage blood sugar levels, its dosage, side effects, and warning signs.',
                'meta_description_hi' => 'समझें कि मेटफॉर्मिन रक्त शर्करा के स्तर को प्रबंधित करने में कैसे मदद करता है, इसकी खुराक, दुष्प्रभाव और चेतावनी के संकेत।',
                'reviewed_by' => 'Dr. V. Mohan',
                'last_reviewed_at' => '2026-01-10 16:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Amoxicillin',
                'slug' => 'amoxicillin',
                'generic_name' => 'Amoxicillin Trihydrate',
                'brand_names_json' => ['Mox 500', 'Novamox', 'Amoxil', 'Almox'],
                'composition' => 'Amoxicillin Trihydrate IP',
                'strength' => '250 mg / 500 mg',
                'medicine_type' => 'Capsule / Oral Suspension',
                'category' => 'Antibiotic',
                'prescription_required' => true,
                'purpose_en' => 'Prescription penicillin-class antibiotic for treating bacterial infections.',
                'purpose_hi' => 'बैक्टीरियल संक्रमणों के इलाज के लिए प्रिस्क्रिप्शन पेनिसिलिन-वर्ग एंटीबायोटिक।',
                'overview_en' => 'Amoxicillin is used to treat a wide variety of bacterial infections. It will not work for viral infections like common cold or flu.',
                'overview_hi' => 'अमोक्सिसिलिन का उपयोग विभिन्न प्रकार के बैक्टीरियल संक्रमणों के इलाज के लिए किया जाता है। यह सामान्य सर्दी या फ्लू जैसे वायरल संक्रमणों के लिए काम नहीं करेगा।',
                'uses_en' => 'Commonly prescribed for ear, nose, throat, skin, and urinary tract infections, and for H. pylori eradication.',
                'uses_hi' => 'आमतौर पर कान, नाक, गले, त्वचा और मूत्र पथ के संक्रमण और एच. पाइलोरी उन्मूलन के लिए निर्धारित किया जाता है।',
                'benefits_en' => 'Effectively eliminates susceptible bacteria, resolving fever and localized infection symptoms.',
                'benefits_hi' => 'संवेदनशील बैक्टीरिया को प्रभावी ढंग से समाप्त करता है, जिससे बुखार और स्थानीय संक्रमण के लक्षणों में राहत मिलती है।',
                'dosage_information_en' => 'Standard adult dose is 250mg to 500mg every 8 hours, or 500mg to 875mg every 12 hours. Complete the entire course.',
                'dosage_information_hi' => 'वयस्कों के लिए सामान्य खुराक हर 8 घंटे में 250mg से 500mg, या हर 12 घंटे में 500mg से 875mg है। पूरा कोर्स समाप्त करें।',
                'mechanism_en' => 'Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins, leading to cell lysis.',
                'mechanism_hi' => 'पेनिसिलिन-बाइंडिंग प्रोटीन से जुड़कर बैक्टीरिया की कोशिका भित्ति के संश्लेषण को रोकता है, जिससे कोशिका नष्ट हो जाती है।',
                'common_side_effects_en' => 'Diarrhea, nausea, vomiting, stomach upset, or skin rash.',
                'common_side_effects_hi' => 'दस्त, मतली, उल्टी, पेट खराब होना, या त्वचा पर लाल चकत्ते।',
                'serious_side_effects_en' => 'Severe skin reactions, C. difficile-associated diarrhea (severe watery stools), or anaphylaxis.',
                'serious_side_effects_hi' => 'गंभीर त्वचा प्रतिक्रियाएं, सी. डिफिसिल से जुड़े दस्त (गंभीर पानी जैसे दस्त), या एनाफिलेक्सिस।',
                'drug_interactions_en' => 'Interacts with methotrexate, allopurinol, probenecid, and oral contraceptives.',
                'drug_interactions_hi' => 'मेथोट्रेक्सेट, एलोप्यूरिनॉल, प्रोबेनेसिड और मौखिक गर्भनिरोधक दवाओं के साथ परस्पर क्रिया कर सकती है।',
                'food_interactions_en' => 'Can be taken with or without food. Taking with food may reduce stomach upset.',
                'food_interactions_hi' => 'इसे भोजन के साथ या बिना लिया जा सकता है। भोजन के साथ लेने से पेट खराब होने की समस्या कम हो सकती है।',
                'alcohol_warning_en' => 'Avoid alcohol as it can dehydrate the body and worsen potential side effects like dizziness and stomach upset.',
                'alcohol_warning_hi' => 'शराब से बचें क्योंकि यह शरीर को निर्जलित कर सकती है और चक्कर आने और पेट खराब होने जैसे दुष्प्रभावों को बढ़ा सकती है।',
                'pregnancy_warning_en' => 'Generally considered safe during pregnancy when prescribed by a doctor.',
                'pregnancy_warning_hi' => 'डॉक्टर द्वारा निर्धारित किए जाने पर गर्भावस्था के दौरान आमतौर पर सुरक्षित माना जाता है।',
                'breastfeeding_warning_en' => 'Excreted in breast milk in small amounts; may cause sensitization, diarrhea, or rash in the infant. Consult a pediatrician.',
                'breastfeeding_warning_hi' => 'दूध में कम मात्रा में उत्सर्जित होती है; शिशु में संवेदनशीलता, दस्त या दाने हो सकते हैं। बाल रोग विशेषज्ञ से सलाह लें।',
                'kidney_warning_en' => 'Dose adjustments are required in patients with severe renal impairment (eGFR < 30 ml/min).',
                'kidney_warning_hi' => 'गंभीर किडनी रोग (eGFR < 30 ml/min) वाले रोगियों में खुराक समायोजन की आवश्यकता होती है।',
                'liver_warning_en' => 'Use with caution; hepatotoxicity has been reported, though it is rare.',
                'liver_warning_hi' => 'सावधानी के साथ प्रयोग करें; लिवर विषाक्तता की सूचना मिली है, हालांकि यह दुर्लभ है।',
                'driving_warning_en' => 'Generally safe to drive unless you experience dizziness or allergic symptoms.',
                'driving_warning_hi' => 'जब तक आपको चक्कर या एलर्जी के लक्षण महसूस न हों, ड्राइव करना आमतौर पर सुरक्षित है।',
                'allergy_warning_en' => 'Do not take if you have a history of allergic reaction to penicillin, cephalosporins, or other beta-lactam antibiotics.',
                'allergy_warning_hi' => 'यदि आपको पेनिसिलिन, सेफलोस्पोरिन या अन्य बीटा-लैक्टम एंटीबायोटिक दवाओं से एलर्जी का इतिहास है तो न लें।',
                'precautions_en' => 'Maintain adequate fluid intake. Do not share this medicine with others.',
                'precautions_hi' => 'पर्याप्त मात्रा में तरल पदार्थों का सेवन बनाए रखें। यह दवा दूसरों के साथ साझा न करें।',
                'contraindications_en' => 'Hypersensitivity to penicillin or any component of the formulation.',
                'contraindications_hi' => 'पेनिसिलिन या फॉर्मूलेशन के किसी भी घटक के प्रति अतिसंवेदनशीलता।',
                'avoid_if_en' => 'Avoid if you have infectious mononucleosis, as a skin rash is highly likely to develop.',
                'avoid_if_hi' => 'यदि आपको संक्रामक मोनोन्यूक्लिओसिस है तो बचें, क्योंकि त्वचा पर लाल चकत्ते विकसित होने की अत्यधिक संभावना होती है।',
                'missed_dose_en' => 'Take as soon as you remember. If it is nearly time for the next dose, skip it. Do not double the dose.',
                'missed_dose_hi' => 'याद आते ही लें। यदि अगली खुराक का समय निकट है, तो इसे छोड़ दें। खुराक दोगुनी न करें।',
                'overdose_en' => 'Overdose can cause renal failure or neuromuscular excitability. Contact emergency healthcare.',
                'overdose_hi' => 'ओवरडोज से किडनी फेल होना या न्यूरोमस्कुलर उत्तेजना हो सकती है। आपातकालीन स्वास्थ्य सेवा से संपर्क करें।',
                'storage_en' => 'Store capsules at room temperature. Liquid suspensions should ideally be refrigerated after reconstitution.',
                'storage_hi' => 'कैप्सूल को कमरे के तापमान पर स्टोर करें। तरल सस्पेंशन को बनाने के बाद फ्रिज में रखा जाना चाहिए।',
                'expert_advice_en' => 'Complete the full course even if you feel better after a few days to prevent bacterial resistance.',
                'expert_advice_hi' => 'बैक्टीरियल प्रतिरोध को रोकने के लिए कुछ दिनों के बाद बेहतर महसूस होने पर भी पूरा कोर्स पूरा करें।',
                'when_to_contact_doctor_en' => 'Contact doctor immediately if you develop severe bloody diarrhea, skin rashes, or facial swelling.',
                'when_to_contact_doctor_hi' => 'यदि आपको गंभीर खूनी दस्त, त्वचा पर लाल चकत्ते, या चेहरे पर सूजन विकसित हो तो तुरंत डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Is amoxicillin strong?', 'answer' => 'It is an effective, standard antibiotic for susceptible bacterial strains, but strength depends on the dose and infection type.'],
                    ['question' => 'Can I take it with dairy?', 'answer' => 'Yes, amoxicillin does not interact significantly with milk or dairy, unlike tetracyclines.'],
                ],
                'source_references_json' => ['NIH DailyMed', 'FDA Prescribing Information'],
                'meta_title_en' => 'Amoxicillin: Uses, Dosage, Side Effects & Warnings',
                'meta_title_hi' => 'अमोक्सिसिलिन: उपयोग, खुराक, दुष्प्रभाव और चेतावनी',
                'meta_description_en' => 'Educational overview of Amoxicillin, including typical bacterial infections treated, safety details, and allergen warnings.',
                'meta_description_hi' => 'अमोक्सिसिलिन का सामान्य शैक्षणिक विवरण, जिसमें उपचारित बैक्टीरियल संक्रमण, सुरक्षा विवरण और एलर्जी चेतावनी शामिल हैं।',
                'reviewed_by' => 'Dr. Rajesh Patel',
                'last_reviewed_at' => '2026-05-20 11:30:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Ibuprofen',
                'slug' => 'ibuprofen',
                'generic_name' => 'Ibuprofen',
                'brand_names_json' => ['Brufen', 'Combiflam', 'Advil', 'Motrin'],
                'composition' => 'Ibuprofen IP',
                'strength' => '200 mg / 400 mg / 600 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Pain relief and anti-inflammatory',
                'prescription_required' => false,
                'purpose_en' => 'Nonsteroidal anti-inflammatory drug (NSAID) for pain, fever, and inflammation relief.',
                'purpose_hi' => 'दर्द, बुखार और सूजन से राहत के लिए नॉन-स्टेरायडल एंटी-इंफ्लेमेटरी ड्रग (NSAID)।',
                'overview_en' => 'Ibuprofen reduces hormones that cause pain and inflammation in the body. It should be taken with food to protect the stomach.',
                'overview_hi' => 'इबुप्रोफेन शरीर में दर्द और सूजन पैदा करने वाले हार्मोन को कम करता है। पेट की सुरक्षा के लिए इसे भोजन के साथ लेना चाहिए।',
                'uses_en' => 'Used to relieve pain from headaches, dental work, muscle aches, arthritis, menstrual cramps, or minor injuries.',
                'uses_hi' => 'सिरदर्द, दांतों के दर्द, मांसपेशियों में दर्द, गठिया, मासिक धर्म की ऐंठन, या मामूली चोटों के दर्द से राहत के लिए उपयोग किया जाता।',
                'benefits_en' => 'Reduces swelling, joint stiffness, pain, and lowers fever effectively.',
                'benefits_hi' => 'यह सूजन, जोड़ों की जकड़न, दर्द को कम करता है और बुखार को प्रभावी ढंग से कम करता है।',
                'dosage_information_en' => 'Adults: 200mg to 400mg every 4 to 6 hours as needed. Do not exceed 1200mg/day for self-medication.',
                'dosage_information_hi' => 'वयस्क: आवश्यकतानुसार हर 4 से 6 घंटे में 200mg से 400mg। स्वयं दवा के लिए 1200mg/दिन से अधिक न लें।',
                'mechanism_en' => 'Reversibly inhibits cyclooxygenase-1 and 2 (COX-1 and 2) enzymes, decreasing prostaglandin synthesis.',
                'mechanism_hi' => 'साइक्लोऑक्सीजिनेज-1 और 2 (COX-1 और 2) एंजाइमों को रोककर प्रोस्टाग्लैंडीन संश्लेषण को कम करता है।',
                'common_side_effects_en' => 'Heartburn, nausea, vomiting, gas, bloating, or dizziness.',
                'common_side_effects_hi' => 'सीने में जलन, मतली, उल्टी, गैस, पेट फूलना, या चक्कर आना।',
                'serious_side_effects_en' => 'Gastrointestinal bleeding (black/tarry stools), kidney damage, or increased risk of heart attack or stroke.',
                'serious_side_effects_hi' => 'गैस्ट्रोइंटेस्टाइनल रक्तस्राव (काले दस्त), किडनी की क्षति, या दिल का दौरा या स्ट्रोक का खतरा बढ़ना।',
                'drug_interactions_en' => 'Interacts with aspirin, other NSAIDs, blood thinners (warfarin), antihypertensives, and diuretics.',
                'drug_interactions_hi' => 'एस्पिरिन, अन्य NSAID, रक्त को पतला करने वाली दवाओं (वारफेरिन), रक्तचाप रोधी दवाओं और मूत्रवर्धक दवाओं के साथ परस्पर क्रिया करता है।',
                'food_interactions_en' => 'Take with food or milk to minimize stomach upset and irritation.',
                'food_interactions_hi' => 'पेट खराब होने और जलन को कम करने के लिए भोजन या दूध के साथ लें।',
                'alcohol_warning_en' => 'Avoid alcohol, as combining it with ibuprofen increases the risk of stomach bleeding.',
                'alcohol_warning_hi' => 'शराब से बचें, क्योंकि इबुप्रोफेन के साथ इसे मिलाने से पेट से खून बहने का खतरा बढ़ जाता है।',
                'pregnancy_warning_en' => 'Avoid using in late pregnancy (third trimester) as it may harm the unborn baby.',
                'pregnancy_warning_hi' => 'गर्भावस्था के अंतिम चरण (तीसरी तिमाही) में उपयोग से बचें क्योंकि यह अजन्मे बच्चे को नुकसान पहुंचा सकता है।',
                'breastfeeding_warning_en' => 'Excreted in breast milk in very low concentrations. Generally considered compatible with breastfeeding.',
                'breastfeeding_warning_hi' => 'स्तन के दूध में बहुत कम मात्रा में उत्सर्जित होती है। आमतौर पर स्तनपान के अनुकूल माना जाता है।',
                'kidney_warning_en' => 'Use with extreme caution. Long term use can lead to renal papillary necrosis and kidney failure.',
                'kidney_warning_hi' => 'अत्यधिक सावधानी के साथ प्रयोग करें। लंबे समय तक उपयोग से किडनी फेल हो सकती है।',
                'liver_warning_en' => 'May cause borderline elevations of liver enzymes. Monitor if used long-term.',
                'liver_warning_hi' => 'लिवर एंजाइमों में आंशिक वृद्धि का कारण बन सकता है। लंबे समय तक उपयोग करने पर निगरानी रखें।',
                'driving_warning_en' => 'May cause dizziness or drowsiness in some individuals. Avoid driving if affected.',
                'driving_warning_hi' => 'कुछ व्यक्तियों में चक्कर या उनींदापन हो सकता है। प्रभावित होने पर गाड़ी चलाने से बचें।',
                'allergy_warning_en' => 'Avoid if you have asthma, hives, or allergic reactions triggered by aspirin or other NSAIDs.',
                'allergy_warning_hi' => 'यदि आपको एस्पिरिन या अन्य NSAID दवाओं द्वारा ट्रिगर होने वाला अस्थमा, पित्ती या एलर्जी है तो बचें।',
                'precautions_en' => 'Use the lowest effective dose for the shortest duration necessary to control symptoms.',
                'precautions_hi' => 'लक्षणों को नियंत्रित करने के लिए आवश्यक न्यूनतम अवधि के लिए सबसे कम प्रभावी खुराक का उपयोग करें।',
                'contraindications_en' => 'Contraindicated after coronary artery bypass graft (CABG) surgery, and in active peptic ulcer disease.',
                'contraindications_hi' => 'कोरोनरी आर्टरी बाईपास ग्राफ्ट (CABG) सर्जरी के बाद और सक्रिय पेप्टिक अल्सर रोग में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have a history of GI bleeding, severe heart failure, or severe renal impairment.',
                'avoid_if_hi' => 'यदि आपको जीआई रक्तस्राव, गंभीर हृदय विफलता, या गंभीर किडनी रोग का इतिहास है तो बचें।',
                'missed_dose_en' => 'Take the missed dose as soon as you remember. If it is close to the next scheduled dose, skip it.',
                'missed_dose_hi' => 'याद आते ही लें। यदि अगली खुराक का समय हो गया हो, तो छूटी हुई खुराक छोड़ दें।',
                'overdose_en' => 'Overdose symptoms include abdominal pain, drowsiness, seizures, or loss of consciousness. Seek emergency care.',
                'overdose_hi' => 'ओवरडोज के लक्षणों में पेट दर्द, उनींदापन, दौरे या बेहोशी शामिल हैं। आपातकालीन देखभाल लें।',
                'storage_en' => 'Store at room temperature below 25°C. Keep container tightly closed.',
                'storage_hi' => '25 डिग्री सेल्सियस से नीचे कमरे के तापमान पर स्टोर करें। कंटेनर को कसकर बंद रखें।',
                'expert_advice_en' => 'Do not take ibuprofen for more than 10 days for pain or 3 days for fever without consulting a doctor.',
                'expert_advice_hi' => 'डॉक्टर से सलाह लिए बिना दर्द के लिए 10 दिनों से अधिक या बुखार के लिए 3 दिनों से अधिक इबुप्रोफेन न लें।',
                'when_to_contact_doctor_en' => 'Contact a doctor if you notice blood in stools, vomit that looks like coffee grounds, or persistent stomach pain.',
                'when_to_contact_doctor_hi' => 'यदि आप मल में खून, कॉफी के रंग की उल्टी, या लगातार पेट दर्द देखते हैं तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Is ibuprofen better than paracetamol?', 'answer' => 'Ibuprofen reduces inflammation, whereas paracetamol does not. However, paracetamol is gentler on the stomach.'],
                    ['question' => 'Can I take ibuprofen on empty stomach?', 'answer' => 'No. Taking it on an empty stomach increases the risk of gastric irritation and ulcers.'],
                ],
                'source_references_json' => ['MedlinePlus', 'American Heart Association'],
                'meta_title_en' => 'Ibuprofen: NSAID Pain Reliever, Uses & Side Effects',
                'meta_title_hi' => 'इबुप्रोफेन: एनएसएआईडी दर्द निवारक, उपयोग और दुष्प्रभाव',
                'meta_description_en' => 'General educational details on Ibuprofen, an anti-inflammatory painkiller, covering safe dosage limits and cardiovascular risks.',
                'meta_description_hi' => 'इबुप्रोफेन, एक सूजन-रोधी दर्द निवारक पर सामान्य शैक्षणिक विवरण, जिसमें सुरक्षित खुराक सीमाएं शामिल हैं।',
                'reviewed_by' => 'Dr. Sanjay Gupta',
                'last_reviewed_at' => '2026-06-01 09:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
            [
                'name' => 'Amlodipine',
                'slug' => 'amlodipine',
                'generic_name' => 'Amlodipine Besylate',
                'brand_names_json' => ['Amlokind', 'Amlopin', 'Amcard', 'Norvasc'],
                'composition' => 'Amlodipine Besylate IP',
                'strength' => '2.5 mg / 5 mg / 10 mg',
                'medicine_type' => 'Tablet',
                'category' => 'Cardiovascular / Antihypertensive',
                'prescription_required' => true,
                'purpose_en' => 'Prescription calcium channel blocker for high blood pressure and chest pain (angina).',
                'purpose_hi' => 'उच्च रक्तचाप और सीने में दर्द (एनजाइना) के लिए प्रिस्क्रिप्शन कैल्शियम चैनल ब्लॉकर।',
                'overview_en' => 'Amlodipine relaxes blood vessels to improve blood flow and lower blood pressure. It must be taken regularly as prescribed to be effective.',
                'overview_hi' => 'एम्लोडिपिन रक्त वाहिकाओं को आराम देता है जिससे रक्त प्रवाह में सुधार होता है और रक्तचाप कम होता है। प्रभावी होने के लिए इसे नियमित रूप से लिया जाना चाहिए।',
                'uses_en' => 'Used to treat hypertension (high blood pressure) and chronic stable or vasospastic angina.',
                'uses_hi' => 'उच्च रक्तचाप और क्रोनिक स्थिर या वासोस्पास्टिक एनजाइना के इलाज के लिए उपयोग किया जाता है।',
                'benefits_en' => 'Lowers blood pressure, reducing the risk of fatal cardiovascular events, strokes, and heart attacks.',
                'benefits_hi' => 'रक्तचाप को कम करता है, जिससे घातक हृदय घटनाओं, स्ट्रोक और दिल के दौरे का खतरा कम होता है।',
                'dosage_information_en' => 'Typically starts at 5mg once daily, with a maximum dose of 10mg once daily. Take at the same time each day.',
                'dosage_information_hi' => 'आमतौर पर दिन में एक बार 5mg से शुरू होता है, अधिकतम खुराक दिन में एक बार 10mg है। प्रतिदिन एक ही समय पर लें।',
                'mechanism_en' => 'Inhibits the transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle cells, causing vasodilation.',
                'mechanism_hi' => 'संवहनी चिकनी मांसपेशियों और हृदय की मांसपेशियों की कोशिकाओं में कैल्शियम आयनों के प्रवाह को रोकता है, जिससे वाहिकाप्रसरण होता है।',
                'common_side_effects_en' => 'Swelling of ankles or feet (edema), headache, dizziness, fatigue, or flushing.',
                'common_side_effects_hi' => 'टखनों या पैरों में सूजन (एडिमा), सिरदर्द, चक्कर आना, थकान, या चेहरे का लाल होना।',
                'serious_side_effects_en' => 'Worsening chest pain or heart attack (especially when starting or increasing dose), or severe low blood pressure.',
                'serious_side_effects_hi' => 'सीने में दर्द या दिल का दौरा बिगड़ना (विशेष रूप से खुराक शुरू करने या बढ़ाने पर), या गंभीर निम्न रक्तचाप।',
                'drug_interactions_en' => 'Interacts with simvastatin, cyclosporine, sildenafil, and other blood pressure lowering drugs.',
                'drug_interactions_hi' => 'सिमवास्टेटिन, साइक्लोस्पोरिन, सिल्डेनाफिल और अन्य रक्तचाप कम करने वाली दवाओं के साथ परस्पर क्रिया करता है।',
                'food_interactions_en' => 'Avoid grapefruit and grapefruit juice, as it can increase amlodipine levels in the blood.',
                'food_interactions_hi' => 'चकोतरा (ग्रेपफ्रूट) और उसके रस से बचें, क्योंकि यह रक्त में एम्लोडिपिन के स्तर को बढ़ा सकता है।',
                'alcohol_warning_en' => 'Avoid alcohol as it can further lower your blood pressure, worsening dizziness or fainting spells.',
                'alcohol_warning_hi' => 'शराब से बचें क्योंकि यह आपके रक्तचाप को और कम कर सकती है, जिससे चक्कर आना या बेहोशी बढ़ सकती है।',
                'pregnancy_warning_en' => 'Use during pregnancy only if the potential benefit justifies the potential risk to the fetus.',
                'pregnancy_warning_hi' => 'गर्भावस्था के दौरान केवल तभी उपयोग करें जब संभावित लाभ भ्रूण के लिए संभावित जोखिम को सही ठहराता हो।',
                'breastfeeding_warning_en' => 'Excreted in human milk. Consult your physician before using while breastfeeding.',
                'breastfeeding_warning_hi' => 'यह स्तन के दूध में उत्सर्जित होती है। स्तनपान के दौरान उपयोग करने से पहले अपने चिकित्सक से सलाह लें।',
                'kidney_warning_en' => 'Safe to use in renal impairment, as amlodipine is not cleared by kidneys. No dose adjustments needed.',
                'kidney_warning_hi' => 'किडनी की खराबी में उपयोग करना सुरक्षित है, क्योंकि एम्लोडिपिन किडनी द्वारा साफ नहीं किया जाता है। कोई खुराक समायोजन आवश्यक नहीं।',
                'liver_warning_en' => 'Metabolized extensively by the liver. Titrate slowly in hepatic impairment patients.',
                'liver_warning_hi' => 'लिवर द्वारा व्यापक रूप से मेटाबोलाइज्ड होता है। लिवर की खराबी वाले रोगियों में खुराक धीरे-धीरे बढ़ाएं।',
                'driving_warning_en' => 'May cause dizziness or fatigue. Use caution before driving or operating machinery.',
                'driving_warning_hi' => 'चक्कर या थकान हो सकती है। गाड़ी चलाने या मशीनरी चलाने से पहले सावधानी बरतें।',
                'allergy_warning_en' => 'Do not take if you have known hypersensitivity to amlodipine or other dihydropyridine calcium channel blockers.',
                'allergy_warning_hi' => 'यदि आपको एम्लोडिपिन या अन्य डाइहाइड्रोपाइरिडाइन कैल्शियम चैनल ब्लॉकर्स के प्रति अतिसंवेदनशीलता है तो न लें।',
                'precautions_en' => 'Monitor blood pressure regularly. Do not stop taking amlodipine abruptly.',
                'precautions_hi' => 'नियमित रूप से रक्तचाप की निगरानी करें। एम्लोडिपिन लेना अचानक बंद न करें।',
                'contraindications_en' => 'Contraindicated in severe hypotension, cardiogenic shock, and clinically significant aortic stenosis.',
                'contraindications_hi' => 'गंभीर निम्न रक्तचाप, कार्डियोजेनिक शॉक और महाधमनी स्टेनोसिस में वर्जित है।',
                'avoid_if_en' => 'Avoid if you have unstable heart conditions or severe liver disease without specialist care.',
                'avoid_if_hi' => 'यदि आपको अस्थिर हृदय की स्थिति या विशेषज्ञ की देखभाल के बिना गंभीर लिवर की बीमारी है तो बचें।',
                'missed_dose_en' => 'Take if remembered within 12 hours. If more than 12 hours have passed, skip the missed dose. Do not double the dose.',
                'missed_dose_hi' => 'यदि 12 घंटे के भीतर याद आ जाए तो लें। यदि 12 घंटे से अधिक समय बीत चुका है, तो छूटी हुई खुराक छोड़ दें। खुराक दोगुनी न करें।',
                'overdose_en' => 'Overdose can cause severe peripheral vasodilation with marked hypotension and reflex tachycardia. Contact emergency services.',
                'overdose_hi' => 'ओवरडोज से गंभीर हाइपोटेंशन और रिफ्लेक्स टैचीकार्डिया हो सकता है। आपातकालीन सेवाओं से संपर्क करें।',
                'storage_en' => 'Store at room temperature between 15°C and 30°C, protected from light.',
                'storage_hi' => 'प्रकाश से सुरक्षित, 15°C और 30°C के बीच कमरे के तापमान पर स्टोर करें।',
                'expert_advice_en' => 'Blood pressure control is a lifelong therapy. Combine with low sodium diet and weight management.',
                'expert_advice_hi' => 'रक्तचाप नियंत्रण एक आजीवन चिकित्सा है। कम सोडियम वाले आहार और वजन प्रबंधन के साथ संयोजन करें।',
                'when_to_contact_doctor_en' => 'Contact doctor if you develop rapid swelling of hands, ankles, or feet, or severe chest pain.',
                'when_to_contact_doctor_hi' => 'यदि आपको हाथों, टखनों या पैरों में तेजी से सूजन, या गंभीर सीने में दर्द विकसित हो तो डॉक्टर से संपर्क करें।',
                'faqs_json' => [
                    ['question' => 'Can amlodipine cause cough?', 'answer' => 'No, unlike ACE inhibitors (like enalapril), amlodipine does not typically cause a dry cough.'],
                    ['question' => 'Should I take it in the morning or night?', 'answer' => 'It can be taken at either time, but it is best to take it at the same time every day.'],
                ],
                'source_references_json' => ['Joint National Committee (JNC)', 'FDA Approved Labeling'],
                'meta_title_en' => 'Amlodipine: High Blood Pressure Medicine, Uses',
                'meta_title_hi' => 'एम्लोडिपिन: उच्च रक्तचाप की दवा, उपयोग और दुष्प्रभाव',
                'meta_description_en' => 'Understand how Amlodipine manages hypertension and angina, including side effects like ankle swelling.',
                'meta_description_hi' => 'समझें कि एम्लोडिपिन कैसे उच्च रक्तचाप और एनजाइना का प्रबंधन करता है, जिसमें टखने की सूजन जैसे दुष्प्रभाव शामिल हैं।',
                'reviewed_by' => 'Dr. Devi Shetty',
                'last_reviewed_at' => '2026-05-01 10:00:00',
                'ai_generated' => false,
                'medically_reviewed' => true,
                'review_status' => 'published',
                'is_published' => true,
            ],
        ];
    }
}
