<?php

namespace App\Services;

class AhmedabadScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'ahmedabad') {
            return [];
        }

        return [
            [
                'name_en' => 'Civil Hospital Blood Bank (B.J. Medical College)',
                'name_hi' => 'सिविल अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380016',
                'address_en' => 'Civil Hospital Campus, Asarwa, Ahmedabad, Gujarat - 380016',
                'address_hi' => 'सिविल अस्पताल परिसर, असरवा, अहमदाबाद, गुजरात - 380016',
                'country_code' => '+91',
                'phone' => '079-22683721',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-22683721',
                'email' => 'bloodbank@bjmcabd.edu.in',
                'website' => 'https://bjmcabd.edu.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Civil Registry',
                'source_url' => 'https://bjmcabd.edu.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Prathama Blood Centre',
                'name_hi' => 'प्रथमा ब्लड सेंटर',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'address_en' => 'B/h Jivraj Mehta Hospital, Vasna, Ahmedabad, Gujarat - 380054',
                'address_hi' => 'जीवराज मेहता अस्पताल के पीछे, वासना, अहमदाबाद, गुजरात - 380054',
                'country_code' => '+91',
                'phone' => '079-26651010',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-26651010',
                'email' => 'contact@prathamabloodcentre.com',
                'website' => 'https://prathamabloodcentre.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Prathama Registry',
                'source_url' => 'https://prathamabloodcentre.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Red Cross Blood Bank Ahmedabad',
                'name_hi' => 'रेड क्रॉस ब्लड बैंक अहमदाबाद',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380013',
                'address_en' => 'Near Khadi Gramodyog Board, Ashram Road, Old Wadaj, Ahmedabad, Gujarat - 380013',
                'address_hi' => 'खादी ग्रामोद्योग बोर्ड के पास, आश्रम रोड, ओल्ड वाडज, अहमदाबाद, गुजरात - 380013',
                'country_code' => '+91',
                'phone' => '079-27551551',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-27551551',
                'email' => 'contact@redcrossahmedabad.org',
                'website' => 'https://redcrossahmedabad.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Red Cross Registry',
                'source_url' => 'https://redcrossahmedabad.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'SVP Hospital Blood Bank (Sardar Vallabhbhai Patel Hospital)',
                'name_hi' => 'एसवीपी अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380006',
                'address_en' => 'Ellis Bridge, Near V. S. Hospital, Ahmedabad, Gujarat - 380006',
                'address_hi' => 'एलिस ब्रिज, वी. एस. अस्पताल के पास, अहमदाबाद, गुजरात - 380006',
                'country_code' => '+91',
                'phone' => '079-26555555',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-26555555',
                'email' => 'bloodbank@svphospital.com',
                'website' => 'https://svphospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / SVP Registry',
                'source_url' => 'https://svphospital.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Zydus Hospital Blood Bank',
                'name_hi' => 'ज़ायडस अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'address_en' => 'Zydus Hospitals Road, S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_hi' => 'ज़ायडस हॉस्पिटल्स रोड, एस.जी. हाईवे, थलतेज, अहमदाबाद, गुजरात - 380054',
                'country_code' => '+91',
                'phone' => '079-66190201',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-66190201',
                'email' => 'bloodbank@zydushospitals.com',
                'website' => 'https://zydushospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Zydus Registry',
                'source_url' => 'https://zydushospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Marengo CIMS Hospital Blood Bank',
                'name_hi' => 'मारेंगो सिम्स अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'address_en' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_hi' => 'सोला फ्लाईओवर के पास, सोला, अहमदाबाद, गुजरात - 380060',
                'country_code' => '+91',
                'phone' => '079-48051200',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-48051200',
                'email' => 'bloodbank@marengocims.com',
                'website' => 'https://marengocims.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Marengo CIMS Registry',
                'source_url' => 'https://marengocims.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Apollo Hospitals Blood Bank Bhat',
                'name_hi' => 'अपोलो अस्पताल ब्लड बैंक भाट',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382428',
                'address_en' => 'Plot No. 1A, Bhat GIDC Estate, Gandhinagar - Ahmedabad Highway, Ahmedabad, Gujarat - 382428',
                'address_hi' => 'प्लॉट नं. 1ए, भाट जीआईडीसी एस्टेट, गांधीनगर - अहमदाबाद हाईवे, अहमदाबाद, गुजरात - 382428',
                'country_code' => '+91',
                'phone' => '079-66701800',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-66701800',
                'email' => 'bloodbank_ahd@apollohospitals.com',
                'website' => 'https://apollohospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Apollo Bhat Registry',
                'source_url' => 'https://apollohospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Sterling Hospital Blood Bank',
                'name_hi' => 'स्टर्लिंग अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'address_en' => 'Sterling Hospital Road, Near Gurukul, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_hi' => 'स्टर्लिंग अस्पताल रोड, गुरुकुल के पास, मेमनगर, अहमदाबाद, गुजरात - 380052',
                'country_code' => '+91',
                'phone' => '079-40011111',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-40011111',
                'email' => 'bloodbank@sterlinghospitals.com',
                'website' => 'https://sterlinghospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Sterling Registry',
                'source_url' => 'https://sterlinghospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'KD Hospital Blood Bank (Kusum Dhirajlal Hospital)',
                'name_hi' => 'केडी अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382421',
                'address_en' => 'Vaishno Devi Circle, S.G. Highway, Ahmedabad, Gujarat - 382421',
                'address_hi' => 'वैष्णो देवी सर्किल, एस.जी. हाईवे, अहमदाबाद, गुजरात - 382421',
                'country_code' => '+91',
                'phone' => '079-66770000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-66770000',
                'email' => 'bloodbank@kdhospital.co.in',
                'website' => 'https://kdhospital.co.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / KD Hospital Registry',
                'source_url' => 'https://kdhospital.co.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Shalby Hospital Blood Bank SG Highway',
                'name_hi' => 'शैल्बी अस्पताल ब्लड बैंक एसजी हाईवे',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380015',
                'address_en' => 'Opposite Karnavati Club, S.G. Highway, Ahmedabad, Gujarat - 380015',
                'address_hi' => 'कर्णावती क्लब के सामने, एस.जी. हाईवे, अहमदाबाद, गुजरात - 380015',
                'country_code' => '+91',
                'phone' => '079-40203000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-40203000',
                'email' => 'bloodbank.sgh@shalby.org',
                'website' => 'https://shalby.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Shalby SG Registry',
                'source_url' => 'https://shalby.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'CIMS Hospital Blood Bank (Marengo CIMS Hospital)',
                'name_hi' => 'सिम्स अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'address_en' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_hi' => 'सोला फ्लाईओवर के पास, सोला, अहमदाबाद, गुजरात - 380060',
                'country_code' => '+91',
                'phone' => '079-48051200',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-48051200',
                'email' => 'bloodbank@cims.org',
                'website' => 'https://cims.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / CIMS Registry',
                'source_url' => 'https://cims.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'GCS Medical College Blood Bank (Gujarat Cancer Society)',
                'name_hi' => 'जीसीएस मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380025',
                'address_en' => 'Opp. DRM Office, Chamunda Bridge, Naroda Road, Ahmedabad, Gujarat - 380025',
                'address_hi' => 'डीआरएम कार्यालय के सामने, चामुंडा ब्रिज, नरोडा रोड, अहमदाबाद, गुजरात - 380025',
                'country_code' => '+91',
                'phone' => '079-66048000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-66048000',
                'email' => 'bloodbank@gcsmc.org',
                'website' => 'https://gcsmc.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / GCS Registry',
                'source_url' => 'https://gcsmc.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Shardaben Hospital Blood Bank',
                'name_hi' => 'शारदाबेन अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380018',
                'address_en' => 'Saraspur, Ahmedabad, Gujarat - 380018',
                'address_hi' => 'सरसपुर, अहमदाबाद, गुजरात - 380018',
                'country_code' => '+91',
                'phone' => '079-22923515',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-22923515',
                'email' => 'bloodbank@shardabenhospital.org',
                'website' => 'https://ahmedabadcity.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => false,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Municipal Registry',
                'source_url' => 'https://ahmedabadcity.gov.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'L.G. Hospital Blood Bank',
                'name_hi' => 'एल.जी. अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380008',
                'address_en' => 'Maninagar, Ahmedabad, Gujarat - 380008',
                'address_hi' => 'मणिनगर, अहमदाबाद, गुजरात - 380008',
                'country_code' => '+91',
                'phone' => '079-25461380',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-25461380',
                'email' => 'lghospital@ahmedabadcity.gov.in',
                'website' => 'https://ahmedabadcity.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / LG Municipal Registry',
                'source_url' => 'https://ahmedabadcity.gov.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Jivraj Mehta Hospital Blood Bank',
                'name_hi' => 'जीवराज मेहता अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380007',
                'address_en' => 'Dr. Jivraj Mehta Marg, Vasna, Ahmedabad, Gujarat - 380007',
                'address_hi' => 'डॉ. जीवराज मेहता मार्ग, वासना, अहमदाबाद, गुजरात - 380007',
                'country_code' => '+91',
                'phone' => '079-26639836',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-26639836',
                'email' => 'bloodbank@jivrajmehtahospital.org',
                'website' => 'https://jivrajmehtahospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Jivraj Mehta Registry',
                'source_url' => 'https://jivrajmehtahospital.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Rajasthan Hospital Blood Bank',
                'name_hi' => 'राजस्थान अस्पताल ब्लड बैंक',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380004',
                'address_en' => 'Shahibaug Road, Shahibaug, Ahmedabad, Gujarat - 380004',
                'address_hi' => 'शाहीबाग रोड, शाहीबाग, अहमदाबाद, गुजरात - 380004',
                'country_code' => '+91',
                'phone' => '079-22866311',
                'emergency_country_code' => '+91',
                'emergency_phone' => '079-22866311',
                'email' => 'bloodbank@rajasthanhospitals.org',
                'website' => 'https://rajasthanhospitals.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Rajasthan Hospital Registry',
                'source_url' => 'https://rajasthanhospitals.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'ahmedabad') {
            return [];
        }

        return [
            [
                'name_en' => 'Civil Hospital Ahmedabad (B.J. Medical College)',
                'name_hi' => 'सिविल अस्पताल अहमदाबाद',
                'type' => 'Government Hospital',
                'address' => 'Civil Hospital Campus, Asarwa, Ahmedabad, Gujarat - 380016',
                'address_line1' => 'Civil Hospital Campus',
                'address_line2' => 'Asarwa',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380016',
                'emergency_phone' => '079-22683721',
                'emergency_country_code' => '+91',
                'latitude' => 23.0520,
                'longitude' => 72.6030,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'Mukhyamantri Amrutam (MA)', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'SVP Hospital (Sardar Vallabhbhai Patel Institute of Medical Sciences)',
                'name_hi' => 'एसवीपी अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Ellis Bridge, Near V. S. Hospital, Ahmedabad, Gujarat - 380006',
                'address_line1' => 'Ellis Bridge',
                'address_line2' => 'Near V. S. Hospital',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380006',
                'emergency_phone' => '079-26555555',
                'emergency_country_code' => '+91',
                'latitude' => 23.0220,
                'longitude' => 72.5710,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MA Yojana', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Zydus Hospital',
                'name_hi' => 'ज़ायडस अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Zydus Hospitals Road, S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Zydus Hospitals Road',
                'address_line2' => 'S.G. Highway, Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'emergency_phone' => '079-66190201',
                'emergency_country_code' => '+91',
                'latitude' => 23.0550,
                'longitude' => 72.5180,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Marengo CIMS Hospital (CIMS Hospital)',
                'name_hi' => 'मारेंगो सिम्स अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Off Sola Flyover',
                'address_line2' => 'Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'emergency_phone' => '079-48051200',
                'emergency_country_code' => '+91',
                'latitude' => 23.0650,
                'longitude' => 72.5200,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Apollo Hospitals, Bhat',
                'name_hi' => 'अपोलो अस्पताल, भाट',
                'type' => 'Private Hospital',
                'address' => 'Plot No. 1A, Bhat GIDC Estate, Gandhinagar - Ahmedabad Highway, Ahmedabad, Gujarat - 382428',
                'address_line1' => 'Plot No. 1A, Bhat GIDC Estate',
                'address_line2' => 'Gandhinagar - Ahmedabad Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382428',
                'emergency_phone' => '079-66701800',
                'emergency_country_code' => '+91',
                'latitude' => 23.1250,
                'longitude' => 72.6180,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Sterling Hospital, Memnagar',
                'name_hi' => 'स्टर्लिंग अस्पताल, मेमनगर',
                'type' => 'Private Hospital',
                'address' => 'Sterling Hospital Road, Near Gurukul, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_line1' => 'Sterling Hospital Road',
                'address_line2' => 'Near Gurukul, Memnagar',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'emergency_phone' => '079-40011111',
                'emergency_country_code' => '+91',
                'latitude' => 23.0450,
                'longitude' => 72.5350,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Max Bupa TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'KD Hospital (Kusum Dhirajlal Hospital)',
                'name_hi' => 'केडी अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Vaishno Devi Circle, S.G. Highway, Ahmedabad, Gujarat - 382421',
                'address_line1' => 'Vaishno Devi Circle',
                'address_line2' => 'S.G. Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382421',
                'emergency_phone' => '079-66770000',
                'emergency_country_code' => '+91',
                'latitude' => 23.1350,
                'longitude' => 72.5450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Shalby Hospital, SG Highway',
                'name_hi' => 'शैल्बी अस्पताल, एसजी हाईवे',
                'type' => 'Private Hospital',
                'address' => 'Opposite Karnavati Club, S.G. Highway, Ahmedabad, Gujarat - 380015',
                'address_line1' => 'Opposite Karnavati Club',
                'address_line2' => 'S.G. Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380015',
                'emergency_phone' => '079-40203000',
                'emergency_country_code' => '+91',
                'latitude' => 23.0180,
                'longitude' => 72.5050,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'SAL Hospital',
                'name_hi' => 'साल अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Drive-in Road, Opposite Doordarshan Tower, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Drive-in Road',
                'address_line2' => 'Opposite Doordarshan Tower, Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'emergency_phone' => '079-66115600',
                'emergency_country_code' => '+91',
                'latitude' => 23.0480,
                'longitude' => 72.5250,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'HCG Cancer Centre, Ahmedabad',
                'name_hi' => 'एचसीजी कैंसर सेंटर, अहमदाबाद',
                'type' => 'Private Hospital',
                'address' => 'Sola - Science City Road, Near Sola Bridge, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Sola - Science City Road',
                'address_line2' => 'Near Sola Bridge, Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'emergency_phone' => '079-40410101',
                'emergency_country_code' => '+91',
                'latitude' => 23.0680,
                'longitude' => 72.5180,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Apex Heart Institute',
                'name_hi' => 'एपेक्स हार्ट इंस्टीट्यूट',
                'type' => 'Private Hospital',
                'address' => 'Mondeal Business Park, Near Gurudwara, S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380059',
                'address_line1' => 'Mondeal Business Park, Near Gurudwara',
                'address_line2' => 'S.G. Highway, Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380059',
                'emergency_phone' => '079-26842200',
                'emergency_country_code' => '+91',
                'latitude' => 23.0380,
                'longitude' => 72.5120,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Narayana Multispeciality Hospital, Rakhial',
                'name_hi' => 'नारायणा मल्टीस्पेशलिटी अस्पताल, रखियाल',
                'type' => 'Private Hospital',
                'address' => 'Near Police Station, Rakhial Road, Ahmedabad, Gujarat - 380023',
                'address_line1' => 'Near Police Station',
                'address_line2' => 'Rakhial Road',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380023',
                'emergency_phone' => '079-71222222',
                'emergency_country_code' => '+91',
                'latitude' => 23.0250,
                'longitude' => 72.6350,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'GCS Medical College, Hospital & Research Centre',
                'name_hi' => 'जीसीएस मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Opp. DRM Office, Chamunda Bridge, Naroda Road, Ahmedabad, Gujarat - 380025',
                'address_line1' => 'Opp. DRM Office, Chamunda Bridge',
                'address_line2' => 'Naroda Road',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380025',
                'emergency_phone' => '079-66048000',
                'emergency_country_code' => '+91',
                'latitude' => 23.0450,
                'longitude' => 72.6110,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MA Yojana', 'CGHS', 'ECHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Shardaben General Hospital',
                'name_hi' => 'शारदाबेन जनरल अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Saraspur, Ahmedabad, Gujarat - 380018',
                'address_line1' => 'Saraspur',
                'address_line2' => 'Near Railway Station',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380018',
                'emergency_phone' => '079-22923515',
                'emergency_country_code' => '+91',
                'latitude' => 23.0310,
                'longitude' => 72.6150,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MA Yojana', 'CGHS'],
            ],
            [
                'name_en' => 'L.G. Hospital (Sheth V.S. General Hospital Campus)',
                'name_hi' => 'एल.जी. अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Maninagar, Ahmedabad, Gujarat - 380008',
                'address_line1' => 'Maninagar',
                'address_line2' => 'Near Rambaug',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380008',
                'emergency_phone' => '079-25461380',
                'emergency_country_code' => '+91',
                'latitude' => 22.9980,
                'longitude' => 72.6020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MA Yojana', 'CGHS'],
            ],
            [
                'name_en' => 'Jivraj Mehta Hospital',
                'name_hi' => 'जीवराज मेहता अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Dr. Jivraj Mehta Marg, Vasna, Ahmedabad, Gujarat - 380007',
                'address_line1' => 'Dr. Jivraj Mehta Marg',
                'address_line2' => 'Vasna',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380007',
                'emergency_phone' => '079-26639836',
                'emergency_country_code' => '+91',
                'latitude' => 23.0080,
                'longitude' => 72.5480,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Rajasthan Hospital',
                'name_hi' => 'राजस्थान अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Shahibaug Road, Shahibaug, Ahmedabad, Gujarat - 380004',
                'address_line1' => 'Shahibaug Road',
                'address_line2' => 'Shahibaug',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380004',
                'emergency_phone' => '079-22866311',
                'emergency_country_code' => '+91',
                'latitude' => 23.0520,
                'longitude' => 72.5950,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Star Hospital, Bopal',
                'name_hi' => 'स्टार अस्पताल, बोपल',
                'type' => 'Private Hospital',
                'address' => 'Bopal, Ahmedabad, Gujarat - 380058',
                'address_line1' => 'Bopal Main Road',
                'address_line2' => 'Bopal',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380058',
                'emergency_phone' => '079-27550001',
                'emergency_country_code' => '+91',
                'latitude' => 23.0280,
                'longitude' => 72.4650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Bodyline Hospital',
                'name_hi' => 'बॉडीलाइन अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Paldi, Ahmedabad, Gujarat - 380007',
                'address_line1' => 'Near Paldi Cross Roads',
                'address_line2' => 'Paldi',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380007',
                'emergency_phone' => '079-26588888',
                'emergency_country_code' => '+91',
                'latitude' => 23.0120,
                'longitude' => 72.5650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'HCG Hospitals, Mithakhali',
                'name_hi' => 'एचसीजी अस्पताल, मीठाखली',
                'type' => 'Private Hospital',
                'address' => 'Mithakhali Six Roads, Ellisbridge, Ahmedabad, Gujarat - 380006',
                'address_line1' => 'Mithakhali Six Roads',
                'address_line2' => 'Ellisbridge',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380006',
                'emergency_phone' => '079-26404142',
                'emergency_country_code' => '+91',
                'latitude' => 23.0280,
                'longitude' => 72.5650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Max Bupa TPA', 'ICICI Lombard TPA'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'ahmedabad') {
            return [];
        }

        return [
            [
                'first_name' => 'Tejas',
                'last_name' => 'Patel',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Apex Heart Institute',
                'hospital_name_hi' => 'एपेक्स हार्ट इंस्टीट्यूट',
                'address' => 'S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380059',
                'address_line1' => 'Mondeal Business Park',
                'address_line2' => 'S.G. Highway, Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380059',
                'latitude' => 23.0380,
                'longitude' => 72.5120,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'FACC', 'Padma Shri'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-1011',
                'about_en' => 'Dr. Tejas Patel is the Chairman and Chief Interventional Cardiologist at Apex Heart Institute, world-renowned for transradial and robotic coronary interventions, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. तेजस पटेल एपेक्स हार्ट इंस्टीट्यूट के अध्यक्ष और मुख्य इंटरवेंशनल कार्डियोलॉजिस्ट तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '079-26842200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Keyur',
                'last_name' => 'Parikh',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Marengo CIMS Hospital',
                'hospital_name_hi' => 'मारेंगो सिम्स अस्पताल',
                'address' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Off Sola Flyover',
                'address_line2' => 'Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0650,
                'longitude' => 72.5200,
                'experience_years' => 40,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FACC', 'FSCAI'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-2022',
                'about_en' => 'Dr. Keyur Parikh is the Chairman of Marengo CIMS Hospital and one of India\'s most senior and respected interventional cardiologists.',
                'about_hi' => 'डॉ. केयूर पारिख मारेंगो सिम्स अस्पताल के अध्यक्ष और भारत के सबसे वरिष्ठ इंटरवेंशनल कार्डियोलॉजिस्ट में से एक हैं।',
                'gender' => 'Male',
                'phone' => '079-48051200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Vikram',
                'last_name' => 'Shah',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Shalby Hospitals',
                'hospital_name_hi' => 'शैल्बी अस्पताल',
                'address' => 'S.G. Highway, Ahmedabad, Gujarat - 380015',
                'address_line1' => 'Opposite Karnavati Club',
                'address_line2' => 'S.G. Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380015',
                'latitude' => 23.0180,
                'longitude' => 72.5050,
                'experience_years' => 35,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'AO Fellowship (Switzerland)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-3033',
                'about_en' => 'Dr. Vikram Shah is the Chairman and Managing Director of Shalby Hospitals, globally renowned for inventing the "Zero Technique" in total knee replacement surgery.',
                'about_hi' => 'डॉ. विक्रम शाह शैल्बी हॉस्पिटल्स के अध्यक्ष और प्रबंध निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '079-40203000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Kaustubh',
                'last_name' => 'Patel',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'HCG Cancer Centre',
                'hospital_name_hi' => 'एचसीजी कैंसर सेंटर',
                'address' => 'Sola - Science City Road, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Sola - Science City Road',
                'address_line2' => 'Near Sola Bridge',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0680,
                'longitude' => 72.5180,
                'experience_years' => 34,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'MCh (Surgical Oncology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-4044',
                'about_en' => 'Dr. Kaustubh Patel is a Senior Head & Neck Surgical Oncologist at HCG Cancer Centre Ahmedabad, expert in complex oral and laryngeal cancer reconstructions.',
                'about_hi' => 'डॉ. कौस्तुभ पटेल एचसीजी कैंसर सेंटर अहमदाबाद में वरिष्ठ हेड एंड नेक सर्जिकल ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-40410101',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sudhir',
                'last_name' => 'Shah',
                'department_name_en' => 'Neurology',
                'department_name_hi' => 'तंत्रिका विज्ञान (न्यूरोलॉजी)',
                'hospital_name_en' => 'Sterling Hospital / SVP',
                'hospital_name_hi' => 'स्टर्लिंग अस्पताल / एसवीपी',
                'address' => 'Sterling Hospital Road, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_line1' => 'Sterling Hospital Road',
                'address_line2' => 'Memnagar',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'latitude' => 23.0450,
                'longitude' => 72.5350,
                'experience_years' => 42,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Neurology)', 'Padma Shri'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-5055',
                'about_en' => 'Dr. Sudhir V. Shah is an eminent Consultant Neurologist, author of numerous books on neurology and cognitive science, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. सुधीर वी. शाह एक प्रख्यात सलाहकार न्यूरोलॉजिस्ट और पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '079-40011111',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Dhiraj',
                'last_name' => 'Boob',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Zydus Hospital',
                'hospital_name_hi' => 'ज़ायडस अस्पताल',
                'address' => 'S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Zydus Hospitals Road',
                'address_line2' => 'Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'latitude' => 23.0550,
                'longitude' => 72.5180,
                'experience_years' => 28,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'Fellowship in Pediatric Intensive Care'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-6066',
                'about_en' => 'Dr. Dhiraj Boob is a Senior Consultant Pediatrician and Pediatric Intensivist at Zydus Hospital Ahmedabad.',
                'about_hi' => 'डॉ. धीरज बूब ज़ायडस अस्पताल अहमदाबाद में वरिष्ठ बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '079-66190201',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Darshana',
                'last_name' => 'Thakker',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Sparsh Women\'s Hospital',
                'hospital_name_hi' => 'स्पर्श विमेंस अस्पताल',
                'address' => 'Navrangpura, Ahmedabad, Gujarat - 380009',
                'address_line1' => 'Navrangpura',
                'address_line2' => 'Near CG Road',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380009',
                'latitude' => 23.0350,
                'longitude' => 72.5550,
                'experience_years' => 28,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-7077',
                'about_en' => 'Dr. Darshana Thakker is a prominent Senior Obstetrician & Gynecologist in Ahmedabad, expert in adolescent gynecology and menopausal healthcare.',
                'about_hi' => 'डॉ. दर्शना ठक्कर अहमदाबाद में एक प्रमुख वरिष्ठ प्रसूति एवं स्त्री रोग विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '079-26565555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Nitin',
                'last_name' => 'Sumant',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'SAL Hospital',
                'hospital_name_hi' => 'साल अस्पताल',
                'address' => 'Drive-in Road, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Drive-in Road',
                'address_line2' => 'Opposite Doordarshan Tower',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'latitude' => 23.0480,
                'longitude' => 72.5250,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FIAGES'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-8088',
                'about_en' => 'Dr. Nitin Sumant is a Senior Consultant Advanced Laparoscopic and GI Surgeon at SAL Hospital Ahmedabad.',
                'about_hi' => 'डॉ. नितिन सुमंत साल अस्पताल अहमदाबाद में वरिष्ठ सलाहकार उन्नत लेप्रोस्कोपिक और जीआई सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-66115600',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Abhay',
                'last_name' => 'Vasavada',
                'department_name_en' => 'Ophthalmology',
                'department_name_hi' => 'नेत्र रोग (ऑप्थल्मोलॉजी)',
                'hospital_name_en' => 'Raghudeep Eye Hospital',
                'hospital_name_hi' => 'रघुदीप आई हॉस्पिटल',
                'address' => 'Gurukul Road, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_line1' => 'Gurukul Road',
                'address_line2' => 'Memnagar',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'latitude' => 23.0460,
                'longitude' => 72.5320,
                'experience_years' => 45,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Ophthalmology)', 'FRCS (England)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-9099',
                'about_en' => 'Dr. Abhay Vasavada is the Founder of Raghudeep Eye Hospital, world-renowned for pediatric cataract surgery and advanced phacoemulsification research.',
                'about_hi' => 'डॉ. अभय वसावड़ा रघुदीप आई हॉस्पिटल के संस्थापक और बाल चिकित्सा मोतियाबिंद सर्जरी के लिए विश्व प्रसिद्ध हैं।',
                'gender' => 'Male',
                'phone' => '079-27492222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Milan',
                'last_name' => 'Chag',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Marengo CIMS Hospital',
                'hospital_name_hi' => 'मारेंगो सिम्स अस्पताल',
                'address' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Off Sola Flyover',
                'address_line2' => 'Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0650,
                'longitude' => 72.5200,
                'experience_years' => 36,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'FACC', 'FESC'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10112',
                'about_en' => 'Dr. Milan Chag is a Managing Director and Senior Interventional Cardiologist at Marengo CIMS Hospital Ahmedabad, with over 3 decades of experience in complex coronary interventions.',
                'about_hi' => 'डॉ. मिलन चाग मारेंगो सिम्स अस्पताल अहमदाबाद में प्रबंध निदेशक और वरिष्ठ इंटरवेंशनल कार्डियोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-48051200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Urmil',
                'last_name' => 'Shah',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Marengo CIMS Hospital',
                'hospital_name_hi' => 'मारेंगो सिम्स अस्पताल',
                'address' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Off Sola Flyover',
                'address_line2' => 'Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0650,
                'longitude' => 72.5200,
                'experience_years' => 32,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'FACC'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10113',
                'about_en' => 'Dr. Urmil Shah is a Senior Interventional Cardiologist at Marengo CIMS Hospital Ahmedabad, specializing in primary angioplasty and structural heart diseases.',
                'about_hi' => 'डॉ. उर्मिल शाह मारेंगो सिम्स अस्पताल अहमदाबाद में वरिष्ठ इंटरवेंशनल कार्डियोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-48051200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Dhaval',
                'last_name' => 'Naik',
                'department_name_en' => 'Cardiothoracic Surgery',
                'department_name_hi' => 'कार्डियोथोरेसिक सर्जरी',
                'hospital_name_en' => 'Marengo CIMS Hospital',
                'hospital_name_hi' => 'मारेंगो सिम्स अस्पताल',
                'address' => 'Off Sola Flyover, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Off Sola Flyover',
                'address_line2' => 'Sola',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0650,
                'longitude' => 72.5200,
                'experience_years' => 26,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'MCh (Cardiothoracic Surgery)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10114',
                'about_en' => 'Dr. Dhaval Naik is a Senior Cardiac Surgeon at Marengo CIMS Hospital, renowned for minimally invasive cardiac surgery and heart transplantation.',
                'about_hi' => 'डॉ. धवल नाइक मारेंगो सिम्स अस्पताल में वरिष्ठ कार्डियक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-48051200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Chirag',
                'last_name' => 'Solanki',
                'department_name_en' => 'Neurosurgery',
                'department_name_hi' => 'न्यूरोसर्जरी',
                'hospital_name_en' => 'Zydus Hospital',
                'hospital_name_hi' => 'ज़ायडस अस्पताल',
                'address' => 'S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Zydus Hospitals Road',
                'address_line2' => 'Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'latitude' => 23.0550,
                'longitude' => 72.5180,
                'experience_years' => 28,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Neurosurgery)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10115',
                'about_en' => 'Dr. Chirag Solanki is a Senior Consultant Neurosurgeon at Zydus Hospital Ahmedabad, expert in micro-neurosurgery and spine surgery.',
                'about_hi' => 'डॉ. चिराग सोलंकी ज़ायडस अस्पताल अहमदाबाद में वरिष्ठ सलाहकार न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-66190201',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Kalpesh',
                'last_name' => 'Shah',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Zydus Hospital',
                'hospital_name_hi' => 'ज़ायडस अस्पताल',
                'address' => 'S.G. Highway, Thaltej, Ahmedabad, Gujarat - 380054',
                'address_line1' => 'Zydus Hospitals Road',
                'address_line2' => 'Thaltej',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380054',
                'latitude' => 23.0550,
                'longitude' => 72.5180,
                'experience_years' => 30,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10116',
                'about_en' => 'Dr. Kalpesh Shah is a Senior Joint Replacement Surgeon at Zydus Hospital Ahmedabad, specializing in complex knee and hip arthroplasty.',
                'about_hi' => 'डॉ. कल्पेश शाह ज़ायडस अस्पताल अहमदाबाद में वरिष्ठ संयुक्त प्रत्यारोपण सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-66190201',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Bharat',
                'last_name' => 'Gadhavi',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'HCG Hospitals',
                'hospital_name_hi' => 'एचसीजी अस्पताल',
                'address' => 'Mithakhali Six Roads, Ellisbridge, Ahmedabad, Gujarat - 380006',
                'address_line1' => 'Mithakhali Six Roads',
                'address_line2' => 'Ellisbridge',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380006',
                'latitude' => 23.0280,
                'longitude' => 72.5650,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10117',
                'about_en' => 'Dr. Bharat Gadhavi is the Medical Director and Senior General Surgeon at HCG Hospitals Ahmedabad.',
                'about_hi' => 'डॉ. भरत गढवी एचसीजी हॉस्पिटल्स अहमदाबाद में चिकित्सा निदेशक और वरिष्ठ जनरल सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-26404142',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Somesh',
                'last_name' => 'Chandra',
                'department_name_en' => 'Surgical Oncology',
                'department_name_hi' => 'सर्जिकल ऑन्कोलॉजी',
                'hospital_name_en' => 'HCG Cancer Centre',
                'hospital_name_hi' => 'एचसीजी कैंसर सेंटर',
                'address' => 'Sola - Science City Road, Sola, Ahmedabad, Gujarat - 380060',
                'address_line1' => 'Sola - Science City Road',
                'address_line2' => 'Near Sola Bridge',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380060',
                'latitude' => 23.0680,
                'longitude' => 72.5180,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Surgical Oncology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10118',
                'about_en' => 'Dr. Somesh Chandra is a Senior Surgical Oncologist at HCG Cancer Centre Ahmedabad, expert in thoracic and GI oncology.',
                'about_hi' => 'डॉ. सोमेश चंद्रा एचसीजी कैंसर सेंटर अहमदाबाद में वरिष्ठ सर्जिकल ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-40410101',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Manoj',
                'last_name' => 'Gumber',
                'department_name_en' => 'Nephrology',
                'department_name_hi' => 'गुर्दा रोग (नेफ्रोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => 'Bhat GIDC Estate, Gandhinagar - Ahmedabad Highway, Ahmedabad, Gujarat - 382428',
                'address_line1' => 'Plot No. 1A, Bhat GIDC Estate',
                'address_line2' => 'Gandhinagar - Ahmedabad Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382428',
                'latitude' => 23.1250,
                'longitude' => 72.6180,
                'experience_years' => 26,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Nephrology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10119',
                'about_en' => 'Dr. Manoj Gumber is a Senior Consultant Nephrologist and Renal Transplant Physician at Apollo Hospitals Ahmedabad.',
                'about_hi' => 'डॉ. मनोज गुम्बर अपोलो हॉस्पिटल्स अहमदाबाद में वरिष्ठ सलाहकार नेफ्रोलॉजिस्ट और गुर्दा प्रत्यारोपण चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '079-66701800',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Abhay',
                'last_name' => 'Khandekar',
                'department_name_en' => 'Urology',
                'department_name_hi' => 'मूत्र रोग (यूरोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => 'Bhat GIDC Estate, Gandhinagar - Ahmedabad Highway, Ahmedabad, Gujarat - 382428',
                'address_line1' => 'Plot No. 1A, Bhat GIDC Estate',
                'address_line2' => 'Gandhinagar - Ahmedabad Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '382428',
                'latitude' => 23.1250,
                'longitude' => 72.6180,
                'experience_years' => 32,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Urology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10120',
                'about_en' => 'Dr. Abhay Khandekar is a Senior Consultant Urologist and Uro-Oncologist at Apollo Hospitals Ahmedabad.',
                'about_hi' => 'डॉ. अभय खांडेकर अपोलो हॉस्पिटल्स अहमदाबाद में वरिष्ठ सलाहकार यूरोलॉजिस्ट और यूरो-ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-66701800',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Pravin',
                'last_name' => 'Patel',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'Sterling Hospital',
                'hospital_name_hi' => 'स्टर्लिंग अस्पताल',
                'address' => 'Sterling Hospital Road, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_line1' => 'Sterling Hospital Road',
                'address_line2' => 'Near Gurukul, Memnagar',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'latitude' => 23.0450,
                'longitude' => 72.5350,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10121',
                'about_en' => 'Dr. Pravin Patel is a Senior Consultant Gastroenterologist and Hepatologist at Sterling Hospital Ahmedabad.',
                'about_hi' => 'डॉ. प्रवीन पटेल स्टर्लिंग अस्पताल अहमदाबाद में वरिष्ठ सलाहकार गैस्ट्रोएंटरोलॉजिस्ट और हेपेटोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '079-40011111',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Alok',
                'last_name' => 'Ahuja',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'Sterling Hospital',
                'hospital_name_hi' => 'स्टर्लिंग अस्पताल',
                'address' => 'Sterling Hospital Road, Memnagar, Ahmedabad, Gujarat - 380052',
                'address_line1' => 'Sterling Hospital Road',
                'address_line2' => 'Near Gurukul, Memnagar',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380052',
                'latitude' => 23.0450,
                'longitude' => 72.5350,
                'experience_years' => 30,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10122',
                'about_en' => 'Dr. Alok Ahuja is a Senior Consultant Advanced Laparoscopic Surgeon at Sterling Hospital Ahmedabad.',
                'about_hi' => 'डॉ. आलोक आहूजा स्टर्लिंग अस्पताल अहमदाबाद में वरिष्ठ सलाहकार उन्नत लेप्रोस्कोपिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-40011111',
                'is_verified' => true,
            ],
            [
                'first_name' => 'R. K.',
                'last_name' => 'Patel',
                'department_name_en' => 'Pulmonology',
                'department_name_hi' => 'श्वसन रोग (पल्मोनोलॉजी)',
                'hospital_name_en' => 'Civil Hospital Ahmedabad',
                'hospital_name_hi' => 'सिविल अस्पताल अहमदाबाद',
                'address' => 'Civil Hospital Campus, Asarwa, Ahmedabad, Gujarat - 380016',
                'address_line1' => 'Civil Hospital Campus',
                'address_line2' => 'Asarwa',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380016',
                'latitude' => 23.0520,
                'longitude' => 72.6030,
                'experience_years' => 36,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Pulmonary Medicine)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10123',
                'about_en' => 'Dr. R. K. Patel is a Senior Professor and Head of Pulmonology at Civil Hospital Ahmedabad, expert in TB and chest diseases.',
                'about_hi' => 'डॉ. आर. के. पटेल सिविल अस्पताल अहमदाबाद में वरिष्ठ प्रोफेसर और पल्मोनोलॉजी के प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '079-22683721',
                'is_verified' => true,
            ],
            [
                'first_name' => 'M. M.',
                'last_name' => 'Prabhakar',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Civil Hospital Ahmedabad',
                'hospital_name_hi' => 'सिविल अस्पताल अहमदाबाद',
                'address' => 'Civil Hospital Campus, Asarwa, Ahmedabad, Gujarat - 380016',
                'address_line1' => 'Civil Hospital Campus',
                'address_line2' => 'Asarwa',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380016',
                'latitude' => 23.0520,
                'longitude' => 72.6030,
                'experience_years' => 40,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10124',
                'about_en' => 'Dr. M. M. Prabhakar is a Senior Professor of Orthopedics and Medical Superintendent at Civil Hospital Ahmedabad.',
                'about_hi' => 'डॉ. एम. एम. प्रभाकर सिविल अस्पताल अहमदाबाद में ऑर्थोपेडिक्स के वरिष्ठ प्रोफेसर और चिकित्सा अधीक्षक हैं।',
                'gender' => 'Male',
                'phone' => '079-22683721',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Neeraj',
                'last_name' => 'Vasavada',
                'department_name_en' => 'Spine Surgery',
                'department_name_hi' => 'रीढ़ की हड्डी की सर्जरी (स्पाइन सर्जरी)',
                'hospital_name_en' => 'Shalby Hospital',
                'hospital_name_hi' => 'शैल्बी अस्पताल',
                'address' => 'S.G. Highway, Ahmedabad, Gujarat - 380015',
                'address_line1' => 'Opposite Karnavati Club',
                'address_line2' => 'S.G. Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380015',
                'latitude' => 23.0180,
                'longitude' => 72.5050,
                'experience_years' => 28,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'Fellowship in Spine Surgery'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10125',
                'about_en' => 'Dr. Neeraj Vasavada is a Senior Consultant Spine Surgeon at Shalby Hospital Ahmedabad, expert in minimally invasive spine surgery.',
                'about_hi' => 'डॉ. नीरज वसावड़ा शैल्बी अस्पताल अहमदाबाद में वरिष्ठ सलाहकार स्पाइन सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '079-40203000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'J. A.',
                'last_name' => 'Thakkar',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Shardaben Hospital',
                'hospital_name_hi' => 'शारदाबेन अस्पताल',
                'address' => 'Saraspur, Ahmedabad, Gujarat - 380018',
                'address_line1' => 'Saraspur',
                'address_line2' => 'Near Railway Station',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380018',
                'latitude' => 23.0310,
                'longitude' => 72.6150,
                'experience_years' => 34,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10126',
                'about_en' => 'Dr. J. A. Thakkar is a Senior Consultant Pediatrician at Shardaben Hospital Ahmedabad.',
                'about_hi' => 'डॉ. जे. ए. ठक्कर शारदाबेन अस्पताल अहमदाबाद में वरिष्ठ बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '079-22923515',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Hemant',
                'last_name' => 'Patel',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Rajasthan Hospital',
                'hospital_name_hi' => 'राजस्थान अस्पताल',
                'address' => 'Shahibaug Road, Shahibaug, Ahmedabad, Gujarat - 380004',
                'address_line1' => 'Shahibaug Road',
                'address_line2' => 'Shahibaug',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'pincode' => '380004',
                'latitude' => 23.0520,
                'longitude' => 72.5950,
                'experience_years' => 32,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)'],
                'medical_council' => 'Gujarat Medical Council (GMC)',
                'registration_number' => 'GMC-10127',
                'about_en' => 'Dr. Hemant Patel is a Senior Obstetrician and Gynecologist at Rajasthan Hospital Ahmedabad.',
                'about_hi' => 'डॉ. हेमंत पटेल राजस्थान अस्पताल अहमदाबाद में वरिष्ठ प्रसूति एवं स्त्री रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '079-22866311',
                'is_verified' => true,
            ],
        ];
    }
}
