<?php

namespace App\Services;

class BangaloreScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (!in_array(strtolower(trim($cityName)), ['bangalore', 'bengaluru'])) {
            return [];
        }

        return [
            [
                'name_en' => 'NIMHANS Blood Bank',
                'name_hi' => 'निमहांस ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560029',
                'address_en' => 'Hosur Road, Lakkasandra, Wilson Garden, Bangalore, Karnataka - 560029',
                'address_hi' => 'होसुर रोड, लक्कासंद्रा, विल्सन गार्डन, बैंगलोर, कर्नाटक - 560029',
                'country_code' => '+91',
                'phone' => '080-26995000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26995000',
                'email' => 'bloodbank@nimhans.ac.in',
                'website' => 'https://nimhans.ac.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / NIMHANS Registry',
                'source_url' => 'https://nimhans.ac.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Victoria Hospital Blood Bank (BMCRI)',
                'name_hi' => 'विक्टोरिया अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560002',
                'address_en' => 'Fort Road, Near City Market, Bangalore, Karnataka - 560002',
                'address_hi' => 'फोर्ट रोड, सिटी मार्केट के पास, बैंगलोर, कर्नाटक - 560002',
                'country_code' => '+91',
                'phone' => '080-26701150',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26701150',
                'email' => 'victoriabloodbank@bmcri.org',
                'website' => 'https://bmcri.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Victoria Registry',
                'source_url' => 'https://bmcri.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Manipal Hospital Blood Bank Old Airport Road',
                'name_hi' => 'मणिपाल अस्पताल ब्लड बैंक ओल्ड एयरपोर्ट रोड',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560017',
                'address_en' => '98, HAL Old Airport Road, Kodihalli, Bangalore, Karnataka - 560017',
                'address_hi' => '98, एचएएल ओल्ड एयरपोर्ट रोड, कोडिहल्ली, बैंगलोर, कर्नाटक - 560017',
                'country_code' => '+91',
                'phone' => '080-25024444',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-25024444',
                'email' => 'bloodbank.oar@manipalhospitals.com',
                'website' => 'https://manipalhospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Manipal OAR Registry',
                'source_url' => 'https://manipalhospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'St. John\'s Medical College Blood Bank',
                'name_hi' => 'सेंट जॉन्स मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560034',
                'address_en' => 'Sarjapur Road, John Nagar, Koramangala, Bangalore, Karnataka - 560034',
                'address_hi' => 'सरजापुर रोड, जॉन नगर, कोरमंगला, बैंगलोर, कर्नाटक - 560034',
                'country_code' => '+91',
                'phone' => '080-22065000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-22065000',
                'email' => 'bloodbank@stjohns.in',
                'website' => 'https://stjohns.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / St Johns Registry',
                'source_url' => 'https://stjohns.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Fortis Hospital Blood Bank Bannerghatta',
                'name_hi' => 'फोर्टिस अस्पताल ब्लड बैंक बन्नेरघट्टा',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'address_en' => '154/9, Bannerghatta Road, Opposite IIM-B, Bangalore, Karnataka - 560076',
                'address_hi' => '154/9, बन्नेरघट्टा रोड, आईआईएम-बी के सामने, बैंगलोर, कर्नाटक - 560076',
                'country_code' => '+91',
                'phone' => '080-66214444',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-66214444',
                'email' => 'bloodbank.bgroad@fortishealthcare.com',
                'website' => 'https://fortishealthcare.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Fortis BG Registry',
                'source_url' => 'https://fortishealthcare.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Apollo Hospitals Blood Bank Bannerghatta',
                'name_hi' => 'अपोलो अस्पताल ब्लड बैंक बन्नेरघट्टा',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'address_en' => '154/11, Bannerghatta Road, Near IIM-B, Bangalore, Karnataka - 560076',
                'address_hi' => '154/11, बन्नेरघट्टा रोड, आईआईएम-बी के पास, बैंगलोर, कर्नाटक - 560076',
                'country_code' => '+91',
                'phone' => '080-26304050',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26304050',
                'email' => 'bloodbank_bgroad@apollohospitals.com',
                'website' => 'https://apollohospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Apollo BG Registry',
                'source_url' => 'https://apollohospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Rotary Bangalore TTK Blood Bank',
                'name_hi' => 'रोटरी बैंगलोर टीटीके ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560038',
                'address_en' => 'Binnamangala, 1st Stage, Indiranagar, Bangalore, Karnataka - 560038',
                'address_hi' => 'बिन्नामंगला, पहला चरण, इंदिरानगर, बैंगलोर, कर्नाटक - 560038',
                'country_code' => '+91',
                'phone' => '080-25287903',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-25287903',
                'email' => 'contact@rotaryttkbloodbank.org',
                'website' => 'https://rotaryttkbloodbank.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Rotary TTK Registry',
                'source_url' => 'https://rotaryttkbloodbank.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Lions Blood Bank Bangalore',
                'name_hi' => 'लायंस ब्लड बैंक बैंगलोर',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560004',
                'address_en' => '4, Lions Eye Hospital Road, Near National College, Basavanagudi, Bangalore, Karnataka - 560004',
                'address_hi' => '4, लायंस आई हॉस्पिटल रोड, नेशनल कॉलेज के पास, बसवनगुडी, बैंगलोर, कर्नाटक - 560004',
                'country_code' => '+91',
                'phone' => '080-26601234',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26601234',
                'email' => 'contact@lionsbloodbankbangalore.org',
                'website' => 'https://lionsbloodbankbangalore.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Lions Registry',
                'source_url' => 'https://lionsbloodbankbangalore.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Bowring & Lady Curzon Hospital Blood Bank',
                'name_hi' => 'बौरिंग एवं लेडी कर्जन अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'address_en' => 'Lady Curzon Road, Tasker Town, Shivaji Nagar, Bangalore, Karnataka - 560001',
                'address_hi' => 'लेडी कर्जन रोड, टास्कर टाउन, शिवाजी नगर, बैंगलोर, कर्नाटक - 560001',
                'country_code' => '+91',
                'phone' => '080-25591325',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-25591325',
                'email' => 'bowringbloodbank@bmcri.org',
                'website' => 'https://bmcri.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Bowring Registry',
                'source_url' => 'https://bmcri.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Sakra World Hospital Blood Bank',
                'name_hi' => 'सकरा वर्ल्ड अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560103',
                'address_en' => 'SY No 52/2 & 52/3, Devarabeesanahalli, Outer Ring Road, Marathahalli, Bangalore, Karnataka - 560103',
                'address_hi' => 'एसवाई नंबर 52/2 और 52/3, देवराबीसनहल्ली, आउटर रिंग रोड, मराठाहल्ली, बैंगलोर, कर्नाटक - 560103',
                'country_code' => '+91',
                'phone' => '080-49694969',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-49694969',
                'email' => 'bloodbank@sakraworldhospital.com',
                'website' => 'https://sakraworldhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Sakra Registry',
                'source_url' => 'https://sakraworldhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'KC General Hospital Blood Bank',
                'name_hi' => 'केसी जनरल अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560003',
                'address_en' => 'Malleswaram Circle, Malleswaram, Bangalore, Karnataka - 560003',
                'address_hi' => 'मल्लेश्वरम सर्किल, मल्लेश्वरम, बैंगलोर, कर्नाटक - 560003',
                'country_code' => '+91',
                'phone' => '080-23341771',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-23341771',
                'email' => 'bloodbank@kcgeneralhospital.gov.in',
                'website' => 'https://karnataka.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => false,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Government Registry',
                'source_url' => 'https://karnataka.gov.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Rashtrotthana Blood Bank',
                'name_hi' => 'रास्ट्रोत्थान ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560019',
                'address_en' => 'Kempegowda Nagar, Gavipuram Extension, Bangalore, Karnataka - 560019',
                'address_hi' => 'केम्पेगौड़ा नगर, गवीपुरम एक्सटेंशन, बैंगलोर, कर्नाटक - 560019',
                'country_code' => '+91',
                'phone' => '080-26612730',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26612730',
                'email' => 'bloodbank@rashtrotthana.org',
                'website' => 'https://rashtrotthana.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Rashtrotthana Registry',
                'source_url' => 'https://rashtrotthana.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Narayana Health City Blood Bank',
                'name_hi' => 'नारायणा हेल्थ सिटी ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560099',
                'address_en' => '258/A, Bommasandra Industrial Area, Hosur Road, Bangalore, Karnataka - 560099',
                'address_hi' => '258/A, बोम्मसंद्रा इंडस्ट्रियल एरिया, होसुर रोड, बैंगलोर, कर्नाटक - 560099',
                'country_code' => '+91',
                'phone' => '080-71222222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-71222222',
                'email' => 'bloodbank@narayanahealth.org',
                'website' => 'https://narayanahealth.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Narayana Registry',
                'source_url' => 'https://narayanahealth.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'MS Ramaiah Memorial Hospital Blood Bank',
                'name_hi' => 'एमएस रमैया मेमोरियल अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560054',
                'address_en' => 'MSR Nagar, MSRIT Post, New BEL Road, Mathikere, Bangalore, Karnataka - 560054',
                'address_hi' => 'एमएसआर नगर, न्यू बीईएल रोड, मथिकेरे, बैंगलोर, कर्नाटक - 560054',
                'country_code' => '+91',
                'phone' => '080-23608888',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-23608888',
                'email' => 'bloodbank@msrmh.com',
                'website' => 'https://msrmh.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Ramaiah Registry',
                'source_url' => 'https://msrmh.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'BGS Gleneagles Global Hospital Blood Bank',
                'name_hi' => 'बीजीएस ग्लेनीगल्स ग्लोबल अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560060',
                'address_en' => '67, Uttarahalli Road, Kengeri, Bangalore, Karnataka - 560060',
                'address_hi' => '67, उत्तरहल्ली रोड, केंगेरी, बैंगलोर, कर्नाटक - 560060',
                'country_code' => '+91',
                'phone' => '080-26255555',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-26255555',
                'email' => 'bloodbank.bgs@globalhospitalsindia.com',
                'website' => 'https://globalhospitalsindia.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Gleneagles Registry',
                'source_url' => 'https://globalhospitalsindia.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Aster CMI Hospital Blood Bank',
                'name_hi' => 'एस्टर सीएमआई अस्पताल ब्लड बैंक',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560092',
                'address_en' => '43/2, New Airport Road, NH 44, Sahakar Nagar, Hebbal, Bangalore, Karnataka - 560092',
                'address_hi' => '43/2, न्यू एयरपोर्ट रोड, एनएच 44, सहकार नगर, हेब्बल, बैंगलोर, कर्नाटक - 560092',
                'country_code' => '+91',
                'phone' => '080-43420100',
                'emergency_country_code' => '+91',
                'emergency_phone' => '080-43420100',
                'email' => 'bloodbank.cmi@asterhospital.com',
                'website' => 'https://asterhospitals.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Aster Registry',
                'source_url' => 'https://asterhospitals.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (!in_array(strtolower(trim($cityName)), ['bangalore', 'bengaluru'])) {
            return [];
        }

        return [
            [
                'name_en' => 'NIMHANS (National Institute of Mental Health and Neuro Sciences)',
                'name_hi' => 'निमहांस (राष्ट्रीय मानसिक स्वास्थ्य एवं तंत्रिका विज्ञान संस्थान)',
                'type' => 'Government Hospital',
                'address' => 'Hosur Road, Lakkasandra, Wilson Garden, Bangalore, Karnataka - 560029',
                'address_line1' => 'Hosur Road, Lakkasandra',
                'address_line2' => 'Wilson Garden',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560029',
                'emergency_phone' => '080-26995000',
                'emergency_country_code' => '+91',
                'latitude' => 12.9375,
                'longitude' => 77.5950,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Victoria Hospital',
                'name_hi' => 'विक्टोरिया अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Fort Road, Near City Market, Bangalore, Karnataka - 560002',
                'address_line1' => 'Fort Road',
                'address_line2' => 'Near City Market',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560002',
                'emergency_phone' => '080-26701150',
                'emergency_country_code' => '+91',
                'latitude' => 12.9630,
                'longitude' => 77.5750,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS', 'Yeshasvini'],
            ],
            [
                'name_en' => 'Manipal Hospital, Old Airport Road',
                'name_hi' => 'मणिपाल अस्पताल, ओल्ड एयरपोर्ट रोड',
                'type' => 'Private Hospital',
                'address' => '98, HAL Old Airport Road, Kodihalli, Bangalore, Karnataka - 560017',
                'address_line1' => '98, HAL Old Airport Road',
                'address_line2' => 'Kodihalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560017',
                'emergency_phone' => '080-25024444',
                'emergency_country_code' => '+91',
                'latitude' => 12.9560,
                'longitude' => 77.6520,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Fortis Hospital, Bannerghatta Road',
                'name_hi' => 'फोर्टिस अस्पताल, बन्नेरघट्टा रोड',
                'type' => 'Private Hospital',
                'address' => '154/9, Bannerghatta Road, Opposite IIM-B, Bangalore, Karnataka - 560076',
                'address_line1' => '154/9, Bannerghatta Road',
                'address_line2' => 'Opposite IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'emergency_phone' => '080-66214444',
                'emergency_country_code' => '+91',
                'latitude' => 12.8940,
                'longitude' => 77.6010,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ICICI Lombard TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Apollo Hospitals, Bannerghatta Road',
                'name_hi' => 'अपोलो अस्पताल, बन्नेरघट्टा रोड',
                'type' => 'Private Hospital',
                'address' => '154/11, Bannerghatta Road, Near IIM-B, Bangalore, Karnataka - 560076',
                'address_line1' => '154/11, Bannerghatta Road',
                'address_line2' => 'Near IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'emergency_phone' => '080-26304050',
                'emergency_country_code' => '+91',
                'latitude' => 12.8950,
                'longitude' => 77.6020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'St. John\'s Medical College Hospital',
                'name_hi' => 'सेंट जॉन्स मेडिकल कॉलेज अस्पताल',
                'type' => 'Semi-Private Hospital',
                'address' => 'Sarjapur Road, John Nagar, Koramangala, Bangalore, Karnataka - 560034',
                'address_line1' => 'Sarjapur Road, John Nagar',
                'address_line2' => 'Koramangala',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560034',
                'emergency_phone' => '080-22065000',
                'emergency_country_code' => '+91',
                'latitude' => 12.9310,
                'longitude' => 77.6310,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Narayana Health City, Bommasandra',
                'name_hi' => 'नारायणा हेल्थ सिटी, बोम्मसंद्रा',
                'type' => 'Private Hospital',
                'address' => '258/A, Bommasandra Industrial Area, Hosur Road, Bangalore, Karnataka - 560099',
                'address_line1' => '258/A, Bommasandra Industrial Area',
                'address_line2' => 'Hosur Road',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560099',
                'emergency_phone' => '080-71222222',
                'emergency_country_code' => '+91',
                'latitude' => 12.8150,
                'longitude' => 77.6850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Aster CMI Hospital, Hebbal',
                'name_hi' => 'एस्टर सीएमआई अस्पताल, हेब्बल',
                'type' => 'Private Hospital',
                'address' => '43/2, New Airport Road, NH 44, Sahakar Nagar, Hebbal, Bangalore, Karnataka - 560092',
                'address_line1' => '43/2, New Airport Road, NH 44',
                'address_line2' => 'Sahakar Nagar, Hebbal',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560092',
                'emergency_phone' => '080-43420100',
                'emergency_country_code' => '+91',
                'latitude' => 13.0530,
                'longitude' => 77.5920,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ICICI Lombard TPA', 'Max Bupa TPA'],
            ],
            [
                'name_en' => 'Sakra World Hospital',
                'name_hi' => 'सकरा वर्ल्ड अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'SY No 52/2 & 52/3, Devarabeesanahalli, Outer Ring Road, Marathahalli, Bangalore, Karnataka - 560103',
                'address_line1' => 'SY No 52/2 & 52/3, Devarabeesanahalli',
                'address_line2' => 'Outer Ring Road, Marathahalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560103',
                'emergency_phone' => '080-49694969',
                'emergency_country_code' => '+91',
                'latitude' => 12.9320,
                'longitude' => 77.6850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Ramaiah Memorial Hospital',
                'name_hi' => 'रमैया मेमोरियल अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'MSR Nagar, MSRIT Post, New BEL Road, Mathikere, Bangalore, Karnataka - 560054',
                'address_line1' => 'MSR Nagar, MSRIT Post',
                'address_line2' => 'New BEL Road, Mathikere',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560054',
                'emergency_phone' => '080-23608888',
                'emergency_country_code' => '+91',
                'latitude' => 13.0300,
                'longitude' => 77.5650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Bowring & Lady Curzon Hospital',
                'name_hi' => 'बौरिंग एवं लेडी कर्जन अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Lady Curzon Road, Tasker Town, Shivaji Nagar, Bangalore, Karnataka - 560001',
                'address_line1' => 'Lady Curzon Road',
                'address_line2' => 'Tasker Town, Shivaji Nagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'emergency_phone' => '080-25591325',
                'emergency_country_code' => '+91',
                'latitude' => 12.9820,
                'longitude' => 77.6050,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS'],
            ],
            [
                'name_en' => 'Sparsh Hospital, Yeshwanthpur',
                'name_hi' => 'स्पर्श अस्पताल, यशवंतपुर',
                'type' => 'Private Hospital',
                'address' => '4/1, Tumkur Road, Yeshwanthpur, Bangalore, Karnataka - 560022',
                'address_line1' => '4/1, Tumkur Road',
                'address_line2' => 'Yeshwanthpur',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560022',
                'emergency_phone' => '080-61222000',
                'emergency_country_code' => '+91',
                'latitude' => 13.0250,
                'longitude' => 77.5450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'KC General Hospital',
                'name_hi' => 'केसी जनरल अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Malleswaram Circle, Malleswaram, Bangalore, Karnataka - 560003',
                'address_line1' => 'Malleswaram Circle',
                'address_line2' => 'Malleswaram',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560003',
                'emergency_phone' => '080-23341771',
                'emergency_country_code' => '+91',
                'latitude' => 12.9920,
                'longitude' => 77.5710,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'BGS Gleneagles Global Hospital',
                'name_hi' => 'बीजीएस ग्लेनीगल्स ग्लोबल अस्पताल',
                'type' => 'Private Hospital',
                'address' => '67, Uttarahalli Road, Kengeri, Bangalore, Karnataka - 560060',
                'address_line1' => '67, Uttarahalli Road',
                'address_line2' => 'Kengeri',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560060',
                'emergency_phone' => '080-26255555',
                'emergency_country_code' => '+91',
                'latitude' => 12.9050,
                'longitude' => 77.5020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Fortis Hospital, Cunningham Road',
                'name_hi' => 'फोर्टिस अस्पताल, कनिंघम रोड',
                'type' => 'Private Hospital',
                'address' => '14, Cunningham Road, Vasanth Nagar, Bangalore, Karnataka - 560052',
                'address_line1' => '14, Cunningham Road',
                'address_line2' => 'Vasanth Nagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560052',
                'emergency_phone' => '080-41994444',
                'emergency_country_code' => '+91',
                'latitude' => 12.9860,
                'longitude' => 77.5950,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Manipal Hospital, Whitefield',
                'name_hi' => 'मणिपाल अस्पताल, व्हाइटफील्ड',
                'type' => 'Private Hospital',
                'address' => '143, 212-215, EPIP Zone, Whitefield, Bangalore, Karnataka - 560066',
                'address_line1' => '143, 212-215, EPIP Zone',
                'address_line2' => 'Whitefield',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560066',
                'emergency_phone' => '080-30430430',
                'emergency_country_code' => '+91',
                'latitude' => 12.9810,
                'longitude' => 77.7280,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Apollo Hospitals, Jayanagar',
                'name_hi' => 'अपोलो अस्पताल, जयनगर',
                'type' => 'Private Hospital',
                'address' => '21/2, 14th Cross, 3rd Block, Jayanagar, Bangalore, Karnataka - 560011',
                'address_line1' => '21/2, 14th Cross, 3rd Block',
                'address_line2' => 'Jayanagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560011',
                'emergency_phone' => '080-26304050',
                'emergency_country_code' => '+91',
                'latitude' => 12.9310,
                'longitude' => 77.5830,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Sita Bhateja Speciality Hospital',
                'name_hi' => 'सीता भटेजा स्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => '8-9, O\'Shaughnessy Road, Langford Gardens, Bangalore, Karnataka - 560025',
                'address_line1' => '8-9, O\'Shaughnessy Road',
                'address_line2' => 'Langford Gardens',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560025',
                'emergency_phone' => '080-41144444',
                'emergency_country_code' => '+91',
                'latitude' => 12.9580,
                'longitude' => 77.6010,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Max Bupa TPA'],
            ],
            [
                'name_en' => 'St. Martha\'s Hospital',
                'name_hi' => 'सेंट मार्था अस्पताल',
                'type' => 'Semi-Private Hospital',
                'address' => '5, Nrupathunga Road, Opposite RBI, Bangalore, Karnataka - 560001',
                'address_line1' => '5, Nrupathunga Road',
                'address_line2' => 'Opposite RBI',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'emergency_phone' => '080-22275081',
                'emergency_country_code' => '+91',
                'latitude' => 12.9750,
                'longitude' => 77.5880,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Baptist Hospital Bangalore',
                'name_hi' => 'बैपटिस्ट अस्पताल बैंगलोर',
                'type' => 'Semi-Private Hospital',
                'address' => 'Bellary Road, Hebbal, Bangalore, Karnataka - 560024',
                'address_line1' => 'Bellary Road, Hebbal',
                'address_line2' => 'Near Hebbal Flyover',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560024',
                'emergency_phone' => '080-22024700',
                'emergency_country_code' => '+91',
                'latitude' => 13.0280,
                'longitude' => 77.5910,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ECHS', 'Care Health TPA'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (!in_array(strtolower(trim($cityName)), ['bangalore', 'bengaluru'])) {
            return [];
        }

        return [
            [
                'first_name' => 'Devi',
                'last_name' => 'Shetty',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Narayana Health City',
                'hospital_name_hi' => 'नारायणा हेल्थ सिटी',
                'address' => '258/A, Bommasandra Industrial Area, Hosur Road, Bangalore, Karnataka - 560099',
                'address_line1' => '258/A, Bommasandra Industrial Area',
                'address_line2' => 'Hosur Road',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560099',
                'latitude' => 12.8150,
                'longitude' => 77.6850,
                'experience_years' => 45,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'FRCS (England)', 'Padma Bhushan', 'Padma Shri'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-1023',
                'about_en' => 'Dr. Devi Prasad Shetty is the Chairman and Founder of Narayana Health, a globally renowned cardiac surgeon who has performed over 15,000 heart surgeries.',
                'about_hi' => 'डॉ. देवी प्रसाद शेट्टी नारायणा हेल्थ के अध्यक्ष और संस्थापक तथा विश्व प्रसिद्ध कार्डियक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '080-71222222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sudarshan',
                'last_name' => 'Ballal',
                'department_name_en' => 'Urology',
                'department_name_hi' => 'मूत्र रोग (यूरोलॉजी)',
                'hospital_name_en' => 'Manipal Hospital',
                'hospital_name_hi' => 'मणिपाल अस्पताल',
                'address' => '98, HAL Old Airport Road, Kodihalli, Bangalore, Karnataka - 560017',
                'address_line1' => '98, HAL Old Airport Road',
                'address_line2' => 'Kodihalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560017',
                'latitude' => 12.9560,
                'longitude' => 77.6520,
                'experience_years' => 42,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRCP (London)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-2045',
                'about_en' => 'Dr. Sudarshan Ballal is the Chairman of Manipal Hospitals and a renowned Nephrologist/Urologist, pioneer in kidney transplantation in Karnataka.',
                'about_hi' => 'डॉ. सुदर्शन बल्लाल मणिपाल हॉस्पिटल्स के अध्यक्ष और कर्नाटक में किडनी प्रत्यारोपण के प्रणेता हैं।',
                'gender' => 'Male',
                'phone' => '080-25024444',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Vivek',
                'last_name' => 'Jawali',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Fortis Hospital',
                'hospital_name_hi' => 'फोर्टिस अस्पताल',
                'address' => '154/9, Bannerghatta Road, Bangalore, Karnataka - 560076',
                'address_line1' => '154/9, Bannerghatta Road',
                'address_line2' => 'Opposite IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'latitude' => 12.8940,
                'longitude' => 77.6010,
                'experience_years' => 40,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Cardiothoracic Surgery)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-3067',
                'about_en' => 'Dr. Vivek Jawali is Chairman of Cardiothoracic and Vascular Surgery at Fortis Hospitals Bangalore, pioneer of beating heart bypass surgery in India.',
                'about_hi' => 'डॉ. विवेक जवाली फोर्टिस हॉस्पिटल्स बैंगलोर में कार्डियोथोरेसिक और वैस्कुलर सर्जरी के अध्यक्ष हैं।',
                'gender' => 'Male',
                'phone' => '080-66214444',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sharan',
                'last_name' => 'Patil',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Sparsh Hospital',
                'hospital_name_hi' => 'स्पर्श अस्पताल',
                'address' => '4/1, Tumkur Road, Yeshwanthpur, Bangalore, Karnataka - 560022',
                'address_line1' => '4/1, Tumkur Road',
                'address_line2' => 'Yeshwanthpur',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560022',
                'latitude' => 13.0250,
                'longitude' => 77.5450,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'FRCS (England)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-4089',
                'about_en' => 'Dr. Sharan Patil is the Chairman and Founder of Sparsh Hospital, globally acclaimed for complex pediatric and adult orthopedic reconstructions.',
                'about_hi' => 'डॉ. शरण पाटिल स्पर्श अस्पताल के अध्यक्ष और संस्थापक हैं।',
                'gender' => 'Male',
                'phone' => '080-61222000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Pratima',
                'last_name' => 'Murthy',
                'department_name_en' => 'Psychiatry',
                'department_name_hi' => 'मनोरोग (साइकेट्री)',
                'hospital_name_en' => 'NIMHANS',
                'hospital_name_hi' => 'निमहांस',
                'address' => 'Hosur Road, Lakkasandra, Bangalore, Karnataka - 560029',
                'address_line1' => 'Hosur Road, Lakkasandra',
                'address_line2' => 'Wilson Garden',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560029',
                'latitude' => 12.9375,
                'longitude' => 77.5950,
                'experience_years' => 38,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Psychiatry)', 'DPM', 'FRCP'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-5101',
                'about_en' => 'Dr. Pratima Murthy is Director of NIMHANS Bangalore, globally respected for her pioneering research in addiction psychiatry and mental health healthcare.',
                'about_hi' => 'डॉ. प्रतिमा मूर्ति निमहांस बैंगलोर की निदेशक और व्यसन मनोरोग तथा मानसिक स्वास्थ्य में अपने अग्रणी शोध के लिए विश्व स्तर पर सम्मानित हैं।',
                'gender' => 'Female',
                'phone' => '080-26995000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Kamini',
                'last_name' => 'Rao',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Milann Fertility Centre',
                'hospital_name_hi' => 'मिलान फर्टिलिटी सेंटर',
                'address' => '7, East Park Road, Kumara Park East, Bangalore, Karnataka - 560001',
                'address_line1' => '7, East Park Road',
                'address_line2' => 'Kumara Park East',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'latitude' => 12.9850,
                'longitude' => 77.5850,
                'experience_years' => 42,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'FRCOG (UK)', 'Padma Shri'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-6123',
                'about_en' => 'Dr. Kamini Rao is a pioneer in Assisted Reproduction in India, Founder of Milann Fertility Centre, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. कामिनी राव भारत में असिस्टेड रिप्रोडक्शन की प्रणेता, मिलान फर्टिलिटी सेंटर की संस्थापक और पद्म श्री से सम्मानित हैं।',
                'gender' => 'Female',
                'phone' => '080-22265000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Soman',
                'last_name' => 'Raju',
                'department_name_en' => 'Neurology',
                'department_name_hi' => 'तंत्रिका विज्ञान (न्यूरोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => '154/11, Bannerghatta Road, Bangalore, Karnataka - 560076',
                'address_line1' => '154/11, Bannerghatta Road',
                'address_line2' => 'Near IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'latitude' => 12.8950,
                'longitude' => 77.6020,
                'experience_years' => 36,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Neurology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-7145',
                'about_en' => 'Dr. Soman Raju is a Senior Consultant Neurologist at Apollo Hospitals Bangalore, specializing in stroke management and epilepsy.',
                'about_hi' => 'डॉ. सोमन राजू अपोलो हॉस्पिटल्स बैंगलोर में एक वरिष्ठ सलाहकार न्यूरोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '080-26304050',
                'is_verified' => true,
            ],
            [
                'first_name' => 'H. S.',
                'last_name' => 'Ballal',
                'department_name_en' => 'General Physician',
                'department_name_hi' => 'सामान्य चिकित्सक (जनरल फिजिशियन)',
                'hospital_name_en' => 'Manipal Hospital',
                'hospital_name_hi' => 'मणिपाल अस्पताल',
                'address' => '98, HAL Old Airport Road, Bangalore, Karnataka - 560017',
                'address_line1' => '98, HAL Old Airport Road',
                'address_line2' => 'Kodihalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560017',
                'latitude' => 12.9560,
                'longitude' => 77.6520,
                'experience_years' => 45,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (General Medicine)', 'FCCP'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-8167',
                'about_en' => 'Dr. H. S. Ballal is a highly respected Senior Consultant Physician and Pro Chancellor of Manipal Academy of Higher Education.',
                'about_hi' => 'डॉ. एच. एस. बल्लाल एक अत्यधिक सम्मानित वरिष्ठ सलाहकार चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '080-25024444',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Bhujang',
                'last_name' => 'Pai',
                'department_name_en' => 'Ophthalmology',
                'department_name_hi' => 'नेत्र रोग (ऑप्थल्मोलॉजी)',
                'hospital_name_en' => 'Nethradhama Super Speciality Eye Hospital',
                'hospital_name_hi' => 'नेत्रधाम सुपर स्पेशलिटी आई हॉस्पिटल',
                'address' => '256/14, Kanakapura Road, Jayanagar 7th Block, Bangalore, Karnataka - 560082',
                'address_line1' => '256/14, Kanakapura Road',
                'address_line2' => 'Jayanagar 7th Block',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560082',
                'latitude' => 12.9250,
                'longitude' => 77.5800,
                'experience_years' => 32,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (Ophthalmology)', 'FRCS'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-9189',
                'about_en' => 'Dr. Bhujang Pai is Chairman of Nethradhama Eye Hospital, renowned for advanced phacoemulsification and LASIK surgery.',
                'about_hi' => 'डॉ. भुजंग पई नेत्रधाम आई हॉस्पिटल के अध्यक्ष और उन्नत मोतियाबिंद तथा लेसिक सर्जरी के लिए प्रसिद्ध हैं।',
                'gender' => 'Male',
                'phone' => '080-26633666',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sita',
                'last_name' => 'Bhateja',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Sita Bhateja Speciality Hospital',
                'hospital_name_hi' => 'सीता भटेजा स्पेशलिटी अस्पताल',
                'address' => '8-9, O\'Shaughnessy Road, Langford Gardens, Bangalore, Karnataka - 560025',
                'address_line1' => '8-9, O\'Shaughnessy Road',
                'address_line2' => 'Langford Gardens',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560025',
                'latitude' => 12.9580,
                'longitude' => 77.6010,
                'experience_years' => 50,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'FRCOG'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-0212',
                'about_en' => 'Dr. Sita Bhateja is the legendary Founder of Sita Bhateja Speciality Hospital and a pioneer in maternal and child healthcare in Bangalore.',
                'about_hi' => 'डॉ. सीता भटेजा सीता भटेजा स्पेशलिटी हॉस्पिटल की संस्थापक और बैंगलोर में मातृ एवं बाल स्वास्थ्य देखभाल की प्रणेता हैं।',
                'gender' => 'Female',
                'phone' => '080-22211111',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Raghavan',
                'last_name' => 'Sundar',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'HCG Cancer Centre',
                'hospital_name_hi' => 'एचसीजी कैंसर सेंटर',
                'address' => '8, P Kalinga Rao Road, Sampangiram Nagar, Bangalore, Karnataka - 560027',
                'address_line1' => '8, P Kalinga Rao Road',
                'address_line2' => 'Sampangiram Nagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560027',
                'latitude' => 12.9650,
                'longitude' => 77.5940,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Medical Oncology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-1234',
                'about_en' => 'Dr. Raghavan Sundar is Chairman of Healthcare Global Enterprises (HCG), redefining cancer care across India through advanced oncology networks.',
                'about_hi' => 'डॉ. राघवन सुंदर एचसीजी कैंसर केयर समूह के अध्यक्ष हैं।',
                'gender' => 'Male',
                'phone' => '080-40206000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Meena',
                'last_name' => 'Prabhu',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Cloudnine Hospital',
                'hospital_name_hi' => 'क्लाउडनाइन अस्पताल',
                'address' => '1533, 9th Main, 3rd Block, Jayanagar, Bangalore, Karnataka - 560011',
                'address_line1' => '1533, 9th Main, 3rd Block',
                'address_line2' => 'Jayanagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560011',
                'latitude' => 12.9290,
                'longitude' => 77.5850,
                'experience_years' => 30,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'DCH'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-2345',
                'about_en' => 'Dr. Meena Prabhu is a Senior Consultant Pediatrician at Cloudnine Hospital Jayanagar, expert in infant nutrition and developmental pediatrics.',
                'about_hi' => 'डॉ. मीना प्रभु क्लाउडनाइन अस्पताल जयनगर में वरिष्ठ बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '080-67906790',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Kishore',
                'last_name' => 'Rao',
                'department_name_en' => 'ENT (Otolaryngology)',
                'department_name_hi' => 'कान, नाक और गला रोग (ईएनटी)',
                'hospital_name_en' => 'St. John\'s Medical College Hospital',
                'hospital_name_hi' => 'सेंट जॉन्स मेडिकल कॉलेज अस्पताल',
                'address' => 'Sarjapur Road, Bangalore, Karnataka - 560034',
                'address_line1' => 'Sarjapur Road',
                'address_line2' => 'Koramangala',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560034',
                'latitude' => 12.9310,
                'longitude' => 77.6310,
                'experience_years' => 34,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (ENT)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-3456',
                'about_en' => 'Dr. Kishore Rao is a highly experienced ENT Surgeon and Head of Otolaryngology at St. John\'s Medical College Hospital.',
                'about_hi' => 'डॉ. किशोर राव सेंट जॉन्स मेडिकल कॉलेज अस्पताल में ईएनटी विभाग के प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '080-22065000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Venkat',
                'last_name' => 'Raman',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'Ramaiah Memorial Hospital',
                'hospital_name_hi' => 'रमैया मेमोरियल अस्पताल',
                'address' => 'MSR Nagar, Mathikere, Bangalore, Karnataka - 560054',
                'address_line1' => 'MSR Nagar, Mathikere',
                'address_line2' => 'New BEL Road',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560054',
                'latitude' => 13.0300,
                'longitude' => 77.5650,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FRCS'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-4567',
                'about_en' => 'Dr. Venkat Raman is a Senior Consultant General and Laparoscopic Surgeon at Ramaiah Memorial Hospital.',
                'about_hi' => 'डॉ. वेंकट रमन रमैया मेमोरियल अस्पताल में वरिष्ठ सलाहकार सामान्य और लेप्रोस्कोपिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '080-23608888',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Ramesh',
                'last_name' => 'Kumar',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'Sakra World Hospital',
                'hospital_name_hi' => 'सकरा वर्ल्ड अस्पताल',
                'address' => 'Devarabeesanahalli, Outer Ring Road, Bangalore, Karnataka - 560103',
                'address_line1' => 'Devarabeesanahalli',
                'address_line2' => 'Outer Ring Road, Marathahalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560103',
                'latitude' => 12.9320,
                'longitude' => 77.6850,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-5678',
                'about_en' => 'Dr. Ramesh Kumar is a Senior Consultant Gastroenterologist at Sakra World Hospital Bangalore, expert in therapeutic endoscopy.',
                'about_hi' => 'डॉ. रमेश कुमार सकरा वर्ल्ड अस्पताल बैंगलोर में वरिष्ठ सलाहकार गैस्ट्रोएंटरोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '080-49694969',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Naresh',
                'last_name' => 'Shetty',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Ramaiah Memorial Hospital',
                'hospital_name_hi' => 'रमैया मेमोरियल अस्पताल',
                'address' => 'MSR Nagar, Mathikere, Bangalore, Karnataka - 560054',
                'address_line1' => 'MSR Nagar, Mathikere',
                'address_line2' => 'New BEL Road',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560054',
                'latitude' => 13.0300,
                'longitude' => 77.5650,
                'experience_years' => 36,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'FICS'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11223',
                'about_en' => 'Dr. Naresh Shetty is a Senior Consultant Orthopedic Surgeon and President of Ramaiah Memorial Hospital, renowned for joint replacements and trauma surgery.',
                'about_hi' => 'डॉ. नरेश शेट्टी रमैया मेमोरियल अस्पताल के अध्यक्ष और वरिष्ठ सलाहकार आर्थोपेडिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '080-23608888',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Colin',
                'last_name' => 'John',
                'department_name_en' => 'Pediatric Cardiology',
                'department_name_hi' => 'बाल हृदय रोग',
                'hospital_name_en' => 'St. John\'s Medical College Hospital',
                'hospital_name_hi' => 'सेंट जॉन्स मेडिकल कॉलेज अस्पताल',
                'address' => 'Sarjapur Road, Bangalore, Karnataka - 560034',
                'address_line1' => 'Sarjapur Road',
                'address_line2' => 'Koramangala',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560034',
                'latitude' => 12.9310,
                'longitude' => 77.6310,
                'experience_years' => 40,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Pediatric Cardiothoracic Surgery)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11224',
                'about_en' => 'Dr. Colin John is a pioneer in Pediatric Cardiac Surgery in India and a Senior Professor at St. John\'s Medical College Hospital.',
                'about_hi' => 'डॉ. कॉलिन जॉन भारत में बाल चिकित्सा कार्डियक सर्जरी के प्रणेता और वरिष्ठ प्रोफेसर हैं।',
                'gender' => 'Male',
                'phone' => '080-22065000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'B. G.',
                'last_name' => 'Dharmanand',
                'department_name_en' => 'Rheumatology',
                'department_name_hi' => 'गठिया रोग (रुमेटोलॉजी)',
                'hospital_name_en' => 'Manipal Hospital',
                'hospital_name_hi' => 'मणिपाल अस्पताल',
                'address' => '98, HAL Old Airport Road, Bangalore, Karnataka - 560017',
                'address_line1' => '98, HAL Old Airport Road',
                'address_line2' => 'Kodihalli',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560017',
                'latitude' => 12.9560,
                'longitude' => 77.6520,
                'experience_years' => 32,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Rheumatology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11225',
                'about_en' => 'Dr. B. G. Dharmanand is a Senior Consultant and Head of Rheumatology at Manipal Hospitals Bangalore, expert in autoimmune and arthritic conditions.',
                'about_hi' => 'डॉ. बी. जी. धर्मानंद मणिपाल हॉस्पिटल्स बैंगलोर में वरिष्ठ सलाहकार और रुमेटोलॉजी के प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '080-25024444',
                'is_verified' => true,
            ],
            [
                'first_name' => 'S. C.',
                'last_name' => 'Sanjay',
                'department_name_en' => 'Pulmonology',
                'department_name_hi' => 'श्वसन रोग (पल्मोनोलॉजी)',
                'hospital_name_en' => 'Fortis Hospital',
                'hospital_name_hi' => 'फोर्टिस अस्पताल',
                'address' => '154/9, Bannerghatta Road, Bangalore, Karnataka - 560076',
                'address_line1' => '154/9, Bannerghatta Road',
                'address_line2' => 'Opposite IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'latitude' => 12.8940,
                'longitude' => 77.6010,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Pulmonary Medicine)', 'DM (Pulmonology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11226',
                'about_en' => 'Dr. S. C. Sanjay is a Senior Consultant Pulmonologist at Fortis Hospital Bannerghatta Road Bangalore, expert in advanced bronchoscopy and asthma.',
                'about_hi' => 'डॉ. एस. सी. संजय फोर्टिस अस्पताल बन्नेरघट्टा रोड बैंगलोर में वरिष्ठ सलाहकार पल्मोनोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '080-66214444',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Anoop',
                'last_name' => 'P.',
                'department_name_en' => 'Hematology',
                'department_name_hi' => 'रक्त विज्ञान (हेमेटोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => '154/11, Bannerghatta Road, Bangalore, Karnataka - 560076',
                'address_line1' => '154/11, Bannerghatta Road',
                'address_line2' => 'Near IIM-B',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560076',
                'latitude' => 12.8950,
                'longitude' => 77.6020,
                'experience_years' => 25,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Clinical Hematology)', 'FRCPath (UK)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11227',
                'about_en' => 'Dr. Anoop P is a Senior Consultant Hematologist and Bone Marrow Transplant Physician at Apollo Hospitals Bangalore.',
                'about_hi' => 'डॉ. अनूप पी अपोलो हॉस्पिटल्स बैंगलोर में वरिष्ठ सलाहकार हेमेटोलॉजिस्ट और बोन मैरो ट्रांसप्लांट फिजिशियन हैं।',
                'gender' => 'Male',
                'phone' => '080-26304050',
                'is_verified' => true,
            ],
            [
                'first_name' => 'H. V.',
                'last_name' => 'Santhosh',
                'department_name_en' => 'Endocrinology',
                'department_name_hi' => 'अंतःस्रावी विज्ञान (एंडोक्रिनोलॉजी)',
                'hospital_name_en' => 'KC General Hospital',
                'hospital_name_hi' => 'केसी जनरल अस्पताल',
                'address' => 'Malleswaram Circle, Malleswaram, Bangalore, Karnataka - 560003',
                'address_line1' => 'Malleswaram Circle',
                'address_line2' => 'Malleswaram',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560003',
                'latitude' => 12.9920,
                'longitude' => 77.5710,
                'experience_years' => 26,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Endocrinology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11228',
                'about_en' => 'Dr. H. V. Santhosh is a Senior Endocrinologist and Diabetologist at KC General Hospital Bangalore.',
                'about_hi' => 'डॉ. एच. वी. संतोष केसी जनरल अस्पताल बैंगलोर में वरिष्ठ एंडोक्रिनोलॉजिस्ट और डायबिटोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '080-23341771',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Anand',
                'last_name' => 'P.',
                'department_name_en' => 'Nephrology',
                'department_name_hi' => 'गुर्दा रोग (नेफ्रोलॉजी)',
                'hospital_name_en' => 'BGS Gleneagles Global Hospital',
                'hospital_name_hi' => 'बीजीएस ग्लेनीगल्स ग्लोबल अस्पताल',
                'address' => '67, Uttarahalli Road, Kengeri, Bangalore, Karnataka - 560060',
                'address_line1' => '67, Uttarahalli Road',
                'address_line2' => 'Kengeri',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560060',
                'latitude' => 12.9050,
                'longitude' => 77.5020,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Nephrology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11229',
                'about_en' => 'Dr. Anand P is a Senior Consultant Nephrologist and Kidney Transplant Physician at BGS Gleneagles Global Hospital Bangalore.',
                'about_hi' => 'डॉ. आनंद पी बीजीएस ग्लेनीगल्स ग्लोबल अस्पताल बैंगलोर में वरिष्ठ सलाहकार नेफ्रोलॉजिस्ट और किडनी प्रत्यारोपण चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '080-26255555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'S. K.',
                'last_name' => 'Shivakumar',
                'department_name_en' => 'Gastrointestinal Surgery',
                'department_name_hi' => 'गैस्ट्रोइंटेस्टाइनल सर्जरी',
                'hospital_name_en' => 'Victoria Hospital',
                'hospital_name_hi' => 'विक्टोरिया अस्पताल',
                'address' => 'Fort Road, Near City Market, Bangalore, Karnataka - 560002',
                'address_line1' => 'Fort Road',
                'address_line2' => 'Near City Market',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560002',
                'latitude' => 12.9630,
                'longitude' => 77.5750,
                'experience_years' => 30,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Surgical Gastroenterology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11230',
                'about_en' => 'Dr. S. K. Shivakumar is a Senior Professor and Head of Surgical Gastroenterology at Victoria Hospital (BMCRI) Bangalore.',
                'about_hi' => 'डॉ. एस. के. शिवकुमार विक्टोरिया अस्पताल (बीएमसीआरआई) बैंगलोर में सर्जिकल गैस्ट्रोएंटरोलॉजी के वरिष्ठ प्रोफेसर और प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '080-26701150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Radhika',
                'last_name' => 'M.',
                'department_name_en' => 'Dermatology',
                'department_name_hi' => 'त्वचा रोग (डर्मेटोलॉजी)',
                'hospital_name_en' => 'Bowring & Lady Curzon Hospital',
                'hospital_name_hi' => 'बौरिंग एवं लेडी कर्जन अस्पताल',
                'address' => 'Lady Curzon Road, Tasker Town, Shivaji Nagar, Bangalore, Karnataka - 560001',
                'address_line1' => 'Lady Curzon Road',
                'address_line2' => 'Tasker Town, Shivaji Nagar',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'latitude' => 12.9820,
                'longitude' => 77.6050,
                'experience_years' => 28,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Dermatology)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11231',
                'about_en' => 'Dr. Radhika M is a Senior Consultant Dermatologist at Bowring & Lady Curzon Hospital Bangalore.',
                'about_hi' => 'डॉ. राधिका एम बौरिंग एवं लेडी कर्जन अस्पताल बैंगलोर में वरिष्ठ सलाहकार त्वचा विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '080-25591325',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Praveen',
                'last_name' => 'K.',
                'department_name_en' => 'Neurosurgery',
                'department_name_hi' => 'न्यूरोसर्जरी',
                'hospital_name_en' => 'Aster CMI Hospital',
                'hospital_name_hi' => 'एस्टर सीएमआई अस्पताल',
                'address' => '43/2, New Airport Road, Hebbal, Bangalore, Karnataka - 560092',
                'address_line1' => '43/2, New Airport Road',
                'address_line2' => 'Hebbal',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560092',
                'latitude' => 13.0530,
                'longitude' => 77.5920,
                'experience_years' => 26,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Neurosurgery)'],
                'medical_council' => 'Karnataka Medical Council (KMC)',
                'registration_number' => 'KMC-11232',
                'about_en' => 'Dr. Praveen K is a Senior Consultant Neurosurgeon at Aster CMI Hospital Bangalore, expert in endovascular and skull base neurosurgery.',
                'about_hi' => 'डॉ. प्रवीण के एस्टर सीएमआई अस्पताल बैंगलोर में वरिष्ठ सलाहकार न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '080-43420100',
                'is_verified' => true,
            ],
        ];
    }
}
