<?php

namespace App\Services;

class ChennaiScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'chennai') {
            return [];
        }

        return [
            [
                'name_en' => 'Rajiv Gandhi Government General Hospital Blood Bank (RGGGH)',
                'name_hi' => 'राजीव गांधी सरकारी सामान्य अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600003',
                'address_en' => 'E.V.R Periyar Salai, Park Town, Opposite Chennai Central Railway Station, Chennai, Tamil Nadu - 600003',
                'address_hi' => 'ई.वी.आर पेरियार सलाई, पार्क टाउन, चेन्नई सेंट्रल रेलवे स्टेशन के सामने, चेन्नई, तमिलनाडु - 600003',
                'country_code' => '+91',
                'phone' => '044-25305000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-25305000',
                'email' => 'bloodbank@mmc.ac.in',
                'website' => 'https://mmc.ac.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / RGGGH Registry',
                'source_url' => 'https://mmc.ac.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Stanley Medical College Blood Bank',
                'name_hi' => 'स्टेनली मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600001',
                'address_en' => '1, Old Jail Road, Royapuram, Chennai, Tamil Nadu - 600001',
                'address_hi' => '1, ओल्ड जेल रोड, रोयापुरम, चेन्नई, तमिलनाडु - 600001',
                'country_code' => '+91',
                'phone' => '044-25281351',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-25281351',
                'email' => 'bloodbank@stanleymedicalcollege.in',
                'website' => 'https://stanleymedicalcollege.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Stanley Registry',
                'source_url' => 'https://stanleymedicalcollege.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Kilpauk Medical College Blood Bank',
                'name_hi' => 'किलपौक मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600010',
                'address_en' => '822, E.V.R Periyar Salai, Kilpauk, Chennai, Tamil Nadu - 600010',
                'address_hi' => '822, ई.वी.आर पेरियार सलाई, किलपौक, चेन्नई, तमिलनाडु - 600010',
                'country_code' => '+91',
                'phone' => '044-26412979',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-26412979',
                'email' => 'bloodbank@gkmc.in',
                'website' => 'https://gkmc.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Kilpauk Registry',
                'source_url' => 'https://gkmc.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Apollo Hospitals Blood Bank Greams Road',
                'name_hi' => 'अपोलो अस्पताल ब्लड बैंक ग्रीम्स रोड',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'address_en' => '21, Greams Lane, Off Greams Road, Thousand Lights, Chennai, Tamil Nadu - 600006',
                'address_hi' => '21, ग्रीम्स लेन, ग्रीम्स रोड के पास, थाउजेंड लाइट्स, चेन्नई, तमिलनाडु - 600006',
                'country_code' => '+91',
                'phone' => '044-28290200',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-28290200',
                'email' => 'bloodbank_greams@apollohospitals.com',
                'website' => 'https://apollohospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Apollo Greams Registry',
                'source_url' => 'https://apollohospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Jeevan Blood Bank and Research Centre',
                'name_hi' => 'जीवन ब्लड बैंक एवं अनुसंधान केंद्र',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600034',
                'address_en' => '22, Wheatcrofts Road, Nungambakkam, Chennai, Tamil Nadu - 600034',
                'address_hi' => '22, व्हीटक्रॉफ्ट्स रोड, नुंगमबक्कम, चेन्नई, तमिलनाडु - 600034',
                'country_code' => '+91',
                'phone' => '044-28251234',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-28251234',
                'email' => 'contact@jeevanbloodbank.org',
                'website' => 'https://jeevanbloodbank.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Jeevan Registry',
                'source_url' => 'https://jeevanbloodbank.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Rotary Central Margaret Sidney Blood Bank',
                'name_hi' => 'रोटरी सेंट्रल मार्गरेट सिडनी ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600017',
                'address_en' => '34, North Usman Road, T. Nagar, Chennai, Tamil Nadu - 600017',
                'address_hi' => '34, नॉर्थ उस्मान रोड, टी. नगर, चेन्नई, तमिलनाडु - 600017',
                'country_code' => '+91',
                'phone' => '044-28142345',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-28142345',
                'email' => 'contact@rotarybloodbankchennai.org',
                'website' => 'https://rotarybloodbankchennai.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Rotary Chennai Registry',
                'source_url' => 'https://rotarybloodbankchennai.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Kauvery Hospital Blood Bank Alwarpet',
                'name_hi' => 'कावेरी अस्पताल ब्लड बैंक अलवरपेट',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600018',
                'address_en' => '81, TTK Road, Alwarpet, Chennai, Tamil Nadu - 600018',
                'address_hi' => '81, टीटीके रोड, अलवरपेट, चेन्नई, तमिलनाडु - 600018',
                'country_code' => '+91',
                'phone' => '044-40006000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-40006000',
                'email' => 'bloodbank@kauveryhospital.com',
                'website' => 'https://kauveryhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Kauvery Registry',
                'source_url' => 'https://kauveryhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'MGM Healthcare Blood Bank Aminjikarai',
                'name_hi' => 'एमजीएम हेल्थकेयर ब्लड बैंक अमीनजिकरई',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600029',
                'address_en' => '72, Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu - 600029',
                'address_hi' => '72, नेल्सन मणिकम रोड, अमीनजिकरई, चेन्नई, तमिलनाडु - 600029',
                'country_code' => '+91',
                'phone' => '044-45242424',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-45242424',
                'email' => 'bloodbank@mgmhealthcare.in',
                'website' => 'https://mgmhealthcare.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / MGM Registry',
                'source_url' => 'https://mgmhealthcare.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'MIOT International Blood Bank Manapakkam',
                'name_hi' => 'मिओट इंटरनेशनल ब्लड बैंक मणपक्कम',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600089',
                'address_en' => '4/112, Mount Poonamallee Road, Manapakkam, Chennai, Tamil Nadu - 600089',
                'address_hi' => '4/112, माउंट पूनमल्ली रोड, मणपक्कम, चेन्नई, तमिलनाडु - 600089',
                'country_code' => '+91',
                'phone' => '044-22492288',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-22492288',
                'email' => 'bloodbank@miotinternational.com',
                'website' => 'https://miotinternational.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / MIOT Registry',
                'source_url' => 'https://miotinternational.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Sri Ramachandra Medical Centre Blood Bank (SRMC)',
                'name_hi' => 'श्री रामचंद्र मेडिकल सेंटर ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600116',
                'address_en' => '1, Ramachandra Nagar, Porur, Chennai, Tamil Nadu - 600116',
                'address_hi' => '1, रामचंद्र नगर, पोरुर, चेन्नई, तमिलनाडु - 600116',
                'country_code' => '+91',
                'phone' => '044-45928500',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-45928500',
                'email' => 'bloodbank@sriramachandra.edu.in',
                'website' => 'https://sriramachandra.edu.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / SRMC Registry',
                'source_url' => 'https://sriramachandra.edu.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Tamil Nadu Dr. M.G.R. Medical University Blood Bank',
                'name_hi' => 'तमिलनाडु डॉ. एम.जी.आर. मेडिकल यूनिवर्सिटी ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600032',
                'address_en' => '69, Anna Salai, Guindy, Chennai, Tamil Nadu - 600032',
                'address_hi' => '69, अन्ना सलाई, गिंडी, चेन्नई, तमिलनाडु - 600032',
                'country_code' => '+91',
                'phone' => '044-22353574',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-22353574',
                'email' => 'bloodbank@tnmgrmu.ac.in',
                'website' => 'https://tnmgrmu.ac.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / MGR University Registry',
                'source_url' => 'https://tnmgrmu.ac.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'VHS Hospital Blood Bank',
                'name_hi' => 'वीएचएस अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600113',
                'address_en' => 'Rajiv Gandhi Salai, IT Corridor, Taramani, Chennai, Tamil Nadu - 600113',
                'address_hi' => 'राजीव गांधी सलाई, आईटी कॉरिडोर, तारामणि, चेन्नई, तमिलनाडु - 600113',
                'country_code' => '+91',
                'phone' => '044-22541972',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-22541972',
                'email' => 'bloodbank@vhschennai.org',
                'website' => 'https://vhschennai.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / VHS Registry',
                'source_url' => 'https://vhschennai.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'SIMS Hospital Blood Bank',
                'name_hi' => 'सिम्स अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600026',
                'address_en' => '1, Jawaharlal Nehru Salai, 100 Feet Road, Vadapalani, Chennai, Tamil Nadu - 600026',
                'address_hi' => '1, जवाहरलाल नेहरू सलाई, 100 फीट रोड, वडापलानी, चेन्नई, तमिलनाडु - 600026',
                'country_code' => '+91',
                'phone' => '044-20002001',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-20002001',
                'email' => 'bloodbank@simshospitals.com',
                'website' => 'https://simshospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / SIMS Registry',
                'source_url' => 'https://simshospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Fortis Malar Hospital Blood Bank',
                'name_hi' => 'फोर्टिस मलार अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600020',
                'address_en' => '52, 1st Main Road, Gandhi Nagar, Adyar, Chennai, Tamil Nadu - 600020',
                'address_hi' => '52, पहली मुख्य सड़क, गांधी नगर, अड्यार, चेन्नई, तमिलनाडु - 600020',
                'country_code' => '+91',
                'phone' => '044-42892222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-42892222',
                'email' => 'bloodbank.malar@fortishealthcare.com',
                'website' => 'https://fortishealthcare.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Fortis Malar Registry',
                'source_url' => 'https://fortishealthcare.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Vijaya Hospital Blood Bank',
                'name_hi' => 'विजया अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600026',
                'address_en' => '434, N.S.K. Salai, Vadapalani, Chennai, Tamil Nadu - 600026',
                'address_hi' => '434, एन.एस.के. सलाई, वडापलानी, चेन्नई, तमिलनाडु - 600026',
                'country_code' => '+91',
                'phone' => '044-24815900',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-24815900',
                'email' => 'bloodbank@vijayahospital.org',
                'website' => 'https://vijayahospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Vijaya Registry',
                'source_url' => 'https://vijayahospital.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Billroth Hospitals Blood Bank',
                'name_hi' => 'बिल्लरोथ अस्पताल ब्लड बैंक',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600030',
                'address_en' => '43, Lakshmi Talkies Road, Shenoy Nagar, Chennai, Tamil Nadu - 600030',
                'address_hi' => '43, लक्ष्मी टॉकीज रोड, शेनॉय नगर, चेन्नई, तमिलनाडु - 600030',
                'country_code' => '+91',
                'phone' => '044-42921111',
                'emergency_country_code' => '+91',
                'emergency_phone' => '044-42921111',
                'email' => 'bloodbank@billrothhospitals.com',
                'website' => 'https://billrothhospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Billroth Registry',
                'source_url' => 'https://billrothhospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'chennai') {
            return [];
        }

        return [
            [
                'name_en' => 'Rajiv Gandhi Government General Hospital (RGGGH)',
                'name_hi' => 'राजीव गांधी सरकारी सामान्य अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'E.V.R Periyar Salai, Park Town, Opposite Chennai Central Railway Station, Chennai, Tamil Nadu - 600003',
                'address_line1' => 'E.V.R Periyar Salai, Park Town',
                'address_line2' => 'Opposite Chennai Central Railway Station',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600003',
                'emergency_phone' => '044-25305000',
                'emergency_country_code' => '+91',
                'latitude' => 13.0830,
                'longitude' => 80.2750,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'CMCHIS (Chief Minister\'s Comprehensive Health Insurance Scheme)', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Apollo Hospitals, Greams Road',
                'name_hi' => 'अपोलो अस्पताल, ग्रीम्स रोड',
                'type' => 'Private Hospital',
                'address' => '21, Greams Lane, Off Greams Road, Thousand Lights, Chennai, Tamil Nadu - 600006',
                'address_line1' => '21, Greams Lane, Off Greams Road',
                'address_line2' => 'Thousand Lights',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'emergency_phone' => '044-28290200',
                'emergency_country_code' => '+91',
                'latitude' => 13.0610,
                'longitude' => 80.2520,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'MGM Healthcare, Aminjikarai',
                'name_hi' => 'एमजीएम हेल्थकेयर, अमीनजिकरई',
                'type' => 'Private Hospital',
                'address' => '72, Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu - 600029',
                'address_line1' => '72, Nelson Manickam Road',
                'address_line2' => 'Aminjikarai',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600029',
                'emergency_phone' => '044-45242424',
                'emergency_country_code' => '+91',
                'latitude' => 13.0720,
                'longitude' => 80.2220,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Kauvery Hospital, Alwarpet',
                'name_hi' => 'कावेरी अस्पताल, अलवरपेट',
                'type' => 'Private Hospital',
                'address' => '81, TTK Road, Alwarpet, Chennai, Tamil Nadu - 600018',
                'address_line1' => '81, TTK Road',
                'address_line2' => 'Alwarpet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600018',
                'emergency_phone' => '044-40006000',
                'emergency_country_code' => '+91',
                'latitude' => 13.0320,
                'longitude' => 80.2550,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'MIOT International, Manapakkam',
                'name_hi' => 'मिओट इंटरनेशनल, मणपक्कम',
                'type' => 'Private Hospital',
                'address' => '4/112, Mount Poonamallee Road, Manapakkam, Chennai, Tamil Nadu - 600089',
                'address_line1' => '4/112, Mount Poonamallee Road',
                'address_line2' => 'Manapakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600089',
                'emergency_phone' => '044-22492288',
                'emergency_country_code' => '+91',
                'latitude' => 13.0180,
                'longitude' => 80.1850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Sri Ramachandra Medical Centre (SRMC), Porur',
                'name_hi' => 'श्री रामचंद्र मेडिकल सेंटर, पोरुर',
                'type' => 'Private Hospital',
                'address' => '1, Ramachandra Nagar, Porur, Chennai, Tamil Nadu - 600116',
                'address_line1' => '1, Ramachandra Nagar',
                'address_line2' => 'Porur',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600116',
                'emergency_phone' => '044-45928500',
                'emergency_country_code' => '+91',
                'latitude' => 13.0380,
                'longitude' => 80.1520,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'ECHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'SIMS Hospital, Vadapalani',
                'name_hi' => 'सिम्स अस्पताल, वडापलानी',
                'type' => 'Private Hospital',
                'address' => '1, Jawaharlal Nehru Salai, 100 Feet Road, Vadapalani, Chennai, Tamil Nadu - 600026',
                'address_line1' => '1, Jawaharlal Nehru Salai, 100 Feet Road',
                'address_line2' => 'Vadapalani',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600026',
                'emergency_phone' => '044-20002001',
                'emergency_country_code' => '+91',
                'latitude' => 13.0510,
                'longitude' => 80.2120,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Fortis Malar Hospital, Adyar',
                'name_hi' => 'फोर्टिस मलार अस्पताल, अड्यार',
                'type' => 'Private Hospital',
                'address' => '52, 1st Main Road, Gandhi Nagar, Adyar, Chennai, Tamil Nadu - 600020',
                'address_line1' => '52, 1st Main Road, Gandhi Nagar',
                'address_line2' => 'Adyar',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600020',
                'emergency_phone' => '044-42892222',
                'emergency_country_code' => '+91',
                'latitude' => 13.0110,
                'longitude' => 80.2580,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Vijaya Hospital, Vadapalani',
                'name_hi' => 'विजया अस्पताल, वडापलानी',
                'type' => 'Private Hospital',
                'address' => '434, N.S.K. Salai, Vadapalani, Chennai, Tamil Nadu - 600026',
                'address_line1' => '434, N.S.K. Salai',
                'address_line2' => 'Vadapalani',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600026',
                'emergency_phone' => '044-24815900',
                'emergency_country_code' => '+91',
                'latitude' => 13.0480,
                'longitude' => 80.2080,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Sankara Nethralaya',
                'name_hi' => 'शंकर नेत्रालय',
                'type' => 'Private Hospital',
                'address' => '41, College Road, Thousand Lights, Nungambakkam, Chennai, Tamil Nadu - 600006',
                'address_line1' => '41, College Road',
                'address_line2' => 'Thousand Lights, Nungambakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'emergency_phone' => '044-42271500',
                'emergency_country_code' => '+91',
                'latitude' => 13.0650,
                'longitude' => 80.2450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS'],
            ],
            [
                'name_en' => 'Stanley Medical College and Hospital',
                'name_hi' => 'स्टेनली मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Government Hospital',
                'address' => '1, Old Jail Road, Royapuram, Chennai, Tamil Nadu - 600001',
                'address_line1' => '1, Old Jail Road',
                'address_line2' => 'Royapuram',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600001',
                'emergency_phone' => '044-25281351',
                'emergency_country_code' => '+91',
                'latitude' => 13.1050,
                'longitude' => 80.2850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS'],
            ],
            [
                'name_en' => 'Dr. Mehta\'s Hospitals, Chetpet',
                'name_hi' => 'डॉ. मेहता अस्पताल, चेटपेट',
                'type' => 'Private Hospital',
                'address' => '2, McNichols Road, 3rd Lane, Chetpet, Chennai, Tamil Nadu - 600031',
                'address_line1' => '2, McNichols Road, 3rd Lane',
                'address_line2' => 'Chetpet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600031',
                'emergency_phone' => '044-42271001',
                'emergency_country_code' => '+91',
                'latitude' => 13.0720,
                'longitude' => 80.2350,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Kilpauk Medical College Hospital',
                'name_hi' => 'किलपौक मेडिकल कॉलेज अस्पताल',
                'type' => 'Government Hospital',
                'address' => '822, E.V.R Periyar Salai, Kilpauk, Chennai, Tamil Nadu - 600010',
                'address_line1' => '822, E.V.R Periyar Salai',
                'address_line2' => 'Kilpauk',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600010',
                'emergency_phone' => '044-26412979',
                'emergency_country_code' => '+91',
                'latitude' => 13.0780,
                'longitude' => 80.2420,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS'],
            ],
            [
                'name_en' => 'Billroth Hospitals',
                'name_hi' => 'बिल्लरोथ अस्पताल',
                'type' => 'Private Hospital',
                'address' => '43, Lakshmi Talkies Road, Shenoy Nagar, Chennai, Tamil Nadu - 600030',
                'address_line1' => '43, Lakshmi Talkies Road',
                'address_line2' => 'Shenoy Nagar',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600030',
                'emergency_phone' => '044-42921111',
                'emergency_country_code' => '+91',
                'latitude' => 13.0790,
                'longitude' => 80.2250,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Prashanth Super Speciality Hospital',
                'name_hi' => 'प्रशांत सुपर स्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => '36 & 36A, Velachery Main Road, Velachery, Chennai, Tamil Nadu - 600042',
                'address_line1' => '36 & 36A, Velachery Main Road',
                'address_line2' => 'Velachery',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600042',
                'emergency_phone' => '044-46805555',
                'emergency_country_code' => '+91',
                'latitude' => 12.9780,
                'longitude' => 80.2210,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Gleneagles Global Health City',
                'name_hi' => 'ग्लेनीगल्स ग्लोबल हेल्थ सिटी',
                'type' => 'Private Hospital',
                'address' => '439, Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu - 600100',
                'address_line1' => '439, Cheran Nagar',
                'address_line2' => 'Perumbakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600100',
                'emergency_phone' => '044-44775000',
                'emergency_country_code' => '+91',
                'latitude' => 12.9020,
                'longitude' => 80.2010,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Apollo Speciality Hospital, Vanagaram',
                'name_hi' => 'अपोलो स्पेशलिटी अस्पताल, वानगरम',
                'type' => 'Private Hospital',
                'address' => '64, Vanagaram to Ambattur Main Road, Chennai, Tamil Nadu - 600095',
                'address_line1' => '64, Vanagaram to Ambattur Main Road',
                'address_line2' => 'Vanagaram',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600095',
                'emergency_phone' => '044-30636700',
                'emergency_country_code' => '+91',
                'latitude' => 13.0620,
                'longitude' => 80.1550,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Kanchi Kamakoti Childs Trust Hospital',
                'name_hi' => 'कांची कामकोटि चाइल्ड्स ट्रस्ट अस्पताल',
                'type' => 'Private Hospital',
                'address' => '12-A, Nageswara Road, Nungambakkam, Chennai, Tamil Nadu - 600034',
                'address_line1' => '12-A, Nageswara Road',
                'address_line2' => 'Nungambakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600034',
                'emergency_phone' => '044-42001800',
                'emergency_country_code' => '+91',
                'latitude' => 13.0550,
                'longitude' => 80.2450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS'],
            ],
            [
                'name_en' => 'Voluntary Health Services (VHS) Hospital',
                'name_hi' => 'वॉलंटरी हेल्थ सर्विसेज (वीएचएस) अस्पताल',
                'type' => 'Semi-Private Hospital',
                'address' => 'Rajiv Gandhi Salai, IT Corridor, Taramani, Chennai, Tamil Nadu - 600113',
                'address_line1' => 'Rajiv Gandhi Salai, IT Corridor',
                'address_line2' => 'Taramani',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600113',
                'emergency_phone' => '044-22541972',
                'emergency_country_code' => '+91',
                'latitude' => 12.9880,
                'longitude' => 80.2450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'CSI Kalyani Multispeciality Hospital',
                'name_hi' => 'सीएसआई कल्याणी मल्टीस्पेशलिटी अस्पताल',
                'type' => 'Semi-Private Hospital',
                'address' => '15, Dr. Radhakrishnan Salai, Mylapore, Chennai, Tamil Nadu - 600004',
                'address_line1' => '15, Dr. Radhakrishnan Salai',
                'address_line2' => 'Mylapore',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600004',
                'emergency_phone' => '044-28475101',
                'emergency_country_code' => '+91',
                'latitude' => 13.0450,
                'longitude' => 80.2650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CMCHIS', 'CGHS', 'Star Health TPA'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'chennai') {
            return [];
        }

        return [
            [
                'first_name' => 'K. R.',
                'last_name' => 'Balakrishnan',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'MGM Healthcare',
                'hospital_name_hi' => 'एमजीएम हेल्थकेयर',
                'address' => '72, Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu - 600029',
                'address_line1' => '72, Nelson Manickam Road',
                'address_line2' => 'Aminjikarai',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600029',
                'latitude' => 13.0720,
                'longitude' => 80.2220,
                'experience_years' => 45,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Cardiothoracic Surgery)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-1011',
                'about_en' => 'Dr. K. R. Balakrishnan is the Chairman of Cardiac Sciences and Director of Heart and Lung Transplant Program at MGM Healthcare, world-renowned for performing India\'s highest number of heart transplants.',
                'about_hi' => 'डॉ. के. आर. बालकृष्णन एमजीएम हेल्थकेयर में कार्डियक साइंसेज के अध्यक्ष और हार्ट एंड लंग ट्रांसप्लांट प्रोग्राम के निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '044-45242424',
                'is_verified' => true,
            ],
            [
                'first_name' => 'V. Mohan',
                'last_name' => 'Rao',
                'department_name_en' => 'Endocrinology',
                'department_name_hi' => 'एंडोक्रिनोलॉजी',
                'hospital_name_en' => 'Dr. Mohan\'s Diabetes Speciality Centre',
                'hospital_name_hi' => 'डॉ. मोहन डायबिटीज स्पेशलिटी सेंटर',
                'address' => '6B, Conran Smith Road, Gopalapuram, Chennai, Tamil Nadu - 600086',
                'address_line1' => '6B, Conran Smith Road',
                'address_line2' => 'Gopalapuram',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600086',
                'latitude' => 13.0480,
                'longitude' => 80.2550,
                'experience_years' => 48,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRCP (London)', 'FRCP (Edin)', 'FRCP (Glasgow)', 'Padma Shri'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-2022',
                'about_en' => 'Dr. V. Mohan is the Chairman of Dr. Mohan\'s Diabetes Speciality Centre, a globally acclaimed diabetologist and researcher, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. वी. मोहन डॉ. मोहन डायबिटीज स्पेशलिटी सेंटर के अध्यक्ष और एक विश्व प्रसिद्ध मधुमेह विशेषज्ञ तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '044-43968888',
                'is_verified' => true,
            ],
            [
                'first_name' => 'P. V. A.',
                'last_name' => 'Mohandas',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'MIOT International',
                'hospital_name_hi' => 'मिओट इंटरनेशनल',
                'address' => '4/112, Mount Poonamallee Road, Manapakkam, Chennai, Tamil Nadu - 600089',
                'address_line1' => '4/112, Mount Poonamallee Road',
                'address_line2' => 'Manapakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600089',
                'latitude' => 13.0180,
                'longitude' => 80.1850,
                'experience_years' => 50,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'MCh (Ortho)', 'Padma Shri'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-3033',
                'about_en' => 'Dr. P. V. A. Mohandas is the Founder and Managing Director of MIOT International, a pioneer in total joint replacement surgery in India, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. पी. वी. ए. मोहनदास मिओट इंटरनेशनल के संस्थापक और प्रबंध निदेशक तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '044-22492288',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sivakumar',
                'last_name' => 'Rao',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'Apollo Cancer Centre',
                'hospital_name_hi' => 'अपोलो कैंसर सेंटर',
                'address' => '320, Padma Complex, Anna Salai, Teynampet, Chennai, Tamil Nadu - 600035',
                'address_line1' => '320, Padma Complex',
                'address_line2' => 'Anna Salai, Teynampet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600035',
                'latitude' => 13.0410,
                'longitude' => 80.2510,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Medical Oncology)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-4044',
                'about_en' => 'Dr. Sivakumar Rao is a Senior Consultant Medical Oncologist at Apollo Cancer Centre Chennai, expert in targeted therapy and precision oncology.',
                'about_hi' => 'डॉ. शिवकुमार राव अपोलो कैंसर सेंटर चेन्नई में वरिष्ठ सलाहकार मेडिकल ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '044-24336119',
                'is_verified' => true,
            ],
            [
                'first_name' => 'S. S.',
                'last_name' => 'Badrinath',
                'department_name_en' => 'Ophthalmology',
                'department_name_hi' => 'नेत्र रोग (ऑप्थल्मोलॉजी)',
                'hospital_name_en' => 'Sankara Nethralaya',
                'hospital_name_hi' => 'शंकर नेत्रालय',
                'address' => '41, College Road, Thousand Lights, Chennai, Tamil Nadu - 600006',
                'address_line1' => '41, College Road',
                'address_line2' => 'Thousand Lights',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'latitude' => 13.0650,
                'longitude' => 80.2450,
                'experience_years' => 55,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'FRCS (Canada)', 'Padma Bhushan', 'Padma Shri'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-5055',
                'about_en' => 'Dr. S. S. Badrinath was the legendary Founder of Sankara Nethralaya, an institution that revolutionized ophthalmic care in India, and recipient of Padma Bhushan and Padma Shri.',
                'about_hi' => 'डॉ. एस. एस. बद्रीनाथ शंकर नेत्रालय के महान संस्थापक और पद्म भूषण तथा पद्म श्री से सम्मानित थे।',
                'gender' => 'Male',
                'phone' => '044-42271500',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Jayashree',
                'last_name' => 'Gopal',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Apollo Women\'s Hospital',
                'hospital_name_hi' => 'अपोलो विमेंस अस्पताल',
                'address' => '15, Shafee Mohammed Road, Thousand Lights, Chennai, Tamil Nadu - 600006',
                'address_line1' => '15, Shafee Mohammed Road',
                'address_line2' => 'Thousand Lights',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'latitude' => 13.0620,
                'longitude' => 80.2520,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'MRCOG'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-6066',
                'about_en' => 'Dr. Jayashree Gopal is a Senior Consultant Obstetrician & Gynecologist at Apollo Women\'s Hospital Chennai, expert in high-risk pregnancies.',
                'about_hi' => 'डॉ. जयश्री गोपाल अपोलो विमेंस अस्पताल चेन्नई में वरिष्ठ सलाहकार प्रसूति एवं स्त्री रोग विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '044-28290200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Prithika',
                'last_name' => 'Chary',
                'department_name_en' => 'Neurology',
                'department_name_hi' => 'तंत्रिका विज्ञान (न्यूरोलॉजी)',
                'hospital_name_en' => 'Kauvery Hospital',
                'hospital_name_hi' => 'कावेरी अस्पताल',
                'address' => '81, TTK Road, Alwarpet, Chennai, Tamil Nadu - 600018',
                'address_line1' => '81, TTK Road',
                'address_line2' => 'Alwarpet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600018',
                'latitude' => 13.0320,
                'longitude' => 80.2550,
                'experience_years' => 42,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Neurology)', 'MCh (Neurosurgery)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-7077',
                'about_en' => 'Dr. Prithika Chary is the Chief Neurologist and Neurosurgeon at Kauvery Hospital, the first and only woman in India to be qualified in both neurology and neurosurgery.',
                'about_hi' => 'डॉ. पृथिका चारी कावेरी अस्पताल में मुख्य न्यूरोलॉजिस्ट और न्यूरोसर्जन हैं।',
                'gender' => 'Female',
                'phone' => '044-40006000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Suresh',
                'last_name' => 'Rao',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Kanchi Kamakoti Childs Trust Hospital',
                'hospital_name_hi' => 'कांची कामकोटि चाइल्ड्स ट्रस्ट अस्पताल',
                'address' => '12-A, Nageswara Road, Nungambakkam, Chennai, Tamil Nadu - 600034',
                'address_line1' => '12-A, Nageswara Road',
                'address_line2' => 'Nungambakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600034',
                'latitude' => 13.0550,
                'longitude' => 80.2450,
                'experience_years' => 38,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'FRCPCH'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-8088',
                'about_en' => 'Dr. Suresh Rao is a Senior Consultant Pediatrician at Kanchi Kamakoti Childs Trust Hospital, specializing in pediatric critical care and neonatology.',
                'about_hi' => 'डॉ. सुरेश राव कांची कामकोटि चाइल्ड्स ट्रस्ट अस्पताल में वरिष्ठ सलाहकार बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '044-42001800',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Mohan',
                'last_name' => 'Kameswaran',
                'department_name_en' => 'ENT (Otolaryngology)',
                'department_name_hi' => 'कान, नाक और गला रोग (ईएनटी)',
                'hospital_name_en' => 'Madras ENT Research Foundation (MERF)',
                'hospital_name_hi' => 'मद्रास ईएनटी रिसर्च फाउंडेशन (एमईआरएफ)',
                'address' => '1, 1st Cross Street, Off Raja Annamalai Puram, Chennai, Tamil Nadu - 600028',
                'address_line1' => '1, 1st Cross Street',
                'address_line2' => 'Off Raja Annamalai Puram',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600028',
                'latitude' => 13.0250,
                'longitude' => 80.2580,
                'experience_years' => 40,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (ENT)', 'FRCS (Edin)', 'Padma Shri'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-9099',
                'about_en' => 'Dr. Mohan Kameswaran is the Managing Director of MERF, a pioneer in cochlear implant surgery in India, and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. मोहन कामेश्वरन एमईआरएफ के प्रबंध निदेशक और भारत में कॉक्लियर इम्प्लांट सर्जरी के प्रणेता तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '044-24958595',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Joy',
                'last_name' => 'Varghese',
                'department_name_en' => 'Hepatology',
                'department_name_hi' => 'यकृत रोग (हेपेटोलॉजी)',
                'hospital_name_en' => 'Gleneagles Global Health City',
                'hospital_name_hi' => 'ग्लेनीगल्स ग्लोबल हेल्थ सिटी',
                'address' => '439, Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu - 600100',
                'address_line1' => '439, Cheran Nagar',
                'address_line2' => 'Perumbakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600100',
                'latitude' => 12.9020,
                'longitude' => 80.2010,
                'experience_years' => 26,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Hepatology)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11233',
                'about_en' => 'Dr. Joy Varghese is a Senior Consultant Hepatologist and Liver Transplant Physician at Gleneagles Global Health City Chennai, renowned for complex liver diseases and intensive care.',
                'about_hi' => 'डॉ. जॉय वर्गीस ग्लेनीगल्स ग्लोबल हेल्थ सिटी चेन्नई में वरिष्ठ सलाहकार हेपेटोलॉजिस्ट और लिवर प्रत्यारोपण चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '044-44775000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Georgi',
                'last_name' => 'Abraham',
                'department_name_en' => 'Nephrology',
                'department_name_hi' => 'गुर्दा रोग (नेफ्रोलॉजी)',
                'hospital_name_en' => 'MGM Healthcare',
                'hospital_name_hi' => 'एमजीएम हेल्थकेयर',
                'address' => '72, Nelson Manickam Road, Aminjikarai, Chennai, Tamil Nadu - 600029',
                'address_line1' => '72, Nelson Manickam Road',
                'address_line2' => 'Aminjikarai',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600029',
                'latitude' => 13.0720,
                'longitude' => 80.2220,
                'experience_years' => 40,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRCP (London)', 'FRCP (Glasgow)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11234',
                'about_en' => 'Dr. Georgi Abraham is a Senior Consultant Nephrologist at MGM Healthcare Chennai, pioneer of continuous ambulatory peritoneal dialysis (CAPD) in India.',
                'about_hi' => 'डॉ. जॉर्जी अब्राहम एमजीएम हेल्थकेयर चेन्नई में वरिष्ठ सलाहकार नेफ्रोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '044-45242424',
                'is_verified' => true,
            ],
            [
                'first_name' => 'B. S.',
                'last_name' => 'Ramakrishna',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'SIMS Hospital',
                'hospital_name_hi' => 'सिम्स अस्पताल',
                'address' => '1, Jawaharlal Nehru Salai, Vadapalani, Chennai, Tamil Nadu - 600026',
                'address_line1' => '1, Jawaharlal Nehru Salai',
                'address_line2' => 'Vadapalani',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600026',
                'latitude' => 13.0510,
                'longitude' => 80.2120,
                'experience_years' => 42,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)', 'FAMS'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11235',
                'about_en' => 'Dr. B. S. Ramakrishna is a Senior Consultant Gastroenterologist at SIMS Hospital Chennai, globally recognized for inflammatory bowel disease research.',
                'about_hi' => 'डॉ. बी. एस. रामकृष्ण सिम्स अस्पताल चेन्नई में वरिष्ठ सलाहकार गैस्ट्रोएंटरोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '044-20002001',
                'is_verified' => true,
            ],
            [
                'first_name' => 'R.',
                'last_name' => 'Ravi',
                'department_name_en' => 'Urology',
                'department_name_hi' => 'मूत्र रोग (यूरोलॉजी)',
                'hospital_name_en' => 'Sri Ramachandra Medical Centre',
                'hospital_name_hi' => 'श्री रामचंद्र मेडिकल सेंटर',
                'address' => '1, Ramachandra Nagar, Porur, Chennai, Tamil Nadu - 600116',
                'address_line1' => '1, Ramachandra Nagar',
                'address_line2' => 'Porur',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600116',
                'latitude' => 13.0380,
                'longitude' => 80.1520,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Urology)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11236',
                'about_en' => 'Dr. R. Ravi is a Senior Professor and Head of Urology at Sri Ramachandra Medical Centre Chennai, expert in endourology and renal transplantation.',
                'about_hi' => 'डॉ. आर. रवि श्री रामचंद्र मेडिकल सेंटर चेन्नई में यूरोलॉजी के वरिष्ठ प्रोफेसर और प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '044-45928500',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Madhuri',
                'last_name' => 'S.',
                'department_name_en' => 'Rheumatology',
                'department_name_hi' => 'गठिया रोग (रुमेटोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => '21, Greams Lane, Thousand Lights, Chennai, Tamil Nadu - 600006',
                'address_line1' => '21, Greams Lane',
                'address_line2' => 'Thousand Lights',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600006',
                'latitude' => 13.0610,
                'longitude' => 80.2520,
                'experience_years' => 28,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Rheumatology)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11237',
                'about_en' => 'Dr. Madhuri S is a Senior Consultant Rheumatologist at Apollo Hospitals Greams Road Chennai, expert in lupus and rheumatoid arthritis.',
                'about_hi' => 'डॉ. माधुरी एस अपोलो अस्पताल ग्रीम्स रोड चेन्नई में वरिष्ठ सलाहकार रुमेटोलॉजिस्ट हैं।',
                'gender' => 'Female',
                'phone' => '044-28290200',
                'is_verified' => true,
            ],
            [
                'first_name' => 'V. P.',
                'last_name' => 'Chandrasekaran',
                'department_name_en' => 'Pulmonology',
                'department_name_hi' => 'श्वसन रोग (पल्मोनोलॉजी)',
                'hospital_name_en' => 'Kauvery Hospital',
                'hospital_name_hi' => 'कावेरी अस्पताल',
                'address' => '81, TTK Road, Alwarpet, Chennai, Tamil Nadu - 600018',
                'address_line1' => '81, TTK Road',
                'address_line2' => 'Alwarpet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600018',
                'latitude' => 13.0320,
                'longitude' => 80.2550,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DTCD'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11238',
                'about_en' => 'Dr. V. P. Chandrasekaran is a Senior Consultant Pulmonologist at Kauvery Hospital Alwarpet Chennai, specializing in interventional pulmonology.',
                'about_hi' => 'डॉ. वी. पी. चंद्रशेखरन कावेरी अस्पताल अलवरपेट चेन्नई में वरिष्ठ सलाहकार पल्मोनोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '044-40006000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'R.',
                'last_name' => 'Rajagopal',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'Billroth Hospitals',
                'hospital_name_hi' => 'बिल्लरोथ अस्पताल',
                'address' => '43, Lakshmi Talkies Road, Shenoy Nagar, Chennai, Tamil Nadu - 600030',
                'address_line1' => '43, Lakshmi Talkies Road',
                'address_line2' => 'Shenoy Nagar',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600030',
                'latitude' => 13.0790,
                'longitude' => 80.2250,
                'experience_years' => 30,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FIAGES'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11239',
                'about_en' => 'Dr. R. Rajagopal is a Senior Consultant General and Laparoscopic Surgeon at Billroth Hospitals Chennai.',
                'about_hi' => 'डॉ. आर. राजगोपाल बिल्लरोथ अस्पताल चेन्नई में वरिष्ठ सलाहकार सामान्य और लेप्रोस्कोपिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '044-42921111',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Anandhi',
                'last_name' => 'M.',
                'department_name_en' => 'Dermatology',
                'department_name_hi' => 'त्वचा रोग (डर्मेटोलॉजी)',
                'hospital_name_en' => 'Stanley Medical College Hospital',
                'hospital_name_hi' => 'स्टेनली मेडिकल कॉलेज अस्पताल',
                'address' => '1, Old Jail Road, Royapuram, Chennai, Tamil Nadu - 600001',
                'address_line1' => '1, Old Jail Road',
                'address_line2' => 'Royapuram',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600001',
                'latitude' => 13.1050,
                'longitude' => 80.2850,
                'experience_years' => 28,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Dermatology)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11240',
                'about_en' => 'Dr. Anandhi M is a Senior Consultant Dermatologist at Stanley Medical College Hospital Chennai.',
                'about_hi' => 'डॉ. आनंधी एम स्टेनली मेडिकल कॉलेज अस्पताल चेन्नई में वरिष्ठ सलाहकार त्वचा विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '044-25281351',
                'is_verified' => true,
            ],
            [
                'first_name' => 'S.',
                'last_name' => 'Thangavelu',
                'department_name_en' => 'Pediatric Surgery',
                'department_name_hi' => 'बाल शल्य चिकित्सा (पीडियाट्रिक सर्जरी)',
                'hospital_name_en' => 'Kanchi Kamakoti Childs Trust Hospital',
                'hospital_name_hi' => 'कांची कामकोटि चाइल्ड्स ट्रस्ट अस्पताल',
                'address' => '12-A, Nageswara Road, Nungambakkam, Chennai, Tamil Nadu - 600034',
                'address_line1' => '12-A, Nageswara Road',
                'address_line2' => 'Nungambakkam',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600034',
                'latitude' => 13.0550,
                'longitude' => 80.2450,
                'experience_years' => 34,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Pediatric Surgery)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11241',
                'about_en' => 'Dr. S. Thangavelu is a Senior Consultant Pediatric Surgeon at Kanchi Kamakoti Childs Trust Hospital Chennai, expert in neonatal surgery.',
                'about_hi' => 'डॉ. एस. थंगावेलु कांची कामकोटि चाइल्ड्स ट्रस्ट अस्पताल चेन्नई में वरिष्ठ सलाहकार बाल सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '044-42001800',
                'is_verified' => true,
            ],
            [
                'first_name' => 'K. S.',
                'last_name' => 'Vijay',
                'department_name_en' => 'Neurosurgery',
                'department_name_hi' => 'न्यूरोसर्जरी',
                'hospital_name_en' => 'Prashanth Super Speciality Hospital',
                'hospital_name_hi' => 'प्रशांत सुपर स्पेशलिटी अस्पताल',
                'address' => '36 & 36A, Velachery Main Road, Velachery, Chennai, Tamil Nadu - 600042',
                'address_line1' => '36 & 36A, Velachery Main Road',
                'address_line2' => 'Velachery',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600042',
                'latitude' => 12.9780,
                'longitude' => 80.2210,
                'experience_years' => 26,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Neurosurgery)'],
                'medical_council' => 'Tamil Nadu Medical Council (TNMC)',
                'registration_number' => 'TNMC-11242',
                'about_en' => 'Dr. K. S. Vijay is a Senior Consultant Neurosurgeon at Prashanth Super Speciality Hospital Chennai, expert in spine and brain trauma surgery.',
                'about_hi' => 'डॉ. के. एस. विजय प्रशांत सुपर स्पेशलिटी अस्पताल चेन्नई में वरिष्ठ सलाहकार न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '044-46805555',
                'is_verified' => true,
            ],
        ];
    }
}
