<?php

namespace App\Services;

class HyderabadScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'hyderabad') {
            return [];
        }

        return [
            [
                'name_en' => 'Chiranjeevi Eye and Blood Bank',
                'name_hi' => 'चिरंजीवी आई एवं ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'address_en' => 'Road No. 1, Jubilee Hills, Hyderabad, Telangana - 500034',
                'address_hi' => 'रोड नं. 1, जुबली हिल्स, हैदराबाद, तेलंगाना - 500034',
                'country_code' => '+91',
                'phone' => '040-23555555',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-23555555',
                'email' => 'contact@chiranjeevibloodbank.com',
                'website' => 'https://chiranjeevibloodbank.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Chiranjeevi Registry',
                'source_url' => 'https://chiranjeevibloodbank.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Osmania General Hospital Blood Bank',
                'name_hi' => 'उस्मानिया जनरल अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500012',
                'address_en' => 'Afzal Gunj, Hyderabad, Telangana - 500012',
                'address_hi' => 'अफजल गंज, हैदराबाद, तेलंगाना - 500012',
                'country_code' => '+91',
                'phone' => '040-24600121',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-24600121',
                'email' => 'osmaniabloodbank@telangana.gov.in',
                'website' => 'https://osmaniageneralhospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Osmania Registry',
                'source_url' => 'https://osmaniageneralhospital.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Gandhi Hospital Blood Bank',
                'name_hi' => 'गांधी अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500025',
                'address_en' => 'Musheerabad, Padmarao Nagar, Secunderabad, Hyderabad, Telangana - 500025',
                'address_hi' => 'मुशीराबाद, पद्मराव नगर, सिकंदराबाद, हैदराबाद, तेलंगाना - 500025',
                'country_code' => '+91',
                'phone' => '040-27702222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-27702222',
                'email' => 'gandhibloodbank@telangana.gov.in',
                'website' => 'https://gandhihospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Gandhi Registry',
                'source_url' => 'https://gandhihospital.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'NIMS Blood Bank (Nizam\'s Institute of Medical Sciences)',
                'name_hi' => 'निम्स ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500082',
                'address_en' => 'Punjagutta, Hyderabad, Telangana - 500082',
                'address_hi' => 'पुंजागुट्टा, हैदराबाद, तेलंगाना - 500082',
                'country_code' => '+91',
                'phone' => '040-23489000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-23489000',
                'email' => 'bloodbank@nims.edu.in',
                'website' => 'https://nims.edu.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / NIMS Registry',
                'source_url' => 'https://nims.edu.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Lions Club of Hyderabad Blood Bank',
                'name_hi' => 'लायंस क्लब ऑफ हैदराबाद ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500029',
                'address_en' => '1-8-32/44, Bapu Bagh, Ramgopalpet, Secunderabad, Hyderabad, Telangana - 500029',
                'address_hi' => '1-8-32/44, बापू बाग, रामगोपालपेट, सिकंदराबाद, हैदराबाद, तेलंगाना - 500029',
                'country_code' => '+91',
                'phone' => '040-27806501',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-27806501',
                'email' => 'contact@lionsbloodbankhyderabad.org',
                'website' => 'https://lionsbloodbankhyderabad.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Lions Registry',
                'source_url' => 'https://lionsbloodbankhyderabad.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Apollo Hospitals Blood Bank Jubilee Hills',
                'name_hi' => 'अपोलो अस्पताल ब्लड बैंक जुबली हिल्स',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500033',
                'address_en' => 'Road No. 92, Jubilee Hills, Hyderabad, Telangana - 500033',
                'address_hi' => 'रोड नं. 92, जुबली हिल्स, हैदराबाद, तेलंगाना - 500033',
                'country_code' => '+91',
                'phone' => '040-23607777',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-23607777',
                'email' => 'bloodbank_jh@apollohospitals.com',
                'website' => 'https://apollohospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Apollo JH Registry',
                'source_url' => 'https://apollohospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Yashoda Hospitals Blood Bank Secunderabad',
                'name_hi' => 'यशोदा अस्पताल ब्लड बैंक सिकंदराबाद',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'address_en' => 'Alexander Road, Secunderabad, Hyderabad, Telangana - 500003',
                'address_hi' => 'अलेक्जेंडर रोड, सिकंदराबाद, हैदराबाद, तेलंगाना - 500003',
                'country_code' => '+91',
                'phone' => '040-45674567',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-45674567',
                'email' => 'bloodbank.sec@yashodamail.com',
                'website' => 'https://yashodahospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Yashoda Sec Registry',
                'source_url' => 'https://yashodahospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'AIG Hospitals Blood Bank Gachibowli',
                'name_hi' => 'एआईजी अस्पताल ब्लड बैंक गचीबाउली',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'address_en' => '1-56/1/1, Mindspace Road, Gachibowli, Hyderabad, Telangana - 500032',
                'address_hi' => '1-56/1/1, माइंडस्पेस रोड, गचीबाउली, हैदराबाद, तेलंगाना - 500032',
                'country_code' => '+91',
                'phone' => '040-42444222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-42444222',
                'email' => 'bloodbank@aighospitals.com',
                'website' => 'https://aighospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / AIG Registry',
                'source_url' => 'https://aighospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'CARE Hospitals Blood Bank Banjara Hills',
                'name_hi' => 'केयर अस्पताल ब्लड बैंक बंजारा हिल्स',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'address_en' => 'Road No. 1, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_hi' => 'रोड नं. 1, बंजारा हिल्स, हैदराबाद, तेलंगाना - 500034',
                'country_code' => '+91',
                'phone' => '040-61656565',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-61656565',
                'email' => 'bloodbank.bh@carehospitals.com',
                'website' => 'https://carehospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / CARE BH Registry',
                'source_url' => 'https://carehospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'KIMS Hospitals Blood Bank Secunderabad',
                'name_hi' => 'किम्स अस्पताल ब्लड बैंक सिकंदराबाद',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'address_en' => '1-8-31/1, Minister Road, Krishna Nagar, Secunderabad, Hyderabad, Telangana - 500003',
                'address_hi' => '1-8-31/1, मिनिस्टर रोड, कृष्णा नगर, सिकंदराबाद, हैदराबाद, तेलंगाना - 500003',
                'country_code' => '+91',
                'phone' => '040-44885000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-44885000',
                'email' => 'bloodbank@kimshospitals.com',
                'website' => 'https://kimshospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / KIMS Registry',
                'source_url' => 'https://kimshospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'NTR Memorial Trust Blood Bank',
                'name_hi' => 'एनटीआर मेमोरियल ट्रस्ट ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'address_en' => 'Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_hi' => 'रोड नं. 2, बंजारा हिल्स, हैदराबाद, तेलंगाना - 500034',
                'country_code' => '+91',
                'phone' => '040-30799999',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-30799999',
                'email' => 'bloodbank@ntrtrust.org',
                'website' => 'https://ntrtrust.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / NTR Trust Registry',
                'source_url' => 'https://ntrtrust.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Institute of Preventive Medicine (IPM) Blood Bank',
                'name_hi' => 'इंस्टीट्यूट ऑफ प्रिवेंटिव मेडिसिन (आईपीएम) ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500029',
                'address_en' => 'Narayanaguda, Hyderabad, Telangana - 500029',
                'address_hi' => 'नारायणगुडा, हैदराबाद, तेलंगाना - 500029',
                'country_code' => '+91',
                'phone' => '040-23232254',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-23232254',
                'email' => 'ipmbloodbank@telangana.gov.in',
                'website' => 'https://telangana.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / IPM Registry',
                'source_url' => 'https://telangana.gov.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Basavatarakam Indo American Cancer Hospital Blood Bank',
                'name_hi' => 'बसावतारकम इंडो अमेरिकन कैंसर अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'address_en' => 'Road No. 10, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_hi' => 'रोड नं. 10, बंजारा हिल्स, हैदराबाद, तेलंगाना - 500034',
                'country_code' => '+91',
                'phone' => '040-23551235',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-23551235',
                'email' => 'bloodbank@indocancer.com',
                'website' => 'https://indocancer.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Basavatarakam Registry',
                'source_url' => 'https://indocancer.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Medicover Hospitals Blood Bank',
                'name_hi' => 'मेडीकवर अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500081',
                'address_en' => 'Behind Cyber Towers, Hitec City, Madhapur, Hyderabad, Telangana - 500081',
                'address_hi' => 'साइबर टावर्स के पीछे, हाईटेक सिटी, माधापुर, हैदराबाद, तेलंगाना - 500081',
                'country_code' => '+91',
                'phone' => '040-68334455',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-68334455',
                'email' => 'bloodbank@medicoverhospitals.in',
                'website' => 'https://medicoverhospitals.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Medicover Registry',
                'source_url' => 'https://medicoverhospitals.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Sunshine Hospitals Blood Bank',
                'name_hi' => 'सनशाइन अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'address_en' => 'PG Road, Paradise, Secunderabad, Hyderabad, Telangana - 500003',
                'address_hi' => 'पीजी रोड, पैराडाइज, सिकंदराबाद, हैदराबाद, तेलंगाना - 500003',
                'country_code' => '+91',
                'phone' => '040-44550000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-44550000',
                'email' => 'bloodbank@sunshinehospitals.com',
                'website' => 'https://sunshinehospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Sunshine Registry',
                'source_url' => 'https://sunshinehospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Continental Hospitals Blood Bank',
                'name_hi' => 'कॉन्टिनेंटल अस्पताल ब्लड बैंक',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'address_en' => 'Plot No. 3, Road No. 2, IT & Financial Dist, Nanakramguda, Gachibowli, Hyderabad, Telangana - 500032',
                'address_hi' => 'प्लॉट नंबर 3, रोड नंबर 2, आईटी और वित्तीय जिला, नानकरामगुडा, गचीबाउली, हैदराबाद, तेलंगाना - 500032',
                'country_code' => '+91',
                'phone' => '040-67000000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '040-67000000',
                'email' => 'bloodbank@continentalhospitals.com',
                'website' => 'https://continentalhospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Continental Registry',
                'source_url' => 'https://continentalhospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'hyderabad') {
            return [];
        }

        return [
            [
                'name_en' => 'Osmania General Hospital',
                'name_hi' => 'उस्मानिया जनरल अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Afzal Gunj, Hyderabad, Telangana - 500012',
                'address_line1' => 'Afzal Gunj',
                'address_line2' => 'Near Nayapul',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500012',
                'emergency_phone' => '040-24600121',
                'emergency_country_code' => '+91',
                'latitude' => 17.3710,
                'longitude' => 78.4750,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'Aarogyasri', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Gandhi Hospital',
                'name_hi' => 'गांधी अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Musheerabad, Padmarao Nagar, Secunderabad, Hyderabad, Telangana - 500025',
                'address_line1' => 'Musheerabad, Padmarao Nagar',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500025',
                'emergency_phone' => '040-27702222',
                'emergency_country_code' => '+91',
                'latitude' => 17.4240,
                'longitude' => 78.5020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'NIMS (Nizam\'s Institute of Medical Sciences)',
                'name_hi' => 'निम्स (निज़ाम्स इंस्टीट्यूट ऑफ मेडिकल साइंसेज)',
                'type' => 'Government Hospital',
                'address' => 'Punjagutta, Hyderabad, Telangana - 500082',
                'address_line1' => 'Punjagutta',
                'address_line2' => 'Near Punjagutta Flyover',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500082',
                'emergency_phone' => '040-23489000',
                'emergency_country_code' => '+91',
                'latitude' => 17.4220,
                'longitude' => 78.4520,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Apollo Hospitals, Jubilee Hills',
                'name_hi' => 'अपोलो अस्पताल, जुबली हिल्स',
                'type' => 'Private Hospital',
                'address' => 'Road No. 92, Jubilee Hills, Hyderabad, Telangana - 500033',
                'address_line1' => 'Road No. 92, Jubilee Hills',
                'address_line2' => 'Near Film Nagar',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500033',
                'emergency_phone' => '040-23607777',
                'emergency_country_code' => '+91',
                'latitude' => 17.4150,
                'longitude' => 78.4050,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'AIG Hospitals, Gachibowli (Asian Institute of Gastroenterology)',
                'name_hi' => 'एआईजी अस्पताल, गचीबाउली',
                'type' => 'Private Hospital',
                'address' => '1-56/1/1, Mindspace Road, Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => '1-56/1/1, Mindspace Road',
                'address_line2' => 'Gachibowli',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'emergency_phone' => '040-42444222',
                'emergency_country_code' => '+91',
                'latitude' => 17.4420,
                'longitude' => 78.3650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Yashoda Hospitals, Secunderabad',
                'name_hi' => 'यशोदा अस्पताल, सिकंदराबाद',
                'type' => 'Private Hospital',
                'address' => 'Alexander Road, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => 'Alexander Road',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'emergency_phone' => '040-45674567',
                'emergency_country_code' => '+91',
                'latitude' => 17.4400,
                'longitude' => 78.5000,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Yashoda Hospitals, Somajiguda',
                'name_hi' => 'यशोदा अस्पताल, सोमाजीगुडा',
                'type' => 'Private Hospital',
                'address' => 'Raj Bhavan Road, Somajiguda, Hyderabad, Telangana - 500082',
                'address_line1' => 'Raj Bhavan Road',
                'address_line2' => 'Somajiguda',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500082',
                'emergency_phone' => '040-45674567',
                'emergency_country_code' => '+91',
                'latitude' => 17.4250,
                'longitude' => 78.4550,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'KIMS Hospitals, Secunderabad (Krishna Institute of Medical Sciences)',
                'name_hi' => 'किम्स अस्पताल, सिकंदराबाद',
                'type' => 'Private Hospital',
                'address' => '1-8-31/1, Minister Road, Krishna Nagar, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => '1-8-31/1, Minister Road',
                'address_line2' => 'Krishna Nagar, Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'emergency_phone' => '040-44885000',
                'emergency_country_code' => '+91',
                'latitude' => 17.4350,
                'longitude' => 78.4850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'Max Bupa TPA'],
            ],
            [
                'name_en' => 'CARE Hospitals, Banjara Hills',
                'name_hi' => 'केयर अस्पताल, बंजारा हिल्स',
                'type' => 'Private Hospital',
                'address' => 'Road No. 1, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 1',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'emergency_phone' => '040-61656565',
                'emergency_country_code' => '+91',
                'latitude' => 17.4180,
                'longitude' => 78.4480,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Continental Hospitals, Gachibowli',
                'name_hi' => 'कॉन्टिनेंटल अस्पताल, गचीबाउली',
                'type' => 'Private Hospital',
                'address' => 'Plot No. 3, Road No. 2, IT & Financial Dist, Nanakramguda, Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => 'Plot No. 3, Road No. 2',
                'address_line2' => 'IT & Financial Dist, Nanakramguda',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'emergency_phone' => '040-67000000',
                'emergency_country_code' => '+91',
                'latitude' => 17.4150,
                'longitude' => 78.3450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Star Hospitals, Banjara Hills',
                'name_hi' => 'स्टार अस्पताल, बंजारा हिल्स',
                'type' => 'Private Hospital',
                'address' => '8-2-596/5, Road No. 10, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => '8-2-596/5, Road No. 10',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'emergency_phone' => '040-44777777',
                'emergency_country_code' => '+91',
                'latitude' => 17.4120,
                'longitude' => 78.4450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Medicover Hospitals, Hitec City',
                'name_hi' => 'मेडीकवर अस्पताल, हाईटेक सिटी',
                'type' => 'Private Hospital',
                'address' => 'Behind Cyber Towers, Hitec City, Madhapur, Hyderabad, Telangana - 500081',
                'address_line1' => 'Behind Cyber Towers',
                'address_line2' => 'Hitec City, Madhapur',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500081',
                'emergency_phone' => '040-68334455',
                'emergency_country_code' => '+91',
                'latitude' => 17.4520,
                'longitude' => 78.3810,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Basavatarakam Indo American Cancer Hospital & Research Institute',
                'name_hi' => 'बसावतारकम इंडो अमेरिकन कैंसर अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Road No. 10, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 10',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'emergency_phone' => '040-23551235',
                'emergency_country_code' => '+91',
                'latitude' => 17.4120,
                'longitude' => 78.4410,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Rainbow Children\'s Hospital & BirthRight by Rainbow',
                'name_hi' => 'रेनबो चिल्ड्रन्स अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 2',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'emergency_phone' => '040-44888888',
                'emergency_country_code' => '+91',
                'latitude' => 17.4200,
                'longitude' => 78.4420,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Sunshine Hospitals (KIMS)',
                'name_hi' => 'सनशाइन अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'PG Road, Paradise, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => 'PG Road, Paradise',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'emergency_phone' => '040-44550000',
                'emergency_country_code' => '+91',
                'latitude' => 17.4410,
                'longitude' => 78.4880,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'CARE Hospitals, Hitec City',
                'name_hi' => 'केयर अस्पताल, हाईटेक सिटी',
                'type' => 'Private Hospital',
                'address' => 'Old Mumbai Highway, Near Cyber Towers, Hitec City, Hyderabad, Telangana - 500081',
                'address_line1' => 'Old Mumbai Highway, Near Cyber Towers',
                'address_line2' => 'Hitec City',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500081',
                'emergency_phone' => '040-67206588',
                'emergency_country_code' => '+91',
                'latitude' => 17.4500,
                'longitude' => 78.3800,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ICICI Lombard TPA', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Yashoda Hospitals, Malakpet',
                'name_hi' => 'यशोदा अस्पताल, मलकपेट',
                'type' => 'Private Hospital',
                'address' => 'Nalgonda X Roads, Malakpet, Hyderabad, Telangana - 500036',
                'address_line1' => 'Nalgonda X Roads',
                'address_line2' => 'Malakpet',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500036',
                'emergency_phone' => '040-45674567',
                'emergency_country_code' => '+91',
                'latitude' => 17.3750,
                'longitude' => 78.4950,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'L V Prasad Eye Institute',
                'name_hi' => 'एल वी प्रसाद आई इंस्टीट्यूट',
                'type' => 'Private Hospital',
                'address' => 'Kallam Anji Reddy Campus, Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Kallam Anji Reddy Campus, Road No. 2',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'emergency_phone' => '040-30612345',
                'emergency_country_code' => '+91',
                'latitude' => 17.4220,
                'longitude' => 78.4350,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS'],
            ],
            [
                'name_en' => 'Government ENT Hospital',
                'name_hi' => 'सरकारी ईएनटी अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Koti, Hyderabad, Telangana - 500095',
                'address_line1' => 'Koti',
                'address_line2' => 'Near Women\'s College',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500095',
                'emergency_phone' => '040-24740251',
                'emergency_country_code' => '+91',
                'latitude' => 17.3850,
                'longitude' => 78.4850,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS'],
            ],
            [
                'name_en' => 'Niloufer Hospital for Women and Children',
                'name_hi' => 'निलौफर महिला एवं बाल अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Red Hills, Lakdikapul, Hyderabad, Telangana - 500004',
                'address_line1' => 'Red Hills',
                'address_line2' => 'Lakdikapul',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500004',
                'emergency_phone' => '040-23393005',
                'emergency_country_code' => '+91',
                'latitude' => 17.3950,
                'longitude' => 78.4620,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Aarogyasri', 'CGHS'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'hyderabad') {
            return [];
        }

        return [
            [
                'first_name' => 'D. Nageshwar',
                'last_name' => 'Reddy',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'AIG Hospitals',
                'hospital_name_hi' => 'एआईजी अस्पताल',
                'address' => 'Mindspace Road, Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => 'Mindspace Road',
                'address_line2' => 'Gachibowli',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'latitude' => 17.4420,
                'longitude' => 78.3650,
                'experience_years' => 45,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)', 'Padma Bhushan', 'Padma Shri'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-1011',
                'about_en' => 'Dr. D. Nageshwar Reddy is the Chairman and Founder of Asian Institute of Gastroenterology (AIG), world-renowned for therapeutic endoscopy and recipient of Padma Bhushan and Padma Shri.',
                'about_hi' => 'डॉ. डी. नागेश्वर रेड्डी एआईजी हॉस्पिटल्स के अध्यक्ष और संस्थापक तथा पद्म भूषण और पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '040-42444222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Gopichand',
                'last_name' => 'Mannam',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Star Hospitals',
                'hospital_name_hi' => 'स्टार अस्पताल',
                'address' => 'Road No. 10, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 10',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4120,
                'longitude' => 78.4450,
                'experience_years' => 40,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'FRCS (London)', 'Padma Shri'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-2022',
                'about_en' => 'Dr. Gopichand Mannam is the Managing Director of Star Hospitals and a legendary Cardiothoracic Surgeon who has performed over 10,000 pediatric and adult heart surgeries.',
                'about_hi' => 'डॉ. गोपीचंद मन्नम स्टार हॉस्पिटल्स के प्रबंध निदेशक और एक महान कार्डियोथोरेसिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '040-44777777',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Somaraju',
                'last_name' => 'Bhupathiraju',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'AIG Hospitals / CARE',
                'hospital_name_hi' => 'एआईजी अस्पताल / केयर',
                'address' => 'Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => 'Mindspace Road',
                'address_line2' => 'Gachibowli',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'latitude' => 17.4420,
                'longitude' => 78.3650,
                'experience_years' => 48,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'Padma Shri'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-3033',
                'about_en' => 'Dr. B. Somaraju is a legendary Cardiologist, Founder of CARE Hospitals, and co-inventor of India\'s first indigenous coronary stent (Kalam-Raju Stent).',
                'about_hi' => 'डॉ. बी. सोमराजू एक महान कार्डियोलॉजिस्ट, केयर हॉस्पिटल्स के संस्थापक और कलाम-राजू स्टेंट के सह-आविष्कारक हैं।',
                'gender' => 'Male',
                'phone' => '040-42444222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Mohana',
                'last_name' => 'Vamsy',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'Omega Hospitals',
                'hospital_name_hi' => 'ओमेगा अस्पताल',
                'address' => 'CHAI Complex, Road No. 12, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'CHAI Complex, Road No. 12',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4100,
                'longitude' => 78.4400,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'DNB (Surgical Oncology)', 'FRCS'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-4044',
                'about_en' => 'Dr. Mohana Vamsy is the Chief Surgical Oncologist and Managing Director of Omega Hospitals, renowned for advanced laparoscopic and robotic oncological surgeries.',
                'about_hi' => 'डॉ. मोहन वामसी ओमेगा हॉस्पिटल्स के मुख्य सर्जिकल ऑन्कोलॉजिस्ट और प्रबंध निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '040-23555555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Prathap',
                'last_name' => 'C. Reddy',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Apollo Hospitals',
                'hospital_name_hi' => 'अपोलो अस्पताल',
                'address' => 'Road No. 92, Jubilee Hills, Hyderabad, Telangana - 500033',
                'address_line1' => 'Road No. 92, Jubilee Hills',
                'address_line2' => 'Near Film Nagar',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500033',
                'latitude' => 17.4150,
                'longitude' => 78.4050,
                'experience_years' => 60,
                'consultation_fee' => 2000,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'Fellowship in Cardiology (USA)', 'Padma Vibhushan'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-5055',
                'about_en' => 'Dr. Prathap C. Reddy is the visionary Founder Chairman of Apollo Hospitals Group, architect of modern corporate healthcare in India, and recipient of the Padma Vibhushan.',
                'about_hi' => 'डॉ. प्रताप सी. रेड्डी अपोलो हॉस्पिटल्स समूह के संस्थापक अध्यक्ष और भारत में आधुनिक कॉर्पोरेट स्वास्थ्य देखभाल के निर्माता हैं।',
                'gender' => 'Male',
                'phone' => '040-23607777',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Gurava',
                'last_name' => 'Reddy',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Sunshine Hospitals (KIMS)',
                'hospital_name_hi' => 'सनशाइन अस्पताल',
                'address' => 'PG Road, Paradise, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => 'PG Road, Paradise',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'latitude' => 17.4410,
                'longitude' => 78.4880,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'FRCS (London)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-6066',
                'about_en' => 'Dr. A. V. Gurava Reddy is the Managing Director and Chief Joint Replacement Surgeon at Sunshine Hospitals, having performed over 20,000 joint replacements.',
                'about_hi' => 'डॉ. ए. वी. गुरुवा रेड्डी सनशाइन हॉस्पिटल्स के प्रबंध निदेशक और मुख्य संयुक्त प्रत्यारोपण सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '040-44550000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sita',
                'last_name' => 'Jayalakshmi',
                'department_name_en' => 'Neurology',
                'department_name_hi' => 'तंत्रिका विज्ञान (न्यूरोलॉजी)',
                'hospital_name_en' => 'KIMS Hospitals',
                'hospital_name_hi' => 'किम्स अस्पताल',
                'address' => 'Minister Road, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => 'Minister Road',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'latitude' => 17.4350,
                'longitude' => 78.4850,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Neurology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-7077',
                'about_en' => 'Dr. Sita Jayalakshmi is a Senior Consultant Neurologist at KIMS Hospitals Secunderabad, expert in epilepsy and electrophysiology.',
                'about_hi' => 'डॉ. सीता जयलक्ष्मी किम्स हॉस्पिटल्स सिकंदराबाद में वरिष्ठ सलाहकार न्यूरोलॉजिस्ट हैं।',
                'gender' => 'Female',
                'phone' => '040-44885000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Pranathi',
                'last_name' => 'Reddy',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Rainbow Hospital for Women and Children',
                'hospital_name_hi' => 'रेनबो अस्पताल',
                'address' => 'Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 2',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4200,
                'longitude' => 78.4420,
                'experience_years' => 30,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'MRCOG (London)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-8088',
                'about_en' => 'Dr. Pranathi Reddy is the Clinical Director of Obstetrics and Gynecology at Rainbow Hospitals Banjara Hills, expert in high-risk obstetrics.',
                'about_hi' => 'डॉ. प्रणति रेड्डी रेनबो हॉस्पिटल्स बंजारा हिल्स में प्रसूति एवं स्त्री रोग की नैदानिक निदेशक हैं।',
                'gender' => 'Female',
                'phone' => '040-44888888',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Ramesh',
                'last_name' => 'Kancharla',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Rainbow Children\'s Hospital',
                'hospital_name_hi' => 'रेनबो चिल्ड्रन्स अस्पताल',
                'address' => 'Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 2',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4200,
                'longitude' => 78.4420,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'MRCP (UK)', 'FRCPCH'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-9099',
                'about_en' => 'Dr. Ramesh Kancharla is the Chairman and Managing Director of Rainbow Children\'s Hospitals, pioneer of dedicated pediatric multi-specialty care in India.',
                'about_hi' => 'डॉ. रमेश कंचारला रेनबो चिल्ड्रन्स हॉस्पिटल्स के अध्यक्ष और प्रबंध निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '040-44888888',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Gullapalli',
                'last_name' => 'N. Rao',
                'department_name_en' => 'Ophthalmology',
                'department_name_hi' => 'नेत्र रोग (ऑप्थल्मोलॉजी)',
                'hospital_name_en' => 'L V Prasad Eye Institute',
                'hospital_name_hi' => 'एल वी प्रसाद आई इंस्टीट्यूट',
                'address' => 'Kallam Anji Reddy Campus, Road No. 2, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 2',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4220,
                'longitude' => 78.4350,
                'experience_years' => 45,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (Ophthalmology)', 'FAMS', 'Padma Shri'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11243',
                'about_en' => 'Dr. Gullapalli N. Rao is the Founder and Distinguished Chair of L V Prasad Eye Institute, a world-renowned ophthalmologist and recipient of the Padma Shri.',
                'about_hi' => 'डॉ. गुल्लापल्ली एन. राव एल वी प्रसाद आई इंस्टीट्यूट के संस्थापक और विशिष्ट अध्यक्ष तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '040-30612345',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Manas',
                'last_name' => 'Panigrahi',
                'department_name_en' => 'Neurosurgery',
                'department_name_hi' => 'न्यूरोसर्जरी',
                'hospital_name_en' => 'KIMS Hospitals',
                'hospital_name_hi' => 'किम्स अस्पताल',
                'address' => 'Minister Road, Secunderabad, Hyderabad, Telangana - 500003',
                'address_line1' => 'Minister Road',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500003',
                'latitude' => 17.4350,
                'longitude' => 78.4850,
                'experience_years' => 32,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Neurosurgery)', 'FACS'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11244',
                'about_en' => 'Dr. Manas Panigrahi is a Senior Consultant Neurosurgeon at KIMS Hospitals Secunderabad, expert in epilepsy surgery and deep brain stimulation.',
                'about_hi' => 'डॉ. मानस पाणिग्रही किम्स हॉस्पिटल्स सिकंदराबाद में वरिष्ठ सलाहकार न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '040-44885000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Ch Mohana',
                'last_name' => 'Vamsy',
                'department_name_en' => 'Surgical Oncology',
                'department_name_hi' => 'सर्जिकल ऑन्कोलॉजी',
                'hospital_name_en' => 'Basavatarakam Indo American Cancer Hospital',
                'hospital_name_hi' => 'बसावतारकम इंडो अमेरिकन कैंसर अस्पताल',
                'address' => 'Road No. 10, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 10',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4120,
                'longitude' => 78.4410,
                'experience_years' => 36,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Surgical Oncology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11245',
                'about_en' => 'Dr. Ch Mohana Vamsy is a Senior Consultant Surgical Oncologist at Basavatarakam Cancer Hospital Hyderabad, expert in complex head & neck and breast cancers.',
                'about_hi' => 'डॉ. सी. एच. मोहन वामसी बसावतारकम कैंसर अस्पताल हैदराबाद में वरिष्ठ सलाहकार सर्जिकल ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '040-23551235',
                'is_verified' => true,
            ],
            [
                'first_name' => 'P. V. L. N.',
                'last_name' => 'Murthy',
                'department_name_en' => 'Urology',
                'department_name_hi' => 'मूत्र रोग (यूरोलॉजी)',
                'hospital_name_en' => 'NIMS',
                'hospital_name_hi' => 'निम्स',
                'address' => 'Punjagutta, Hyderabad, Telangana - 500082',
                'address_line1' => 'Punjagutta',
                'address_line2' => 'Near Punjagutta Flyover',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500082',
                'latitude' => 17.4220,
                'longitude' => 78.4520,
                'experience_years' => 38,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Urology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11246',
                'about_en' => 'Dr. P. V. L. N. Murthy is a Senior Professor and Head of Urology at NIMS Hyderabad, expert in renal transplant and endourology.',
                'about_hi' => 'डॉ. पी. वी. एल. एन. मूर्ति निम्स हैदराबाद में यूरोलॉजी के वरिष्ठ प्रोफेसर और प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '040-23489000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'G. N. V.',
                'last_name' => 'Prasad',
                'department_name_en' => 'Nephrology',
                'department_name_hi' => 'गुर्दा रोग (नेफ्रोलॉजी)',
                'hospital_name_en' => 'Osmania General Hospital',
                'hospital_name_hi' => 'उस्मानिया जनरल अस्पताल',
                'address' => 'Afzal Gunj, Hyderabad, Telangana - 500012',
                'address_line1' => 'Afzal Gunj',
                'address_line2' => 'Near Nayapul',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500012',
                'latitude' => 17.3710,
                'longitude' => 78.4750,
                'experience_years' => 30,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Nephrology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11247',
                'about_en' => 'Dr. G. N. V. Prasad is a Senior Consultant Nephrologist at Osmania General Hospital Hyderabad, expert in acute kidney injury and dialysis.',
                'about_hi' => 'डॉ. जी. एन. वी. प्रसाद उस्मानिया जनरल अस्पताल हैदराबाद में वरिष्ठ सलाहकार नेफ्रोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '040-24600121',
                'is_verified' => true,
            ],
            [
                'first_name' => 'B. N.',
                'last_name' => 'Rao',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'Yashoda Hospitals',
                'hospital_name_hi' => 'यशोदा अस्पताल',
                'address' => 'Raj Bhavan Road, Somajiguda, Hyderabad, Telangana - 500082',
                'address_line1' => 'Raj Bhavan Road',
                'address_line2' => 'Somajiguda',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500082',
                'latitude' => 17.4250,
                'longitude' => 78.4550,
                'experience_years' => 34,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FIAGES'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11248',
                'about_en' => 'Dr. B. N. Rao is a Senior Consultant General and Laparoscopic Surgeon at Yashoda Hospitals Somajiguda Hyderabad.',
                'about_hi' => 'डॉ. बी. एन. राव यशोदा हॉस्पिटल्स सोमाजीगुडा हैदराबाद में वरिष्ठ सलाहकार सामान्य और लेप्रोस्कोपिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '040-45674567',
                'is_verified' => true,
            ],
            [
                'first_name' => 'S. A.',
                'last_name' => 'Raju',
                'department_name_en' => 'Dermatology',
                'department_name_hi' => 'त्वचा रोग (डर्मेटोलॉजी)',
                'hospital_name_en' => 'Gandhi Hospital',
                'hospital_name_hi' => 'गांधी अस्पताल',
                'address' => 'Musheerabad, Padmarao Nagar, Secunderabad, Hyderabad, Telangana - 500025',
                'address_line1' => 'Musheerabad, Padmarao Nagar',
                'address_line2' => 'Secunderabad',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500025',
                'latitude' => 17.4240,
                'longitude' => 78.5020,
                'experience_years' => 28,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Dermatology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11249',
                'about_en' => 'Dr. S. A. Raju is a Senior Consultant Dermatologist at Gandhi Hospital Hyderabad.',
                'about_hi' => 'डॉ. एस. ए. राजू गांधी अस्पताल हैदराबाद में वरिष्ठ सलाहकार त्वचा विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '040-27702222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'P. V.',
                'last_name' => 'Rao',
                'department_name_en' => 'Endocrinology',
                'department_name_hi' => 'अंतःस्रावी विज्ञान (एंडोक्रिनोलॉजी)',
                'hospital_name_en' => 'CARE Hospitals',
                'hospital_name_hi' => 'केयर अस्पताल',
                'address' => 'Road No. 1, Banjara Hills, Hyderabad, Telangana - 500034',
                'address_line1' => 'Road No. 1',
                'address_line2' => 'Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500034',
                'latitude' => 17.4180,
                'longitude' => 78.4480,
                'experience_years' => 36,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Endocrinology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11250',
                'about_en' => 'Dr. P. V. Rao is a Senior Consultant Endocrinologist and Diabetologist at CARE Hospitals Banjara Hills Hyderabad.',
                'about_hi' => 'डॉ. पी. वी. राव केयर हॉस्पिटल्स बंजारा हिल्स हैदराबाद में वरिष्ठ सलाहकार एंडोक्रिनोलॉजिस्ट और डायबिटोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '040-61656565',
                'is_verified' => true,
            ],
            [
                'first_name' => 'K. S. S.',
                'last_name' => 'Sai',
                'department_name_en' => 'Pulmonology',
                'department_name_hi' => 'श्वसन रोग (पल्मोनोलॉजी)',
                'hospital_name_en' => 'Continental Hospitals',
                'hospital_name_hi' => 'कॉन्टिनेंटल अस्पताल',
                'address' => 'Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => 'Nanakramguda',
                'address_line2' => 'Gachibowli',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'latitude' => 17.4150,
                'longitude' => 78.3450,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Pulmonary Medicine)', 'DM (Pulmonology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11251',
                'about_en' => 'Dr. K. S. S. Sai is a Senior Consultant Pulmonologist at Continental Hospitals Gachibowli Hyderabad, expert in sleep medicine and interventional pulmonology.',
                'about_hi' => 'डॉ. के. एस. एस. साई कॉन्टिनेंटल हॉस्पिटल्स गचीबाउली हैदराबाद में वरिष्ठ सलाहकार पल्मोनोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '040-67000000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'M. V.',
                'last_name' => 'Rao',
                'department_name_en' => 'Rheumatology',
                'department_name_hi' => 'गठिया रोग (रुमेटोलॉजी)',
                'hospital_name_en' => 'AIG Hospitals',
                'hospital_name_hi' => 'एआईजी अस्पताल',
                'address' => 'Mindspace Road, Gachibowli, Hyderabad, Telangana - 500032',
                'address_line1' => 'Mindspace Road',
                'address_line2' => 'Gachibowli',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500032',
                'latitude' => 17.4420,
                'longitude' => 78.3650,
                'experience_years' => 30,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Rheumatology)'],
                'medical_council' => 'Telangana State Medical Council (TSMC)',
                'registration_number' => 'TSMC-11252',
                'about_en' => 'Dr. M. V. Rao is a Senior Consultant Rheumatologist at AIG Hospitals Gachibowli Hyderabad, expert in arthritis and autoimmune disorders.',
                'about_hi' => 'डॉ. एम. वी. राव एआईजी हॉस्पिटल्स गचीबाउली हैदराबाद में वरिष्ठ सलाहकार रुमेटोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '040-42444222',
                'is_verified' => true,
            ],
        ];
    }
}
