<?php

namespace App\Services;

class KolkataScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'kolkata') {
            return [];
        }

        return [
            [
                'name_en' => 'SSKM Hospital Blood Bank (IPGMER)',
                'name_hi' => 'एसएसकेएम अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'address_en' => '244, AJC Bose Road, Bhowanipore, Kolkata, West Bengal - 700020',
                'address_hi' => '244, एजेसी बोस रोड, भवानीपुर, कोलकाता, पश्चिम बंगाल - 700020',
                'country_code' => '+91',
                'phone' => '033-22235181',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-22235181',
                'email' => 'bloodbank@ipgmer.gov.in',
                'website' => 'https://ipgmer.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / SSKM Registry',
                'source_url' => 'https://ipgmer.gov.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Calcutta Medical College Blood Bank',
                'name_hi' => 'कलकत्ता मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700073',
                'address_en' => '88, College Street, Near Calcutta University, Kolkata, West Bengal - 700073',
                'address_hi' => '88, कॉलेज स्ट्रीट, कलकत्ता विश्वविद्यालय के पास, कोलकाता, पश्चिम बंगाल - 700073',
                'country_code' => '+91',
                'phone' => '033-22551621',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-22551621',
                'email' => 'bloodbank@mchkolkata.gov.in',
                'website' => 'https://mchkolkata.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Medical College Registry',
                'source_url' => 'https://mchkolkata.gov.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Central Blood Bank Kolkata',
                'name_hi' => 'सेंट्रल ब्लड बैंक कोलकाता',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700006',
                'address_en' => '20, Barashi Bagan Lane, Maniktala, Kolkata, West Bengal - 700006',
                'address_hi' => '20, बाराशी बगान लेन, मानिकतला, कोलकाता, पश्चिम बंगाल - 700006',
                'country_code' => '+91',
                'phone' => '033-23510619',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-23510619',
                'email' => 'centralbloodbank@wbhealth.gov.in',
                'website' => 'https://wbhealth.gov.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / WB Health Registry',
                'source_url' => 'https://wbhealth.gov.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Apollo Multispeciality Hospitals Blood Bank',
                'name_hi' => 'अपोलो मल्टीस्पेशलिटी अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700054',
                'address_en' => '58, Canal Circular Road, Kadapara, Phool Bagan, Kolkata, West Bengal - 700054',
                'address_hi' => '58, कैनाल सर्कुलर रोड, कडापारा, फूल बगान, कोलकाता, पश्चिम बंगाल - 700054',
                'country_code' => '+91',
                'phone' => '033-23202122',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-23202122',
                'email' => 'bloodbank_kol@apollohospitals.com',
                'website' => 'https://apollohospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Apollo Kolkata Registry',
                'source_url' => 'https://apollohospitals.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'AMRI Hospitals Blood Bank Dhakuria',
                'name_hi' => 'आमरी अस्पताल ब्लड बैंक ढाकुरिया',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700029',
                'address_en' => 'P-4 & 5, Gariahat Road, Block A, Dhakuria, Kolkata, West Bengal - 700029',
                'address_hi' => 'पी-4 और 5, गरियाहाट रोड, ब्लॉक ए, ढाकुरिया, कोलकाता, पश्चिम बंगाल - 700029',
                'country_code' => '+91',
                'phone' => '033-66800000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-66800000',
                'email' => 'bloodbank@amrihospitals.in',
                'website' => 'https://amrihospitals.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / AMRI Registry',
                'source_url' => 'https://amrihospitals.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Fortis Hospital Blood Bank Anandapur',
                'name_hi' => 'फोर्टिस अस्पताल ब्लड बैंक आनंदपुर',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700107',
                'address_en' => '730, Anandapur, E.M. Bypass Road, Kolkata, West Bengal - 700107',
                'address_hi' => '730, आनंदपुर, ई.एम. बाईपास रोड, कोलकाता, पश्चिम बंगाल - 700107',
                'country_code' => '+91',
                'phone' => '033-66284444',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-66284444',
                'email' => 'bloodbank.kolkata@fortishealthcare.com',
                'website' => 'https://fortishealthcare.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Fortis Anandapur Registry',
                'source_url' => 'https://fortishealthcare.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Medica Superspecialty Hospital Blood Bank',
                'name_hi' => 'मेडिका सुपरस्पेशलिटी अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700099',
                'address_en' => '127, Mukundapur, E.M. Bypass, Kolkata, West Bengal - 700099',
                'address_hi' => '127, मुकुंदपुर, ई.एम. बाईपास, कोलकाता, पश्चिम बंगाल - 700099',
                'country_code' => '+91',
                'phone' => '033-66520000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-66520000',
                'email' => 'bloodbank@medicahospitals.in',
                'website' => 'https://medicahospitals.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Medica Registry',
                'source_url' => 'https://medicahospitals.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Tata Medical Center Blood Bank Rajarhat',
                'name_hi' => 'टाटा मेडिकल सेंटर ब्लड बैंक राजारहाट',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700160',
                'address_en' => '14, MAR (E-W), New Town, Rajarhat, Kolkata, West Bengal - 700160',
                'address_hi' => '14, एमएआर (ई-डब्ल्यू), न्यू टाउन, राजारहाट, कोलकाता, पश्चिम बंगाल - 700160',
                'country_code' => '+91',
                'phone' => '033-66057000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-66057000',
                'email' => 'bloodbank@tmckolkata.com',
                'website' => 'https://tmckolkata.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Tata Medical Registry',
                'source_url' => 'https://tmckolkata.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Lions Blood Bank Kolkata',
                'name_hi' => 'लायंस ब्लड बैंक कोलकाता',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700016',
                'address_en' => '12, Loudon Street, Park Street Area, Kolkata, West Bengal - 700016',
                'address_hi' => '12, लाउडन स्ट्रीट, पार्क स्ट्रीट एरिया, कोलकाता, पश्चिम बंगाल - 700016',
                'country_code' => '+91',
                'phone' => '033-22872222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-22872222',
                'email' => 'contact@lionsbloodbankkolkata.org',
                'website' => 'https://lionsbloodbankkolkata.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Lions Kolkata Registry',
                'source_url' => 'https://lionsbloodbankkolkata.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Ruby General Hospital Blood Bank',
                'name_hi' => 'रूबी जनरल अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700107',
                'address_en' => 'Kasba Golpark, E.M. Bypass, Kolkata, West Bengal - 700107',
                'address_hi' => 'कस्बा गोलपार्क, ई.एम. बाईपास, कोलकाता, पश्चिम बंगाल - 700107',
                'country_code' => '+91',
                'phone' => '033-39871800',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-39871800',
                'email' => 'bloodbank@rubyhospital.com',
                'website' => 'https://rubyhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Ruby Registry',
                'source_url' => 'https://rubyhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Belle Vue Clinic Blood Bank',
                'name_hi' => 'बेले व्यू क्लिनिक ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'address_en' => '9, Dr. U. N. Brahmachari Street, Elgin, Kolkata, West Bengal - 700017',
                'address_hi' => '9, डॉ. यू. एन. ब्रह्मचारी स्ट्रीट, एल्गिन, कोलकाता, पश्चिम बंगाल - 700017',
                'country_code' => '+91',
                'phone' => '033-22872321',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-22872321',
                'email' => 'bloodbank@bellevueclinic.com',
                'website' => 'https://bellevueclinic.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Belle Vue Registry',
                'source_url' => 'https://bellevueclinic.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Woodlands Hospital Blood Bank',
                'name_hi' => 'वुडलैंड्स अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'address_en' => '8/5, Alipore Road, Alipore, Kolkata, West Bengal - 700027',
                'address_hi' => '8/5, अलीपुर रोड, अलीपुर, कोलकाता, पश्चिम बंगाल - 700027',
                'country_code' => '+91',
                'phone' => '033-40237000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-40237000',
                'email' => 'bloodbank@woodlandshospital.in',
                'website' => 'https://woodlandshospital.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Woodlands Registry',
                'source_url' => 'https://woodlandshospital.in',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'BM Birla Heart Research Centre Blood Bank',
                'name_hi' => 'बीएम बिड़ला हार्ट रिसर्च सेंटर ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'address_en' => '1/1, National Library Avenue, Alipore, Kolkata, West Bengal - 700027',
                'address_hi' => '1/1, नेशनल लाइब्रेरी एवेन्यू, अलीपुर, कोलकाता, पश्चिम बंगाल - 700027',
                'country_code' => '+91',
                'phone' => '033-40884088',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-40884088',
                'email' => 'bloodbank@bmbirladoctors.org',
                'website' => 'https://bmbirladoctors.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / BM Birla Registry',
                'source_url' => 'https://bmbirladoctors.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Peerless Hospital Blood Bank',
                'name_hi' => 'पीयरलेस अस्पताल ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700094',
                'address_en' => '360, Panchasayar, Near Garia, Kolkata, West Bengal - 700094',
                'address_hi' => '360, पंचसायर, गरिया के पास, कोलकाता, पश्चिम बंगाल - 700094',
                'country_code' => '+91',
                'phone' => '033-40111222',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-40111222',
                'email' => 'bloodbank@peerlesshospital.com',
                'website' => 'https://peerlesshospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Peerless Registry',
                'source_url' => 'https://peerlesshospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Kothari Medical Centre Blood Bank',
                'name_hi' => 'कोठारी मेडिकल सेंटर ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'address_en' => '8/3, Alipore Road, Alipore, Kolkata, West Bengal - 700027',
                'address_hi' => '8/3, अलीपुर रोड, अलीपुर, कोलकाता, पश्चिम बंगाल - 700027',
                'country_code' => '+91',
                'phone' => '033-24567050',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-24567050',
                'email' => 'bloodbank@kotharimedical.com',
                'website' => 'https://kotharimedical.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Kothari Registry',
                'source_url' => 'https://kotharimedical.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'NRS Medical College Blood Bank',
                'name_hi' => 'एनआरएस मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700014',
                'address_en' => '138, AJC Bose Road, Sealdah, Kolkata, West Bengal - 700014',
                'address_hi' => '138, एजेसी बोस रोड, सियालदह, कोलकाता, पश्चिम बंगाल - 700014',
                'country_code' => '+91',
                'phone' => '033-22443213',
                'emergency_country_code' => '+91',
                'emergency_phone' => '033-22443213',
                'email' => 'bloodbank@nrsmc.edu.in',
                'website' => 'https://nrsmc.edu.in',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / NRS Registry',
                'source_url' => 'https://nrsmc.edu.in',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'kolkata') {
            return [];
        }

        return [
            [
                'name_en' => 'SSKM Hospital (IPGMER - Institute of Post Graduate Medical Education and Research)',
                'name_hi' => 'एसएसकेएम अस्पताल',
                'type' => 'Government Hospital',
                'address' => '244, AJC Bose Road, Bhowanipore, Kolkata, West Bengal - 700020',
                'address_line1' => '244, AJC Bose Road',
                'address_line2' => 'Bhowanipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'emergency_phone' => '033-22235181',
                'emergency_country_code' => '+91',
                'latitude' => 22.5390,
                'longitude' => 88.3430,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'Swasthya Sathi', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Calcutta Medical College and Hospital',
                'name_hi' => 'कलकत्ता मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Government Hospital',
                'address' => '88, College Street, Near Calcutta University, Kolkata, West Bengal - 700073',
                'address_line1' => '88, College Street',
                'address_line2' => 'Near Calcutta University',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700073',
                'emergency_phone' => '033-22551621',
                'emergency_country_code' => '+91',
                'latitude' => 22.5740,
                'longitude' => 88.3630,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS'],
            ],
            [
                'name_en' => 'Apollo Multispeciality Hospitals, Kolkata',
                'name_hi' => 'अपोलो मल्टीस्पेशलिटी अस्पताल, कोलकाता',
                'type' => 'Private Hospital',
                'address' => '58, Canal Circular Road, Kadapara, Phool Bagan, Kolkata, West Bengal - 700054',
                'address_line1' => '58, Canal Circular Road, Kadapara',
                'address_line2' => 'Phool Bagan',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700054',
                'emergency_phone' => '033-23202122',
                'emergency_country_code' => '+91',
                'latitude' => 22.5750,
                'longitude' => 88.4020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'HDFC ERGO TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'AMRI Hospitals, Dhakuria',
                'name_hi' => 'आमरी अस्पताल, ढाकुरिया',
                'type' => 'Private Hospital',
                'address' => 'P-4 & 5, Gariahat Road, Block A, Dhakuria, Kolkata, West Bengal - 700029',
                'address_line1' => 'P-4 & 5, Gariahat Road, Block A',
                'address_line2' => 'Dhakuria',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700029',
                'emergency_phone' => '033-66800000',
                'emergency_country_code' => '+91',
                'latitude' => 22.5120,
                'longitude' => 88.3650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Fortis Hospital, Anandapur',
                'name_hi' => 'फोर्टिस अस्पताल, आनंदपुर',
                'type' => 'Private Hospital',
                'address' => '730, Anandapur, E.M. Bypass Road, Kolkata, West Bengal - 700107',
                'address_line1' => '730, Anandapur',
                'address_line2' => 'E.M. Bypass Road',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700107',
                'emergency_phone' => '033-66284444',
                'emergency_country_code' => '+91',
                'latitude' => 22.5150,
                'longitude' => 88.4050,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA', 'Max Bupa TPA'],
            ],
            [
                'name_en' => 'Medica Superspecialty Hospital',
                'name_hi' => 'मेडिका सुपरस्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => '127, Mukundapur, E.M. Bypass, Kolkata, West Bengal - 700099',
                'address_line1' => '127, Mukundapur',
                'address_line2' => 'E.M. Bypass',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700099',
                'emergency_phone' => '033-66520000',
                'emergency_country_code' => '+91',
                'latitude' => 22.4920,
                'longitude' => 88.4010,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Tata Medical Center, Rajarhat',
                'name_hi' => 'टाटा मेडिकल सेंटर, राजारहाट',
                'type' => 'Private Hospital',
                'address' => '14, MAR (E-W), New Town, Rajarhat, Kolkata, West Bengal - 700160',
                'address_line1' => '14, MAR (E-W), New Town',
                'address_line2' => 'Rajarhat',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700160',
                'emergency_phone' => '033-66057000',
                'emergency_country_code' => '+91',
                'latitude' => 22.5800,
                'longitude' => 88.4800,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Ruby General Hospital',
                'name_hi' => 'रूबी जनरल अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Kasba Golpark, E.M. Bypass, Kolkata, West Bengal - 700107',
                'address_line1' => 'Kasba Golpark',
                'address_line2' => 'E.M. Bypass',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700107',
                'emergency_phone' => '033-39871800',
                'emergency_country_code' => '+91',
                'latitude' => 22.5140,
                'longitude' => 88.4020,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Peerless Hospital',
                'name_hi' => 'पीयरलेस अस्पताल',
                'type' => 'Private Hospital',
                'address' => '360, Panchasayar, Near Garia, Kolkata, West Bengal - 700094',
                'address_line1' => '360, Panchasayar',
                'address_line2' => 'Near Garia',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700094',
                'emergency_phone' => '033-40111222',
                'emergency_country_code' => '+91',
                'latitude' => 22.4750,
                'longitude' => 88.3950,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'BM Birla Heart Research Centre',
                'name_hi' => 'बीएम बिड़ला हार्ट रिसर्च सेंटर',
                'type' => 'Private Hospital',
                'address' => '1/1, National Library Avenue, Alipore, Kolkata, West Bengal - 700027',
                'address_line1' => '1/1, National Library Avenue',
                'address_line2' => 'Alipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'emergency_phone' => '033-40884088',
                'emergency_country_code' => '+91',
                'latitude' => 22.5320,
                'longitude' => 88.3320,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Woodlands Multispeciality Hospital',
                'name_hi' => 'वुडलैंड्स मल्टीस्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => '8/5, Alipore Road, Alipore, Kolkata, West Bengal - 700027',
                'address_line1' => '8/5, Alipore Road',
                'address_line2' => 'Alipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'emergency_phone' => '033-40237000',
                'emergency_country_code' => '+91',
                'latitude' => 22.5310,
                'longitude' => 88.3340,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Belle Vue Clinic',
                'name_hi' => 'बेले व्यू क्लिनिक',
                'type' => 'Private Hospital',
                'address' => '9, Dr. U. N. Brahmachari Street, Elgin, Kolkata, West Bengal - 700017',
                'address_line1' => '9, Dr. U. N. Brahmachari Street',
                'address_line2' => 'Elgin',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'emergency_phone' => '033-22872321',
                'emergency_country_code' => '+91',
                'latitude' => 22.5420,
                'longitude' => 88.3550,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Care Health TPA'],
            ],
            [
                'name_en' => 'NRS Medical College and Hospital (Nil Ratan Sircar)',
                'name_hi' => 'एनआरएस मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Government Hospital',
                'address' => '138, AJC Bose Road, Sealdah, Kolkata, West Bengal - 700014',
                'address_line1' => '138, AJC Bose Road',
                'address_line2' => 'Sealdah',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700014',
                'emergency_phone' => '033-22443213',
                'emergency_country_code' => '+91',
                'latitude' => 22.5620,
                'longitude' => 88.3710,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS'],
            ],
            [
                'name_en' => 'R. G. Kar Medical College and Hospital',
                'name_hi' => 'आर. जी. कर मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Government Hospital',
                'address' => '1, Khudiram Bose Sarani, Shyambazar, Kolkata, West Bengal - 700004',
                'address_line1' => '1, Khudiram Bose Sarani',
                'address_line2' => 'Shyambazar',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700004',
                'emergency_phone' => '033-25557676',
                'emergency_country_code' => '+91',
                'latitude' => 22.5940,
                'longitude' => 88.3780,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS'],
            ],
            [
                'name_en' => 'Kothari Medical Centre',
                'name_hi' => 'कोठारी मेडिकल सेंटर',
                'type' => 'Private Hospital',
                'address' => '8/3, Alipore Road, Alipore, Kolkata, West Bengal - 700027',
                'address_line1' => '8/3, Alipore Road',
                'address_line2' => 'Alipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700027',
                'emergency_phone' => '033-24567050',
                'emergency_country_code' => '+91',
                'latitude' => 22.5320,
                'longitude' => 88.3340,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Fortis Medical Centre',
                'name_hi' => 'फोर्टिस मेडिकल सेंटर',
                'type' => 'Private Hospital',
                'address' => '2/7, Sarat Bose Road, Minto Park, Kolkata, West Bengal - 700020',
                'address_line1' => '2/7, Sarat Bose Road',
                'address_line2' => 'Minto Park',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'emergency_phone' => '033-24754320',
                'emergency_country_code' => '+91',
                'latitude' => 22.5400,
                'longitude' => 88.3560,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'BP Poddar Hospital & Medical Research Ltd',
                'name_hi' => 'बीपी पोद्दार अस्पताल',
                'type' => 'Private Hospital',
                'address' => '1/1, Humayun Kabir Sarani, Block G, New Alipore, Kolkata, West Bengal - 700053',
                'address_line1' => '1/1, Humayun Kabir Sarani',
                'address_line2' => 'Block G, New Alipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700053',
                'emergency_phone' => '033-24458901',
                'emergency_country_code' => '+91',
                'latitude' => 22.5180,
                'longitude' => 88.3390,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Shambhunath Pandit Hospital',
                'name_hi' => 'शंभूनाथ पंडित अस्पताल',
                'type' => 'Government Hospital',
                'address' => '11, Elgin Road, Elgin, Kolkata, West Bengal - 700020',
                'address_line1' => '11, Elgin Road',
                'address_line2' => 'Elgin',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'emergency_phone' => '033-22236245',
                'emergency_country_code' => '+91',
                'latitude' => 22.5400,
                'longitude' => 88.3450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS'],
            ],
            [
                'name_en' => 'Calcutta National Medical College & Hospital',
                'name_hi' => 'कलकत्ता नेशनल मेडिकल कॉलेज एवं अस्पताल',
                'type' => 'Government Hospital',
                'address' => '32, Gorachand Road, Beniapukur, Kolkata, West Bengal - 700014',
                'address_line1' => '32, Gorachand Road',
                'address_line2' => 'Beniapukur',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700014',
                'emergency_phone' => '033-22844834',
                'emergency_country_code' => '+91',
                'latitude' => 22.5450,
                'longitude' => 88.3680,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'Swasthya Sathi', 'CGHS'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'kolkata') {
            return [];
        }

        return [
            [
                'first_name' => 'Kunal',
                'last_name' => 'Sarkar',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Medica Superspecialty Hospital',
                'hospital_name_hi' => 'मेडिका सुपरस्पेशलिटी अस्पताल',
                'address' => 'Mukundapur, E.M. Bypass, Kolkata, West Bengal - 700099',
                'address_line1' => '127, Mukundapur',
                'address_line2' => 'E.M. Bypass',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700099',
                'latitude' => 22.4920,
                'longitude' => 88.4010,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'FRCS (Edin)', 'FRCS (Glasgow)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-1011',
                'about_en' => 'Dr. Kunal Sarkar is the Senior Vice Chairman and Chief Cardiac Surgeon at Medica Superspecialty Hospital, globally renowned for beating heart coronary bypass surgery.',
                'about_hi' => 'डॉ. कुणाल सरकार मेडिका सुपरस्पेशलिटी अस्पताल में वरिष्ठ उपाध्यक्ष और मुख्य कार्डियक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '033-66520000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sukumar',
                'last_name' => 'Mukherjee',
                'department_name_en' => 'General Physician',
                'department_name_hi' => 'सामान्य चिकित्सक (जनरल फिजिशियन)',
                'hospital_name_en' => 'Nightangles Clinic / CMRI',
                'hospital_name_hi' => 'नाइटेगल्स क्लिनिक',
                'address' => 'Shakespeare Sarani, Kolkata, West Bengal - 700017',
                'address_line1' => 'Shakespeare Sarani',
                'address_line2' => 'Near Camac Street',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'latitude' => 22.5450,
                'longitude' => 88.3520,
                'experience_years' => 55,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRCP (London)', 'FRCP (Edin)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-2022',
                'about_en' => 'Dr. Sukumar Mukherjee is a legendary Senior Consultant Physician in Kolkata, former professor of medicine, and recipient of numerous state and national accolades.',
                'about_hi' => 'डॉ. सुकुमार मुखर्जी कोलकाता में एक महान वरिष्ठ सलाहकार चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '033-22827777',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Mammen',
                'last_name' => 'Chandy',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'Tata Medical Center',
                'hospital_name_hi' => 'टाटा मेडिकल सेंटर',
                'address' => 'New Town, Rajarhat, Kolkata, West Bengal - 700160',
                'address_line1' => '14, MAR (E-W), New Town',
                'address_line2' => 'Rajarhat',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700160',
                'latitude' => 22.5800,
                'longitude' => 88.4800,
                'experience_years' => 45,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRACP', 'FAMS', 'Padma Shri'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-3033',
                'about_en' => 'Dr. Mammen Chandy is the former Director of Tata Medical Center Kolkata and a pioneer in bone marrow transplantation and hematology in India, recipient of the Padma Shri.',
                'about_hi' => 'डॉ. मम्मेन चांडी टाटा मेडिकल सेंटर कोलकाता के पूर्व निदेशक और भारत में अस्थि मज्जा प्रत्यारोपण के प्रणेता तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '033-66057000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Apurba',
                'last_name' => 'Ghosh',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Institute of Child Health (ICH)',
                'hospital_name_hi' => 'इंस्टीट्यूट ऑफ चाइल्ड हेल्थ (आईसीएच)',
                'address' => '11, Dr. Biresh Guha Street, Park Circus, Kolkata, West Bengal - 700017',
                'address_line1' => '11, Dr. Biresh Guha Street',
                'address_line2' => 'Park Circus',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'latitude' => 22.5380,
                'longitude' => 88.3650,
                'experience_years' => 40,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'DCH', 'FRCP', 'FIAP'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-4044',
                'about_en' => 'Dr. Apurba Ghosh is the Director of Institute of Child Health Kolkata and an eminent Senior Pediatrician specializing in pediatric infectious diseases and immunology.',
                'about_hi' => 'डॉ. अपूर्व घोष इंस्टीट्यूट ऑफ चाइल्ड हेल्थ कोलकाता के निदेशक और एक प्रख्यात वरिष्ठ बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '033-22895369',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Rabin',
                'last_name' => 'Chakraborty',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Medica Superspecialty Hospital',
                'hospital_name_hi' => 'मेडिका सुपरस्पेशलिटी अस्पताल',
                'address' => 'Mukundapur, E.M. Bypass, Kolkata, West Bengal - 700099',
                'address_line1' => '127, Mukundapur',
                'address_line2' => 'E.M. Bypass',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700099',
                'latitude' => 22.4920,
                'longitude' => 88.4010,
                'experience_years' => 36,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'FRCP', 'FACC'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-5055',
                'about_en' => 'Dr. Rabin Chakraborty is a Senior Consultant Interventional Cardiologist and Electrophysiologist at Medica Superspecialty Hospital.',
                'about_hi' => 'डॉ. रबिन चक्रवर्ती मेडिका सुपरस्पेशलिटी अस्पताल में वरिष्ठ सलाहकार इंटरवेंशनल कार्डियोलॉजिस्ट और इलेक्ट्रोफिजियोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '033-66520000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Suresh',
                'last_name' => 'Rao',
                'department_name_en' => 'ENT (Otolaryngology)',
                'department_name_hi' => 'कान, नाक और गला रोग (ईएनटी)',
                'hospital_name_en' => 'AMRI Hospitals',
                'hospital_name_hi' => 'आमरी अस्पताल',
                'address' => 'Dhakuria, Kolkata, West Bengal - 700029',
                'address_line1' => 'P-4 & 5, Gariahat Road',
                'address_line2' => 'Dhakuria',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700029',
                'latitude' => 22.5120,
                'longitude' => 88.3650,
                'experience_years' => 32,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (ENT)', 'FRCS'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-6066',
                'about_en' => 'Dr. Suresh Rao is a highly experienced ENT and Head & Neck Surgeon at AMRI Hospitals Dhakuria.',
                'about_hi' => 'डॉ. सुरेश राव आमरी अस्पताल ढाकुरिया में एक अत्यधिक अनुभवी ईएनटी और हेड एंड नेक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '033-66800000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Baidyanath',
                'last_name' => 'Chakravarty',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Institute of Reproductive Medicine (IRM)',
                'hospital_name_hi' => 'इंस्टीट्यूट ऑफ रिप्रोडक्टिव मेडिसिन (आईआरएम)',
                'address' => 'HB-36/A/3, Sector III, Salt Lake, Kolkata, West Bengal - 700106',
                'address_line1' => 'HB-36/A/3, Sector III',
                'address_line2' => 'Salt Lake',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700106',
                'latitude' => 22.5700,
                'longitude' => 88.4100,
                'experience_years' => 50,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'FRCOG', 'DSc'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-7077',
                'about_en' => 'Dr. Baidyanath Chakravarty was the legendary Founder of IRM Kolkata and a pioneer of IVF and reproductive endocrinology in India.',
                'about_hi' => 'डॉ. बैद्यनाथ चक्रवर्ती आईआरएम कोलकाता के संस्थापक और भारत में आईवीएफ तथा प्रजनन एंडोक्रिनोलॉजी के प्रणेता थे।',
                'gender' => 'Male',
                'phone' => '033-23345555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Bikas',
                'last_name' => 'Ghosh',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Peerless Hospital',
                'hospital_name_hi' => 'पीयरलेस अस्पताल',
                'address' => '360, Panchasayar, Kolkata, West Bengal - 700094',
                'address_line1' => '360, Panchasayar',
                'address_line2' => 'Near Garia',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700094',
                'latitude' => 22.4750,
                'longitude' => 88.3950,
                'experience_years' => 35,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'FRCS'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-8088',
                'about_en' => 'Dr. Bikas Ghosh is a Senior Consultant Orthopedic and Joint Replacement Surgeon at Peerless Hospital Kolkata.',
                'about_hi' => 'डॉ. बिकास घोष पीयरलेस अस्पताल कोलकाता में वरिष्ठ सलाहकार आर्थोपेडिक और संयुक्त प्रत्यारोपण सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '033-40111222',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Mahesh',
                'last_name' => 'Goenka',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'Apollo Multispeciality Hospitals',
                'hospital_name_hi' => 'अपोलो मल्टीस्पेशलिटी अस्पताल',
                'address' => '58, Canal Circular Road, Kolkata, West Bengal - 700054',
                'address_line1' => '58, Canal Circular Road',
                'address_line2' => 'Kadapara, Phool Bagan',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700054',
                'latitude' => 22.5750,
                'longitude' => 88.4020,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)', 'FACP', 'FACG'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-9099',
                'about_en' => 'Dr. Mahesh Goenka is Director of Institute of Gastrosciences at Apollo Multispeciality Hospitals Kolkata, world-renowned for advanced therapeutic endoscopy.',
                'about_hi' => 'डॉ. महेश गोयनका अपोलो मल्टीस्पेशलिटी अस्पताल कोलकाता में गैस्ट्रोसाइंसेज संस्थान के निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '033-23202122',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Abhijit',
                'last_name' => 'Chowdhury',
                'department_name_en' => 'Hepatology',
                'department_name_hi' => 'यकृत रोग (हेपेटोलॉजी)',
                'hospital_name_en' => 'IPGMER & SSKM Hospital',
                'hospital_name_hi' => 'एसएसकेएम अस्पताल',
                'address' => '244, AJC Bose Road, Bhowanipore, Kolkata, West Bengal - 700020',
                'address_line1' => '244, AJC Bose Road',
                'address_line2' => 'Bhowanipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'latitude' => 22.5390,
                'longitude' => 88.3430,
                'experience_years' => 32,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (General Medicine)', 'DM (Gastroenterology / Hepatology)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11432',
                'about_en' => 'Dr. Abhijit Chowdhury is a Senior Professor and Head of Hepatology at IPGMER and SSKM Hospital Kolkata, highly acclaimed for public health initiatives and liver disease management.',
                'about_hi' => 'डॉ. अभिजीत चौधरी आईपीजीएमईआर और एसएसकेएम अस्पताल कोलकाता में हेपेटोलॉजी के वरिष्ठ प्रोफेसर और प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '033-22235181',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Subrata',
                'last_name' => 'Maitra',
                'department_name_en' => 'General Medicine',
                'department_name_hi' => 'सामान्य चिकित्सा (जनरल मेडिसिन)',
                'hospital_name_en' => 'Belle Vue Clinic',
                'hospital_name_hi' => 'बेले व्यू क्लिनिक',
                'address' => '9, Dr. U. N. Brahmachari Street, Elgin, Kolkata, West Bengal - 700017',
                'address_line1' => '9, Dr. U. N. Brahmachari Street',
                'address_line2' => 'Elgin',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'latitude' => 22.5420,
                'longitude' => 88.3550,
                'experience_years' => 40,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'FRCP (London)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11433',
                'about_en' => 'Dr. Subrata Maitra is a legendary Senior Consultant Physician at Belle Vue Clinic Kolkata, widely expert in critical care and internal medicine.',
                'about_hi' => 'डॉ. सुब्रत मैत्र बेले व्यू क्लिनिक कोलकाता में एक प्रख्यात वरिष्ठ सलाहकार चिकित्सक हैं।',
                'gender' => 'Male',
                'phone' => '033-22872321',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Plaban',
                'last_name' => 'Mukherjee',
                'department_name_en' => 'Cardiothoracic Surgery',
                'department_name_hi' => 'कार्डियोथोरेसिक सर्जरी',
                'hospital_name_en' => 'Medical College Kolkata',
                'hospital_name_hi' => 'कलकत्ता मेडिकल कॉलेज',
                'address' => '88, College Street, Kolkata, West Bengal - 700073',
                'address_line1' => '88, College Street',
                'address_line2' => 'Near Calcutta University',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700073',
                'latitude' => 22.5740,
                'longitude' => 88.3630,
                'experience_years' => 30,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Cardiothoracic Surgery)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11434',
                'about_en' => 'Dr. Plaban Mukherjee is a renowned Professor and Head of Cardiothoracic Surgery at Calcutta Medical College, pioneer in vascular and pediatric cardiac surgeries.',
                'about_hi' => 'डॉ. प्लावन मुखर्जी कलकत्ता मेडिकल कॉलेज में कार्डियोथोरेसिक सर्जरी के प्रसिद्ध प्रोफेसर और प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '033-22551621',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sandip',
                'last_name' => 'Chatterji',
                'department_name_en' => 'Neurosurgery',
                'department_name_hi' => 'न्यूरोसर्जरी',
                'hospital_name_en' => 'Park Clinic',
                'hospital_name_hi' => 'पार्क क्लिनिक',
                'address' => '4, Gorky Terrace, Minto Park, Kolkata, West Bengal - 700017',
                'address_line1' => '4, Gorky Terrace',
                'address_line2' => 'Minto Park',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700017',
                'latitude' => 22.5410,
                'longitude' => 88.3570,
                'experience_years' => 34,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'FRCS (Edin)', 'FRCS (SN)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11435',
                'about_en' => 'Dr. Sandip Chatterji is a Senior Consultant Pediatric Neurosurgeon at Park Clinic Kolkata, nationally respected for childhood brain tumor and hydrocephalus surgery.',
                'about_hi' => 'डॉ. संदीप चटर्जी पार्क क्लिनिक कोलकाता में वरिष्ठ सलाहकार बाल रोग न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '033-22801986',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Ashis',
                'last_name' => 'Mukherjee',
                'department_name_en' => 'Radiation Oncology',
                'department_name_hi' => 'विकिरण कैंसर रोग (रेडिएशन ऑन्कोलॉजी)',
                'hospital_name_en' => 'Netaji Subhas Chandra Bose Cancer Hospital',
                'hospital_name_hi' => 'नेताजी सुभाष चंद्र बोस कैंसर अस्पताल',
                'address' => '3081, Nayabad, New Town, Kolkata, West Bengal - 700099',
                'address_line1' => '3081, Nayabad',
                'address_line2' => 'Near Mukundapur',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700099',
                'latitude' => 22.4850,
                'longitude' => 88.4060,
                'experience_years' => 38,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Radiotherapy)', 'DMRT'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11436',
                'about_en' => 'Dr. Ashis Mukherjee is the Medical Director and Senior Consultant Oncologist at Netaji Subhas Chandra Bose Cancer Hospital, specialized in advanced linear accelerator therapy.',
                'about_hi' => 'डॉ. आशीष मुखर्जी नेताजी सुभाष चंद्र बोस कैंसर अस्पताल में चिकित्सा निदेशक और वरिष्ठ सलाहकार ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '033-24186666',
                'is_verified' => true,
            ],
            [
                'first_name' => 'G. K.',
                'last_name' => 'Dhali',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'IPGMER & SSKM Hospital',
                'hospital_name_hi' => 'एसएसकेएम अस्पताल',
                'address' => '244, AJC Bose Road, Bhowanipore, Kolkata, West Bengal - 700020',
                'address_line1' => '244, AJC Bose Road',
                'address_line2' => 'Bhowanipore',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700020',
                'latitude' => 22.5390,
                'longitude' => 88.3430,
                'experience_years' => 32,
                'consultation_fee' => 500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)'],
                'medical_council' => 'West Bengal Medical Council (WBMC)',
                'registration_number' => 'WBMC-11437',
                'about_en' => 'Dr. G. K. Dhali is a renowned Professor and Senior Gastroenterologist at SSKM Hospital Kolkata, expert in inflammatory bowel disease and pancreatic disorders.',
                'about_hi' => 'डॉ. जी. के. ढाली एसएसकेएम अस्पताल कोलकाता में प्रसिद्ध प्रोफेसर और वरिष्ठ गैस्ट्रोएंटरोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '033-22235181',
                'is_verified' => true,
            ],
        ];
    }
}
