<?php

namespace App\Services;

class PuneScraperService extends BaseScraperService
{
    protected static function getFallbackBloodBanks(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'pune') {
            return [];
        }

        return [
            [
                'name_en' => 'Sassoon General Hospital Blood Bank',
                'name_hi' => 'ससून जनरल अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'address_en' => 'Jay Prakash Narayan Road, Near Pune Railway Station, Pune, Maharashtra - 411001',
                'address_hi' => 'जय प्रकाश नारायण रोड, पुणे रेलवे स्टेशन के पास, पुणे, महाराष्ट्र - 411001',
                'country_code' => '+91',
                'phone' => '020-26128000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-26128000',
                'email' => 'sassoonbloodbank@maharashtra.gov.in',
                'website' => 'https://bjmcpune.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => true,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Sassoon Registry',
                'source_url' => 'https://bjmcpune.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Ruby Hall Clinic Blood Bank',
                'name_hi' => 'रूबी हॉल क्लिनिक ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'address_en' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_hi' => '40, ससून रोड, पुणे, महाराष्ट्र - 411001',
                'country_code' => '+91',
                'phone' => '020-66455150',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66455150',
                'email' => 'bloodbank@rubyhall.com',
                'website' => 'https://rubyhall.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Ruby Hall Registry',
                'source_url' => 'https://rubyhall.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Jehangir Hospital Blood Bank',
                'name_hi' => 'जहांगीर अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'address_en' => '32, Sassoon Road, Pune, Maharashtra - 411001',
                'address_hi' => '32, ससून रोड, पुणे, महाराष्ट्र - 411001',
                'country_code' => '+91',
                'phone' => '020-66819999',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66819999',
                'email' => 'bloodbank@jehangirhospital.com',
                'website' => 'https://jehangirhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Jehangir Registry',
                'source_url' => 'https://jehangirhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Deenanath Mangeshkar Hospital Blood Bank',
                'name_hi' => 'दीनानाथ मंगेशकर अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'address_en' => 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra - 411038',
                'address_hi' => 'म्हात्रे ब्रिज के पास, एरंडवाने, पुणे, महाराष्ट्र - 411038',
                'country_code' => '+91',
                'phone' => '020-40151000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-40151000',
                'email' => 'bloodbank@dmhospital.org',
                'website' => 'https://dmhospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / DMH Registry',
                'source_url' => 'https://dmhospital.org',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Sahyadri Super Speciality Hospital Blood Bank',
                'name_hi' => 'सह्याद्रि सुपर स्पेशलिटी अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'address_en' => 'Plot No. 30-C, Erandwane, Deccan Gymkhana, Pune, Maharashtra - 411004',
                'address_hi' => 'प्लॉट नं. 30-सी, एरंडवाने, डेक्कन जिमखाना, पुणे, महाराष्ट्र - 411004',
                'country_code' => '+91',
                'phone' => '020-67213000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-67213000',
                'email' => 'bloodbank@sahyadrihospitals.com',
                'website' => 'https://sahyadrihospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Sahyadri Registry',
                'source_url' => 'https://sahyadrihospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Aditya Birla Memorial Hospital Blood Bank',
                'name_hi' => 'आदित्य बिड़ला मेमोरियल अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411033',
                'address_en' => 'Aditya Birla Hospital Marg, Thergaon, Chinchwad, Pune, Maharashtra - 411033',
                'address_hi' => 'आदित्य बिड़ला अस्पताल मार्ग, थेरगांव, चिंचवड़, पुणे, महाराष्ट्र - 411033',
                'country_code' => '+91',
                'phone' => '020-30717500',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-30717500',
                'email' => 'bloodbank@adityabirlahospital.com',
                'website' => 'https://adityabirlahospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Aditya Birla Registry',
                'source_url' => 'https://adityabirlahospital.com',
                'source_confidence_score' => 99,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'KEM Hospital Pune Blood Bank',
                'name_hi' => 'केईएम अस्पताल पुणे ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411011',
                'address_en' => '489, Sardar Moodliar Road, Rasta Peth, Pune, Maharashtra - 411011',
                'address_hi' => '489, सरदार मुदलियार रोड, रास्ता पेठ, पुणे, महाराष्ट्र - 411011',
                'country_code' => '+91',
                'phone' => '020-66037300',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66037300',
                'email' => 'bloodbank@kempune.org',
                'website' => 'https://kempune.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / KEM Pune Registry',
                'source_url' => 'https://kempune.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Noble Hospital Blood Bank',
                'name_hi' => 'नोबल अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411013',
                'address_en' => '153, Magarpatta City Road, Hadapsar, Pune, Maharashtra - 411013',
                'address_hi' => '153, मगरपट्टा सिटी रोड, हडपसर, पुणे, महाराष्ट्र - 411013',
                'country_code' => '+91',
                'phone' => '020-66285000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66285000',
                'email' => 'bloodbank@noblehospitalspune.com',
                'website' => 'https://noblehospitalspune.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Noble Registry',
                'source_url' => 'https://noblehospitalspune.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Jupiter Hospital Baner Blood Bank',
                'name_hi' => 'ज्यूपिटर अस्पताल बानेर ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411045',
                'address_en' => 'Baner - Pimple Nilakh Road, Baner, Pune, Maharashtra - 411045',
                'address_hi' => 'बानेर - पिम्पले निलख रोड, बानेर, पुणे, महाराष्ट्र - 411045',
                'country_code' => '+91',
                'phone' => '020-27992799',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-27992799',
                'email' => 'bloodbank.pune@jupiterhospital.com',
                'website' => 'https://jupiterhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Jupiter Pune Registry',
                'source_url' => 'https://jupiterhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Bharati Vidyapeeth Medical College Blood Bank',
                'name_hi' => 'भारती विद्यापीठ मेडिकल कॉलेज ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411043',
                'address_en' => 'Pune-Satara Road, Dhankawadi, Pune, Maharashtra - 411043',
                'address_hi' => 'पुणे-सतारा रोड, धनकवडी, पुणे, महाराष्ट्र - 411043',
                'country_code' => '+91',
                'phone' => '020-24363226',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-24363226',
                'email' => 'bvduimcbloodbank@bharatividyapeeth.edu',
                'website' => 'https://bvpmedpune.edu',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Bharati Vidyapeeth Registry',
                'source_url' => 'https://bvpmedpune.edu',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Inamdar Multispeciality Hospital Blood Bank',
                'name_hi' => 'इनामदार मल्टीस्पेशलिटी अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411040',
                'address_en' => 'Hospital Building, S. No. 15, Fatima Nagar, Wanowrie, Pune, Maharashtra - 411040',
                'address_hi' => 'हॉस्पिटल बिल्डिंग, एस. नं. 15, फातिमा नगर, वानवडी, पुणे, महाराष्ट्र - 411040',
                'country_code' => '+91',
                'phone' => '020-66858888',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66858888',
                'email' => 'bloodbank@inamdarhospital.com',
                'website' => 'https://inamdarhospital.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Inamdar Registry',
                'source_url' => 'https://inamdarhospital.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Manipal Hospital Kharadi Blood Bank',
                'name_hi' => 'मणिपाल अस्पताल खराडी ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411014',
                'address_en' => 'Survey No. 22/2A, Near Radisson Blu Hotel, Kharadi, Pune, Maharashtra - 411014',
                'address_hi' => 'सर्वे नंबर 22/2ए, रेडिसन ब्लू होटल के पास, खराडी, पुणे, महाराष्ट्र - 411014',
                'country_code' => '+91',
                'phone' => '020-61656666',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-61656666',
                'email' => 'bloodbank.kharadi@manipalhospitals.com',
                'website' => 'https://manipalhospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Manipal Kharadi Registry',
                'source_url' => 'https://manipalhospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Janakalyan Blood Bank Pune',
                'name_hi' => 'जनकल्याण ब्लड बैंक पुणे',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'address_en' => 'Janakalyan Bhawan, Near Swargate, Pune, Maharashtra - 411038',
                'address_hi' => 'जनकल्याण भवन, स्वारगेट के पास, पुणे, महाराष्ट्र - 411038',
                'country_code' => '+91',
                'phone' => '020-24449527',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-24449527',
                'email' => 'contact@janakalyanbloodbankpune.org',
                'website' => 'https://janakalyanbloodbankpune.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Janakalyan Registry',
                'source_url' => 'https://janakalyanbloodbankpune.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Poona Hospital & Research Centre Blood Bank',
                'name_hi' => 'पूना अस्पताल एवं अनुसंधान केंद्र ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411030',
                'address_en' => '27, Sadashiv Peth, Near Alka Talkies, Pune, Maharashtra - 411030',
                'address_hi' => '27, सदाशिव पेठ, अलका टॉकीज के पास, पुणे, महाराष्ट्र - 411030',
                'country_code' => '+91',
                'phone' => '020-66096000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-66096000',
                'email' => 'bloodbank@poonahospital.org',
                'website' => 'https://poonahospital.org',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Poona Hospital Registry',
                'source_url' => 'https://poonahospital.org',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
            [
                'name_en' => 'Surya Mother & Child Super Speciality Hospital Blood Bank',
                'name_hi' => 'सूर्या मदर एवं चाइल्ड सुपर स्पेशलिटी अस्पताल ब्लड बैंक',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'address_en' => 'Survey No. 8, Bhawani Peth, Near Kasba Peth, Pune, Maharashtra - 411005',
                'address_hi' => 'सर्वे नंबर 8, भवानी पेठ, कस्बा पेठ के पास, पुणे, महाराष्ट्र - 411005',
                'country_code' => '+91',
                'phone' => '020-67520000',
                'emergency_country_code' => '+91',
                'emergency_phone' => '020-67520000',
                'email' => 'bloodbank.pune@suryahospitals.com',
                'website' => 'https://suryahospitals.com',
                'is_verified' => true,
                'is_24_7' => true,
                'is_government' => false,
                'component_facility' => true,
                'apheresis_facility' => true,
                'available_blood_groups' => ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'],
                'source_name' => 'e-RaktKosh / Surya Pune Registry',
                'source_url' => 'https://suryahospitals.com',
                'source_confidence_score' => 98,
                'source_verification_status' => 'verified_active',
            ],
        ];
    }

    protected static function getFallbackHospitals(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'pune') {
            return [];
        }

        return [
            [
                'name_en' => 'Sassoon General Hospital',
                'name_hi' => 'ससून जनरल अस्पताल',
                'type' => 'Government Hospital',
                'address' => 'Jay Prakash Narayan Road, Near Pune Railway Station, Pune, Maharashtra - 411001',
                'address_line1' => 'Jay Prakash Narayan Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'emergency_phone' => '020-26128000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5275,
                'longitude' => 73.8740,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'MJPJAY', 'CGHS', 'ECHS'],
            ],
            [
                'name_en' => 'Ruby Hall Clinic',
                'name_hi' => 'रूबी हॉल क्लिनिक',
                'type' => 'Private Hospital',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'emergency_phone' => '020-66455150',
                'emergency_country_code' => '+91',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MJPJAY', 'CGHS', 'HDFC ERGO TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Jehangir Hospital',
                'name_hi' => 'जहांगीर अस्पताल',
                'type' => 'Private Hospital',
                'address' => '32, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '32, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'emergency_phone' => '020-66819999',
                'emergency_country_code' => '+91',
                'latitude' => 18.5290,
                'longitude' => 73.8750,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'ICICI Lombard TPA', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Deenanath Mangeshkar Hospital and Research Center',
                'name_hi' => 'दीनानाथ मंगेशकर अस्पताल एवं अनुसंधान केंद्र',
                'type' => 'Private Hospital',
                'address' => 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra - 411038',
                'address_line1' => 'Near Mhatre Bridge, Erandwane',
                'address_line2' => 'Opposite Mhatre Bridge',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'emergency_phone' => '020-40151000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5080,
                'longitude' => 73.8340,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MJPJAY', 'CGHS', 'Care Health TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'Sahyadri Super Speciality Hospital, Deccan Gymkhana',
                'name_hi' => 'सह्याद्रि सुपर स्पेशलिटी अस्पताल, डेक्कन जिमखाना',
                'type' => 'Private Hospital',
                'address' => 'Plot No. 30-C, Erandwane, Deccan Gymkhana, Pune, Maharashtra - 411004',
                'address_line1' => 'Plot No. 30-C, Erandwane',
                'address_line2' => 'Deccan Gymkhana',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'emergency_phone' => '020-67213000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5150,
                'longitude' => 73.8380,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'Aditya Birla Health TPA'],
            ],
            [
                'name_en' => 'Aditya Birla Memorial Hospital',
                'name_hi' => 'आदित्य बिड़ला मेमोरियल अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Aditya Birla Hospital Marg, Thergaon, Chinchwad, Pune, Maharashtra - 411033',
                'address_line1' => 'Aditya Birla Hospital Marg, Thergaon',
                'address_line2' => 'Chinchwad',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411033',
                'emergency_phone' => '020-30717500',
                'emergency_country_code' => '+91',
                'latitude' => 18.6210,
                'longitude' => 73.7650,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA', 'Star Health TPA'],
            ],
            [
                'name_en' => 'KEM Hospital Pune',
                'name_hi' => 'केईएम अस्पताल पुणे',
                'type' => 'Semi-Private Hospital',
                'address' => '489, Sardar Moodliar Road, Rasta Peth, Pune, Maharashtra - 411011',
                'address_line1' => '489, Sardar Moodliar Road',
                'address_line2' => 'Rasta Peth',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411011',
                'emergency_phone' => '020-66037300',
                'emergency_country_code' => '+91',
                'latitude' => 18.5200,
                'longitude' => 73.8680,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'MJPJAY', 'CGHS', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Noble Hospital',
                'name_hi' => 'नोबल अस्पताल',
                'type' => 'Private Hospital',
                'address' => '153, Magarpatta City Road, Hadapsar, Pune, Maharashtra - 411013',
                'address_line1' => '153, Magarpatta City Road',
                'address_line2' => 'Hadapsar',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411013',
                'emergency_phone' => '020-66285000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5080,
                'longitude' => 73.9290,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Jupiter Hospital, Baner',
                'name_hi' => 'ज्यूपिटर अस्पताल, बानेर',
                'type' => 'Private Hospital',
                'address' => 'Baner - Pimple Nilakh Road, Baner, Pune, Maharashtra - 411045',
                'address_line1' => 'Baner - Pimple Nilakh Road',
                'address_line2' => 'Baner',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411045',
                'emergency_phone' => '020-27992799',
                'emergency_country_code' => '+91',
                'latitude' => 18.5630,
                'longitude' => 73.7840,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'Max Bupa TPA'],
            ],
            [
                'name_en' => 'Bharati Vidyapeeth Medical College Hospital',
                'name_hi' => 'भारती विद्यापीठ मेडिकल कॉलेज अस्पताल',
                'type' => 'Semi-Private Hospital',
                'address' => 'Pune-Satara Road, Dhankawadi, Pune, Maharashtra - 411043',
                'address_line1' => 'Pune-Satara Road',
                'address_line2' => 'Dhankawadi',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411043',
                'emergency_phone' => '020-24363226',
                'emergency_country_code' => '+91',
                'latitude' => 18.4610,
                'longitude' => 73.8540,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat Yojana (PM-JAY)', 'MJPJAY', 'CGHS'],
            ],
            [
                'name_en' => 'Inamdar Multispeciality Hospital',
                'name_hi' => 'इनामदार मल्टीस्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Hospital Building, S. No. 15, Fatima Nagar, Wanowrie, Pune, Maharashtra - 411040',
                'address_line1' => 'Hospital Building, S. No. 15',
                'address_line2' => 'Fatima Nagar, Wanowrie',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411040',
                'emergency_phone' => '020-66858888',
                'emergency_country_code' => '+91',
                'latitude' => 18.5020,
                'longitude' => 73.9010,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'Manipal Hospital, Kharadi',
                'name_hi' => 'मणिपाल अस्पताल, खराडी',
                'type' => 'Private Hospital',
                'address' => 'Survey No. 22/2A, Near Radisson Blu Hotel, Kharadi, Pune, Maharashtra - 411014',
                'address_line1' => 'Survey No. 22/2A',
                'address_line2' => 'Near Radisson Blu Hotel, Kharadi',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411014',
                'emergency_phone' => '020-61656666',
                'emergency_country_code' => '+91',
                'latitude' => 18.5520,
                'longitude' => 73.9350,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Poona Hospital and Research Centre',
                'name_hi' => 'पूना अस्पताल एवं अनुसंधान केंद्र',
                'type' => 'Private Hospital',
                'address' => '27, Sadashiv Peth, Near Alka Talkies, Pune, Maharashtra - 411030',
                'address_line1' => '27, Sadashiv Peth',
                'address_line2' => 'Near Alka Talkies',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411030',
                'emergency_phone' => '020-66096000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5130,
                'longitude' => 73.8450,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA'],
            ],
            [
                'name_en' => 'Surya Mother and Child Super Speciality Hospital',
                'name_hi' => 'सूर्या मदर एवं चाइल्ड सुपर स्पेशलिटी अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Survey No. 8, Bhawani Peth, Near Kasba Peth, Pune, Maharashtra - 411005',
                'address_line1' => 'Survey No. 8, Bhawani Peth',
                'address_line2' => 'Near Kasba Peth',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'emergency_phone' => '020-67520000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5180,
                'longitude' => 73.8640,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Rao Nursing Home',
                'name_hi' => 'राव नर्सिंग होम',
                'type' => 'Private Hospital',
                'address' => 'Bibwewadi Main Road, Bibwewadi, Pune, Maharashtra - 411037',
                'address_line1' => 'Bibwewadi Main Road',
                'address_line2' => 'Bibwewadi',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411037',
                'emergency_phone' => '020-24214455',
                'emergency_country_code' => '+91',
                'latitude' => 18.4750,
                'longitude' => 73.8610,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Bajaj Allianz TPA'],
            ],
            [
                'name_en' => 'AIMS Hospital Pune (Aundh Institute of Medical Sciences)',
                'name_hi' => 'एम्स अस्पताल पुणे',
                'type' => 'Private Hospital',
                'address' => 'Near Aundh Gaon, Aundh, Pune, Maharashtra - 411007',
                'address_line1' => 'Near Aundh Gaon',
                'address_line2' => 'Aundh',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411007',
                'emergency_phone' => '020-25800000',
                'emergency_country_code' => '+91',
                'latitude' => 18.5610,
                'longitude' => 73.8050,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'HDFC ERGO TPA', 'ICICI Lombard TPA'],
            ],
            [
                'name_en' => 'Lokmanya Hospital, Nigdi',
                'name_hi' => 'लोकमान्य अस्पताल, निगडी',
                'type' => 'Private Hospital',
                'address' => 'Sector 24, Pradhikaran, Nigdi, Pune, Maharashtra - 411044',
                'address_line1' => 'Sector 24, Pradhikaran',
                'address_line2' => 'Nigdi',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411044',
                'emergency_phone' => '020-27657000',
                'emergency_country_code' => '+91',
                'latitude' => 18.6510,
                'longitude' => 73.7630,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Star Health TPA', 'Care Health TPA'],
            ],
            [
                'name_en' => 'Niramaya Hospital',
                'name_hi' => 'निरामय अस्पताल',
                'type' => 'Private Hospital',
                'address' => 'Chinchwad Station Road, Chinchwad, Pune, Maharashtra - 411019',
                'address_line1' => 'Chinchwad Station Road',
                'address_line2' => 'Chinchwad',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411019',
                'emergency_phone' => '020-27453333',
                'emergency_country_code' => '+91',
                'latitude' => 18.6250,
                'longitude' => 73.7880,
                'accepts_ayushman' => true,
                'accepts_janaadhaar' => false,
                'accepts_cghs' => true,
                'is_cashless' => true,
                'cashless_schemes_list' => ['Ayushman Bharat', 'CGHS', 'Max Bupa TPA'],
            ],
        ];
    }

    protected static function getFallbackDoctors(string $cityName): array
    {
        if (strtolower(trim($cityName)) !== 'pune') {
            return [];
        }

        return [
            [
                'first_name' => 'Purvez',
                'last_name' => 'Grant',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Ruby Hall Clinic',
                'hospital_name_hi' => 'रूबी हॉल क्लिनिक',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'experience_years' => 45,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (General Medicine)', 'FACC', 'FCSI'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-1245',
                'about_en' => 'Dr. Purvez Grant is the Managing Trustee and Chief Cardiologist at Ruby Hall Clinic Pune, globally renowned for his pioneering work in interventional cardiology.',
                'about_hi' => 'डॉ. परवेज ग्रांट रूबी हॉल क्लिनिक पुणे के प्रबंध न्यासी और मुख्य कार्डियोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'K. B.',
                'last_name' => 'Grant',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'Ruby Hall Clinic',
                'hospital_name_hi' => 'रूबी हॉल क्लिनिक',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'experience_years' => 50,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FRCS'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-1011',
                'about_en' => 'Dr. K. B. Grant was the legendary Founder of Ruby Hall Clinic and a pioneer in advanced oncological and surgical care in Pune.',
                'about_hi' => 'डॉ. के. बी. ग्रांट रूबी हॉल क्लिनिक के संस्थापक और पुणे में उन्नत ऑन्कोलॉजिकल देखभाल के प्रणेता थे।',
                'gender' => 'Male',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Dhananjay',
                'last_name' => 'Kelkar',
                'department_name_en' => 'Oncology',
                'department_name_hi' => 'कैंसर रोग (ऑन्कोलॉजी)',
                'hospital_name_en' => 'Deenanath Mangeshkar Hospital',
                'hospital_name_hi' => 'दीनानाथ मंगेशकर अस्पताल',
                'address' => 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra - 411038',
                'address_line1' => 'Near Mhatre Bridge, Erandwane',
                'address_line2' => 'Opposite Mhatre Bridge',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'latitude' => 18.5080,
                'longitude' => 73.8340,
                'experience_years' => 40,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'MCh (Surgical Oncology)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-2356',
                'about_en' => 'Dr. Dhananjay Kelkar is the Medical Director of Deenanath Mangeshkar Hospital and an eminent Surgical Oncologist.',
                'about_hi' => 'डॉ. धनंजय केलकर दीनानाथ मंगेशकर अस्पताल के चिकित्सा निदेशक और एक प्रख्यात सर्जिकल ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '020-40151000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Charudutt',
                'last_name' => 'Apte',
                'department_name_en' => 'Neurology',
                'department_name_hi' => 'तंत्रिका विज्ञान (न्यूरोलॉजी)',
                'hospital_name_en' => 'Sahyadri Super Speciality Hospital',
                'hospital_name_hi' => 'सह्याद्रि सुपर स्पेशलिटी अस्पताल',
                'address' => 'Plot No. 30-C, Erandwane, Deccan Gymkhana, Pune, Maharashtra - 411004',
                'address_line1' => 'Plot No. 30-C, Erandwane',
                'address_line2' => 'Deccan Gymkhana',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'latitude' => 18.5150,
                'longitude' => 73.8380,
                'experience_years' => 42,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Surgery)', 'MCh (Neurosurgery)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-3412',
                'about_en' => 'Dr. Charudutt Apte is the Chairman of Sahyadri Hospitals and a highly esteemed Neurosurgeon, recipient of numerous national awards.',
                'about_hi' => 'डॉ. चारुदत्त आप्टे सह्याद्रि अस्पताल समूह के अध्यक्ष और एक अत्यधिक सम्मानित न्यूरोसर्जन हैं।',
                'gender' => 'Male',
                'phone' => '020-67213000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sundeep',
                'last_name' => 'Salvi',
                'department_name_en' => 'Pulmonology',
                'department_name_hi' => 'श्वसन रोग (पल्मोनोलॉजी)',
                'hospital_name_en' => 'Pulmocare Research and Education (CRF)',
                'hospital_name_hi' => 'पल्मोकेयर रिसर्च एंड एजुकेशन',
                'address' => 'Kondhwa, Pune, Maharashtra - 411048',
                'address_line1' => 'Kondhwa',
                'address_line2' => 'Near NIBM Road',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411048',
                'latitude' => 18.4710,
                'longitude' => 73.8900,
                'experience_years' => 35,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Chest Medicine)', 'PhD (UK)', 'FCCP'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-4512',
                'about_en' => 'Dr. Sundeep Salvi is a world-renowned Pulmonologist and researcher in asthma, COPD, and air pollution impacts on lung health.',
                'about_hi' => 'डॉ. संदीप साल्वी एक विश्व प्रसिद्ध पल्मोनोलॉजिस्ट और शोधकर्ता हैं।',
                'gender' => 'Male',
                'phone' => '020-26855555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Shrikant',
                'last_name' => 'Kelkar',
                'department_name_en' => 'Ophthalmology',
                'department_name_hi' => 'नेत्र रोग (ऑप्थल्मोलॉजी)',
                'hospital_name_en' => 'National Institute of Ophthalmology (NIO)',
                'hospital_name_hi' => 'राष्ट्रीय नेत्र विज्ञान संस्थान (एनआईओ)',
                'address' => '1187/30, Off Ghole Road, Shivaji Nagar, Pune, Maharashtra - 411005',
                'address_line1' => '1187/30, Off Ghole Road',
                'address_line2' => 'Shivaji Nagar',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'latitude' => 18.5280,
                'longitude' => 73.8450,
                'experience_years' => 45,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MS (Ophthalmology)', 'DOMS'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-5678',
                'about_en' => 'Dr. Shrikant Kelkar is the Founder of NIO Pune and an eminent Eye Surgeon specializing in cataract and refractive surgery.',
                'about_hi' => 'डॉ. श्रीकांत केलकर एनआईओ पुणे के संस्थापक और एक प्रख्यात नेत्र सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '020-25536369',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Pramod',
                'last_name' => 'Jog',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'Jog Children\'s Clinic / Deenanath',
                'hospital_name_hi' => 'जोग चिल्ड्रन्स क्लिनिक / दीनानाथ',
                'address' => 'Erandwane, Pune, Maharashtra - 411038',
                'address_line1' => 'Erandwane',
                'address_line2' => 'Near Karve Road',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'latitude' => 18.5100,
                'longitude' => 73.8350,
                'experience_years' => 40,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'FIAP'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-6789',
                'about_en' => 'Dr. Pramod Jog is a Past President of the Indian Academy of Pediatrics (IAP) and a leading Pediatrician in Pune.',
                'about_hi' => 'डॉ. प्रमोद जोग इंडियन एकेडमी ऑफ पीडियाट्रिक्स (IAP) के पूर्व अध्यक्ष और पुणे के एक प्रमुख बाल रोग विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '020-25433333',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sunita',
                'last_name' => 'Tandulwadkar',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Ruby Hall Clinic',
                'hospital_name_hi' => 'रूबी हॉल क्लिनिक',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'experience_years' => 38,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)', 'FICS'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-7890',
                'about_en' => 'Dr. Sunita Tandulwadkar is Chief of IVF and Endoscopy Center at Ruby Hall Clinic Pune, globally recognized for ART and laparoscopic gynecology.',
                'about_hi' => 'डॉ. सुनीता तांदुलवाडकर रूबी हॉल क्लिनिक पुणे में आईवीएफ और एंडोस्कोपी सेंटर की प्रमुख हैं।',
                'gender' => 'Female',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Parikshit',
                'last_name' => 'Prayag',
                'department_name_en' => 'General Physician',
                'department_name_hi' => 'सामान्य चिकित्सक (जनरल फिजिशियन)',
                'hospital_name_en' => 'Deenanath Mangeshkar Hospital',
                'hospital_name_hi' => 'दीनानाथ मंगेशकर अस्पताल',
                'address' => 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra - 411038',
                'address_line1' => 'Near Mhatre Bridge, Erandwane',
                'address_line2' => 'Opposite Mhatre Bridge',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'latitude' => 18.5080,
                'longitude' => 73.8340,
                'experience_years' => 22,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (General Medicine)', 'FIDSA'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-8901',
                'about_en' => 'Dr. Parikshit Prayag is a Senior Consultant in Infectious Diseases and General Medicine at Deenanath Mangeshkar Hospital.',
                'about_hi' => 'डॉ. परीक्षित प्रयाग दीनानाथ मंगेशकर अस्पताल में संक्रामक रोगों और सामान्य चिकित्सा के वरिष्ठ सलाहकार हैं।',
                'gender' => 'Male',
                'phone' => '020-40151000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Parag',
                'last_name' => 'Sancheti',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Sancheti Hospital',
                'hospital_name_hi' => 'संचेती अस्पताल',
                'address' => '16, Shivajinagar, Pune, Maharashtra - 411005',
                'address_line1' => '16, Shivajinagar',
                'address_line2' => 'Near College of Engineering Pune (COEP)',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'latitude' => 18.5285,
                'longitude' => 73.8550,
                'experience_years' => 35,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'FRCS (Edin)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-9012',
                'about_en' => 'Dr. Parag Sancheti is the Chairman and Managing Director of Sancheti Institute for Orthopaedics & Rehabilitation, world-renowned for joint replacement surgery.',
                'about_hi' => 'डॉ. पराग संचेती संचेती इंस्टीट्यूट फॉर ऑर्थोपेडिक्स एंड रिहैबिलिटेशन के अध्यक्ष और प्रबंध निदेशक हैं।',
                'gender' => 'Male',
                'phone' => '020-28999999',
                'is_verified' => true,
            ],
            [
                'first_name' => 'K. H.',
                'last_name' => 'Sancheti',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Sancheti Hospital',
                'hospital_name_hi' => 'संचेती अस्पताल',
                'address' => '16, Shivajinagar, Pune, Maharashtra - 411005',
                'address_line1' => '16, Shivajinagar',
                'address_line2' => 'Near COEP',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'latitude' => 18.5285,
                'longitude' => 73.8550,
                'experience_years' => 60,
                'consultation_fee' => 2000,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)', 'Padma Vibhushan', 'Padma Bhushan', 'Padma Shri'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-0012',
                'about_en' => 'Dr. K. H. Sancheti is a legendary orthopedic physician, inventor of India\'s first indigenous prosthetic knee, and recipient of Padma Vibhushan, Padma Bhushan, and Padma Shri.',
                'about_hi' => 'डॉ. के. एच. संचेती एक महान आर्थोपेडिक चिकित्सक और पद्म विभूषण, पद्म भूषण तथा पद्म श्री से सम्मानित हैं।',
                'gender' => 'Male',
                'phone' => '020-28999999',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Shashank',
                'last_name' => 'Shah',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'LaparoObeso Centre / Lilavati',
                'hospital_name_hi' => 'लेपरोओबेसो सेंटर',
                'address' => 'Pashan Road, Pune, Maharashtra - 411008',
                'address_line1' => 'Pashan Road',
                'address_line2' => 'Near Pune University',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411008',
                'latitude' => 18.5450,
                'longitude' => 73.8150,
                'experience_years' => 32,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'FAIS', 'FALS'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-1123',
                'about_en' => 'Dr. Shashank Shah is a pioneer in bariatric and metabolic surgery in India, having performed over 10,000 successful laparoscopic bariatric procedures.',
                'about_hi' => 'डॉ. शशांक शाह भारत में बेरिएट्रिक और मेटाबोलिक सर्जरी के प्रणेता हैं।',
                'gender' => 'Male',
                'phone' => '020-25655555',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Avinash',
                'last_name' => 'Bhutani',
                'department_name_en' => 'Dermatology',
                'department_name_hi' => 'त्वचा रोग (डर्मेटोलॉजी)',
                'hospital_name_en' => 'Ruby Hall Clinic',
                'hospital_name_hi' => 'रूबी हॉल क्लिनिक',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'experience_years' => 28,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Dermatology)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-2234',
                'about_en' => 'Dr. Avinash Bhutani is a highly respected Senior Consultant Dermatologist at Ruby Hall Clinic Pune.',
                'about_hi' => 'डॉ. अविनाश भूटानी रूबी हॉल क्लिनिक पुणे में एक अत्यधिक सम्मानित वरिष्ठ सलाहकार त्वचा विशेषज्ञ हैं।',
                'gender' => 'Male',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Jayshree',
                'last_name' => 'Todkar',
                'department_name_en' => 'General Surgery',
                'department_name_hi' => 'सामान्य शल्य चिकित्सा (जनरल सर्जरी)',
                'hospital_name_en' => 'JT Bariatric Centre / Ruby Hall',
                'hospital_name_hi' => 'जेटी बेरिएट्रिक सेंटर / रूबी हॉल',
                'address' => 'Dhole Patil Road, Pune, Maharashtra - 411001',
                'address_line1' => 'Dhole Patil Road',
                'address_line2' => 'Near Ruby Hall Clinic',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5320,
                'longitude' => 73.8800,
                'experience_years' => 25,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'Fellowship in Bariatric Surgery'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-3345',
                'about_en' => 'Dr. Jayshree Todkar is India\'s first female bariatric surgeon and a renowned researcher in metabolic diseases.',
                'about_hi' => 'डॉ. जयश्री तोडकर भारत की पहली महिला बेरिएट्रिक सर्जन और मेटाबोलिक रोगों की प्रसिद्ध शोधकर्ता हैं।',
                'gender' => 'Female',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Kalyani',
                'last_name' => 'Barmade',
                'department_name_en' => 'Gynecology',
                'department_name_hi' => 'स्त्री रोग (गायनेकोलॉजी)',
                'hospital_name_en' => 'Surya Mother & Child Hospital',
                'hospital_name_hi' => 'सूर्या मदर एवं चाइल्ड अस्पताल',
                'address' => 'Survey No. 8, Bhawani Peth, Pune, Maharashtra - 411005',
                'address_line1' => 'Survey No. 8, Bhawani Peth',
                'address_line2' => 'Near Kasba Peth',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'latitude' => 18.5180,
                'longitude' => 73.8640,
                'experience_years' => 24,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Obstetrics & Gynecology)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-4456',
                'about_en' => 'Dr. Kalyani Barmade is a Senior Consultant Obstetrician & Gynecologist at Surya Mother and Child Super Speciality Hospital Pune.',
                'about_hi' => 'डॉ. कल्याणी बरमडे सूर्या मदर एंड चाइल्ड सुपर स्पेशलिटी हॉस्पिटल पुणे में वरिष्ठ सलाहकार प्रसूति एवं स्त्री रोग विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '020-67520000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Nitin',
                'last_name' => 'Bhagali',
                'department_name_en' => 'Orthopedics',
                'department_name_hi' => 'हड्डी रोग (ऑर्थोपेडिक्स)',
                'hospital_name_en' => 'Bhagali Nursing Home',
                'hospital_name_hi' => 'भागली नर्सिंग होम',
                'address' => 'Bhandarkar Road, Deccan Gymkhana, Pune, Maharashtra - 411004',
                'address_line1' => 'Bhandarkar Road',
                'address_line2' => 'Deccan Gymkhana',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'latitude' => 18.5170,
                'longitude' => 73.8320,
                'experience_years' => 36,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (Orthopedics)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-5567',
                'about_en' => 'Dr. Nitin Bhagali is a highly experienced Orthopedic Surgeon in Pune, specializing in trauma and fracture management.',
                'about_hi' => 'डॉ. नितिन भागली पुणे में एक अत्यधिक अनुभवी आर्थोपेडिक सर्जन हैं।',
                'gender' => 'Male',
                'phone' => '020-25672233',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Amita',
                'last_name' => 'Phadnis',
                'department_name_en' => 'Pediatrics',
                'department_name_hi' => 'बाल रोग',
                'hospital_name_en' => 'ONP Hospitals (Oyster & Pearl)',
                'hospital_name_hi' => 'ओएनपी अस्पताल',
                'address' => 'Ganeshkhind Road, Shivaji Nagar, Pune, Maharashtra - 411005',
                'address_line1' => 'Ganeshkhind Road',
                'address_line2' => 'Shivaji Nagar',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411005',
                'latitude' => 18.5320,
                'longitude' => 73.8420,
                'experience_years' => 34,
                'consultation_fee' => 1000,
                'education_degrees' => ['MBBS', 'MD (Pediatrics)', 'Fellowship in Neonatology (USA)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-6678',
                'about_en' => 'Dr. Amita Phadnis is the Managing Director of ONP Hospitals and a prominent Senior Pediatrician and Neonatologist in Pune.',
                'about_hi' => 'डॉ. अमिता फड़नीस ओएनपी हॉस्पिटल्स की प्रबंध निदेशक और पुणे में एक प्रमुख वरिष्ठ बाल रोग विशेषज्ञ तथा नवजात शिशु रोग विशेषज्ञ हैं।',
                'gender' => 'Female',
                'phone' => '020-67216600',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Sachin',
                'last_name' => 'Gandhi',
                'department_name_en' => 'ENT (Otolaryngology)',
                'department_name_hi' => 'कान, नाक और गला रोग (ईएनटी)',
                'hospital_name_en' => 'Deenanath Mangeshkar Hospital',
                'hospital_name_hi' => 'दीनानाथ मंगेशकर अस्पताल',
                'address' => 'Near Mhatre Bridge, Erandwane, Pune, Maharashtra - 411038',
                'address_line1' => 'Near Mhatre Bridge, Erandwane',
                'address_line2' => 'Opposite Mhatre Bridge',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411038',
                'latitude' => 18.5080,
                'longitude' => 73.8340,
                'experience_years' => 32,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (ENT)', 'DORL'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-7789',
                'about_en' => 'Dr. Sachin Gandhi is Head of Department of Voice and Laryngology at Deenanath Mangeshkar Hospital, widely acclaimed for phonosurgery.',
                'about_hi' => 'डॉ. सचिन गांधी दीनानाथ मंगेशकर अस्पताल में वॉयस और लैरींगोलॉजी विभाग के प्रमुख हैं।',
                'gender' => 'Male',
                'phone' => '020-40151000',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Bhalchandra',
                'last_name' => 'Kashyapi',
                'department_name_en' => 'Urology',
                'department_name_hi' => 'मूत्र रोग (यूरोलॉजी)',
                'hospital_name_en' => 'Kasba Peth Clinic / Deenanath',
                'hospital_name_hi' => 'कस्बा पेठ क्लिनिक / दीनानाथ',
                'address' => 'Kasba Peth, Pune, Maharashtra - 411011',
                'address_line1' => 'Kasba Peth',
                'address_line2' => 'Near Shaniwar Wada',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411011',
                'latitude' => 18.5220,
                'longitude' => 73.8560,
                'experience_years' => 28,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MS (General Surgery)', 'MCh (Urology)', 'DNB (Urology)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-8890',
                'about_en' => 'Dr. Bhalchandra Kashyapi is a Senior Consultant Urologist and Uro-Oncologist in Pune, expert in robotic and endourology.',
                'about_hi' => 'डॉ. भालचंद्र कश्यपी पुणे में एक वरिष्ठ सलाहकार मूत्र रोग विशेषज्ञ और यूरो-ऑन्कोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '020-24578899',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Shirish',
                'last_name' => 'Hiremath',
                'department_name_en' => 'Cardiology',
                'department_name_hi' => 'हृदय रोग (कार्डियोलॉजी)',
                'hospital_name_en' => 'Ruby Hall Clinic',
                'hospital_name_hi' => 'रूबी हॉल क्लिनिक',
                'address' => '40, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '40, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5305,
                'longitude' => 73.8770,
                'experience_years' => 38,
                'consultation_fee' => 1500,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Cardiology)', 'FACC'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-9901',
                'about_en' => 'Dr. Shirish Hiremath is Director of Cardiology at Ruby Hall Clinic and a former President of the Cardiological Society of India (CSI).',
                'about_hi' => 'डॉ. शिरीष हिरेमठ रूबी हॉल क्लिनिक में कार्डियोलॉजी के निदेशक और कार्डियोलॉजिकल सोसाइटी ऑफ इंडिया (CSI) के पूर्व अध्यक्ष हैं।',
                'gender' => 'Male',
                'phone' => '020-66455150',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Ritu',
                'last_name' => 'Biyani',
                'department_name_en' => 'Dentistry',
                'department_name_hi' => 'दंत चिकित्सा (डेंटिस्ट्री)',
                'hospital_name_en' => 'Biyani Dental Clinic / Sahyadri',
                'hospital_name_hi' => 'बियानी डेंटल क्लिनिक / सह्याद्रि',
                'address' => 'Deccan Gymkhana, Pune, Maharashtra - 411004',
                'address_line1' => 'Deccan Gymkhana',
                'address_line2' => 'Near Bhandarkar Road',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411004',
                'latitude' => 18.5160,
                'longitude' => 73.8370,
                'experience_years' => 25,
                'consultation_fee' => 800,
                'education_degrees' => ['BDS', 'MDS (Prosthodontics)'],
                'medical_council' => 'Maharashtra State Dental Council (MSDC)',
                'registration_number' => 'MSDC-1234',
                'about_en' => 'Dr. Ritu Biyani is a Senior Dental Surgeon and Prosthodontist in Pune, renowned for advanced cosmetic dentistry and implants.',
                'about_hi' => 'डॉ. रितु बियानी पुणे में एक वरिष्ठ दंत चिकित्सक और प्रोस्थोडोंटिस्ट हैं।',
                'gender' => 'Female',
                'phone' => '020-25651122',
                'is_verified' => true,
            ],
            [
                'first_name' => 'Pradeep',
                'last_name' => 'Sharma',
                'department_name_en' => 'Gastroenterology',
                'department_name_hi' => 'गैस्ट्रोएंटरोलॉजी',
                'hospital_name_en' => 'Jehangir Hospital',
                'hospital_name_hi' => 'जहांगीर अस्पताल',
                'address' => '32, Sassoon Road, Pune, Maharashtra - 411001',
                'address_line1' => '32, Sassoon Road',
                'address_line2' => 'Near Pune Railway Station',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'latitude' => 18.5290,
                'longitude' => 73.8750,
                'experience_years' => 30,
                'consultation_fee' => 1200,
                'education_degrees' => ['MBBS', 'MD (Medicine)', 'DM (Gastroenterology)'],
                'medical_council' => 'Maharashtra Medical Council (MMC)',
                'registration_number' => 'MMC-3456',
                'about_en' => 'Dr. Pradeep Sharma is a Senior Consultant Gastroenterologist and Hepatologist at Jehangir Hospital Pune.',
                'about_hi' => 'डॉ. प्रदीप शर्मा जहांगीर अस्पताल पुणे में एक वरिष्ठ सलाहकार गैस्ट्रोएंटरोलॉजिस्ट और हेपेटोलॉजिस्ट हैं।',
                'gender' => 'Male',
                'phone' => '020-66819999',
                'is_verified' => true,
            ],
        ];
    }
}
