import React, { useState } from 'react';
import { Box, Paper, TextField, Button, MenuItem, InputAdornment, Checkbox, FormControlLabel, FormGroup, Slider, Chip, IconButton, Avatar, Pagination, Drawer, Divider, Alert, AlertTitle, CircularProgress, Tooltip } from '@mui/material';
import Search from '@mui/icons-material/Search';
import Tune from '@mui/icons-material/Tune';
import Close from '@mui/icons-material/Close';
import Call from '@mui/icons-material/CallOutlined';
import Directions from '@mui/icons-material/DirectionsOutlined';
import Calendar from '@mui/icons-material/CalendarMonthOutlined';
import Hospital from '@mui/icons-material/LocalHospitalOutlined';
import Flag from '@mui/icons-material/OutlinedFlag';
import Bookmark from '@mui/icons-material/BookmarkBorder';
import BookmarkAdded from '@mui/icons-material/BookmarkAddedOutlined';
import Verified from '@mui/icons-material/VerifiedUserOutlined';
import Place from '@mui/icons-material/LocationOnOutlined';
import Near from '@mui/icons-material/MyLocation';
import { config, t, localized, href, safeUrl, Stack, Typography, Page, PageIntro, Advisory } from './shared';

function useSaved() {
  const [saved, setSaved] = useState(() => { try { const value = JSON.parse(localStorage.getItem('arogio_saved_doctors') || '[]'); return Array.isArray(value) ? value : []; } catch { return []; } });
  return [saved, id => { const next = saved.includes(id) ? saved.filter(v => v !== id) : [...saved, id]; setSaved(next); try { localStorage.setItem('arogio_saved_doctors', JSON.stringify(next)); } catch { /* Saving still works for this visit. */ } }];
}
export function Directory() {
  const d = window.arogioDirectory;
  const [filters, setFilters] = useState({ ...d.filters, department: d.filters.department.map(String), experience: Number(d.filters.experience?.[0] || 0) });
  const [mobile, setMobile] = useState(false);
  const [saved, toggleSaved] = useSaved();
  const [geo, setGeo] = useState(false);
  const [notice, setNotice] = useState('');
  const city = filters.city[0];
  const set = (key, value) => setFilters(current => ({ ...current, [key]: value }));
  const toggle = (key, value) => set(key, filters[key].includes(value) ? filters[key].filter(v => v !== value) : [...filters[key], value]);
  function navigate(extra = {}) { const next = { ...filters, ...extra }; if (!next.experience) delete next.experience; location.href = href('doctors.index', next); }
  const activeCount = filters.department.length + filters.type.length + filters.benefit.length + (filters.experience > 0 ? 1 : 0);
  function nearby() {
    if (!navigator.geolocation) { setNotice(t('Location is unavailable. Search by city instead.', 'स्थान उपलब्ध नहीं है। शहर से खोजें।')); return; }
    setGeo(true);
    navigator.geolocation.getCurrentPosition(position => navigate({ user_lat: position.coords.latitude, user_lng: position.coords.longitude, sort: 'nearest' }), () => { setGeo(false); setNotice(t('Location permission was unavailable. You can still use the city filter.', 'स्थान की अनुमति नहीं मिली। आप शहर का फ़िल्टर उपयोग कर सकते हैं।')); }, { timeout: 10000 });
  }
  const panel = <Box component="form" onSubmit={e => { e.preventDefault(); navigate({ page: 1 }); }} sx={{ p: 2.5 }}><Stack direction="row" alignItems="center" justifyContent="space-between" sx={{ mb: 2 }}><Typography variant="h3">{t('Filters', 'फ़िल्टर')}</Typography><Chip label={`${activeCount} ${t('active', 'सक्रिय')}`} size="small" /></Stack>
    <TextField fullWidth label={t('Practitioner keyword', 'डॉक्टर का नाम या शब्द')} value={filters.search} onChange={e => set('search', e.target.value)} size="small" />
    <Typography fontWeight={700} sx={{ mt: 3, mb: 1 }}>{t('Clinical specialty', 'चिकित्सा विशेषज्ञता')}</Typography><FormGroup sx={{ maxHeight: 270, overflowY: 'auto', overflowX: 'hidden', flexWrap: 'nowrap', width: '100%', pr: 0.5, '&::-webkit-scrollbar': { width: '6px' }, '&::-webkit-scrollbar-thumb': { backgroundColor: 'rgba(0,0,0,0.15)', borderRadius: '3px' } }}>{d.departments.map(dep => <FormControlLabel key={dep.id} control={<Checkbox size="small" checked={filters.department.includes(String(dep.id))} onChange={() => toggle('department', String(dep.id))} />} label={<Typography variant="body2">{localized(dep.name)}</Typography>} sx={{ width: '100%', mr: 0, ml: -0.5, '& .MuiFormControlLabel-label': { whiteSpace: 'normal', wordBreak: 'break-word' } }} />)}</FormGroup>{!d.departments.length && <Typography variant="body2" color="text.secondary">{t('No specialties available yet.', 'अभी विशेषज्ञता उपलब्ध नहीं है।')}</Typography>}
    <Stack direction="row" justifyContent="space-between" sx={{ mt: 3 }}><Typography fontWeight={700}>{t('Minimum experience', 'न्यूनतम अनुभव')}</Typography><Typography color="primary">{filters.experience}+ {t('yrs', 'वर्ष')}</Typography></Stack><Box sx={{ px: 1 }}><Slider min={0} max={40} step={1} value={filters.experience} onChange={(_, value) => set('experience', value)} valueLabelDisplay="auto" aria-label={t('Minimum experience in years', 'वर्षों में न्यूनतम अनुभव')} marks={[{ value: 0, label: '0' }, { value: 20, label: '20' }, { value: 40, label: '40+' }]} /></Box>
    {!!d.types.length && <><Typography fontWeight={700} sx={{ mt: 3 }}>{t('Care provider type', 'स्वास्थ्य प्रदाता का प्रकार')}</Typography><FormGroup sx={{ flexWrap: 'nowrap', width: '100%', overflowX: 'hidden' }}>{d.types.map(type => <FormControlLabel key={type} control={<Checkbox size="small" checked={filters.type.includes(type)} onChange={() => toggle('type', type)} />} label={<Typography variant="body2">{type}</Typography>} sx={{ width: '100%', mr: 0, ml: -0.5, '& .MuiFormControlLabel-label': { whiteSpace: 'normal', wordBreak: 'break-word' } }} />)}</FormGroup></>}
    <Typography fontWeight={700} sx={{ mt: 3 }}>{t('Public benefit empanelment', 'स्वास्थ्य योजना की स्वीकृति')}</Typography><FormGroup sx={{ flexWrap: 'nowrap', width: '100%', overflowX: 'hidden' }}>{[['esic', 'ESIC'], ['cghs', 'CGHS'], ['ayushman', 'Ayushman Bharat'], ['janaadhaar', 'Jan Aadhaar'], ['cashless', t('Cashless', 'कैशलेस')]].map(([value, label]) => <FormControlLabel key={value} control={<Checkbox size="small" checked={filters.benefit.includes(value)} onChange={() => toggle('benefit', value)} />} label={<Typography variant="body2">{label}</Typography>} sx={{ width: '100%', mr: 0, ml: -0.5, '& .MuiFormControlLabel-label': { whiteSpace: 'normal', wordBreak: 'break-word' } }} />)}</FormGroup>
    <Button type="submit" variant="contained" fullWidth startIcon={<Tune />} sx={{ mt: 3 }}>{t('Apply filters', 'फ़िल्टर लागू करें')}</Button><Button fullWidth href={href('doctors.index', { city })} sx={{ mt: 1 }}>{t('Reset all filters', 'सभी फ़िल्टर हटाएँ')}</Button>
  </Box>;
  return <Page name="directory"><PageIntro title={t(`Find Doctors in ${city}`, `${city} में डॉक्टर खोजें`)} label={t('Healthcare directory', 'स्वास्थ्य सेवा निर्देशिका')} description={t('Browse qualified specialists, clinics, and consultation information. Always call to confirm availability before visiting.', 'विशेषज्ञ, क्लिनिक और परामर्श की जानकारी देखें। जाने से पहले उपलब्धता की पुष्टि के लिए कॉल करें।')} trail={[t('Find Care', 'सेवा खोजें'), t('Doctors', 'डॉक्टर')]} />
    <Paper component="form" onSubmit={e => { e.preventDefault(); navigate({ page: 1 }); }} sx={{ p: { xs: 2, md: 2.5 }, mb: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2}><TextField select label={t('Select city', 'शहर चुनें')} value={city} onChange={e => set('city', [e.target.value])} sx={{ minWidth: { md: 260 } }}>{d.cities.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</TextField><TextField fullWidth label={t('Search directory', 'निर्देशिका में खोजें')} value={filters.search} onChange={e => set('search', e.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }} /><Button type="submit" variant="contained" startIcon={<Tune />} sx={{ minWidth: 180 }}>{t('Update Search', 'खोज अपडेट करें')}</Button></Stack><Stack direction="row" gap={1} flexWrap="wrap" alignItems="center" sx={{ mt: 2 }}><Typography variant="caption" color="text.secondary">{t('Active criteria:', 'सक्रिय मानदंड:')}</Typography><Chip size="small" icon={<Place />} label={city} color="primary" variant="outlined" />{filters.department.map(id => <Chip key={id} size="small" label={localized(d.departments.find(v => String(v.id) === id)?.name) || id} onDelete={() => navigate({ department: filters.department.filter(v => v !== id), page: 1 })} />)}{filters.benefit.map(v => <Chip key={v} label={v.toUpperCase()} size="small" onDelete={() => navigate({ benefit: filters.benefit.filter(b => b !== v), page: 1 })} />)}{d.filters.user_lat != null && <Chip size="small" label={t('Within 50 km', '50 किमी के अंदर')} onDelete={() => navigate({ user_lat: null, user_lng: null, sort: 'experience' })} />}<Box sx={{ flexGrow: 1 }} /><Button onClick={nearby} disabled={geo} size="small" startIcon={geo ? <CircularProgress size={16} /> : <Near />}>{t('Near me', 'मेरे पास')}</Button></Stack>{notice && <Alert severity="info" sx={{ mt: 2 }}>{notice}</Alert>}</Paper>
    <Box className="stitch-directory-layout"><Box sx={{ display: { xs: 'none', lg: 'block' } }}><Paper variant="outlined">{panel}</Paper><Alert severity="info" sx={{ mt: 2 }}><AlertTitle>{t('Directory quality', 'निर्देशिका की गुणवत्ता')}</AlertTitle>{t('Check registration and contact details before visiting. Report outdated information to help improve the directory.', 'जाने से पहले पंजीकरण और संपर्क की जानकारी जाँचें। पुरानी जानकारी की रिपोर्ट करें।')}</Alert></Box><Box sx={{ minWidth: 0 }}>
      <Paper sx={{ p: 1.5, mb: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5} justifyContent="space-between" alignItems={{ sm: 'center' }}><Typography variant="h3">{t(`Showing ${d.total} doctors`, `${d.total} डॉक्टर उपलब्ध`)}</Typography><Button startIcon={<Tune />} onClick={() => setMobile(true)} sx={{ display: { lg: 'none' } }}>{t('Filters', 'फ़िल्टर')} ({activeCount})</Button><TextField select size="small" label={t('Sort by', 'क्रम बदलें')} value={filters.sort} onChange={e => navigate({ sort: e.target.value, page: 1 })} sx={{ minWidth: 220 }}>{[['experience', t('Experience: high to low', 'अनुभव: अधिक से कम')], ['name', t('Name: A to Z', 'नाम: A से Z')], ['latest', t('Recently added', 'हाल में जोड़े गए')], ...(d.filters.user_lat != null ? [['nearest', t('Proximity: nearest', 'दूरी: सबसे नज़दीक')]] : [])].map(([v, label]) => <MenuItem key={v} value={v}>{label}</MenuItem>)}</TextField></Stack></Paper>
      <Stack gap={2}>{d.doctors.map(doctor => {
        const name = [doctor.first_name, doctor.last_name].filter(Boolean).join(' ');
        const hospital = doctor.hospitals?.[0];
        const phone = doctor.phone_1;
        const address = hospital?.display_address || hospital?.address || [doctor.address_line1, doctor.city].filter(Boolean).join(', ');
        const directions = safeUrl(hospital?.map_directions_url) || (address ? 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent(address) : null);
        const education = Array.isArray(doctor.education_degrees) ? doctor.education_degrees.join(', ') : doctor.education_degrees;
        return <Paper key={doctor.id} className="stitch-doctor-card" variant="outlined" sx={{ p: { xs: 2, md: 3 } }}><Stack direction="row" gap={2}><Avatar variant="rounded" sx={{ width: { xs: 56, sm: 94 }, height: { xs: 64, sm: 104 }, bgcolor: 'action.hover', color: 'primary.main', fontSize: 30 }}>{name.split(' ').map(v => v[0]).slice(0, 2).join('')}</Avatar><Box sx={{ flex: 1, minWidth: 0 }}><Stack direction="row" justifyContent="space-between" alignItems="flex-start"><Box><Typography variant="h2" sx={{ fontSize: { xs: 22, md: 26 } }}>{name}</Typography>{education && <Typography variant="body2" color="text.secondary">{education}</Typography>}</Box><Stack direction="row"><Tooltip title={t('Report inaccuracy', 'गलत जानकारी की रिपोर्ट')}><IconButton size="small" aria-label={`${t('Report', 'रिपोर्ट')} ${name}`} onClick={() => window.openListingReportModal?.('doctor', doctor.id, name)}><Flag fontSize="small" /></IconButton></Tooltip><Tooltip title={t('Save on this device', 'इस डिवाइस पर सेव करें')}><IconButton size="small" aria-label={`${t('Save', 'सेव करें')} ${name}`} aria-pressed={saved.includes(doctor.id)} onClick={() => toggleSaved(doctor.id)}>{saved.includes(doctor.id) ? <BookmarkAdded color="primary" /> : <Bookmark fontSize="small" />}</IconButton></Tooltip></Stack></Stack><Typography color="primary" fontWeight={700} sx={{ mt: 1 }}>{doctor.specialization_summary || localized(doctor.department?.name)}</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 1 }}>{doctor.experience_years != null && <Typography variant="body2">{doctor.experience_years} {t('years experience', 'वर्ष का अनुभव')}</Typography>}{doctor.distance_km != null && <Chip size="small" label={`${doctor.distance_km} km`} />}</Stack></Box></Stack>
          <Box sx={{ pl: { xs: 0, sm: '110px' }, mt: 2 }}>{hospital && <Typography sx={{ display: 'flex', gap: 1, alignItems: 'center' }}><Hospital fontSize="small" color="primary" />{localized(hospital.name)}</Typography>}<Typography color="text.secondary" variant="body2" sx={{ mt: .5 }}>{address || t('Address not supplied', 'पता उपलब्ध नहीं है')}</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 1.5 }}>{doctor.is_verified && <Chip icon={<Verified />} size="small" label={t('Verified listing', 'सत्यापित रिकॉर्ड')} color="primary" variant="outlined" />}{hospital?.accepts_esic && <Chip size="small" label="ESIC" />}{hospital?.accepts_cghs && <Chip size="small" label="CGHS" />}{hospital?.accepts_ayushman && <Chip size="small" label="Ayushman Bharat" />}{hospital?.pivot?.availability && <Chip size="small" label={String(hospital.pivot.availability)} />}</Stack><Paper elevation={0} sx={{ p: 1.5, my: 2, bgcolor: 'action.hover' }}><Stack direction={{ xs: 'column', sm: 'row' }} gap={1} justifyContent="space-between"><Typography fontWeight={700} variant="body2">{phone || t('Phone not available', 'फ़ोन उपलब्ध नहीं है')}</Typography><Typography variant="caption" color="text.secondary">{t('Always call before visiting', 'जाने से पहले कॉल करें')}</Typography>{doctor.registration_number && <Typography variant="caption">{t('Reg ID:', 'पंजीकरण:')} {doctor.registration_number}</Typography>}</Stack></Paper><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="contained" startIcon={<Call />} href={phone ? `tel:${String(phone).replace(/[^+\d]/g, '')}` : undefined} disabled={!phone}>{t('Call Clinic', 'क्लिनिक को कॉल करें')}</Button><Button startIcon={<Directions />} href={directions || undefined} disabled={!directions} target="_blank" rel="noopener noreferrer">{t('Get Directions', 'दिशा-निर्देश')}</Button></Stack>{doctor.hospitals?.length > 1 && <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1 }}>{t('Also at:', 'यहाँ भी:')} {doctor.hospitals.slice(1).map(h => localized(h.name)).join(', ')}</Typography>}</Box></Paper>;
      })}</Stack>
      {!d.doctors.length && <Paper sx={{ p: 5, textAlign: 'center' }}><Search sx={{ fontSize: 44, color: 'text.secondary', mb: 2 }} /><Typography variant="h2" sx={{ fontSize: 24 }}>{t('No matching doctors found', 'कोई डॉक्टर नहीं मिला')}</Typography><Typography color="text.secondary" sx={{ my: 2 }}>{t('Try a different specialty or city, or remove a filter. An empty directory does not mean care is unavailable in your area.', 'दूसरी विशेषज्ञता या शहर चुनें, या फ़िल्टर हटाएँ। खाली निर्देशिका का अर्थ यह नहीं कि आपके क्षेत्र में सेवा नहीं है।')}</Typography><Button href={href('doctors.index', { city })}>{t('Clear filters', 'फ़िल्टर हटाएँ')}</Button></Paper>}
      <Paper sx={{ p: 2, mt: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2} alignItems="center" justifyContent="space-between"><Typography variant="body2" color="text.secondary">{d.from || 0}–{d.to || 0} / {d.total}</Typography><TextField select label={t('Rows per page', 'प्रति पृष्ठ रिकॉर्ड')} size="small" value={filters.per_page} onChange={e => navigate({ per_page: e.target.value, page: 1 })}>{[10, 20, 50].map(n => <MenuItem key={n} value={n}>{n}</MenuItem>)}</TextField><Pagination color="primary" count={d.pages} page={d.page} onChange={(_, page) => navigate({ page })} siblingCount={0} /></Stack></Paper><Alert severity="info" sx={{ mt: 2 }}><AlertTitle>{t('Public verification notice', 'सार्वजनिक सत्यापन सूचना')}</AlertTitle>{t('Listing details can change. Use the report button for outdated hours, incorrect addresses, or non-working phone numbers.', 'जानकारी बदल सकती है। पुराने समय, गलत पते या बंद फ़ोन की रिपोर्ट करें।')}</Alert>
    </Box></Box><Drawer anchor="left" open={mobile} onClose={() => setMobile(false)}><Box sx={{ width: 'min(340px, 90vw)' }}><Box sx={{ textAlign: 'right' }}><IconButton aria-label={t('Close filters', 'फ़िल्टर बंद करें')} onClick={() => setMobile(false)}><Close /></IconButton></Box>{panel}</Box></Drawer><Advisory /></Page>;
}
