import React, { useState } from 'react';
import { Box, Paper, Card, CardActionArea, TextField, Button, Chip, Alert, AlertTitle, InputAdornment, Pagination, Divider, Snackbar } from '@mui/material';
import Search from '@mui/icons-material/Search';
import Leaf from '@mui/icons-material/SpaOutlined';
import Science from '@mui/icons-material/ScienceOutlined';
import Check from '@mui/icons-material/CheckCircleOutlined';
import Warning from '@mui/icons-material/WarningAmber';
import Share from '@mui/icons-material/ShareOutlined';
import Bookmark from '@mui/icons-material/BookmarkBorder';
import Done from '@mui/icons-material/BookmarkAddedOutlined';
import Arrow from '@mui/icons-material/ArrowForward';
import Family from '@mui/icons-material/FamilyRestroom';
import { config, t, href, safeUrl, Stack, Typography, Page, PageIntro, Heading, InfoBlock, PlainText, Advisory } from './shared';

const evidence = {
  traditional: [t('Traditional Use', 'पारंपरिक उपयोग'), 'default'], limited: [t('Limited Evidence', 'सीमित प्रमाण'), 'info'], supportive: [t('Some Supporting Evidence', 'कुछ सहायक प्रमाण'), 'info'], moderate: [t('Moderate Evidence', 'मध्यम प्रमाण'), 'warning'], strong: [t('Strong Evidence', 'मज़बूत प्रमाण'), 'success'], not_recommended: [t('Not Recommended', 'अनुशंसित नहीं'), 'error'],
};
function Evidence({ level }) { const [label, color] = evidence[level] || evidence.traditional; return <Chip icon={<Science />} label={label} color={color} size="small" variant="outlined" />; }
function lines(value) { return String(value || '').split(/\r?\n|\|/).map(s => s.trim()).filter(Boolean); }
function References({ value }) {
  if (!value) return null;
  let parsed = value;
  try { parsed = JSON.parse(value); } catch { /* Plain-text references are supported. */ }
  const values = Array.isArray(parsed) ? parsed : typeof parsed === 'object' ? [parsed] : lines(parsed);
  return <Box sx={{ mt: 3 }}><Typography variant="h3" sx={{ mb: 1 }}>{t('Source references', 'स्रोत संदर्भ')}</Typography><Stack gap={1}>{values.map((entry, i) => { const text = typeof entry === 'string' ? entry : entry.title || entry.name || entry.url || JSON.stringify(entry); const link = typeof entry === 'string' && /^https?:\/\//i.test(entry) ? safeUrl(entry) : typeof entry === 'object' ? safeUrl(entry.url) : null; return link ? <Typography key={i} component="a" href={link} target="_blank" rel="noopener noreferrer" color="primary" sx={{ overflowWrap: 'anywhere' }}>{text}</Typography> : <PlainText key={i}>{text}</PlainText>; })}</Stack></Box>;
}
function Dossier({ item, notify }) {
  const [saved, setSaved] = useState(() => { try { const values = JSON.parse(localStorage.getItem('arogio_saved_remedies') || '[]'); return Array.isArray(values) && values.includes(item.id); } catch { return false; } });
  const toggle = () => { try { const parsed = JSON.parse(localStorage.getItem('arogio_saved_remedies') || '[]'); const values = Array.isArray(parsed) ? parsed : []; const next = saved ? values.filter(v => v !== item.id) : [...new Set([...values, item.id])]; localStorage.setItem('arogio_saved_remedies', JSON.stringify(next)); setSaved(!saved); notify(t('Saved preference updated on this device.', 'इस डिवाइस पर सेव करने की पसंद अपडेट हुई।')); } catch { notify(t('Saving is unavailable in this browser.', 'इस ब्राउज़र में सेव करना उपलब्ध नहीं है।')); } };
  async function share() { try { if (navigator.share) await navigator.share({ title: item.title, url: item.url }); else { await navigator.clipboard.writeText(item.url); notify(t('Remedy link copied.', 'नुस्खे का लिंक कॉपी हुआ।')); } } catch (e) { if (e.name !== 'AbortError') notify(t('Unable to share. Copy the page address from your browser.', 'साझा नहीं हो सका। ब्राउज़र से पेज का पता कॉपी करें।')); } }
  const ingredients = item.ingredientItems?.length ? item.ingredientItems : lines(item.ingredients).map(name => ({ name }));
  const steps = lines(item.steps || item.preparation);
  const cautions = [['not_suitable_for', t('Not suitable for', 'इनके लिए उपयुक्त नहीं')], ['child_warning', t('Children', 'बच्चे')], ['pregnancy_warning', t('Pregnancy', 'गर्भावस्था')], ['elderly_warning', t('Older adults', 'वृद्ध वयस्क')], ['medical_condition_warning', t('Medical conditions', 'चिकित्सा स्थितियाँ')], ['medicine_interactions', t('Medicine interactions', 'दवा अंतःक्रियाएँ')], ['possible_side_effects', t('Possible side effects', 'संभावित दुष्प्रभाव')]].filter(([key]) => item[key]);
  return <Paper variant="outlined" className="stitch-remedy-dossier" sx={{ p: { xs: 2, md: 3.5 } }}>
    <Box className="stitch-remedy-intro"><Box><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mb: 2 }}><Evidence level={item.evidence} />{item.category && <Chip size="small" icon={<Leaf />} label={item.category} component="a" href={item.categoryUrl} clickable />}</Stack><Typography variant="h2" sx={{ fontSize: { xs: 27, md: 33 } }}>{item.title}</Typography>{item.problem_name && <Typography color="text.secondary" sx={{ my: 1 }}>{item.problem_name}</Typography>}<Paper elevation={0} sx={{ p: 2, mt: 2, bgcolor: 'action.hover' }}><Typography variant="overline" color="primary">{t('Purpose & overview', 'उद्देश्य और परिचय')}</Typography><PlainText>{item.short_description || item.description || t('Read the preparation and safety information before use.', 'उपयोग से पहले तैयारी और सुरक्षा जानकारी पढ़ें।')}</PlainText></Paper></Box><Box component="img" src={config.images.remedies} alt={t('Illustrative traditional herbal preparation', 'पारंपरिक हर्बल तैयारी का चित्र')} sx={{ width: '100%', height: 255, borderRadius: 2, objectFit: 'cover' }} /></Box>
    <Box className="design-grid two" sx={{ mt: 3 }}><InfoBlock title={t('Ingredients & Measurements', 'सामग्री और मात्रा')}><Stack gap={1}>{ingredients.map((ingredient, i) => <Paper key={i} elevation={0} sx={{ p: 1.5 }}><Stack direction="row" gap={1} justifyContent="space-between" alignItems="center"><Check color="primary" fontSize="small" /><Typography component={ingredient.url ? 'a' : 'span'} href={ingredient.url} sx={{ flex: 1 }} variant="body2">{ingredient.name}</Typography>{ingredient.quantity && <Chip label={ingredient.quantity} size="small" />}</Stack></Paper>)}</Stack>{!ingredients.length && <PlainText>{t('Ingredient quantities have not been supplied for this entry.', 'इस नुस्खे के लिए सामग्री की मात्रा उपलब्ध नहीं है।')}</PlainText>}{item.dosage_or_quantity && <Typography variant="body2" sx={{ mt: 2 }}>{item.dosage_or_quantity}</Typography>}</InfoBlock><InfoBlock title={t('Preparation & Regimen', 'तैयारी और उपयोग')}><Stack gap={2}>{steps.map((step, i) => <Stack direction="row" gap={1.5} key={i}><Chip size="small" color="primary" label={i + 1} /><PlainText variant="body2">{step.replace(/^\d+[.)]\s*/, '')}</PlainText></Stack>)}</Stack>{!steps.length && <PlainText>{t('Preparation details have not been supplied.', 'तैयारी की जानकारी उपलब्ध नहीं है।')}</PlainText>}{item.usage_instructions && <PlainText variant="body2" sx={{ mt: 2 }}>{item.usage_instructions}</PlainText>}<Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 2 }}>{item.frequency && <Chip label={item.frequency} size="small" />}{item.recommended_duration && <Chip label={item.recommended_duration} size="small" />}</Stack></InfoBlock></Box>
    {(item.how_it_may_help || item.evidence_summary || item.traditional_benefit) && <Alert severity="info" icon={<Science />} sx={{ mt: 3 }}><AlertTitle>{t('How it may help & evidence', 'संभावित लाभ और प्रमाण')}</AlertTitle><PlainText variant="body2">{[item.how_it_may_help, item.evidence_summary, item.traditional_benefit].filter(Boolean).join('\n\n')}</PlainText></Alert>}
    {item.suitable_for && <Box sx={{ mt: 2 }}><Typography variant="h3">{t('Suitable for', 'इनके लिए उपयुक्त')}</Typography><PlainText>{item.suitable_for}</PlainText></Box>}
    <Box className="design-grid two" sx={{ mt: 3 }}><Alert severity="warning" icon={<Warning />} sx={{ borderLeft: '4px solid', borderColor: 'warning.main' }}><AlertTitle>{t('Contraindications & Cautions', 'निषेध और सावधानियाँ')}</AlertTitle>{cautions.length ? cautions.map(([key, label]) => <Box key={key} sx={{ mb: 1.5 }}><Typography variant="body2" fontWeight={700}>{label}</Typography><PlainText variant="body2">{item[key]}</PlainText></Box>) : <PlainText variant="body2">{t('Check with a qualified professional before using a remedy, especially when taking medicines. Missing warnings do not establish safety.', 'नुस्खा उपयोग करने से पहले योग्य चिकित्सक से पूछें, विशेषकर दवा लेते समय। चेतावनी का न होना सुरक्षा का प्रमाण नहीं है।')}</PlainText>}</Alert><Alert severity="error" sx={{ borderLeft: '4px solid', borderColor: 'error.main' }}><AlertTitle>{t('When to See a Medical Doctor', 'डॉक्टर से कब मिलें')}</AlertTitle><PlainText variant="body2">{[item.red_flags, item.when_to_see_doctor].filter(Boolean).join('\n\n') || t('Seek professional care for concerns that are severe, persistent, or worsening. Do not delay urgent care for a home remedy.', 'गंभीर, लगातार या बढ़ती समस्या के लिए चिकित्सक से मिलें। घरेलू नुस्खे के लिए तत्काल इलाज में देरी न करें।')}</PlainText><Button href={href('doctors.index', { department: item.department })} color="error" sx={{ mt: 2 }}>{t('Find a doctor', 'डॉक्टर खोजें')}</Button></Alert></Box>
    <References value={item.references} />{item.medical_disclaimer && <PlainText variant="body2" sx={{ mt: 3 }}>{item.medical_disclaimer}</PlainText>}
    <Paper elevation={0} sx={{ p: 2, mt: 3, bgcolor: 'action.hover' }}><Stack direction={{ xs: 'column', sm: 'row' }} gap={2} alignItems={{ sm: 'center' }} justifyContent="space-between"><Box><Typography variant="body2" fontWeight={700}>{t('Reviewed content', 'समीक्षित सामग्री')}</Typography><Typography variant="caption" color="text.secondary">{item.reviewedAt ? `${t('Last reviewed:', 'अंतिम समीक्षा:')} ${item.reviewedAt}` : t('Review date not supplied', 'समीक्षा की तारीख उपलब्ध नहीं है')}</Typography></Box><Stack direction="row" gap={1}><Button startIcon={saved ? <Done /> : <Bookmark />} aria-pressed={saved} onClick={toggle}>{saved ? t('Saved', 'सेव किया') : t('Save Remedy', 'नुस्खा सेव करें')}</Button><Button variant="contained" startIcon={<Share />} onClick={share}>{t('Share Dossier', 'जानकारी साझा करें')}</Button></Stack></Stack></Paper>
  </Paper>;
}
export function Remedies() {
  const d = window.arogioRemedies;
  const [query, setQuery] = useState(d.query || '');
  const [message, setMessage] = useState('');
  const items = d.items.filter(item => item.id !== d.featured?.id);
  const changePage = page => { const target = new URL(location.href); target.searchParams.set('page', page); location.href = target.href; };
  return <Page name="remedies"><PageIntro title={d.context || t('Nani Dadi Ke Nuskhe — Traditional Remedies', 'नानी दादी के नुस्खे — पारंपरिक घरेलू उपाय')} label={t('Traditional wisdom, evidence & safety', 'पारंपरिक ज्ञान, प्रमाण और सुरक्षा')} description={t('Explore Indian home remedies with clear evidence labels, preparation information, precautions, and guidance on when to seek care.', 'प्रमाण, तैयारी, सावधानियों और डॉक्टर से मिलने की जानकारी के साथ भारतीय घरेलू नुस्खे देखें।')} trail={[t('Health Information', 'स्वास्थ्य जानकारी'), t('Nani Dadi Ke Nuskhe', 'नानी दादी के नुस्खे')]} />
    <Alert severity="info" sx={{ mb: 4 }}><AlertTitle>{t('Arogio evidence & safety guidance', 'Arogio प्रमाण और सुरक्षा जानकारी')}</AlertTitle>{t('Traditional does not automatically mean safe or effective. Read the evidence and precautions for each remedy. These resources do not replace medical care.', 'पारंपरिक होने का अर्थ हमेशा सुरक्षित या प्रभावी नहीं है। हर नुस्खे के प्रमाण और सावधानियाँ पढ़ें। यह जानकारी चिकित्सा देखभाल का विकल्प नहीं है।')}</Alert>
    {!d.detail && <Paper component="form" action={location.pathname} method="get" sx={{ p: { xs: 2, md: 3 } }}><Stack direction={{ xs: 'column', sm: 'row' }} gap={2}><TextField fullWidth label={t('Search remedies, concerns, or ingredients', 'नुस्खे, समस्याएँ या सामग्री खोजें')} name="q" value={query} onChange={e => setQuery(e.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }} /><Button type="submit" variant="contained" sx={{ minWidth: 110 }}>{t('Search', 'खोजें')}</Button></Stack><Typography variant="overline" sx={{ display: 'block', mt: 2 }}>{t('Filter by health concern', 'स्वास्थ्य समस्या के अनुसार फ़िल्टर')}</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Chip label={t('All remedies', 'सभी नुस्खे')} component="a" href={href('nani-dadi.index')} clickable color={!d.context ? 'primary' : 'default'} />{d.categories.map(category => <Chip key={category.url} label={category.name} component="a" href={category.url} clickable />)}</Stack>{!!d.ingredients.length && <Stack direction="row" gap={1} flexWrap="wrap" alignItems="center" sx={{ mt: 2 }}><Typography variant="caption" color="text.secondary">{t('Common kitchen staples:', 'रसोई की सामान्य सामग्री:')}</Typography>{d.ingredients.slice(0, 8).map(ingredient => <Chip size="small" key={ingredient.url} label={ingredient.name} component="a" href={ingredient.url} clickable variant="outlined" />)}</Stack>}</Paper>}
    {d.contextDescription && <Alert severity="warning" sx={{ mt: 2 }}>{d.contextDescription}</Alert>}
    {d.featured ? <><Heading>{d.detail ? t('Remedy Dossier', 'नुस्खे की पूरी जानकारी') : t('Featured Remedy Dossier', 'प्रमुख नुस्खे की जानकारी')}</Heading><Dossier key={d.featured.id} item={d.featured} notify={setMessage} /></> : <Paper sx={{ p: 5, mt: 3, textAlign: 'center' }}><Leaf sx={{ fontSize: 50, color: 'primary.main', mb: 2 }} /><Typography variant="h2" sx={{ fontSize: 26 }}>{t('No matching reviewed remedies', 'कोई समीक्षित नुस्खा नहीं मिला')}</Typography><Typography color="text.secondary" sx={{ my: 2 }}>{t('Try another search or return to the full library. Only eligible reviewed content appears here.', 'दूसरी खोज करें या पूरी लाइब्रेरी पर जाएँ। यहाँ केवल योग्य समीक्षित सामग्री दिखाई जाती है।')}</Typography><Button href={href('nani-dadi.index')}>{t('View all remedies', 'सभी नुस्खे देखें')}</Button></Paper>}
    {!!items.length && <><Heading href={href('nani-dadi.index')}>{t('Explore More Nuskhe', 'और नुस्खे देखें')}</Heading><Box className="design-grid three">{items.map(item => <Card key={item.id}><CardActionArea href={item.url} sx={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'stretch' }}><Box sx={{ height: 150, bgcolor: 'action.hover', display: 'grid', placeItems: 'center', color: 'primary.main' }}><Leaf sx={{ fontSize: 65 }} /></Box><Box sx={{ p: 2.5, flex: 1 }}><Evidence level={item.evidence} /><Typography variant="overline" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>{item.category}</Typography><Typography variant="h3">{item.title}</Typography><PlainText variant="body2" sx={{ mt: 1.5 }}>{item.short_description}</PlainText></Box><Stack direction="row" justifyContent="space-between" sx={{ p: 2.5, pt: 0, color: 'primary.main' }}><Typography variant="body2" fontWeight={700}>{t('Read Full Remedy', 'पूरा नुस्खा पढ़ें')}</Typography><Arrow fontSize="small" /></Stack></CardActionArea></Card>)}</Box></>}
    {!d.detail && d.pages > 1 && <Stack alignItems="center" sx={{ mt: 3 }}><Pagination count={d.pages} page={d.page} onChange={(_, page) => changePage(page)} color="primary" /></Stack>}
    <Paper sx={{ p: 3, mt: 5 }}><Typography variant="h3" sx={{ mb: 2 }}>{t('Understanding Arogio Evidence Tiers', 'Arogio के प्रमाण स्तर समझें')}</Typography><Box className="design-grid three">{[['strong', t('Read the cited sources and evidence summary to understand the basis for this label.', 'इस लेबल का आधार समझने के लिए स्रोत और प्रमाण सारांश पढ़ें।')], ['moderate', t('Check the scope and limitations described in the individual remedy.', 'व्यक्तिगत नुस्खे में बताए गए दायरे और सीमाओं को जाँचें।')], ['limited', t('Evidence is limited. Traditional use does not establish effectiveness or safety.', 'प्रमाण सीमित हैं। पारंपरिक उपयोग प्रभावशीलता या सुरक्षा सिद्ध नहीं करता।')]].map(([level, description]) => <Box key={level} sx={{ p: 2, bgcolor: 'action.hover', borderRadius: 2 }}><Evidence level={level} /><Typography variant="body2" color="text.secondary" sx={{ mt: 1.5 }}>{description}</Typography></Box>)}</Box></Paper>
    <Paper sx={{ p: 3, mt: 4, bgcolor: 'action.hover' }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2} alignItems={{ md: 'center' }} justifyContent="space-between"><Box><Typography variant="h3">{t('Have a question or a family remedy to share?', 'कोई सवाल या परिवार का नुस्खा साझा करना चाहते हैं?')}</Typography><Typography color="text.secondary" variant="body2" sx={{ mt: 1 }}>{t('Contact Arogio with your suggestion. Submitted information requires review before publication.', 'अपने सुझाव के साथ Arogio से संपर्क करें। प्रकाशन से पहले समीक्षा आवश्यक है।')}</Typography></Box><Button href={href('contact')} variant="contained" startIcon={<Family />} sx={{ flexShrink: 0 }}>{t('Contact Arogio', 'Arogio से संपर्क करें')}</Button></Stack></Paper><Advisory /><Snackbar open={Boolean(message)} autoHideDuration={4500} onClose={() => setMessage('')} message={message} />
  </Page>;
}
