import React, { useState, useRef, useEffect } from 'react';
import { Box, Paper, TextField, MenuItem, Button, Stepper, Step, StepLabel, Alert, AlertTitle, Chip, Autocomplete, CircularProgress, Divider } from '@mui/material';
import Next from '@mui/icons-material/ArrowForward';
import Back from '@mui/icons-material/ArrowBack';
import Edit from '@mui/icons-material/EditNote';
import Reset from '@mui/icons-material/RestartAlt';
import Assessment from '@mui/icons-material/AssignmentIndOutlined';
import Doctor from '@mui/icons-material/MedicalServicesOutlined';
import Leaf from '@mui/icons-material/SpaOutlined';
import Print from '@mui/icons-material/PrintOutlined';
import { config, t, localized, href, Stack, Typography, Page, PageIntro, Heading, InfoBlock, Advisory } from './shared';

export function Symptoms() {
  const catalog = window.arogioSymptoms.symptoms;
  const [step, setStep] = useState(0);
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('unknown');
  const [selected, setSelected] = useState([]);
  const [text, setText] = useState('');
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const request = useRef(null);
  const anchor = useRef(null);
  useEffect(() => () => request.current?.abort(), []);
  function move(next) { setError(''); setStep(next); anchor.current?.scrollIntoView({ block: 'start' }); }
  function reset() { request.current?.abort(); setAge(''); setGender('unknown'); setSelected([]); setText(''); setResult(null); setBusy(false); move(0); }
  async function analyze() {
    setError(''); setBusy(true);
    request.current?.abort(); const controller = new AbortController(); request.current = controller;
    const timeout = setTimeout(() => controller.abort(), 25000);
    try {
      const response = await fetch(href('symptom-test.analyze'), { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-CSRF-TOKEN': config.csrf }, body: JSON.stringify({ age: Number(age), gender, symptoms: selected.map(s => s.name?.en || localized(s.name)), symptom_text: text }), signal: controller.signal });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.message || t('Please check your answers and try again.', 'जवाब जाँचें और दोबारा प्रयास करें।'));
      setResult(payload); move(3);
    } catch (e) { setError(e.name === 'AbortError' ? t('The assessment timed out. Please try again.', 'आकलन में अधिक समय लगा। दोबारा प्रयास करें।') : e.message); }
    finally { clearTimeout(timeout); setBusy(false); }
  }
  const department = result?.recommended_department || result?.likely_conditions?.[0]?.department;
  const doctorLink = href('doctors.index', { department: department?.id || department?.name?.en || '', city: config.city });
  const genderLabel = { male: t('Male', 'पुरुष'), female: t('Female', 'महिला'), other: t('Other', 'अन्य'), unknown: t('Not specified', 'नहीं बताया') }[gender];
  return <Page name="symptoms"><PageIntro title={t('Guided Symptom Assessment', 'लक्षणों का निर्देशित आकलन')} description={t('Enter your basic details and symptoms to discover relevant medical specialties and informative care guidance.', 'संबंधित चिकित्सा विशेषज्ञता और स्वास्थ्य जानकारी के लिए अपनी सामान्य जानकारी और लक्षण भरें।')} trail={[t('Health Information', 'स्वास्थ्य जानकारी'), t('Guided Symptom Checker', 'लक्षण आकलन')]} />
    <Paper ref={anchor} sx={{ p: { xs: 2, md: 3 }, mb: 3, scrollMarginTop: 100 }}><Stepper activeStep={step} alternativeLabel>{[t('Basic Details', 'सामान्य जानकारी'), t('Symptoms', 'लक्षण'), t('Review', 'समीक्षा'), t('Results', 'परिणाम')].map(label => <Step key={label}><StepLabel>{label}</StepLabel></Step>)}</Stepper></Paper>
    <Alert severity="warning" sx={{ mb: 3 }}><AlertTitle>{t('Informational matches only', 'केवल जानकारी के लिए मिलान')}</AlertTitle>{t('This assessment does not provide a formal medical diagnosis or prescription. Consult a qualified medical professional for evaluation and personal care.', 'यह आकलन चिकित्सीय निदान या नुस्खा नहीं देता। जाँच और व्यक्तिगत सलाह के लिए योग्य चिकित्सक से मिलें।')}</Alert>
    {error && <Alert severity="error" sx={{ mb: 2 }} role="alert">{error}</Alert>}
    {step < 3 && <Paper sx={{ p: { xs: 2.5, md: 4 }, maxWidth: 900, mx: 'auto' }}>
      {step === 0 && <Box component="form" onSubmit={e => { e.preventDefault(); move(1); }}><Typography variant="h2" sx={{ fontSize: 27, mb: 1 }}>{t('Tell us a little about yourself', 'अपने बारे में थोड़ा बताएँ')}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{t('Only the details needed for this assessment. You do not need an account.', 'आकलन के लिए केवल आवश्यक जानकारी दें। खाते की ज़रूरत नहीं है।')}</Typography><Box className="design-grid two"><TextField required type="number" label={t('Age in years', 'उम्र (वर्ष)')} value={age} onChange={e => setAge(e.target.value)} slotProps={{ htmlInput: { min: 0, max: 120, step: 1 } }} /><TextField select label={t('Gender', 'लिंग')} value={gender} onChange={e => setGender(e.target.value)}>{Object.entries({ male: t('Male', 'पुरुष'), female: t('Female', 'महिला'), other: t('Other', 'अन्य'), unknown: t('Prefer not to say', 'नहीं बताना चाहते') }).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Box><Button variant="contained" type="submit" endIcon={<Next />} sx={{ mt: 3 }}>{t('Continue to symptoms', 'लक्षणों पर जाएँ')}</Button></Box>}
      {step === 1 && <><Typography variant="h2" sx={{ fontSize: 27, mb: 1 }}>{t('What symptoms are you experiencing?', 'आपको क्या लक्षण हैं?')}</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>{t('Choose up to 20 symptoms, describe them in your own words, or do both.', '20 तक लक्षण चुनें, अपने शब्दों में बताएँ, या दोनों करें।')}</Typography><Autocomplete multiple options={catalog} value={selected} onChange={(_, next) => setSelected(next.slice(0, 20))} getOptionLabel={option => localized(option.name)} isOptionEqualToValue={(a, b) => String(a.id) === String(b.id)} renderInput={params => <TextField {...params} label={t('Select symptoms', 'लक्षण चुनें')} placeholder={t('Search symptoms', 'लक्षण खोजें')} />} /><TextField fullWidth multiline minRows={4} label={t('Describe your symptoms', 'अपने लक्षण बताएँ')} value={text} onChange={e => setText(e.target.value)} sx={{ mt: 3 }} slotProps={{ htmlInput: { maxLength: 1000 } }} helperText={`${text.length}/1000`} /><Stack direction="row" justifyContent="space-between" sx={{ mt: 3 }}><Button startIcon={<Back />} onClick={() => move(0)}>{t('Back', 'वापस')}</Button><Button variant="contained" endIcon={<Next />} disabled={!selected.length && !text.trim()} onClick={() => move(2)}>{t('Review answers', 'जवाब की समीक्षा')}</Button></Stack></>}
      {step === 2 && <><Typography variant="h2" sx={{ fontSize: 27, mb: 2 }}>{t('Review your assessment', 'अपने आकलन की समीक्षा करें')}</Typography><Typography>{t('Age:', 'उम्र:')} {age} · {genderLabel}</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{ my: 2 }}>{selected.map(s => <Chip key={s.id} label={localized(s.name)} />)}</Stack>{text && <Typography sx={{ whiteSpace: 'pre-wrap' }}>{text}</Typography>}<Alert severity="info" sx={{ my: 3 }}>{t('Submitting will send these details to Arogio for analysis. Results are informational, not diagnostic probabilities.', 'जमा करने पर यह जानकारी Arogio को विश्लेषण के लिए भेजी जाएगी। परिणाम जानकारी हैं, निदान की संभावनाएँ नहीं।')}</Alert><Stack direction="row" justifyContent="space-between"><Button disabled={busy} startIcon={<Edit />} onClick={() => move(1)}>{t('Edit symptoms', 'लक्षण बदलें')}</Button><Button variant="contained" disabled={busy} startIcon={busy ? <CircularProgress size={18} color="inherit" /> : <Assessment />} onClick={analyze}>{busy ? t('Analyzing…', 'विश्लेषण जारी…') : t('View assessment', 'आकलन देखें')}</Button></Stack></>}
    </Paper>}
    {step === 3 && result && <Box aria-live="polite"><Paper sx={{ p: 2.5, bgcolor: 'action.hover', mb: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2} justifyContent="space-between" alignItems={{ md: 'center' }}><Stack direction="row" gap={2}><Assessment color="primary" sx={{ fontSize: 35 }} /><Box><Typography fontWeight={700}>{t('Patient Assessment Profile', 'आकलन प्रोफ़ाइल')}</Typography><Typography color="text.secondary">{t('Age', 'उम्र')} {age} · {genderLabel}</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 1 }}>{selected.map(s => <Chip key={s.id} size="small" label={localized(s.name)} />)}</Stack>{text && <Typography variant="body2" sx={{ mt: 1, whiteSpace: 'pre-wrap' }}>{text}</Typography>}</Box></Stack><Stack direction="row" gap={1}><Button startIcon={<Edit />} onClick={() => move(0)}>{t('Edit Details', 'जानकारी बदलें')}</Button><Button startIcon={<Reset />} onClick={reset}>{t('Restart', 'फिर शुरू करें')}</Button></Stack></Stack></Paper>
      <Heading>{t('Informational Condition Matches', 'जानकारी के लिए स्थितियों का मिलान')}</Heading>
      {!result.likely_conditions?.length && <Alert severity="info">{result.message || t('No close match was found. Add more details or speak with a doctor.', 'कोई निकट मिलान नहीं मिला। और जानकारी दें या डॉक्टर से बात करें।')}</Alert>}
      <Stack gap={2}>{(result.likely_conditions || []).map((condition, i) => { const matched = condition.matched_symptoms || []; const total = new Set([...matched, ...(condition.remaining_symptoms || [])].map(s => String(s.id))).size; return <Paper key={condition.id || i} sx={{ p: { xs: 2.5, md: 3 } }}><Stack direction={{ xs: 'column', md: 'row' }} gap={3} justifyContent="space-between"><Box sx={{ flex: 1 }}><Chip size="small" label={t('Symptom information match', 'लक्षण जानकारी का मिलान')} color={i === 0 ? 'primary' : 'default'} variant="outlined" sx={{ mb: 1.5 }} /><Typography variant="h2" sx={{ fontSize: 25 }}>{localized(condition.name)}</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{ my: 2 }}>{matched.map(s => <Chip key={s.id} size="small" label={localized(s.name)} />)}</Stack><InfoBlock title={t('Recommended Specialist', 'सुझाई गई विशेषज्ञता')}><Typography fontWeight={700}>{localized(condition.department?.name) || t('Consult a qualified physician', 'योग्य चिकित्सक से मिलें')}</Typography><Typography variant="body2" color="text.secondary">{t('A clinician can evaluate symptoms and determine appropriate care.', 'चिकित्सक लक्षणों की जाँच करके उचित देखभाल बता सकते हैं।')}</Typography></InfoBlock></Box><Box sx={{ minWidth: 150, maxWidth: { xs: '100%', md: 190 }, bgcolor: 'action.hover', p: 2.5, borderRadius: 2, textAlign: 'center', alignSelf: { md: 'flex-start' } }}><Box sx={{ display: 'inline-grid', placeItems: 'center', position: 'relative' }}><CircularProgress variant="determinate" value={total ? Math.min(100, matched.length / total * 100) : 0} size={82} thickness={4} /><Typography sx={{ position: 'absolute', fontSize: 25, fontWeight: 700 }}>{matched.length}</Typography></Box><Typography variant="body2" fontWeight={700} sx={{ mt: 1 }}>{t('Reported symptoms matched', 'बताए गए लक्षणों का मिलान')}</Typography><Typography variant="caption" color="text.secondary">{t('Not a diagnosis probability', 'निदान की संभावना नहीं')}</Typography></Box></Stack></Paper>; })}</Stack>
      {!!result.next_symptoms?.length && <Paper sx={{ p: 2.5, mt: 2 }}><Typography variant="h3">{t('Other symptoms to consider', 'अन्य लक्षणों पर विचार करें')}</Typography><Typography color="text.secondary" variant="body2" sx={{ my: 1 }}>{t('Only add symptoms you are actually experiencing.', 'केवल वही लक्षण जोड़ें जो आपको वास्तव में हैं।')}</Typography><Stack direction="row" gap={1} flexWrap="wrap">{result.next_symptoms.map(s => <Chip key={s.id} label={localized(s.name) || s.label} onClick={() => { if (selected.length < 20 && !selected.some(v => String(v.id) === String(s.id))) setSelected([...selected, s]); move(1); }} />)}</Stack></Paper>}
      <Heading>{t('Recommended Healthcare Actions & Next Steps', 'स्वास्थ्य सेवा और अगले कदम')}</Heading><Box className="design-grid two"><Paper sx={{ p: 3 }}><Doctor color="primary" /><Typography variant="h2" sx={{ fontSize: 25, my: 1 }}>{t('Consult a Doctor', 'डॉक्टर से परामर्श लें')}</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>{t('Connect with relevant specialists and confirm consultation details directly.', 'संबंधित विशेषज्ञ से जुड़ें और परामर्श की जानकारी की सीधे पुष्टि करें।')}</Typography><Box component="img" src={config.images.health} alt="" sx={{ width: '100%', height: 160, objectFit: 'cover', borderRadius: 2, mb: 2 }} /><Button href={doctorLink} fullWidth variant="contained" endIcon={<Next />}>{localized(department?.name) || t('Find doctors', 'डॉक्टर खोजें')}</Button></Paper><Paper sx={{ p: 3 }}><Leaf color="primary" /><Typography variant="h2" sx={{ fontSize: 25, my: 1 }}>{t('Home Care & Safety Information', 'घरेलू देखभाल और सुरक्षा जानकारी')}</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>{t('Explore traditional remedies with their evidence, precautions, and guidance on when to seek care.', 'प्रमाण, सावधानियों और डॉक्टर से मिलने की जानकारी के साथ पारंपरिक नुस्खे देखें।')}</Typography><Box component="img" src={config.images.remedies} alt="" sx={{ width: '100%', height: 160, objectFit: 'cover', borderRadius: 2, mb: 2 }} /><Button fullWidth href={href('nani-dadi.index')} variant="outlined" startIcon={<Leaf />}>{t('View Preparation & Safety Precautions', 'तैयारी और सुरक्षा की जानकारी देखें')}</Button></Paper></Box>
      <Alert severity="error" sx={{ mt: 3 }}><AlertTitle>{t('Severe or urgent symptoms?', 'गंभीर या तत्काल सहायता वाले लक्षण?')}</AlertTitle>{t('Do not wait for an online assessment if you need urgent medical help. Use emergency resources or seek immediate in-person care.', 'तत्काल चिकित्सा सहायता की ज़रूरत हो तो ऑनलाइन आकलन की प्रतीक्षा न करें। आपातकालीन संसाधन या तत्काल व्यक्तिगत सहायता लें।')}<Button color="error" href={href('emergency')} sx={{ display: 'flex', mt: 1 }}>{t('Emergency resources', 'आपातकालीन संसाधन')}</Button></Alert><Stack direction="row" justifyContent="flex-end" sx={{ mt: 2 }}><Button startIcon={<Print />} onClick={() => window.print()}>{t('Print / Save PDF summary', 'प्रिंट / PDF सारांश सेव करें')}</Button></Stack>
    </Box>}
    {step < 3 && <Advisory />}
  </Page>;
}
