<?php
namespace App\Filament\Resources;
use App\Filament\Resources\HomeRemedyResource\Pages; use App\Models\{HomeRemedy,HomeRemedyCategory,HomeRemedyIngredient,Department}; use Filament\Forms; use Filament\Schemas\Schema; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class HomeRemedyResource extends Resource { protected static ?string $model=HomeRemedy::class; protected static \BackedEnum|string|null $navigationIcon='heroicon-o-sparkles'; protected static \UnitEnum|string|null $navigationGroup='Content Management'; protected static ?string $navigationLabel='Nani Dadi Ke Nuskhe'; protected static ?int $navigationSort=1;
 public static function form(Schema $schema):Schema{return $schema->schema([Forms\Components\Tabs::make('Remedy')->tabs([
 Forms\Components\Tabs\Tab::make('Basic')->schema([Forms\Components\TextInput::make('title_en')->required(),Forms\Components\TextInput::make('title_hi')->required(),Forms\Components\TextInput::make('slug')->required(),Forms\Components\TextInput::make('problem_name_en'),Forms\Components\TextInput::make('problem_name_hi'),Forms\Components\Select::make('category_id')->options(HomeRemedyCategory::orderBy('name_en')->pluck('name_en','id'))->required()->searchable(),Forms\Components\Select::make('doctor_speciality_id')->label('Doctor speciality')->options(Department::orderBy('name_en')->pluck('name_en','id'))->searchable(),Forms\Components\Select::make('ingredients')->multiple()->relationship('ingredients','name_en')->preload()->searchable(),Forms\Components\Toggle::make('is_featured'),Forms\Components\Toggle::make('is_published'),Forms\Components\TextInput::make('sort_order')->numeric()])->columns(2),
 Forms\Components\Tabs\Tab::make('English Content')->schema(self::content('en')),
 Forms\Components\Tabs\Tab::make('Hindi Content')->schema(self::content('hi')),
 Forms\Components\Tabs\Tab::make('Safety')->schema(self::safety()),
 Forms\Components\Tabs\Tab::make('Evidence & SEO')->schema([Forms\Components\Select::make('evidence_level')->options(['traditional'=>'Traditional Use','limited'=>'Limited Evidence','supportive'=>'Some Supporting Evidence','moderate'=>'Moderate Evidence','strong'=>'Strong Evidence','not_recommended'=>'Not Recommended'])->required(),Forms\Components\Textarea::make('evidence_summary_en'),Forms\Components\Textarea::make('evidence_summary_hi'),Forms\Components\Select::make('medical_review_status')->options(array_combine(['draft','content_reviewed','medical_review_pending','medical_reviewed','published','rejected'],['Draft','Content reviewed','Medical review pending','Medical reviewed','Published','Rejected']))->required(),Forms\Components\Textarea::make('references'),Forms\Components\Textarea::make('source_notes'),Forms\Components\TextInput::make('meta_title_en'),Forms\Components\TextInput::make('meta_title_hi'),Forms\Components\Textarea::make('meta_description_en'),Forms\Components\Textarea::make('meta_description_hi'),Forms\Components\Textarea::make('search_keywords_en'),Forms\Components\Textarea::make('search_keywords_hi'),Forms\Components\Textarea::make('search_aliases')->helperText('Separate aliases with commas or new lines.')])
 ])]);}
 private static function content(string $l):array{$fields=['short_description'=>'Short description','description'=>'Description','ingredients'=>'Ingredients','preparation'=>'Preparation','steps'=>'Steps','usage_instructions'=>'How to use','dosage_or_quantity'=>'Quantity','frequency'=>'Frequency','recommended_duration'=>'Duration','traditional_benefit'=>'Traditional benefit','how_it_may_help'=>'How it may help'];return array_map(fn($f)=>Forms\Components\Textarea::make($f.'_'.$l)->label($f==='short_description'?'Short description ('.$l.')':ucwords(str_replace('_',' ',$f)).' ('.$l.')')->rows($f==='description'?5:3),array_keys($fields));}
 private static function safety():array{$fields=['suitable_for','not_suitable_for','child_warning','pregnancy_warning','elderly_warning','medical_condition_warning','medicine_interactions','possible_side_effects','red_flags','when_to_see_doctor','medical_disclaimer'];$out=[];foreach(['en','hi'] as $l)foreach($fields as $f)$out[]=Forms\Components\Textarea::make($f.'_'.$l)->label(ucwords(str_replace('_',' ',$f)).' ('.$l.')')->rows(3)->required(in_array($f,['suitable_for','not_suitable_for','red_flags','when_to_see_doctor']));return $out;}
 public static function table(Table $table):Table{return $table->columns([Tables\Columns\TextColumn::make('id')->sortable(),Tables\Columns\TextColumn::make('title_en')->label('Title')->searchable()->sortable(),Tables\Columns\TextColumn::make('title_hi')->label('Hindi Title')->searchable(),Tables\Columns\TextColumn::make('category.name_en')->label('Category')->sortable(),Tables\Columns\TextColumn::make('evidence_level')->badge(),Tables\Columns\TextColumn::make('medical_review_status')->badge(),Tables\Columns\IconColumn::make('is_featured')->boolean(),Tables\Columns\IconColumn::make('is_published')->boolean(),Tables\Columns\TextColumn::make('updated_at')->dateTime()->sortable()])->filters([Tables\Filters\SelectFilter::make('category_id')->options(HomeRemedyCategory::pluck('name_en','id')),Tables\Filters\SelectFilter::make('evidence_level')->options(['traditional'=>'Traditional','limited'=>'Limited','supportive'=>'Supportive','moderate'=>'Moderate','strong'=>'Strong','not_recommended'=>'Not recommended']),Tables\Filters\SelectFilter::make('medical_review_status')->options(array_combine(['draft','content_reviewed','medical_review_pending','medical_reviewed','published','rejected'],['Draft','Content reviewed','Medical pending','Medical reviewed','Published','Rejected'])),Tables\Filters\TernaryFilter::make('is_published'),Tables\Filters\TernaryFilter::make('is_featured')])->actions([Tables\Actions\EditAction::make(),Tables\Actions\DeleteAction::make()])->bulkActions([Tables\Actions\BulkActionGroup::make([Tables\Actions\DeleteBulkAction::make()])]);}
 public static function getPages():array{return ['index'=>Pages\ListHomeRemedies::route('/'),'create'=>Pages\CreateHomeRemedy::route('/create'),'edit'=>Pages\EditHomeRemedy::route('/{record}/edit')];}
}
